extensions/contentextraction/ivy.xml
extensions/modules/xslfo/ivy.xml

Update to Tika version 1.20

---

extensions/contentextraction/ivy.xml
extensions/modules/xslfo/ivy.xml

Backport of https://github.com/eXist-db/exist/pull/2558

(5.0.0) Update to Tika version 1.20

---

exist-core/src/main/java/org/exist/dom/persistent/NewArrayNodeSet.java
exist-core/src/main/java/org/exist/repo/AutoDeploymentTrigger.java
exist-core/src/main/java/org/exist/xquery/ElementConstructor.java
exist-core/src/main/java/org/exist/xquery/NamespaceConstructor.java
exist-core/src/main/java/org/exist/xquery/XQueryContext.java
exist-core/src/main/resources/org/exist/xquery/lib/xqsuite/xqsuite.xql
exist-core/src/test/xquery/namespaces.xql
exist-core/src/test/xquery/positional-nested.xql
exist-core/src/test/xquery/xquery3/load-xquery-module.xql

This fixes an issue raised by @dizzzz where not all test failures were reported from XQSuite correctly, which caused XSuite to show tests as passing when they were actually failing.

XQSuite+XSuite was not correctly reporting all test failures

---

exist-core/src/main/java/org/exist/dom/persistent/NewArrayNodeSet.java
exist-core/src/main/java/org/exist/repo/AutoDeploymentTrigger.java
exist-core/src/main/java/org/exist/xquery/ElementConstructor.java
exist-core/src/main/java/org/exist/xquery/NamespaceConstructor.java
exist-core/src/main/java/org/exist/xquery/XQueryContext.java
exist-core/src/main/resources/org/exist/xquery/lib/xqsuite/xqsuite.xql
exist-core/src/test/xquery/namespaces.xql
exist-core/src/test/xquery/positional-nested.xql
exist-core/src/test/xquery/xquery3/load-xquery-module.xql

Backport of https://github.com/eXist-db/exist/pull/2140

(4.x.x) XQSuite+XSuite was not correctly reporting all test failures

---

exist-core/src/main/java/org/exist/dom/persistent/NewArrayNodeSet.java
exist-core/src/main/java/org/exist/repo/AutoDeploymentTrigger.java
exist-core/src/main/java/org/exist/xquery/ElementConstructor.java
exist-core/src/main/java/org/exist/xquery/NamespaceConstructor.java
exist-core/src/main/java/org/exist/xquery/XQueryContext.java
exist-core/src/main/resources/org/exist/xquery/lib/xqsuite/xqsuite.xql
exist-core/src/test/xquery/namespaces.xql
exist-core/src/test/xquery/positional-nested.xql
exist-core/src/test/xquery/xquery3/load-xquery-module.xql

Backport of https://github.com/eXist-db/exist/pull/2140

(5.0.0) XQSuite+XSuite was not correctly reporting all test failures

---

exist-core/src/main/java/org/exist/xquery/NamespaceConstructor.java
exist-core/src/test/xquery/namespaces.xql

Backport of https://github.com/eXist-db/exist/pull/2582

(4.x.x) Fix an issue with the Namespace Constructor and empty prefix

---

exist-core/src/main/java/org/exist/xquery/NamespaceConstructor.java
exist-core/src/test/xquery/namespaces.xql

Backport of https://github.com/eXist-db/exist/pull/2582

(5.0.0) Fix an issue with the Namespace Constructor and empty prefix

---

eXist-db.iml
extensions/indexes/sort/src/test/java/xquery/sort/SortTests.java

Backport of https://github.com/eXist-db/exist/pull/2570

(5.0.0) Fix standard project layout for SortIndex tests 

---

eXist-db.iml
extensions/indexes/sort/src/test/java/xquery/sort/SortTests.java

Backport of https://github.com/eXist-db/exist/pull/2570

(4.x.x) Fix standard project layout for SortIndex tests

---

appveyor.yml

This captures the JUnit output to an artifact in AppVeyor if any tests fail.

Appveyor failed test data

---

appveyor.yml

Backport of https://github.com/eXist-db/exist/pull/2593

(4.x.x) Appveyor failed test data

---

appveyor.yml

Backport of https://github.com/eXist-db/exist/pull/2593

(5.0.0) Appveyor failed test data

---

exist-core/src/main/java/org/exist/collections/MutableCollection.java
exist-core/src/main/java/org/exist/storage/BrokerPool.java
exist-core/src/main/java/org/exist/storage/lock/Lock.java
exist-core/src/main/java/org/exist/storage/lock/LockEventJsonListener.java
exist-core/src/main/java/org/exist/storage/lock/LockEventLogListener.java
exist-core/src/main/java/org/exist/storage/lock/LockEventXmlListener.java
exist-core/src/main/java/org/exist/storage/lock/LockManager.java
exist-core/src/main/java/org/exist/storage/lock/LockTable.java
exist-core/src/main/java/org/exist/util/RingBuffer.java
exist-core/src/test/java/org/exist/storage/NativeBrokerLockingTest.java
exist-core/src/test/java/org/exist/storage/StartupLockingTest.java
exist-core/src/test/java/org/exist/storage/lock/CollectionLocksTest.java
exist-core/src/test/java/org/exist/storage/lock/DocumentLocksTest.java
exist-core/src/test/java/org/exist/storage/lock/LockManagerTest.java

Backport of https://github.com/eXist-db/exist/pull/2590

(5.0.0) Improve the performance of the LockTable

---

exist-core/src/main/java/org/exist/collections/MutableCollection.java
exist-core/src/main/java/org/exist/dom/persistent/DocumentImpl.java
exist-core/src/test/java/org/exist/storage/AllStorageTests.java
exist-core/src/test/java/org/exist/storage/CopyResourceTest.java
exist-core/src/test/java/org/exist/storage/StoreBinaryTest.java
exist-core/src/test/java/org/exist/storage/StoreResourceTest.java

Backport of https://github.com/eXist-db/exist/pull/2594

(5.0.0) Fix a permissions issue with replacing binary resources

---

exist-core/src/main/java/org/exist/collections/MutableCollection.java
exist-core/src/test/java/org/exist/storage/AllStorageTests.java
exist-core/src/test/java/org/exist/storage/StoreBinaryTest.java
exist-core/src/test/java/org/exist/storage/StoreResourceTest.java

Backport of https://github.com/eXist-db/exist/pull/2594

(4.x.x) Fix a permissions issue with replacing binary resources

---

build.properties
installer/apps.properties

Backport of https://github.com/eXist-db/exist/pull/2423.

(5.0.0) [feature] switch to new dashboard

---

exist-core/src/main/java/org/exist/xquery/ExternalModule.java
exist-core/src/main/java/org/exist/xquery/ExternalModuleImpl.java
exist-core/src/main/java/org/exist/xquery/VariableDeclaration.java
exist-core/src/main/java/org/exist/xquery/functions/fn/LoadXQueryModule.java
exist-core/src/main/java/org/exist/xquery/functions/inspect/ModuleFunctions.java
exist-core/src/main/java/org/exist/xquery/functions/util/PrologFunctions.java
exist-core/src/test/xquery/xquery3/closure-in-maps.xql
exist-core/src/test/xquery/xquery3/dynamically-declared-vars.xql
exist-core/src/test/xquery/xquery3/load-xquery-module.xql

(4.x.x) Dynamically loaded module vars not analyzed

---

exist-core/src/main/java/org/exist/xquery/ExternalModule.java
exist-core/src/main/java/org/exist/xquery/ExternalModuleImpl.java
exist-core/src/main/java/org/exist/xquery/VariableDeclaration.java
exist-core/src/main/java/org/exist/xquery/functions/fn/LoadXQueryModule.java
exist-core/src/main/java/org/exist/xquery/functions/inspect/ModuleFunctions.java
exist-core/src/main/java/org/exist/xquery/functions/util/PrologFunctions.java
exist-core/src/test/xquery/xquery3/closure-in-maps.xql
exist-core/src/test/xquery/xquery3/dynamically-declared-vars.xql
exist-core/src/test/xquery/xquery3/load-xquery-module.xql

(5.0.0) Dynamically loaded module vars not analyzed

---

exist-core/src/test/java/org/exist/storage/RecoveryTest.java

Backport of https://github.com/eXist-db/exist/pull/2606

(5.0.0) Fix RecoveryTest determinism

---

exist-core/src/test/java/org/exist/storage/RecoveryTest.java

https://github.com/eXist-db/exist/pull/2606

(4.x.x) Fix RecoveryTest determinism

---

test/src/xquery/literals-in-curlies.xql

This adds tests for https://github.com/eXist-db/exist/issues/291
xqsuite

add testsuite for literals in curly braces

---

test/src/xquery/literals-in-curlies.xql

(5.0.0) add testsuite for literals in curly braces

---

exist-core/src/main/java/org/exist/storage/BackupSystemTask.java
exist-core/src/main/java/org/exist/util/FileUtils.java

Backport of https://github.com/eXist-db/exist/pull/2585

(4.x.x) Fix purging of old zip backups

---

exist-core/src/main/java/org/exist/storage/BackupSystemTask.java
exist-core/src/main/java/org/exist/util/FileUtils.java

Backport of https://github.com/eXist-db/exist/pull/2585

(5.0.0) Fix purging of old zip backups

---

.classpath
extensions/xqdoc/src/test/java/xqdoc/XQDocTests.java

Forward port of https://github.com/eXist-db/exist/pull/2578

Update Eclipse classpath to fix compilation

---

.classpath
extensions/xqdoc/src/test/java/xqdoc/XQDocTests.java

Backport of https://github.com/eXist-db/exist/pull/2581

(5.0.0) Update Eclipse classpath to fix compilation

---

extensions/security/ldap/src/main/java/org/exist/security/realm/ldap/LDAPRealm.java

Closes https://github.com/eXist-db/exist/issues/2280

Fix NPE in LDAPRealm when seraching for group members

---

extensions/security/ldap/src/main/java/org/exist/security/realm/ldap/LDAPRealm.java

Backport of https://github.com/eXist-db/exist/pull/2617

(5.0.0) Fix NPE in LDAPRealm when seraching for group members

---

extensions/security/ldap/src/main/java/org/exist/security/realm/ldap/LDAPRealm.java

Backport of https://github.com/eXist-db/exist/pull/2617

(4.x.x) Fix NPE in LDAPRealm when seraching for group members

---

exist-core/src/main/java/org/exist/xquery/ArrowOperator.java
exist-core/src/main/java/org/exist/xquery/functions/fn/FunHigherOrderFun.java
exist-core/src/main/java/org/exist/xquery/functions/fn/FunSort.java
exist-core/src/test/xquery/xquery3/arrowop.xql
exist-core/src/test/xquery/xquery3/fnSort.xql

fix context sequence for higher order functions and sorting

---

exist-core/src/main/java/org/exist/xquery/ArrowOperator.java
exist-core/src/main/java/org/exist/xquery/functions/fn/FunHigherOrderFun.java
exist-core/src/main/java/org/exist/xquery/functions/fn/FunSort.java
exist-core/src/test/xquery/xquery3/arrowop.xql
exist-core/src/test/xquery/xquery3/fnSort.xql

fix context sequence for higher order functions and sorting
result of a joint effort by @line-o @windauer @wolfgangmm @JoernT and @tuurma
Has been already approved in #2443 but redoing the PR since I followed incorrect procedure before
solves #1960
relevant tests have been added with this PR

(4.x.x) fix context sequence for higher order functions and sorting

---

exist-core/src/main/java/org/exist/xquery/ArrowOperator.java
exist-core/src/main/java/org/exist/xquery/functions/fn/FunHigherOrderFun.java
exist-core/src/main/java/org/exist/xquery/functions/fn/FunSort.java
exist-core/src/test/xquery/xquery3/arrowop.xql
exist-core/src/test/xquery/xquery3/fnSort.xql

(5.0.0) fix context sequence for higher order functions and sorting

---

build/scripts/junit.xml
exist-core/src/main/java/org/exist/dom/persistent/StoredNode.java
exist-core/src/test/java/org/exist/xquery/XQueryUpdateTest.java

The tests were previously not run, so we could not see this was broken :-(
I enabled the test and fixed the issue.
This was revealed by the Mavenized version on eXist-db. Maven runs all tests by default... unlike our Ant build!

Fix XQuery Update insert following

---

build/scripts/junit.xml
exist-core/src/main/java/org/exist/dom/persistent/StoredNode.java
exist-core/src/test/java/org/exist/xquery/XQueryUpdateTest.java

Backport of https://github.com/eXist-db/exist/pull/2623

(5.0.0) Fix XQuery Update insert following

---

build/scripts/junit.xml
exist-core/src/main/java/org/exist/dom/persistent/StoredNode.java
exist-core/src/test/java/org/exist/xquery/XQueryUpdateTest.java

Backport of https://github.com/eXist-db/exist/pull/2623

(4.x.x) Fix XQuery Update insert following

---

.idea/compiler.xml
build/scripts/extensions-common.xml
exist-core/src/main/java/org/exist/storage/structural/NativeStructuralIndexWorker.java
exist-core/src/main/java/org/exist/xquery/functions/util/IndexKeys.java
extensions/indexes/spatial/extension.xml
extensions/indexes/spatial/ivy.xml
extensions/indexes/spatial/ivysettings.xml
extensions/indexes/spatial/src/main/java/org/exist/indexing/spatial/AbstractGMLJDBCIndexWorker.java
extensions/indexes/spatial/src/main/java/org/exist/indexing/spatial/GMLHSQLIndex.java
extensions/indexes/spatial/src/main/java/org/exist/indexing/spatial/GMLHSQLIndexWorker.java
extensions/indexes/spatial/src/main/java/org/exist/xquery/modules/spatial/FunGMLProducers.java
extensions/indexes/spatial/src/main/java/org/exist/xquery/modules/spatial/FunGeometricProperties.java
extensions/indexes/spatial/src/main/java/org/exist/xquery/modules/spatial/FunSpatialSearch.java
extensions/indexes/spatial/src/test/java/org/exist/indexing/spatial/GMLIndexTest.java
extensions/indexes/spatial/src/test/resources/README.txt
extensions/indexes/spatial/src/test/resources/conf.xml

Backport of https://github.com/eXist-db/exist/pull/2600

(5.0.0) Fix the Spatial Index

---

.idea/compiler.xml
build/scripts/extensions-common.xml
exist-core/src/main/java/org/exist/plugin/PluginsManagerImpl.java
exist-core/src/main/java/org/exist/storage/structural/NativeStructuralIndexWorker.java
exist-core/src/main/java/org/exist/xquery/functions/util/IndexKeys.java
extensions/indexes/spatial/extension.xml
extensions/indexes/spatial/ivy.xml
extensions/indexes/spatial/ivysettings.xml
extensions/indexes/spatial/src/main/java/org/exist/indexing/spatial/AbstractGMLJDBCIndexWorker.java
extensions/indexes/spatial/src/main/java/org/exist/indexing/spatial/GMLHSQLIndex.java
extensions/indexes/spatial/src/main/java/org/exist/indexing/spatial/GMLHSQLIndexWorker.java
extensions/indexes/spatial/src/main/java/org/exist/xquery/modules/spatial/FunGMLProducers.java
extensions/indexes/spatial/src/main/java/org/exist/xquery/modules/spatial/FunGeometricProperties.java
extensions/indexes/spatial/src/main/java/org/exist/xquery/modules/spatial/FunSpatialSearch.java
extensions/indexes/spatial/src/test/java/org/exist/indexing/spatial/GMLIndexTest.java
extensions/indexes/spatial/src/test/resources/README.txt
extensions/indexes/spatial/src/test/resources/conf.xml

Backport of https://github.com/eXist-db/exist/pull/2600

(4.x.x) Fix the Spatial Index

---

.idea/compiler.xml
build/scripts/extensions-common.xml
exist-core/src/main/java/org/exist/storage/structural/NativeStructuralIndexWorker.java
exist-core/src/main/java/org/exist/xquery/functions/util/IndexKeys.java
extensions/indexes/spatial/extension.xml
extensions/indexes/spatial/ivy.xml
extensions/indexes/spatial/ivysettings.xml
extensions/indexes/spatial/src/main/java/org/exist/indexing/spatial/AbstractGMLJDBCIndexWorker.java
extensions/indexes/spatial/src/main/java/org/exist/indexing/spatial/GMLHSQLIndex.java
extensions/indexes/spatial/src/main/java/org/exist/indexing/spatial/GMLHSQLIndexWorker.java
extensions/indexes/spatial/src/main/java/org/exist/xquery/modules/spatial/FunGMLProducers.java
extensions/indexes/spatial/src/main/java/org/exist/xquery/modules/spatial/FunGeometricProperties.java
extensions/indexes/spatial/src/main/java/org/exist/xquery/modules/spatial/FunSpatialSearch.java
extensions/indexes/spatial/src/test/java/org/exist/indexing/spatial/GMLIndexTest.java
extensions/indexes/spatial/src/test/resources/README.txt
extensions/indexes/spatial/src/test/resources/conf.xml

Fixes the compilation and operation of the Spatial Index.
There is still one test failure, the `update` test. However, I cannot see that this could ever have worked.
So it seems the Spatial Index is restored, but at present does not support XUpdate or XQuery Update.

Fix the Spatial Index

---

exist-core/src/main/java/org/exist/util/io/MemoryContents.java
exist-core/src/main/java/org/exist/util/io/MemoryContentsImpl.java
exist-core/src/main/java/org/exist/util/io/MemoryContentsInputStream.java
exist-core/src/main/java/org/exist/util/io/MemoryContentsOutputStream.java
exist-core/src/main/java/org/exist/util/io/OutputStreamSupplier.java
exist-core/src/main/java/org/exist/util/io/OverflowToDiskStream.java
exist-core/src/main/java/org/exist/util/io/VirtualTempPath.java
exist-core/src/main/java/org/exist/xmldb/AbstractRemoteResource.java
exist-core/src/main/java/org/exist/xmldb/LocalCollection.java.orig
exist-core/src/main/java/org/exist/xmldb/RemoteCollection.java
exist-core/src/main/java/org/exist/xmldb/RemoteXMLResource.java
exist-core/src/test/java/org/exist/util/io/MemoryContentsImplTest.java
exist-core/src/test/java/org/exist/util/io/MemoryContentsInputStreamTest.java
exist-core/src/test/java/org/exist/util/io/MemoryContentsOutputStreamTest.java
exist-core/src/test/java/org/exist/util/io/OverflowToDiskStreamTest.java
exist-core/src/test/java/org/exist/util/io/VirtualTempPathTest.java

Adds in-memory buffer for all remote `XMLResource` including JUnit tests for the newly added functionality.

Implements VirtualTempPath as described in #2592

---

exist-core/src/main/java/org/exist/util/io/MemoryContents.java
exist-core/src/main/java/org/exist/util/io/MemoryContentsImpl.java
exist-core/src/main/java/org/exist/util/io/MemoryContentsInputStream.java
exist-core/src/main/java/org/exist/util/io/MemoryContentsOutputStream.java
exist-core/src/main/java/org/exist/util/io/OutputStreamSupplier.java
exist-core/src/main/java/org/exist/util/io/OverflowToDiskStream.java
exist-core/src/main/java/org/exist/util/io/VirtualTempPath.java
exist-core/src/main/java/org/exist/xmldb/AbstractRemoteResource.java
exist-core/src/main/java/org/exist/xmldb/LocalCollection.java.orig
exist-core/src/main/java/org/exist/xmldb/RemoteCollection.java
exist-core/src/main/java/org/exist/xmldb/RemoteXMLResource.java
exist-core/src/test/java/org/exist/util/io/MemoryContentsImplTest.java
exist-core/src/test/java/org/exist/util/io/MemoryContentsInputStreamTest.java
exist-core/src/test/java/org/exist/util/io/MemoryContentsOutputStreamTest.java
exist-core/src/test/java/org/exist/util/io/OverflowToDiskStreamTest.java
exist-core/src/test/java/org/exist/util/io/VirtualTempPathTest.java

Adds in-memory buffer for all remote `XMLResource` including JUnit tests for the newly added functionality.

(5.0.0) Implements VirtualTempPath as described in #2592

---

exist-core/src/main/java/org/exist/xquery/functions/xmldb/XMLDBCopy.java
exist-core/src/test/xquery/xmldb/copy-tests.xql
exist-core/src/test/xquery/xmldb/permission-tests.xql

(5.0.0) Fix xmldb:copy-resource/xmldb:copy-collection

---

build/scripts/extensions-common.xml
eXist-db.iml
exist-core/src/test/java/org/exist/http/LoginModuleTest.java
extensions/modules/persistentlogin/src/main/resources/org/exist/xquery/modules/persistentlogin/login.xql
extensions/modules/persistentlogin/src/test/java/org/exist/xquery/modules/persistentlogin/LoginModuleTest.java

Replace xmldb:is-admin-user with sm:is-dba to restore packaged apps for develop and 5.0.

Fix use of deprecated functions to restore dashboard etc.

---

build/scripts/extensions-common.xml
eXist-db.iml
exist-core/src/test/java/org/exist/http/LoginModuleTest.java
extensions/modules/persistentlogin/src/main/resources/org/exist/xquery/modules/persistentlogin/login.xql
extensions/modules/persistentlogin/src/test/java/org/exist/xquery/modules/persistentlogin/LoginModuleTest.java

(5.0.0) Fix use of deprecated functions to restore dashboard etc.

---

build/scripts/dist.xml

Backport of https://github.com/eXist-db/exist/pull/2648

(4.x.x) Fix the Ant dist target for releases

---

build/scripts/dist.xml

Backport of https://github.com/eXist-db/exist/pull/2648

(5.0.0) Fix the Ant dist target for releases

---

log4j2.xml

Backport of https://github.com/eXist-db/exist/pull/2661

(5.x.x) Remove unused log

---

exist-core/src/main/java/org/exist/util/Collations.java
exist-core/src/main/java/org/exist/xquery/value/OrderedValueSequence.java

Closes https://github.com/eXist-db/exist/issues/2278
Also adds a couple of small optimisations.

Fix sorting sequences of more than 8192 items with collations

---

exist-core/src/main/java/org/exist/util/Collations.java
exist-core/src/main/java/org/exist/xquery/value/OrderedValueSequence.java

Backport of https://github.com/eXist-db/exist/pull/2667

(5.0.0) Fix sorting sequences of more than 8192 items with collations

---

.idea/misc.xml
exist-core/src/main/java/org/exist/util/Collations.java
exist-core/src/main/java/org/exist/xquery/value/OrderedValueSequence.java

Backport of https://github.com/eXist-db/exist/pull/2667

(4.x.x) Fix sorting sequences of more than 8192 items with collations

---

exist-core/src/main/java/org/exist/util/Collations.java
exist-core/src/test/xquery/collations.xq

(4.x.x) Fix a problem with collation comparison on empty strings

---

exist-core/src/main/java/org/exist/util/Collations.java
exist-core/src/test/xquery/collations.xq

Backport of https://github.com/eXist-db/exist/pull/2670

(5.0.0) Fix a problem with collation comparison on empty strings

---

exist-core/src/main/java/org/exist/util/Collations.java
exist-core/src/test/xquery/collations.xq

Closes https://github.com/eXist-db/exist/issues/1898

Fix a problem with collation comparison on empty strings

---

exist-core/src/main/java/org/exist/plugin/PluginsManagerImpl.java
log4j2.xml

Remove a couple of dead things that were missed when removing deprecated stuff.

Minor cleanup

---

exist-core/src/main/java/org/exist/plugin/PluginsManagerImpl.java
log4j2.xml

Backport of https://github.com/eXist-db/exist/pull/2676

(5.0.0) Minor cleanup

---

exist-core/src/main/java/org/exist/storage/NativeBroker.java
exist-core/src/main/java/org/exist/storage/NodePath.java
exist-core/src/test/java/org/exist/storage/ShutdownTest.java
extensions/indexes/lucene/src/main/java/org/exist/indexing/lucene/NodePathPattern.java
extensions/indexes/lucene/src/test/java/org/exist/indexing/lucene/LuceneIndexTest.java

(4.x.x) Descendant nodes wrongly indexed, fix PR #2367

---

exist-core/src/main/java/org/exist/storage/NativeBroker.java
exist-core/src/main/java/org/exist/storage/NodePath.java
exist-core/src/test/java/org/exist/storage/ShutdownTest.java
extensions/indexes/lucene/src/main/java/org/exist/indexing/lucene/NodePathPattern.java
extensions/indexes/lucene/src/test/java/org/exist/indexing/lucene/LuceneIndexTest.java

(5.0.0) Descendant nodes wrongly indexed, fix PR #2367

---

exist-core/src/main/java/org/exist/storage/lock/LockTable.java

Closes https://github.com/eXist-db/exist/issues/2685

Fix an issue with LockTable Entries#unmerge under high concurrency

---

exist-core/src/main/java/org/exist/storage/lock/LockTable.java

Backport of https://github.com/eXist-db/exist/pull/2689

(5.0.0) Fix an issue with LockTable Entries#unmerge under high concurrency

---

exist-core/src/main/java/org/exist/storage/NativeBroker.java
exist-core/src/test/java/org/exist/collections/AllCollectionTests.java
exist-core/src/test/java/org/exist/collections/OpenCollectionTest.java

(5.0.0) Opening a collection using full XmldbURI (with scheme) fails.

---

exist-distribution/pom.xml

Backport of https://github.com/eXist-db/exist/pull/2707

(5.0.0) Update the public-xar-repo-plugin

---

extensions/indexes/lucene/src/main/java/org/exist/indexing/lucene/LuceneIndexWorker.java
extensions/indexes/lucene/src/main/java/org/exist/indexing/lucene/LuceneMatch.java
extensions/indexes/lucene/src/main/java/org/exist/xquery/modules/lucene/Facets.java

(5.0.0) Lucene: fix AlreadyClosedException

---

README.md

Backport of https://github.com/eXist-db/exist/pull/2706

(5.0.0) Fix the logo image path in README.md

---

exist-installer/pom.xml
exist-parent/pom.xml

The installer is not meant to be uploaded as a Maven artifact... instead it goes to Bintray

Don't deploy the IzPack Jar to the Maven repo

---

exist-installer/pom.xml
exist-parent/pom.xml

Backport of https://github.com/eXist-db/exist/pull/2715

(5.0.0) Don't deploy the IzPack Jar to the Maven repo

---

.travis.yml
appveyor.yml

enable push of `latest` tags from develop branch
make the logs less verbose

hotfix(ci): deploy latest tag from develop

---

.travis.yml
appveyor.yml

dev-5.0.0 fix(ci): deploy latest tag from develop, make install logs less verbose

---

exist-core/src/main/java/org/exist/launcher/ConfigurationDialog.java
exist-core/src/main/java/org/exist/launcher/LauncherWrapper.java

(5.0.0) LauncherWrapper not exiting after first start

---

exist-core/src/main/java/org/exist/xquery/functions/fn/FunTokenize.java
exist-core/src/test/java/org/exist/xquery/XQueryFunctionsTest.java

Closes https://github.com/eXist-db/exist/issues/2694

fn:tokenize should be case sensitive by default

---

exist-core/src/main/java/org/exist/xquery/functions/fn/FunTokenize.java
exist-core/src/test/java/org/exist/xquery/XQueryFunctionsTest.java

Backport of https://github.com/eXist-db/exist/pull/2741

(5.0.0) fn:tokenize should be case sensitive by default

---

exist-core/src/main/java/org/exist/xmldb/AbstractRemoteResource.java
exist-core/src/test/java/org/exist/xmldb/RemoteCollectionTest.java

Fixes the default in memory size from 64M to 4M

---

exist-core/src/main/java/org/exist/xmldb/AbstractRemoteResource.java
exist-core/src/test/java/org/exist/xmldb/RemoteCollectionTest.java

Fixes #2743 on `develop-5.0.0`

(5.0.0) Fixes the default in memory size from 64M to 4M

---

exist-core/src/main/java/org/exist/xmldb/AbstractRemoteResource.java
exist-core/src/test/java/org/exist/xmldb/RemoteCollectionTest.java

Fixes #2743 on `develop-4.x.x`

(4.x.x) Fixes the default in memory size from 64M to 4M

---

exist-core/src/main/java/org/exist/launcher/WindowsServiceManager.java

(5.0.0) Installing service fails with OpenJDK

---

exist-core/src/test/xquery/dates/format-dates.xql

Fixes all test failing if the system language is other than English.

Fixes tests failing if system language it not english

---

exist-core/src/test/xquery/dates/format-dates.xql

Fixes all test failing if the system language is other than English for `develop-5.0.0`

(5.0.0) Fixes tests failing if system language it not english

---

SECURITY.md

Replaces placeholder text in the first section with a project specific explanation

[doc]: Update SECURITY.MD

---

exist-core/src/main/java/org/exist/util/io/VirtualTempPath.java
exist-core/src/test/java/org/exist/util/io/VirtualTempPathTest.java

(5.0.0) Fixes getBytes() method returning wrong data if switched to file

---

exist-core/src/main/java/org/exist/util/io/VirtualTempPath.java
exist-core/src/test/java/org/exist/util/io/VirtualTempPathTest.java

(4.x.x) Fixes getBytes() method returning wrong data if switched to file

---

exist-core/src/main/java/org/exist/TestUtils.java
exist-core/src/main/java/org/exist/collections/MutableCollection.java
exist-core/src/main/java/org/exist/security/PermissionFactory.java
exist-core/src/main/java/org/exist/storage/NativeBroker.java
exist-core/src/main/java/org/exist/xmldb/XmldbURI.java
exist-core/src/test/java/org/exist/config/TwoDatabasesTest.java
exist-core/src/test/java/org/exist/storage/CopyCollectionTest.java
exist-core/src/test/java/org/exist/storage/CopyResourceTest.java
exist-core/src/test/java/org/exist/storage/ModificationTimeTest.java
exist-core/src/test/java/org/exist/storage/StoreResourceTest.java
exist-core/src/test/java/org/exist/storage/lock/ProtectedModeTest.java
exist-core/src/test/java/org/exist/storage/txn/ConcurrentTransactionsTest.java
exist-core/src/test/java/org/exist/xquery/functions/securitymanager/PermissionsFunctionChmodTest.java
exist-core/src/test/java/org/exist/xquery/functions/securitymanager/PermissionsFunctionChownTest.java

Backport of https://github.com/eXist-db/exist/pull/2751

(5.0.0) Very small fixes

---

.travis.yml

Backport of https://github.com/eXist-db/exist/pull/2773

(5.0.0) Don't quieten Maven output on Travis-CI

---

.travis.yml
exist-core/src/main/java/org/exist/Indexer.java
exist-core/src/main/java/org/exist/backup/ConsistencyCheck.java
exist-core/src/main/java/org/exist/backup/SystemExport.java
exist-core/src/main/java/org/exist/collections/Collection.java
exist-core/src/main/java/org/exist/collections/LockedCollection.java
exist-core/src/main/java/org/exist/collections/MutableCollection.java
exist-core/src/main/java/org/exist/dom/persistent/BinaryDocument.java
exist-core/src/main/java/org/exist/dom/persistent/DocumentImpl.java
exist-core/src/main/java/org/exist/dom/persistent/DocumentMetadata.java
exist-core/src/main/java/org/exist/dom/persistent/DocumentTypeImpl.java
exist-core/src/main/java/org/exist/dom/persistent/LockToken.java
exist-core/src/main/java/org/exist/storage/DBBroker.java
exist-core/src/main/java/org/exist/storage/NativeBroker.java
exist-core/src/main/java/org/exist/storage/statistics/IndexStatisticsWorker.java
exist-core/src/main/java/org/exist/util/io/Resource.java
exist-core/src/test/java/org/exist/collections/CollectionStoreTest.java
exist-core/src/test/java/org/exist/dom/persistent/DocumentImplTest.java
exist-core/src/test/java/org/exist/storage/journal/JournalBinaryTest.java
extensions/webdav/src/main/java/org/exist/webdav/ExistDocument.java
extensions/webdav/src/main/java/org/exist/webdav/MiltonResource.java

Closes https://github.com/eXist-db/exist/pull/1358 when considered alongside https://github.com/eXist-db/exist/pull/2687

Make doc id in DocumentImpl immutable

---

.travis.yml
exist-core/src/main/java/org/exist/Indexer.java
exist-core/src/main/java/org/exist/backup/ConsistencyCheck.java
exist-core/src/main/java/org/exist/backup/SystemExport.java
exist-core/src/main/java/org/exist/collections/Collection.java
exist-core/src/main/java/org/exist/collections/LockedCollection.java
exist-core/src/main/java/org/exist/collections/MutableCollection.java
exist-core/src/main/java/org/exist/dom/persistent/BinaryDocument.java
exist-core/src/main/java/org/exist/dom/persistent/DocumentImpl.java
exist-core/src/main/java/org/exist/dom/persistent/DocumentMetadata.java
exist-core/src/main/java/org/exist/dom/persistent/DocumentTypeImpl.java
exist-core/src/main/java/org/exist/dom/persistent/LockToken.java
exist-core/src/main/java/org/exist/storage/DBBroker.java
exist-core/src/main/java/org/exist/storage/NativeBroker.java
exist-core/src/main/java/org/exist/storage/statistics/IndexStatisticsWorker.java
exist-core/src/main/java/org/exist/util/io/Resource.java
exist-core/src/test/java/org/exist/collections/CollectionStoreTest.java
exist-core/src/test/java/org/exist/dom/persistent/DocumentImplTest.java
exist-core/src/test/java/org/exist/storage/journal/JournalBinaryTest.java
extensions/webdav/src/main/java/org/exist/webdav/ExistDocument.java
extensions/webdav/src/main/java/org/exist/webdav/MiltonResource.java

Backport of https://github.com/eXist-db/exist/pull/2701

(5.0.0) Make doc id in DocumentImpl immutable

---

.travis.yml
exist-core/src/main/java/org/exist/storage/txn/TransactionManager.java
exist-core/src/test/java/org/exist/backup/SystemExportFiltersTest.java
exist-core/src/test/java/org/exist/backup/SystemExportImportTest.java
exist-core/src/test/java/org/exist/backup/XMLDBBackupTest.java

Closes https://github.com/eXist-db/exist/issues/2767

Make sure that binary resources are described in system export

---

.travis.yml
exist-core/src/main/java/org/exist/storage/txn/TransactionManager.java
exist-core/src/test/java/org/exist/backup/SystemExportFiltersTest.java
exist-core/src/test/java/org/exist/backup/SystemExportImportTest.java
exist-core/src/test/java/org/exist/backup/XMLDBBackupTest.java

Backport of https://github.com/eXist-db/exist/pull/2771

(5.0.0) Make sure that binary resources are described in system export

---

extensions/webdav/src/main/java/org/exist/webdav/ExistDocument.java

Closes https://github.com/eXist-db/exist/issues/2787

Fix wrong lock taken in WebDAV delete document code

---

extensions/webdav/src/main/java/org/exist/webdav/ExistDocument.java

Backport of https://github.com/eXist-db/exist/pull/2788

(5.0.0) Fix wrong lock taken in WebDAV delete document code

---

exist-core/src/main/java/org/exist/xquery/functions/fn/FnModule.java
exist-core/src/main/java/org/exist/xquery/functions/fn/FunContainsToken.java
exist-core/src/test/xquery/xquery3/fn.xql

implements fn:contains-token with relevant tests

Feature/implement fn:contains-token

---

exist-core/src/main/java/org/exist/xquery/functions/fn/FnModule.java
exist-core/src/main/java/org/exist/xquery/functions/fn/FunContainsToken.java
exist-core/src/test/xquery/xquery3/fn.xql

port of #2792
implements fn:contains-token with relevant tests

(5.0.0) Feature/implement fn:contains-token

---

.travis.yml

increase timeout but silence install logs

---

exist-core/src/main/java/org/exist/http/Descriptor.java

Closes https://github.com/eXist-db/exist/issues/2808

Fix descriptor.xml lookup

---

exist-core/src/main/java/org/exist/http/Descriptor.java

Backport of https://github.com/eXist-db/exist/pull/2809

(5.0.0) Fix descriptor.xml lookup

---

extensions/expath/pom.xml

Closes https://github.com/eXist-db/exist/issues/2783

Update the EXPath HTTP Client

---

extensions/expath/pom.xml

Backport of https://github.com/eXist-db/exist/pull/2813

(5.0.0) Update the EXPath HTTP Client

---

exist-core/src/main/java/org/exist/repo/ExistRepository.java

Closes https://markmail.org/message/tu6pzw5gxrjp4kyt

Make sure to close the stream to avoid leaking file handles

---

exist-core/src/main/java/org/exist/repo/ExistRepository.java

Backport of https://github.com/eXist-db/exist/pull/2821

(4.x.x) Make sure to close the stream to avoid leaking file handles

---

exist-core/src/main/java/org/exist/repo/ExistRepository.java

(5.0.0) Make sure to close the stream to avoid leaking file handles

---

exist-distribution/pom.xml
exist-distribution/src/main/scripts/create-dmg-mac.sh
exist-distribution/src/main/scripts/create-dmg-unix.sh

Closes https://github.com/eXist-db/exist/issues/2791

Make the `mvn package` phase repeatable

---

exist-distribution/pom.xml
exist-distribution/src/main/scripts/create-dmg-mac.sh
exist-distribution/src/main/scripts/create-dmg-unix.sh

Backport of https://github.com/eXist-db/exist/pull/2825

(5.0.0) Make the `mvn package` phase repeatable

---

exist-distribution/pom.xml
exist-parent/pom.xml

(5.0.0) Enable JSR-356 websocket support in jetty

---

exist-core/src/main/java/org/exist/util/Holder.java
exist-core/src/main/java/org/exist/util/WeakLazyStripes.java

Backport of https://github.com/eXist-db/exist/pull/2830

(5.0.0) Improve the performance of WeakLazyStripes

---

exist-core/src/main/java/org/exist/util/Holder.java
exist-core/src/main/java/org/exist/util/WeakLazyStripes.java

Closes https://github.com/eXist-db/exist/issues/2686

Improve the performance of WeakLazyStripes

---

exist-core/src/main/java/org/exist/xquery/Optimizer.java
extensions/indexes/range/src/test/xquery/range/optimizer.xql

(4.x.x) Disable bad optimization

---

exist-core/src/main/java/org/exist/xquery/Optimizer.java
extensions/indexes/range/src/test/xquery/range/optimizer.xql

(5.0.0) Disable bad optimization

---

exist-core/src/main/java/org/exist/util/io/ByteArrayContent.java
exist-core/src/main/java/org/exist/util/io/ContentFile.java
exist-core/src/main/java/org/exist/util/io/VirtualTempPath.java
exist-core/src/main/java/org/exist/xmldb/AbstractRemoteResource.java
exist-core/src/main/java/org/exist/xmldb/RemoteCollection.java
exist-core/src/main/java/org/exist/xmldb/RemoteResourceSet.java
exist-core/src/main/java/org/exist/xmldb/RemoteXMLResource.java
exist-core/src/test/java/org/exist/util/io/ByteArrayContentTest.java

Backport of https://github.com/eXist-db/exist/pull/2842

(4.x.x) Adds VirtualTempPath on set content methods

---

exist-core/src/main/java/org/exist/util/io/ByteArrayContent.java
exist-core/src/main/java/org/exist/util/io/ContentFile.java
exist-core/src/main/java/org/exist/util/io/VirtualTempPath.java
exist-core/src/main/java/org/exist/xmldb/AbstractRemoteResource.java
exist-core/src/main/java/org/exist/xmldb/RemoteCollection.java
exist-core/src/main/java/org/exist/xmldb/RemoteResourceSet.java
exist-core/src/main/java/org/exist/xmldb/RemoteXMLResource.java
exist-core/src/test/java/org/exist/util/io/ByteArrayContentTest.java

Backport of https://github.com/eXist-db/exist/pull/2842

(5.0.0) Adds VirtualTempPath on set content methods

---

exist-core/src/main/java/org/exist/xquery/functions/system/GetProductName.java
exist-core/src/main/java/org/exist/xquery/functions/system/SystemModule.java

A simple function which retrieves the product name from `system.properties`.

Added system:get-product-name()

---

exist-core/src/main/java/org/exist/xquery/functions/system/GetProductName.java
exist-core/src/main/java/org/exist/xquery/functions/system/SystemModule.java

Backport of https://github.com/eXist-db/exist/pull/2838

(4.x.x) Added system:get-product-name()

---

exist-core/src/main/java/org/exist/xquery/functions/system/GetProductName.java
exist-core/src/main/java/org/exist/xquery/functions/system/SystemModule.java

Backport of https://github.com/eXist-db/exist/pull/2838

(5.x.x) Added system:get-product-name()

---

exist-distribution/src/main/scripts/create-dmg-unix.sh

Backport of https://github.com/eXist-db/exist/pull/2846

(5.0.0) Fix the DMG build on Unix

---

exist-distribution/src/main/scripts/create-dmg-unix.sh

Fix the DMG build on Unix

---

installer/install.xml.tmpl
installer/jobs.xml
installer/scripts/conf.xslt

Fixes the data directory specified during installation is not taken into account.
Manual installation test using the GUI dialog, specifying a different data directory-
Unattended installation using the following command:
`-jar exist/installer/eXist-db-setup-4.8.0-SNAPSHOT+201907081452.jar autoinstaller.xml`
where the content of `autoinstaller.xml` was:
```xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<AutomatedInstallation langpack="eng">
<com.izforge.izpack.panels.HTMLInfoPanel id="start"/>
<com.izforge.izpack.panels.TargetPanel id="UNKNOWN (com.izforge.izpack.panels.TargetPanel)">
<installpath>/opt/exist-test</installpath>
</com.izforge.izpack.panels.TargetPanel>
<com.izforge.izpack.panels.UserInputPanel id="UserInputPanel.0">
<userInput>
<entry key="dataDir" …
```

(4.x.x) Fixes ignored data directory

---

exist-core/src/main/java/org/exist/storage/DBBroker.java

one issue remaining with `{@link org.exist.storage.DBBroker#openCollection(XmldbURI, LockMode)}`
due to https://bugs.openjdk.java.net/browse/JDK-8031625

fix: javadoc for org.exist.storage.DBBroker

---

exist-docker/src/main/resources-filtered/Dockerfile

I diffed and checked the dependencies with a fresh pull of the builder image. 
folks will have to rebase
Not on my pc could someone please open a dev-5 port
TBD

Dockerfile copy errors

---

exist-docker/src/main/resources-filtered/Dockerfile

Backport of https://github.com/eXist-db/exist/pull/2883

(5.0.0) Dockerfile copy errors

---

exist-ant/src/main/java/org/exist/ant/UserPasswordTask.java
exist-core/src/main/java/org/exist/client/security/UserDialog.java
exist-core/src/main/java/org/exist/config/ConfigurationDocumentTrigger.java
exist-core/src/main/java/org/exist/security/AbstractAccount.java
exist-core/src/main/java/org/exist/security/AbstractRealm.java
exist-core/src/main/java/org/exist/security/PermissionFactory.java
exist-core/src/main/java/org/exist/security/SecurityManager.java
exist-core/src/main/java/org/exist/security/internal/RealmImpl.java
exist-core/src/main/java/org/exist/security/internal/SecurityManagerImpl.java
exist-core/src/main/java/org/exist/security/internal/aider/UserAider.java
exist-core/src/main/java/org/exist/xquery/functions/securitymanager/FindGroupFunction.java
exist-core/src/main/java/org/exist/xquery/functions/securitymanager/GroupManagementFunction.java
exist-core/src/main/java/org/exist/xquery/functions/securitymanager/SecurityManagerModule.java
exist-core/src/test/java/org/exist/backup/XMLDBRestoreTest.java
exist-core/src/test/java/org/exist/security/AbstractAccountTest.java
exist-core/src/test/java/org/exist/security/AbstractSecurityManagerRoundtripTest.java
exist-core/src/test/java/org/exist/xquery/functions/securitymanager/AccountManagementFunctionRemoveAccountTest.java
exist-core/src/test/java/org/exist/xquery/functions/securitymanager/GroupManagementFunctionRemoveGroupTest.java
exist-core/src/test/java/org/exist/xquery/functions/securitymanager/GroupMembershipFunctionRemoveGroupMemberTest.java
exist-core/src/test/java/org/exist/xquery/functions/securitymanager/PermissionsFunctionChownTest.java

Backport of https://github.com/eXist-db/exist/pull/2876

(5.0.0) Fix a number of security issues around user groups

---

exist-core/src/main/antlr/org/exist/xquery/parser/XQuery.g
exist-core/src/test/xquery/maps/maps.xql
exist-core/src/test/xquery/optimizer/optimizer.xql
exist-core/src/test/xquery/xquery3/inline.xml
exist-core/src/test/xquery/xquery3/recursion_calls.xml
extensions/modules/cache/src/test/xquery/modules/cache/cache.xqm

(5.0.0) Remove XQuery draft Map constructor

---

exist-ant/src/main/java/org/exist/ant/AbstractXMLDBTask.java
exist-ant/src/main/java/org/exist/ant/XMLDBExtractTask.java

Further javadoc fixes

---

exist-ant/src/main/java/org/exist/ant/AbstractXMLDBTask.java
exist-ant/src/main/java/org/exist/ant/XMLDBExtractTask.java

(5.0.0) Further javadoc fixes

---

exist-core/pom.xml
exist-parent/pom.xml

Forward port of https://github.com/eXist-db/exist/pull/2900

Remove OSS Parent

---

exist-distribution/pom.xml
exist-installer/pom.xml
exist-parent/pom.xml

* Add missing Maven Central requirement
* Fix BinTray artifact upload

(5.0.0) Fix release process

---

exist-distribution/pom.xml
exist-installer/pom.xml
exist-parent/pom.xml

Forward port of https://github.com/eXist-db/exist/pull/2906

Fix release process

---

extensions/indexes/lucene/src/main/java/org/exist/indexing/lucene/NodePathPattern.java

Forward port of https://github.com/eXist-db/exist/pull/2904/

Small code improvement with Object.equals

---

extensions/indexes/lucene/src/main/java/org/exist/indexing/lucene/NodePathPattern.java

Thank you for your contribution to eXist-db! 
To help the community judge your pull request (PR), please include the following:
- A (short) description of the content of changes.
- A context reference to a [Github Issue](https://github.com/eXist-db/exist/issues), a message in the [eXist-open mailinglist](http://exist-open.markmail.org), or a [specification](https://www.w3.org/TR/xquery-31/).
- Tests. The [XQSuite - Annotation-based Test Framework for XQuery](http://exist-db.org/exist/apps/doc/xqsuite.xml) makes it very easy for you to create tests. These tests can be executed from the [eXide editor](http://exist-db.org/exist/apps/eXide/index.html) via XQuery > Run as Test.
Your PR will be tested using [Travis CI](https://travis-ci.com/eXist-db/exist) and …

(4.x.x) Small code improvement with Object.equals

---

README.md

Simple badge to link to our Maven Artifacts.

[doc] Add a badge for Maven Central

---

README.md

[doc] Repair slack link

---

exist-core/src/main/java/org/exist/xquery/UserSwitchingBasicFunction.java

Backport of https://github.com/eXist-db/exist/pull/2923

(5.0.0) Fix user leak in XQuery User Switching functions

---

exist-core/src/main/java/org/exist/xquery/UserSwitchingBasicFunction.java

Backport of https://github.com/eXist-db/exist/pull/2923

(4.x.x) Fix user leak in XQuery User Switching functions

---

exist-distribution/pom.xml

Backport of https://github.com/eXist-db/exist/pull/2909

(5.0.0) Mac artifact should be named eXist-db-$ver.dmg

---

exist-core/src/main/java/org/exist/util/Configuration.java

Closes https://github.com/eXist-db/exist/issues/2874

Make sure embedded restore chooses correct data dir

---

exist-core/src/main/java/org/exist/util/Configuration.java

Backport of https://github.com/eXist-db/exist/pull/2926

(5.0.0) Make sure embedded restore chooses correct data dir

---

exist-core/src/main/java/org/exist/client/ClientFrame.java
exist-core/src/main/java/org/exist/client/InteractiveClient.java

Backport of https://github.com/eXist-db/exist/pull/2933

(4.x.x) Java Admin Client should be able to change logged in account password

---

exist-core/src/main/java/org/exist/client/ClientFrame.java
exist-core/src/main/java/org/exist/client/InteractiveClient.java

Backport of https://github.com/eXist-db/exist/pull/2933

(5.0.0) Java Admin Client should be able to change logged in account password

---

exist-core/src/main/java/org/exist/client/ClientFrame.java
exist-core/src/main/java/org/exist/client/InteractiveClient.java

Closes https://github.com/eXist-db/exist/issues/2918

Java Admin Client should be able to change logged in account password

---

exist-distribution/pom.xml

Closes https://github.com/eXist-db/exist/issues/2917

Reinstate the bin scripts in the App produced for Mac platforms

---

exist-distribution/pom.xml

Backport of https://github.com/eXist-db/exist/pull/2930

(5.0.0) Reinstate the bin scripts in the App produced for Mac platforms

---

exist-parent/pom.xml

When doing a release, we should ideally sign the Git tag.

Make sure to sign Git tags

---

exist-docker/pom.xml

Closes https://github.com/eXist-db/exist/issues/2880

Fix the WebSocket server when run from Uber Jar (e.g. Docker)

---

exist-docker/pom.xml

Backport of https://github.com/eXist-db/exist/pull/2928

(5.0.0) Fix the WebSocket server when run from Uber Jar (e.g. Docker)

---

test/src/xquery/boolean-sequences.xql

(5.0.0) test: add testuite for boolean sequences

---

test/src/xquery/boolean-sequences.xql

(4.x.x) add test suite for boolean sequences

---

exist-core/src/main/java/org/exist/security/AbstractRealm.java
exist-core/src/main/java/org/exist/security/internal/SecurityManagerImpl.java
exist-core/src/main/java/org/exist/security/management/AccountsManagement.java
exist-core/src/main/java/org/exist/security/management/GroupsManagement.java
extensions/security/ldap/src/main/java/org/exist/security/realm/ldap/LDAPRealm.java

Closes https://github.com/eXist-db/exist/issues/2280
Closes https://github.com/eXist-db/exist/issues/2281

Fix a couple of issues in LDAP

---

exist-core/src/main/java/org/exist/security/AbstractRealm.java
exist-core/src/main/java/org/exist/security/internal/SecurityManagerImpl.java
exist-core/src/main/java/org/exist/security/management/AccountsManagement.java
exist-core/src/main/java/org/exist/security/management/GroupsManagement.java
extensions/security/ldap/src/main/java/org/exist/security/realm/ldap/LDAPRealm.java

Backport of https://github.com/eXist-db/exist/pull/2327

(5.0.0) Fix a couple of issues in LDAP

---

exist-core/src/main/java/org/exist/security/AbstractRealm.java
exist-core/src/main/java/org/exist/security/internal/SecurityManagerImpl.java
exist-core/src/main/java/org/exist/security/management/AccountsManagement.java
exist-core/src/main/java/org/exist/security/management/GroupsManagement.java
extensions/security/ldap/src/main/java/org/exist/security/realm/ldap/LDAPRealm.java

Backport of https://github.com/eXist-db/exist/pull/2327

(4.x.x) Fix a couple of issues in LDAP

---

extensions/contentextraction/pom.xml

* Backport of https://github.com/eXist-db/exist/pull/2954

(5.0.0) Update Tika to avoid security issues

---

exist-core/src/main/java/org/exist/management/impl/SystemInfo.java
exist-core/src/main/java/org/exist/management/impl/SystemInfoMXBean.java

* Product name can now be retrieved
* Version numbers are product specific

Improve product details available over JMX

---

exist-core/src/main/java/org/exist/management/impl/SystemInfo.java
exist-core/src/main/java/org/exist/management/impl/SystemInfoMXBean.java

Backport of https://github.com/eXist-db/exist/pull/2960

(5.0.0) Improve product details available over JMX

---

exist-core/pom.xml

Closes https://github.com/eXist-db/exist/issues/2951

Update to the latest version of jline to avoid an issue with linux terminal types

---

exist-core-jmh/src/main/java/org/exist/storage/lock/LockTableBenchmark.java
exist-core/src/main/java/org/exist/dom/persistent/DocumentImpl.java
exist-core/src/main/java/org/exist/storage/BrokerPool.java
exist-core/src/main/java/org/exist/storage/lock/LockManager.java
exist-core/src/main/java/org/exist/storage/lock/LockTable.java
exist-core/src/main/java/org/exist/util/Configuration.java
exist-core/src/main/java/org/exist/util/WeakLazyStripes.java
exist-core/src/main/java/org/exist/xmldb/XmldbURI.java
exist-core/src/main/java/org/exist/xquery/RootNode.java
exist-distribution/src/main/config/conf.xml
schema/conf.xsd

See https://github.com/eXist-db/exist/issues/2014#issuecomment-522358491

Improve Lock Table lease recording performance

---

exist-core/src/main/java/org/exist/dom/persistent/DocumentImpl.java
exist-core/src/main/java/org/exist/storage/BrokerPool.java
exist-core/src/main/java/org/exist/storage/lock/LockManager.java
exist-core/src/main/java/org/exist/storage/lock/LockTable.java
exist-core/src/main/java/org/exist/util/Configuration.java
exist-core/src/main/java/org/exist/util/WeakLazyStripes.java
exist-core/src/main/java/org/exist/xmldb/XmldbURI.java
exist-core/src/main/java/org/exist/xquery/RootNode.java
exist-distribution/src/main/config/conf.xml
schema/conf.xsd

Backport of https://github.com/eXist-db/exist/pull/2962

(5.0.0) Improve Lock Table lease recording performance

---

exist-parent/pom.xml

Backport of https://github.com/eXist-db/exist/pull/2965

(5.0.0) Bump pkg-java from 1.4.0 to 1.4.1

---

exist-core/src/main/java/org/exist/util/WeakLazyStripes.java

Fixes a regression introduced in https://github.com/eXist-db/exist/pull/2962

Fix an NPE under load recently introduced in WeakLazyStripes

---

exist-core/src/main/java/org/exist/util/WeakLazyStripes.java

Fixes a regression introduced in https://github.com/eXist-db/exist/pull/2963
Backport of https://github.com/eXist-db/exist/pull/2969

(5.0.0) Fix an NPE under load recently introduced in WeakLazyStripes

---

exist-core/pom.xml
exist-core/src/main/java/org/exist/storage/XQueryPool.java

Closes https://github.com/eXist-db/exist/issues/1769

Improve the concurrent performance of the Compiled XQuery Pool

---

exist-core/pom.xml
exist-core/src/main/java/org/exist/storage/XQueryPool.java

Backport of https://github.com/eXist-db/exist/pull/2971

(5.0.0) Improve the concurrent performance of the Compiled XQuery Pool

---

exist-core/src/main/java/org/exist/util/Collations.java
exist-core/src/test/xquery/collations.xq

Closes https://github.com/eXist-db/exist/issues/2678

Fix collation comparison on empty strings

---

exist-core/src/main/java/org/exist/util/Collations.java
exist-core/src/test/xquery/collations.xq

Backport of https://github.com/eXist-db/exist/pull/2966

(5.0.0) Fix collation comparison on empty strings

---

exist-core/src/main/java/org/exist/repo/Deployment.java
exist-distribution/pom.xml
exist-distribution/src/main/config/log4j2.xml

Backport of https://github.com/eXist-db/exist/pull/2974

(5.0.0) Add missing Semver.xq to autodeploy

---

exist-core/src/main/java/org/exist/storage/NativeBroker.java
exist-core/src/test/java/org/exist/collections/InitCollectionConfigurationTest.java
exist-core/src/test/java/org/exist/storage/journal/AbstractJournalTest.java
exist-core/src/test/resources/collection.xconf.init

Closes https://github.com/eXist-db/exist/issues/2976

Make sure collection.xconf.init is deployed

---

exist-core/src/main/java/org/exist/storage/NativeBroker.java
exist-core/src/test/java/org/exist/collections/InitCollectionConfigurationTest.java
exist-core/src/test/java/org/exist/storage/journal/AbstractJournalTest.java
exist-core/src/test/resources/collection.xconf.init

Backport of https://github.com/eXist-db/exist/pull/2977

(5.0.0) Make sure collection.xconf.init is deployed

---

exist-core/src/main/java/org/exist/repo/Deployment.java

Simple improvements to LOG warning messages.

Improve warning messages when deploying packages

---

exist-core/src/main/java/org/exist/repo/Deployment.java

Backport of https://github.com/eXist-db/exist/pull/2981

(5.0.0) Improve warning messages when deploying packages

---

exist-core/src/main/java/org/exist/backup/ConsistencyCheck.java
exist-core/src/main/java/org/exist/backup/ExportGUI.java
exist-core/src/main/java/org/exist/backup/ExportMain.java
exist-core/src/main/java/org/exist/backup/SystemExport.java
exist-core/src/main/java/org/exist/scheduler/impl/ShutdownTask.java
exist-core/src/main/java/org/exist/storage/BackupSystemTask.java
exist-core/src/main/java/org/exist/storage/BrokerPool.java
exist-core/src/main/java/org/exist/storage/ConsistencyCheckTask.java
exist-core/src/main/java/org/exist/storage/DBBroker.java
exist-core/src/main/java/org/exist/storage/DataBackup.java
exist-core/src/main/java/org/exist/storage/NativeBroker.java
exist-core/src/main/java/org/exist/storage/SystemTask.java
exist-core/src/main/java/org/exist/storage/SystemTaskManager.java
exist-core/src/main/java/org/exist/storage/statistics/IndexStatisticsWorker.java
exist-core/src/main/java/org/exist/storage/sync/SyncTask.java
exist-core/src/main/java/org/exist/storage/txn/TransactionManager.java
exist-core/src/main/java/org/exist/xquery/functions/system/FnExport.java
exist-core/src/main/java/org/exist/xquery/functions/system/UpdateStatistics.java
exist-core/src/test/java/org/exist/backup/SystemExportFiltersTest.java
exist-core/src/test/java/org/exist/backup/SystemExportImportTest.java
exist-core/src/test/java/org/exist/storage/DataBackupTest.java
exist-core/src/test/java/org/exist/storage/blob/BlobStoreRecoveryTest.java

Closes https://github.com/eXist-db/exist/issues/2893

Fix deadlock which can occur with System Tasks

---

exist-core/src/main/java/org/exist/backup/ConsistencyCheck.java
exist-core/src/main/java/org/exist/backup/ExportGUI.java
exist-core/src/main/java/org/exist/backup/ExportMain.java
exist-core/src/main/java/org/exist/backup/SystemExport.java
exist-core/src/main/java/org/exist/scheduler/impl/ShutdownTask.java
exist-core/src/main/java/org/exist/storage/BackupSystemTask.java
exist-core/src/main/java/org/exist/storage/BrokerPool.java
exist-core/src/main/java/org/exist/storage/ConsistencyCheckTask.java
exist-core/src/main/java/org/exist/storage/DBBroker.java
exist-core/src/main/java/org/exist/storage/DataBackup.java
exist-core/src/main/java/org/exist/storage/NativeBroker.java
exist-core/src/main/java/org/exist/storage/SystemTask.java
exist-core/src/main/java/org/exist/storage/SystemTaskManager.java
exist-core/src/main/java/org/exist/storage/statistics/IndexStatisticsWorker.java
exist-core/src/main/java/org/exist/storage/sync/SyncTask.java
exist-core/src/main/java/org/exist/storage/txn/TransactionManager.java
exist-core/src/main/java/org/exist/xquery/functions/system/FnExport.java
exist-core/src/main/java/org/exist/xquery/functions/system/UpdateStatistics.java
exist-core/src/test/java/org/exist/backup/SystemExportFiltersTest.java
exist-core/src/test/java/org/exist/backup/SystemExportImportTest.java
exist-core/src/test/java/org/exist/storage/DataBackupTest.java
exist-core/src/test/java/org/exist/storage/blob/BlobStoreRecoveryTest.java

Backport of https://github.com/eXist-db/exist/pull/2983

(5.0.0) Fix a deadlock which can occur with System Tasks

---

exist-installer/src/main/izpack/install.xml

Backport of https://github.com/eXist-db/exist/pull/2988

(5.0.0) Small fixes to the IzPack installer

---

exist-core/pom.xml
exist-distribution/pom.xml
exist-docker/pom.xml
exist-parent/pom.xml
exist-service/pom.xml
extensions/indexes/spatial/pom.xml
extensions/modules/cqlparser/pom.xml

Dependabot only operates on the `develop` branch. This PR updates the dependencies of `develop-5.0.0` inline with those of `develop`.

(5.0.0) Update dependencies inline with 'develop' branch

---

exist-core/src/main/java/org/exist/launcher/WindowsServiceManager.java
exist-distribution/src/main/config/log4j2.xml

Backport of https://github.com/eXist-db/exist/pull/2995

(5.0.0) Fix eXist-db Service on Windows

---

exist-core/src/main/java/org/exist/launcher/WindowsServiceManager.java
exist-distribution/src/main/config/log4j2.xml

Related to https://github.com/eXist-db/exist/issues/2994

Fix eXist-db Service on Windows

---

exist-core/src/main/java/org/exist/backup/ConsistencyCheck.java
exist-core/src/main/java/org/exist/backup/restore/RestoreHandler.java
exist-core/src/main/java/org/exist/storage/DBBroker.java
exist-core/src/main/java/org/exist/storage/SystemTask.java
exist-core/src/main/java/org/exist/util/WeakLazyStripes.java

Fix javadoc

---

exist-core/src/main/java/org/exist/backup/ConsistencyCheck.java
exist-core/src/main/java/org/exist/backup/restore/RestoreHandler.java
exist-core/src/main/java/org/exist/storage/DBBroker.java
exist-core/src/main/java/org/exist/storage/SystemTask.java
exist-core/src/main/java/org/exist/util/WeakLazyStripes.java

Backport of https://github.com/eXist-db/exist/pull/2999

(5.0.0) Fix javadoc

---

exist-core/src/main/java/org/exist/client/InteractiveClient.java

Closes https://github.com/eXist-db/exist/issues/3007

Fix inverted command line arg test in Java Admin Client.

---

.travis.yml

Avoid failing macOS builds on travis

---

exist-core/src/main/java/org/exist/storage/DBBroker.java
exist-core/src/main/java/org/exist/storage/txn/TransactionManager.java
exist-core/src/main/java/org/exist/storage/txn/Txn.java
exist-core/src/test/java/org/exist/storage/AbstractRecoverTest.java
exist-core/src/test/java/org/exist/storage/journal/AbstractJournalTest.java
exist-core/src/test/java/org/exist/storage/txn/ReusableTxnTest.java
exist-core/src/test/java/org/exist/storage/txn/TransactionManagerTestHelper.java
exist-core/src/test/java/org/exist/storage/txn/TxnTest.java

Simple change to allow multiple transactions per-broker.

Allow multiple transactions per broker

---

extensions/modules/expathrepo/pom.xml

based on feedback adam:
https://github.com/eXist-db/exist/pull/2949#pullrequestreview-297824962

Rework classloader: pom

---

exist-core/src/main/java/org/exist/security/SimpleACLPermission.java
exist-core/src/main/java/org/exist/security/internal/aider/SimpleACLPermissionAider.java
exist-core/src/main/java/org/exist/storage/NativeBroker.java
exist-core/src/main/java/org/exist/xquery/functions/fn/ExtCollection.java
exist-core/src/main/java/org/exist/xquery/functions/fn/FunDoc.java
exist-core/src/test/java/org/exist/security/AbstractApiSecurityTest.java
exist-core/src/test/java/org/exist/security/ApiException.java
exist-core/src/test/java/org/exist/security/FnCollectionSecurityTest.java
exist-core/src/test/java/org/exist/security/FnDocSecurityTest.java
exist-core/src/test/java/org/exist/security/RestApiSecurityTest.java
exist-core/src/test/java/org/exist/security/XmldbApiSecurityTest.java
exist-core/src/test/java/org/exist/security/XqueryApiTest.java
extensions/indexes/lucene/src/test/java/org/exist/indexing/lucene/OptimizerTest.java

I have intentionally left the details of this absent so as not to explicitly inform people on how to exploit the issue.

Fix a security issue with collection access

---

exist-core/src/main/java/org/exist/http/RESTServer.java
exist-core/src/main/java/org/exist/storage/serializers/XIncludeFilter.java

Closes https://github.com/eXist-db/exist/issues/3058

Make sure that compiled queries are returned to the pool

---

exist-core/src/main/java/org/exist/storage/NativeBroker.java

Backport of https://github.com/eXist-db/exist/pull/3078

(4.x.x) Avoid NPE when reporting error

---

extensions/modules/sql/pom.xml
extensions/modules/sql/src/main/java/org/exist/xquery/modules/sql/ExecuteFunction.java
extensions/modules/sql/src/main/java/org/exist/xquery/modules/sql/GetConnectionFunction.java
extensions/modules/sql/src/main/java/org/exist/xquery/modules/sql/GetJNDIConnectionFunction.java
extensions/modules/sql/src/main/java/org/exist/xquery/modules/sql/PrepareFunction.java
extensions/modules/sql/src/main/java/org/exist/xquery/modules/sql/PreparedStatementWithSQL.java
extensions/modules/sql/src/main/java/org/exist/xquery/modules/sql/SQLModule.java
extensions/modules/sql/src/main/java/org/exist/xquery/modules/sql/SQLUtils.java
extensions/modules/sql/src/test/java/org/exist/xquery/modules/sql/ExecuteFunctionTest.java

1. You can now get results back from calling Stored Procedures
2. You can now specify `<sql:null/>` inside a `<sql:param>` when calling a stored procedure, see https://github.com/eXist-db/exist/issues/2139

Some small improvements to the SQL Module

---

exist-core/src/main/java/org/exist/xquery/UnaryExpr.java
exist-core/src/test/xquery/treatAs.xq
exist-core/src/test/xquery/xquery3/bang.xql

Closes https://github.com/eXist-db/exist/issues/3111

Fix a StackOverflowError caused by lost type into

---

extensions/indexes/lucene/src/main/java/org/exist/indexing/lucene/XMLToQuery.java
extensions/indexes/lucene/src/test/xquery/lucene/queries.xml

add support for minimum-must-match on BooleanQuery
added tests
fixes #392
can one help with documentation?

Lucene:  add support for minimum-must-match on BooleanQuery 

---

extensions/modules/xslfo/pom.xml
extensions/modules/xslfo/src/main/java/org/exist/xquery/modules/xslfo/ApacheFopProcessorAdapter.java
extensions/modules/xslfo/src/test/java/org/exist/xquery/modules/xslfo/ApacheFopTest.java
extensions/modules/xslfo/src/test/resources-filtered/conf.xml
extensions/modules/xslfo/src/test/resources/log4j2.xml

Closes https://github.com/eXist-db/exist/issues/3125

Fix an NPE with Apache FOP XSL:FO rendering

---

exist-core/src/main/java/org/exist/xquery/functions/array/ArrayFunction.java
exist-core/src/main/java/org/exist/xquery/functions/array/ArrayModule.java
exist-core/src/main/java/org/exist/xquery/functions/array/ArrayType.java
exist-core/src/test/xquery/arrays/arrays.xql

Implemented array:put
[array:put](https://www.w3.org/TR/xpath-functions-31/#func-array-put)
XQSuite Tests: exist-core/src/test/xquery/arrays/arrays.xql

[feature] implemented array:put

---

exist-core/src/test/java/org/exist/storage/BrokerPoolsTest.java

Fixes illegal characters in path

Fixes illegal characters in path

---

exist-core/src/test/java/org/exist/storage/BrokerPoolsTest.java

Test should override default config

---

exist-core/src/main/java/org/exist/management/AgentFactory.java
exist-core/src/main/java/org/exist/management/impl/JMXAgent.java
exist-core/src/main/java/org/exist/storage/BrokerPool.java
exist-core/src/main/java/org/exist/storage/BrokerPoolServicesManager.java
exist-core/src/main/java/org/exist/storage/ContentLoadingObserver.java
exist-core/src/main/java/org/exist/storage/DefaultCacheManager.java
exist-core/src/main/java/org/exist/storage/NativeBroker.java
exist-core/src/main/java/org/exist/storage/NativeValueIndex.java
exist-core/src/main/java/org/exist/storage/btree/BTree.java
exist-core/src/main/java/org/exist/storage/btree/Paged.java
exist-core/src/main/java/org/exist/storage/dom/DOMFile.java
exist-core/src/main/java/org/exist/storage/index/BFile.java
exist-core/src/main/java/org/exist/util/Lockable.java

Closes https://github.com/eXist-db/exist/pull/3169

(4.x.x) Memory leak on shutdown

---

exist-core/src/main/java/org/exist/xquery/value/SubSequence.java
exist-core/src/test/xquery/subsequence.xq

Closes https://github.com/eXist-db/exist/issues/3148

Fix cast exception in fn:subsequence

---

exist-core/src/main/java/org/exist/xmldb/RemoteXMLResource.java
exist-core/src/main/java/org/exist/xquery/functions/fn/JSON.java

Correct broken javadoc - prevents a release!

Fix broken javadoc

---

exist-versioning-release.md

Pass args to release plugin

---

.idea/runConfigurations/Java_Admin_Client.xml
.idea/runConfigurations/Jetty_Server.xml

Update IntelliJ config for 5.3.0-SNAPSHOT

---

exist-core/src/main/java/org/exist/xquery/FunctionFactory.java
exist-core/src/main/java/org/exist/xquery/functions/util/Compile.java

Closes https://github.com/eXist-db/exist/issues/1583

Make sure the context is preserved when dynamically compiling a query

---

exist-core/src/main/java/org/exist/http/Descriptor.java

Closes https://github.com/eXist-db/exist/issues/2808

Descriptor file should be read from $EXIST_HOME/etc

---

exist-core/src/main/java/org/exist/xquery/CastExpression.java
exist-core/src/main/java/org/exist/xquery/UntypedValueCheck.java
exist-core/src/main/java/org/exist/xquery/functions/array/ArrayType.java
exist-core/src/main/java/org/exist/xquery/value/IntegerValue.java
exist-core/src/test/java/org/exist/xquery/value/DoubleValueTest.java
exist-core/src/test/xquery/integers.xq

Closes https://github.com/eXist-db/exist/issues/1849

Fix type conversion of xs:positiveInteger and xs:negativeInteger types 

---

exist-core/src/main/java/org/exist/scheduler/impl/QuartzSchedulerImpl.java
exist-distribution/src/main/config/quartz.properties

Closes https://github.com/eXist-db/exist/issues/3252

Make Quartz Scheduler properties easily configurable

---

exist-core/src/main/java/org/exist/xquery/functions/fn/ParsingFunctions.java
exist-core/src/test/xquery/xquery3/parse-xml.xq

Closes https://github.com/eXist-db/exist/issues/2181

fn:parse-xml-fragment should return a document-node()

---

exist-core/src/main/java/org/exist/xquery/functions/fn/FunUnparsedText.java

Closes https://github.com/eXist-db/exist/issues/3220

With fn:unparsed-text#1 non-dba users should only be restricted from filesystem

---

exist-core/src/main/java/org/exist/launcher/ConfigurationDialog.java
exist-core/src/main/java/org/exist/launcher/ConfigurationUtility.java
exist-core/src/main/java/org/exist/launcher/Launcher.java
exist-core/src/main/java/org/exist/launcher/LauncherWrapper.java
exist-core/src/main/java/org/exist/launcher/WindowsServiceManager.java

1. Make sure that -Xmx is set in the service from the Launcher.
2. Present a `Never` option for installing as a service, so the user is not prompted at every startup.
Closes https://github.com/eXist-db/exist/issues/3230
Closes https://github.com/eXist-db/exist/issues/3253

Fix some small Windows Service issues

---

exist-core/src/main/java/org/exist/dom/persistent/NodeProxy.java
exist-core/src/main/java/org/exist/xquery/InstanceOfExpression.java
exist-core/src/main/java/org/exist/xquery/LetExpr.java
exist-core/src/main/java/org/exist/xquery/VariableImpl.java
exist-core/src/main/java/org/exist/xquery/value/SequenceType.java
exist-core/src/test/xquery/document-nodes.xq

Closes https://github.com/eXist-db/exist/issues/1932

Fix some issues with document-node type checks

---

exist-core/src/main/java/org/exist/storage/index/CollectionStore.java

Just an updated and refactored version of @shabanovd's earlier suggestion #1324. Thanks Dmitriy :-)
Closes https://github.com/eXist-db/exist/pull/1324

Switch to nonblocking free ids processing algorithms

---

exist-core/pom.xml

See https://github.com/eXist-db/exist/issues/3025

Update Jing and switch to official artifact

---

exist-core/src/main/java/org/exist/interpreter/Context.java
exist-core/src/main/java/org/exist/repo/ExistRepository.java
exist-core/src/main/java/org/exist/xquery/ErrorCodes.java
exist-core/src/main/java/org/exist/xquery/XQueryContext.java
exist-core/src/main/java/org/exist/xquery/functions/fn/LoadXQueryModule.java
exist-core/src/main/java/org/exist/xquery/functions/inspect/InspectionModule.java
exist-core/src/main/java/org/exist/xquery/functions/inspect/ModuleFunctions.java
exist-core/src/main/java/org/exist/xquery/value/AnyURIValue.java

Closes https://github.com/eXist-db/exist/pull/1285

Ensure Inspect Module functions throws errors appropriately

---

exist-core/src/main/java/org/exist/xquery/functions/system/FnExport.java

Small cleanup and refactoring to make logic around push/pop document context clearer

Refactor system:export

---

exist-core/src/main/java/org/exist/dom/persistent/NodeProxy.java
exist-core/src/main/java/org/exist/storage/dom/DOMFile.java
exist-core/src/main/java/org/exist/test/runner/ExtTestErrorFunction.java
exist-core/src/main/java/org/exist/test/runner/JUnitIntegrationFunction.java
exist-core/src/test/xquery/unicode.xqm

Closes https://github.com/eXist-db/exist/issues/780
p.s. If anyone is interested in eXist-db 4.x.x then this needs back-porting to there too (by someone else)

Fix the UTF8 decoding of Node Values

---

exist-core/src/main/java/org/exist/launcher/SplashScreen.java

Closes https://github.com/eXist-db/exist/issues/3301

Don't keep the splash screen in front of everything else

---

exist-core/pom.xml
exist-core/src/main/java/org/exist/util/serializer/AdaptiveWriter.java
exist-core/src/main/java/org/exist/util/serializer/json/JSONSerializer.java
exist-core/src/main/java/org/exist/xquery/Lookup.java
exist-core/src/main/java/org/exist/xquery/XQueryContext.java
exist-core/src/main/java/org/exist/xquery/functions/array/ArrayType.java
exist-core/src/main/java/org/exist/xquery/functions/fn/FnRandomNumberGenerator.java
exist-core/src/main/java/org/exist/xquery/functions/fn/FunDeepEqual.java
exist-core/src/main/java/org/exist/xquery/functions/fn/FunSerialize.java
exist-core/src/main/java/org/exist/xquery/functions/fn/LoadXQueryModule.java
exist-core/src/main/java/org/exist/xquery/functions/map/AbstractMapType.java
exist-core/src/main/java/org/exist/xquery/functions/map/MapExpr.java
exist-core/src/main/java/org/exist/xquery/functions/map/MapFunction.java
exist-core/src/main/java/org/exist/xquery/functions/map/MapType.java
exist-core/src/main/java/org/exist/xquery/functions/map/SingleKeyMapType.java
exist-core/src/main/java/org/exist/xquery/util/SerializerUtils.java
exist-core/src/main/java/org/exist/xquery/value/ArrayListValueSequence.java
exist-core/src/test/xquery/maps/maps.xql
exist-core/src/test/xquery/maps/mapsLookup.xql
exist-core/src/test/xquery/xquery3/arrowop.xql
exist-parent/pom.xml
extensions/indexes/lucene/pom.xml
extensions/indexes/lucene/src/main/java/org/exist/xquery/modules/lucene/Facets.java
extensions/indexes/lucene/src/main/java/org/exist/xquery/modules/lucene/QueryOptions.java
extensions/indexes/lucene/src/test/xquery/lucene/facets.xql

My research leads me to believe that this is the fastest implementation available for the JVM.
Could a couple of people give this a test and see if it speeds up their XQuery Maps code?

A more performant implementation of immutable maps

---

exist-core/src/main/java/org/exist/xquery/value/IntegerValue.java
exist-core/src/test/xquery/integers.xq

Fixes a regression introduced in https://github.com/eXist-db/exist/pull/3266
Closes https://github.com/eXist-db/exist/issues/3323

Fix casting integers as union type xs:numeric

---

exist-core/src/main/java/org/exist/test/runner/ExtTestErrorFunction.java

Avoid an NPE when reconstructing nested stack traces

---

exist-core/src/main/java/org/exist/client/DocumentView.java

Remove system.out message for debugging

---

exist-core/src/main/java/org/exist/xquery/functions/fn/FnFormatNumbers.java
exist-core/src/test/xquery/numbers/format-numbers.xql

Closes https://github.com/eXist-db/exist/issues/3346

Fix bounds issues with group separators in fn:format-number

---

exist-core/src/main/java/org/exist/xquery/functions/fn/ExtCollection.java

Closes https://github.com/eXist-db/exist/issues/1964

fn:collection should only return XML documents

---

exist-core/src/main/java/org/exist/xquery/Function.java
exist-core/src/main/java/org/exist/xquery/PathExpr.java
exist-core/src/main/java/org/exist/xquery/functions/fn/FunHigherOrderFun.java
exist-core/src/main/java/org/exist/xquery/functions/fn/FunReverse.java
exist-core/src/main/java/org/exist/xquery/functions/fn/FunStrLength.java
exist-core/src/main/java/org/exist/xquery/functions/fn/FunSubSequence.java
exist-core/src/test/xquery/xquery3/bang.xql

Closes https://github.com/eXist-db/exist/issues/2798

Context Item should not be atomized when used as argument for fn:string-length

---

exist-core/src/main/java/org/exist/dom/QName.java
exist-core/src/main/java/org/exist/interpreter/Context.java
exist-core/src/main/java/org/exist/xquery/FunctionId.java
exist-core/src/main/java/org/exist/xquery/XQueryContext.java
exist-core/src/test/xquery/last.xql
exist-core/src/test/xquery/unparsed-text.xql
exist-core/src/test/xquery/xquery3/arrowop.xql
exist-core/src/test/xquery/xquery3/fnSort.xql
exist-core/src/test/xquery/xquery3/serialize.xql
extensions/indexes/lucene/src/test/xquery/lucene/facets.xql
extensions/indexes/range/src/test/xquery/range/conditions.xql
extensions/indexes/range/src/test/xquery/range/types.xql

Prohibit functions with the same name and arity as per the XQuery spec.
Closes https://github.com/eXist-db/exist/issues/1665
Closes https://github.com/eXist-db/exist/issues/1174

Prohibit duplicate function declarations

---

exist-core/src/test/xquery/xquery3/xq3-is-not-xq31.xml

When I saw this test I thought it would be wrong. The name is misleading. I therefore changed the name to make its goal a little clearer.

[test] rename test to clarify goal

---

exist-core/src/main/java/org/exist/client/QueryDialog.java

Small fixes to avoid stack-traces on the console when selecting items from the query history etc in the Java Admin Client.

Avoid IndexOutOfBounds when selecting combo box items in JAC

---

exist-core/src/main/java/org/exist/test/runner/ExtTestErrorFunction.java
exist-core/src/main/java/org/exist/xquery/functions/fn/LoadXQueryModule.java
exist-core/src/main/java/org/exist/xquery/functions/inspect/ModuleFunctions.java
exist-core/src/test/java/xquery/securitymanager/SecurityManagerTests.java
exist-core/src/test/xquery/securitymanager/id.xqm

See https://exist.markmail.org/thread/pozp5mh4w7z22fmr

Fix an NPE with Security Context in dynamically loaded modules

---

.travis.yml

Deploy step is only run from JDK8 build env, so let's make sure that one passes!

Fix Travis Deploy step

---

.travis.yml

see #3395
we ll only know if this fixes the problem, once it is merged to develop unfortunately.

fix deployment syntax on travis

---

exist-core/src/main/java/org/exist/xquery/functions/inspect/InspectionModule.java
exist-core/src/main/java/org/exist/xquery/functions/system/SystemModule.java
exist-core/src/main/java/org/exist/xquery/functions/util/UtilModule.java
exist-core/src/main/java/org/exist/xquery/functions/xmldb/XMLDBModule.java
exist-core/src/test/xquery/inspect/inspect.xql
extensions/modules/cache/src/main/java/org/exist/xquery/modules/cache/CacheModule.java
extensions/modules/compression/src/main/java/org/exist/xquery/modules/compression/CompressionModule.java
extensions/modules/sql/src/main/java/org/exist/xquery/modules/sql/SQLUtils.java

Repair module prefixes. Fixes #3424

---

exist-core/src/main/java/org/exist/xquery/functions/util/BuiltinFunctions.java

Fixes #3425
(adam: sorry, there is a bit of mark-up changed too; I tried to rework original PR and then all fell down)

Add java modules to list functions. Fixes #3425

---

exist-core/src/main/java/org/exist/storage/NativeValueIndex.java
exist-core/src/main/java/org/exist/test/runner/ExtTestFailureFunction.java
exist-core/src/main/java/org/exist/xquery/functions/map/MapExpr.java
exist-core/src/test/java/org/exist/xquery/ValueIndexTest.java

Very small backports of small improvements.

Small fixes

---

README.md

Need to update the link to the O'Reilly book

Fix link to book

---

exist-core/src/main/java/org/exist/xquery/ConditionalExpression.java

bugfix: add missing location from error messages

---

exist-core/src/main/java/org/exist/xquery/FilteredExpression.java

Isolate location from predicate and add to exception
Closes #3462

Get location from predicate evaluation and add to exception

---

exist-core/src/test/java/org/exist/storage/DataBackupTest.java

Just a simple additional test.

Make sure the blob.dbx is present in the data backup

---

exist-core/src/main/java/org/exist/xquery/functions/fn/FunMatches.java

Small cleanup to fn:matches code

---

exist-core/src/main/java/org/exist/jetty/JettyStart.java
exist-core/src/main/java/org/exist/storage/BrokerPools.java
exist-core/src/main/java/org/exist/storage/dom/NodeIterator.java
exist-core/src/main/java/org/exist/util/MimeTable.java
exist-core/src/main/java/org/exist/xquery/functions/system/Shutdown.java
exist-core/src/test/java/org/exist/http/urlrewrite/URLRewritingTest.java
exist-core/src/test/java/org/exist/management/JmxRemoteTest.java
exist-core/src/test/java/org/exist/storage/DirtyShutdownTest.java
exist-core/src/test/java/org/exist/xmldb/IndexingTest.java
exist-core/src/test/resources/log4j2.xml
extensions/debuggee/src/test/resources/log4j2.xml
extensions/expath/src/test/resources/log4j2.xml
extensions/exquery/restxq/src/test/java/org/exist/extensions/exquery/restxq/impl/IntegrationTest.java
extensions/security/activedirectory/src/test/resources/log4j2.xml
extensions/xqdoc/src/test/resources/log4j2.xml

* several small fixes all related to shutdown when running tests

Fixes to shutdown when running tests

---

exist-core/src/main/java/org/exist/repo/ExistRepository.java
exist-core/src/main/java/org/exist/storage/btree/Paged.java
exist-core/src/main/java/org/exist/util/JDKCompatibility.java
exist-core/src/main/java/org/exist/xmldb/EXistCollectionManagementService.java
exist-core/src/main/java/org/exist/xquery/Cardinality.java
exist-core/src/main/java/org/exist/xquery/functions/map/MapType.java
extensions/indexes/lucene/src/main/java/org/exist/indexing/lucene/LuceneConfig.java
extensions/indexes/lucene/src/main/java/org/exist/indexing/lucene/LuceneIndexWorker.java
extensions/indexes/lucene/src/main/java/org/exist/indexing/lucene/NodePathPattern.java
extensions/modules/compression/src/main/java/org/exist/xquery/modules/compression/AbstractExtractFunction.java
extensions/modules/file/src/main/java/org/exist/xquery/modules/file/DirectoryList.java

Small javadoc fixes to repair the build.

Fix javadocs

---

exist-core/src/test/java/org/exist/collections/CollectionRemovalTest.java

Simplify test setup

---

exist-core/src/main/java/org/exist/xquery/SwitchExpression.java
exist-core/src/test/xquery/xquery3/xq3_switch.xml

Proposed fix for NPE with empty case expression.
Fixes #3560

Proposed fix for NPE with empty case expression. Fixes 3560

---

.travis.yml

See https://github.com/eXist-db/exist/issues/3375

Allow Travis CI JDK14 job to fail

---

exist-core/src/main/java/org/exist/dom/persistent/ElementImpl.java
exist-core/src/main/java/org/exist/storage/NodePath.java
exist-core/src/main/java/org/exist/storage/NodePath2.java
exist-core/src/test/java/org/exist/storage/NodePathTest.java
exist-core/src/test/java/org/exist/xquery/update/AbstractTestUpdate.java
exist-core/src/test/java/org/exist/xquery/update/UpdateReplaceTest.java
exist-core/src/test/java/org/exist/xquery/update/UpdateValueTest.java
extensions/indexes/lucene/src/main/java/org/exist/indexing/lucene/NodePathPattern.java

Closes https://github.com/eXist-db/exist/issues/3475

Fix an NPE in XQuery Update Replace

---

extensions/modules/expathrepo/src/test/resources/org/exist/repo/README.md

Simple doc of where to find the source code.

Add details of where to find the XAR source-code

---

exist-core/pom.xml
exist-core/src/main/java/org/exist/xquery/Except.java
exist-core/src/main/java/org/exist/xquery/Intersect.java
exist-core/src/main/java/org/exist/xquery/functions/array/ArrayFunction.java
exist-core/src/main/java/org/exist/xquery/functions/array/ArrayModule.java
exist-core/src/main/java/org/exist/xquery/functions/array/ArrayType.java
exist-core/src/main/java/org/exist/xquery/functions/fn/FunData.java
exist-core/src/main/java/org/exist/xquery/value/ArrayListValueSequence.java
exist-core/src/main/java/org/exist/xquery/value/AtomicValueComparator.java
exist-core/src/main/java/org/exist/xquery/value/SequenceComparator.java
exist-core/src/main/java/org/exist/xquery/value/ValueSequence.java
exist-core/src/test/xquery/arrays/arrays.xql

Implementation of array:sort

---

.travis.yml

Upgrade to curent OpenJDK version (15) in Travis

Update to Java15

---

exist-ant/src/main/java/org/exist/ant/AbstractXMLDBTask.java
exist-ant/src/main/java/org/exist/ant/AddGroupTask.java
exist-ant/src/main/java/org/exist/ant/AddUserTask.java
exist-ant/src/main/java/org/exist/ant/BackupTask.java
exist-ant/src/main/java/org/exist/ant/ChmodTask.java
exist-ant/src/main/java/org/exist/ant/ChownTask.java
exist-ant/src/main/java/org/exist/ant/ListGroupsTask.java
exist-ant/src/main/java/org/exist/ant/ListUsersTask.java
exist-ant/src/main/java/org/exist/ant/LockResourceTask.java
exist-ant/src/main/java/org/exist/ant/RemoveGroupTask.java
exist-ant/src/main/java/org/exist/ant/RemoveUserTask.java
exist-ant/src/main/java/org/exist/ant/RestoreTask.java
exist-ant/src/main/java/org/exist/ant/UserPasswordTask.java
exist-ant/src/main/java/org/exist/ant/XMLDBCopyTask.java
exist-ant/src/main/java/org/exist/ant/XMLDBCreateTask.java
exist-ant/src/main/java/org/exist/ant/XMLDBExistTask.java
exist-ant/src/main/java/org/exist/ant/XMLDBExtractTask.java
exist-ant/src/main/java/org/exist/ant/XMLDBListTask.java
exist-ant/src/main/java/org/exist/ant/XMLDBMoveTask.java
exist-ant/src/main/java/org/exist/ant/XMLDBRemoveTask.java
exist-ant/src/main/java/org/exist/ant/XMLDBStoreTask.java
exist-ant/src/main/java/org/exist/ant/XMLDBXPathTask.java
exist-ant/src/main/java/org/exist/ant/XMLDBXQueryTask.java
exist-ant/src/main/java/org/exist/ant/XMLDBXUpdateTask.java
exist-start/src/main/java/org/exist/start/Classpath.java
exist-start/src/main/java/org/exist/start/Main.java
exist-start/src/main/java/org/exist/start/StopException.java
exist-start/src/main/java/org/exist/start/Version.java
extensions/exquery/restxq/src/main/java/org/exist/extensions/exquery/restxq/impl/ExistXqueryRegistry.java

Small code improvements

---

exist-ant/src/main/java/org/exist/ant/XMLDBExtractTask.java
exist-core/src/main/java/org/exist/client/DocumentView.java

Fixing some resource management issues

---

exist-core/src/main/java/org/exist/xquery/RootNode.java
exist-core/src/test/java/org/exist/storage/ShutdownTest.java
exist-core/src/test/xquery/util/eval-with-context.xql

Closes https://github.com/eXist-db/exist/issues/3039

Make sure the correct context sequence is used with util:eval-with-context

---

exist-ant/src/main/java/org/exist/ant/XMLDBExtractTask.java
exist-core/src/main/java/org/exist/storage/XQueryPool.java

Simple code change to check codacy.

Simple code change to check codacy.

---

.github/workflows/build.yml
exist-parent/pom.xml

Finger crossed
https://sonarcloud.io/organizations/exist-db/projects

Add sonarcloud

---

exist-core/src/main/java/org/exist/http/servlets/ExistExtensionServlet.java
exist-core/src/main/java/org/exist/jetty/JettyStart.java
extensions/security/iprange/pom.xml
extensions/security/iprange/src/main/java/org/exist/security/realm/iprange/IPRangeServlet.java
extensions/security/iprange/src/main/resources/META-INF/services/org.exist.http.servlets.ExistExtensionServlet

Currently the IPrange servlet is (more or less) hardcoded initialised during eXist-db startup.
I think that this specific servlet should be removed BUT the concept introduced in this PR might be useful eg for authentication/authorization alternatives.
Please could you share some thoughts ?

Concept: Make servlets pluggable

---

exist-core/src/main/java/org/exist/xquery/functions/securitymanager/AccountStatusFunction.java
exist-core/src/test/xquery/securitymanager/account.xqm

Fix for  #3688

---

exist-core/src/main/java/org/exist/backup/Backup.java
exist-core/src/main/java/org/exist/client/ClientFrame.java

Handle NPE, fixes #3677
If user does not explicitly agree to delete backup folder/file, abort backup. (cannot find issue report)
potential open issue: position of new dialog boxes

Improve backup-ui dialog flow

---

exist-core/src/main/java/org/exist/xquery/functions/math/NoParamFunctions.java
exist-core/src/main/java/org/exist/xquery/functions/math/OneParamFunctions.java
exist-core/src/main/java/org/exist/xquery/functions/math/TwoParamFunctions.java

NPEs found in XQTS suite for math functions. 
one issue remaining, see below

Prevent NPEs in math:* functions. Tested in XQTS suite

---

.github/workflows/build.yml
exist-core/pom.xml
exist-distribution/pom.xml
exist-parent/pom.xml
extensions/debuggee/pom.xml
extensions/modules/file/pom.xml
extensions/modules/persistentlogin/pom.xml

- converts the argument line into system property variables
- defines a fixed user environment for running the tests

Use fixed user environment for tests

---

BUILD.md

Given the lack of knowledge on how to build the docker image, and as users as lazy to read documentation, I added a couple of items in the BUILD.md  to clarity.

Add useful switches in the readme

---

exist-core/src/main/java/org/exist/xquery/value/NumericValue.java
exist-core/src/test/xquery/numbers/nan.xq

Closes https://github.com/eXist-db/exist/issues/3723
Fixes comparisons where the left-or-right of a numeric comparison is NaN

Fix NaN comparisons

---

exist-core/src/main/java/org/exist/xquery/value/Type.java

Closes https://github.com/eXist-db/exist/issues/3727

 xs:anyType is the top of a Type hierarchy, don't look further

---

.github/workflows/ci.yml

Fix typo in CI config

---

.github/workflows/ci.yml
exist-core/src/main/java/org/exist/collections/triggers/Trigger.java
exist-core/src/main/java/org/exist/http/servlets/XQueryServlet.java
exist-core/src/main/java/org/exist/storage/blob/BlobStore.java
exist-core/src/main/java/org/exist/storage/btree/Paged.java
exist-core/src/main/java/org/exist/storage/journal/JournalManager.java
exist-core/src/main/java/org/exist/storage/journal/LogEntryTypes.java
exist-core/src/main/java/org/exist/xmldb/MapResourceSet.java
exist-core/src/main/java/org/exist/xquery/FunctionDSL.java
exist-core/src/main/java/org/exist/xquery/FunctionSignature.java
exist-core/src/main/java/org/exist/xquery/functions/inspect/InspectFunctionHelper.java
exist-core/src/main/java/org/exist/xquery/functions/inspect/InspectModule.java
exist-core/src/main/java/org/exist/xquery/functions/inspect/InspectionModule.java
exist-core/src/main/java/org/exist/xquery/functions/inspect/ModuleFunctions.java
exist-core/src/main/java/org/exist/xquery/functions/util/BuiltinFunctions.java
exist-core/src/main/java/org/exist/xquery/functions/util/DescribeFunction.java
exist-core/src/main/java/org/exist/xquery/functions/util/InspectFunction.java
exist-core/src/main/java/org/exist/xquery/functions/util/ModuleInfo.java
exist-core/src/main/java/org/exist/xquery/functions/util/PrologFunctions.java
exist-core/src/main/java/org/exist/xquery/functions/util/UtilModule.java
exist-core/src/test/java/org/exist/storage/BrokerPoolsTest.java
exist-core/src/test/java/org/exist/storage/lock/CollectionLocksTest.java
exist-parent/pom.xml

Further fixes to CI

---

.github/workflows/ci.yml

still with jetty copy-rename errors
but it deploys docker images closes #3696, 
supersedes #3756
removes appveyor, runs j15 only on ubuntu
feel free to squash and merge

Add Docker to CI and tweak CI settings

---

README.md

GitHub CI Badge in README.md should be for the `develop` branch

---

extensions/modules/cqlparser/pom.xml

[hotfix] repair build CQL Parser Module

---

README.md

Before:
> <img width="341" alt="Screen Shot 2021-04-07 at 3 27 37 PM" src="https://user-images.githubusercontent.com/59118/113922960-f1690b00-97b5-11eb-9e6d-31a8c8aa21cc.png">
After:
> <img width="348" alt="Screen Shot 2021-04-07 at 3 29 03 PM" src="https://user-images.githubusercontent.com/59118/113922993-ffb72700-97b5-11eb-81ee-b16212664680.png">
n/a
n/a

Fix URL for build status page and badge

---

exist-core/src/main/java/org/exist/management/impl/SystemInfo.java
exist-parent/pom.xml

Signed-off-by: Patrick Reinhart <patrick@reini.net>

Fixes corrupted stream message with maven-surefire-plugin

---

exist-core/src/main/java/org/exist/http/urlrewrite/XQueryURLRewrite.java
exist-core/src/test/java/org/exist/http/AbstractHttpTest.java
exist-core/src/test/java/org/exist/http/urlrewrite/ControllerTest.java
exist-core/src/test/java/org/exist/http/urlrewrite/URLRewritingTest.java

Closes https://github.com/eXist-db/exist/issues/3739

Look for controller.xq before controller.xql

---

exist-core/src/main/java/org/exist/dom/memtree/DocumentImpl.java
exist-core/src/main/java/org/exist/dom/persistent/ElementImpl.java
exist-core/src/main/java/org/exist/xquery/functions/fn/FnModule.java
exist-core/src/main/java/org/exist/xquery/functions/fn/FunBaseURI.java
exist-core/src/test/xquery/base-uri.xql

Clean version of the former PR https://github.com/eXist-db/exist/pull/3700

[bugfix] reimplement fn:base-uri()

---

appveyor.yml

- upgrade Ubuntu
- remove docker part

[hotfix] repair appveyor build

---

exist-core/src/main/java/org/exist/repo/AutoDeploymentTrigger.java
exist-docker/src/main/xslt/log4j2-docker.xslt

1. Log a warning if autodeploy dir is not found
2. Show Repo logs on the Docker stdout console

Import repo logging

---

exist-docker/src/test/bats/01-connect-spec.bats

[fix] test the feature in container

---

exist-core/src/main/java/org/exist/util/io/TemporaryFileManager.java

Fixes #3826 
Appears to be a problem on Centos/REHL and Ubuntu.

[Bugfix] Repair missing tmp dir TemporaryFileManager

---

exist-core/src/main/java/org/exist/xmldb/AbstractLocal.java

Fixes #3505 
Make sure transaction is aborted upon exception.

[HOTFIX] Avoid unauthorised creation of collections.

---

exist-core/src/main/java/org/exist/repo/ExistRepository.java
extensions/modules/xmldiff/pom.xml
extensions/modules/xmldiff/src/main/java/org/exist/xquery/modules/xmldiff/Compare.java

Closes https://github.com/eXist-db/exist/issues/3907

Very Small fixes

---

exist-core/src/main/java/org/exist/xquery/XQueryContext.java
exist-core/src/test/java/org/exist/xquery/ImportModuleTest.java

Closes https://github.com/eXist-db/exist/issues/3790

Fix arity in XQuery error when there are duplicate functions in a main module

---

extensions/modules/cache/src/main/java/org/exist/xquery/modules/cache/Cache.java
extensions/modules/cache/src/test/java/org/exist/xquery/modules/cache/LazyCacheTest.java
extensions/modules/cache/src/test/java/org/exist/xquery/modules/cache/NonLazyCacheTest.java
extensions/modules/cache/src/test/resources-filtered/lazy-cache-conf.xml
extensions/modules/cache/src/test/resources-filtered/non-lazy-cache-conf.xml

Closes https://github.com/eXist-db/exist/issues/3932

Further tests for Cache Module and a small NPE avoidance fix

---

.idea/runConfigurations/Java_Admin_Client.xml
.idea/runConfigurations/Jetty_Server.xml

These need to be updated to work with the new development version.

Update IntelliJ run configurations for 5.4.0-SNAPSHOT

---

exist-core/pom.xml
exist-parent/pom.xml
extensions/modules/file/pom.xml

- Use the Jakarta JAXB implementations instead of the old ones
- Extracts version definitions for the test environment

Use Jakarta JAXB and extracts Test versions

---

.github/workflows/ci-test.yml
exist-core/src/main/java/org/exist/test/runner/AbstractTestRunner.java
exist-core/src/main/java/org/exist/test/runner/XMLTestRunner.java
exist-core/src/main/java/org/exist/test/runner/XQueryTestRunner.java
exist-core/src/test/java/org/exist/storage/lock/CollectionLocksTest.java
exist-core/src/test/java/org/exist/test/runner/AbstractTestRunnerTest.java
exist-core/src/test/java/org/exist/test/runner/XMLTestRunnerTest.java
exist-core/src/test/java/org/exist/test/runner/XQueryTestRunnerTest.java
exist-core/src/test/resources/org/exist/test/runner/no-tests.xq
exist-core/src/test/resources/org/exist/test/runner/single-test.xq
exist-core/src/test/xquery/xquery3/inline.xml
exist-core/src/test/xquery/xquery3/recursion_calls.xml

This is an extraction from the PR of @reinhapa https://github.com/eXist-db/exist/pull/3322 to just focus on the improvement of XSuite test desciptions.

Fix issues with XSuite test descriptions

---

exist-parent/pom.xml

Fixes Saxon issue Bug #4684: "NullPointerException compiling a stylesheet using eXist-DB transform() function;"
for Alexander henket

[library] upgrade to most recent saxon 9.9 version

---

exist-core/pom.xml
exist-core/src/main/java/org/exist/collections/CollectionConfiguration.java
exist-core/src/main/java/org/exist/collections/MutableCollection.java
exist-core/src/main/java/org/exist/http/RESTServer.java
exist-core/src/main/java/org/exist/util/Configuration.java
exist-core/src/main/java/org/exist/util/XMLReaderObjectFactory.java
exist-core/src/main/java/org/exist/util/XMLReaderPool.java
exist-core/src/main/java/org/exist/util/serializer/SerializerObjectFactory.java
exist-core/src/main/java/org/exist/util/serializer/SerializerPool.java
exist-core/src/main/java/org/exist/validation/Validator.java
exist-core/src/main/java/org/exist/xmldb/LocalXMLResource.java
exist-core/src/main/java/org/exist/xquery/functions/validation/GrammarTooling.java
exist-core/src/main/java/org/exist/xquery/functions/validation/Jaxp.java
exist-core/src/test/java/org/exist/util/AbstractXMLReaderSecurityTest.java
exist-core/src/test/java/org/exist/util/XMLReaderExpansionTest.java
exist-core/src/test/java/org/exist/util/XMLReaderPoolTest.java
exist-parent/pom.xml

Many small improvements... API has been kept the same.
Fixed a bunch of issues where XMLReaders were reused but not correctly reset.

Cleanup of XML Reader Pool

---

exist-core/src/main/java/org/exist/http/RESTServer.java

Found by sonar cloud : https://sonarcloud.io/project/issues?id=eXist-db_exist&open=AXvMIVOjggjSG_DiiJ2a&pullRequest=4017&resolved=false&types=CODE_SMELL 
this is the only change:

Bugfix: be sure to close writer in restserver

---

exist-core/src/main/java/org/exist/backup/Backup.java
exist-core/src/main/java/org/exist/management/client/JMXtoXML.java
exist-core/src/main/java/org/exist/storage/BrokerPool.java
exist-core/src/main/java/org/exist/storage/NativeBroker.java
exist-core/src/main/java/org/exist/storage/serializers/XmlSerializerPool.java
exist-core/src/main/java/org/exist/storage/serializers/XmlSerializerPoolObjectFactory.java
exist-core/src/main/java/org/exist/util/XMLReaderPool.java
exist-core/src/main/java/org/exist/util/serializer/SerializerPool.java
exist-core/src/test/java/org/exist/backup/DeepEmbeddedBackupRestoreTest.java
exist-core/src/test/java/org/exist/util/XMLReaderPoolTest.java
exist-core/src/test/java/org/exist/util/serializer/SerializerPoolTest.java

Closes https://github.com/eXist-db/exist/pull/4047
Closes https://github.com/eXist-db/exist/issues/4045

Further tests for Pools and some sizing fixes

---

extensions/indexes/lucene/src/main/java/org/exist/indexing/lucene/AnalyzerConfig.java
extensions/indexes/lucene/src/test/java/org/exist/indexing/lucene/AnalyzerConfigTest.java

This allows two additional parameter types when specifying a custom analyzer:
1. `java.lang.String[]`
2. `char[]`
Documentation is here: https://github.com/eXist-db/documentation/pull/706

Improve custom analyzer config

---

.github/workflows/ci-build.yml
.github/workflows/ci-deploy.yml
.github/workflows/ci-docs.yml
.github/workflows/ci-test.yml
.github/workflows/sonarcloud.yml

Uses the Eclipse Foundation Adoptium JDK implementation for the build pipeline.

[feature] use of Adoptiums 'temurin' JDK

---

exist-core/pom.xml

Small doc improvement about the requirement for jansi

[doc] Add a comment about the requirement for jansi

---

exist-core/pom.xml
exist-core/src/main/java/org/exist/test/ExistWebServer.java
exist-core/src/main/java/org/exist/util/IPUtil.java
extensions/modules/mail/pom.xml
extensions/modules/mail/src/main/java/org/exist/xquery/modules/mail/SendEmailFunction.java
extensions/modules/mail/src/test/java/org/exist/xquery/modules/mail/SendEmailIT.java
extensions/modules/mail/src/test/java/org/exist/xquery/modules/mail/Util.java
extensions/modules/mail/src/test/resources-filtered/conf.xml
extensions/modules/mail/src/test/resources/log4j2.xml

Closes https://github.com/eXist-db/exist/issues/4156

Tests for mail:send-email

---

exist-core/src/test/java/org/exist/security/SecurityManagerTest.java

Further tests to ensure the Accounts and Groups 'removed' collections are accessible

Further checks around removed accounts

---

exist-core/src/main/java/org/exist/security/AbstractRealm.java

Improves startup when restoring a database that was affected by the Collection bug in 4.x.x before https://github.com/eXist-db/exist/pull/4188

[4.x.x] make removed startup robust

---

exist-core/src/main/java/org/exist/storage/blob/BlobStoreImpl.java
exist-core/src/main/java/org/exist/storage/journal/Journal.java
exist-core/src/main/java/org/exist/storage/journal/JournalManager.java
exist-core/src/main/java/org/exist/storage/journal/JournalReader.java
exist-core/src/main/java/org/exist/storage/recovery/RecoveryManager.java
exist-core/src/test/java/org/exist/storage/journal/AbstractJournalTest.java
exist-core/src/test/java/org/exist/storage/journal/JournalTest.java

This is a backport of https://github.com/eXist-db/exist/pull/4193

[4.x.x] Fix Journal Bugs

---

exist-core/pom.xml
exist-core/src/main/java/org/exist/xquery/Function.java
exist-core/src/main/java/org/exist/xquery/FunctionCall.java
exist-core/src/main/java/org/exist/xquery/functions/fn/FunConcat.java
exist-core/src/main/java/org/exist/xquery/functions/fn/FunCurrentDateTime.java
exist-core/src/main/java/org/exist/xquery/functions/fn/FunGetDateComponent.java
exist-core/src/main/java/org/exist/xquery/functions/fn/FunGetDurationComponent.java
exist-core/src/main/java/org/exist/xquery/functions/fn/FunMatches.java
exist-core/src/main/java/org/exist/xquery/functions/fn/FunReplace.java
exist-core/src/main/java/org/exist/xquery/functions/fn/FunReverse.java
exist-core/src/main/java/org/exist/xquery/functions/fn/FunSubSequence.java
exist-core/src/main/java/org/exist/xquery/functions/map/MapExpr.java
exist-core/src/main/java/org/exist/xquery/functions/securitymanager/IdFunction.java
exist-core/src/main/java/org/exist/xquery/functions/securitymanager/IsAuthenticatedFunction.java
exist-core/src/main/java/org/exist/xquery/functions/system/FnExport.java
exist-core/src/main/java/org/exist/xquery/functions/system/FnImport.java
exist-core/src/main/java/org/exist/xquery/functions/util/QNameIndexLookup.java
exist-core/src/main/java/org/exist/xquery/functions/util/SystemTime.java
exist-core/src/test/java/org/exist/test/Util.java
exist-core/src/test/java/org/exist/xquery/ForwardReferenceTest.java
extensions/indexes/lucene/src/main/java/org/exist/xquery/modules/lucene/Query.java
extensions/indexes/ngram/src/main/java/org/exist/xquery/modules/ngram/NGramSearch.java
extensions/indexes/range/src/main/java/org/exist/xquery/modules/range/FieldLookup.java
extensions/indexes/range/src/main/java/org/exist/xquery/modules/range/Lookup.java
extensions/indexes/spatial/src/main/java/org/exist/xquery/modules/spatial/FunGeometricProperties.java

Fixes a `NullPointerException` when analyze was called on a `FunctionCall` that was a Deferred Function Reference that had not yet been resolved.

Fix NPE in FunctionCall for Deferred Forward Reference

---

exist-core/pom.xml
exist-core/src/main/java/org/exist/jetty/JettyStart.java
exist-core/src/test/java/org/exist/dom/persistent/CDataIntergationTest.java
extensions/webdav/pom.xml
extensions/webdav/src/main/java/org/exist/webdav/ExistCollection.java
extensions/webdav/src/main/java/org/exist/webdav/MiltonCollection.java
extensions/webdav/src/main/java/org/exist/webdav/MiltonDocument.java
extensions/webdav/src/test/java/com/ettrema/cache/Cache.java
extensions/webdav/src/test/java/com/ettrema/cache/MemoryCache.java
extensions/webdav/src/test/java/org/exist/webdav/AlwaysBasicPreAuth.java
extensions/webdav/src/test/java/org/exist/webdav/CDataIntergationTest.java
extensions/webdav/src/test/java/org/exist/webdav/CopyTest.java
extensions/webdav/src/test/java/org/exist/webdav/DeleteTest.java
extensions/webdav/src/test/java/org/exist/webdav/RenameTest.java
extensions/webdav/src/test/java/org/exist/webdav/ReplaceTest.java
extensions/webdav/src/test/java/org/exist/webdav/StoreAndRetrieveTest.java
extensions/webdav/src/test/resources-filtered/conf.xml
extensions/webdav/src/test/resources/log4j2.xml
extensions/webdav/src/test/resources/standalone-webapp/WEB-INF/controller-config.xml
extensions/webdav/src/test/resources/standalone-webapp/WEB-INF/web.xml

Closes https://github.com/eXist-db/exist/issues/4213

XML documents were stored incorrectly by WebDAV 

---

exist-core/pom.xml
exist-core/src/main/java/org/exist/jetty/JettyStart.java
exist-core/src/test/java/org/exist/dom/persistent/CDataIntergationTest.java
extensions/webdav/pom.xml
extensions/webdav/src/main/java/org/exist/webdav/ExistCollection.java
extensions/webdav/src/main/java/org/exist/webdav/MiltonCollection.java
extensions/webdav/src/main/java/org/exist/webdav/MiltonDocument.java
extensions/webdav/src/test/java/com/ettrema/cache/Cache.java
extensions/webdav/src/test/java/com/ettrema/cache/MemoryCache.java
extensions/webdav/src/test/java/org/exist/webdav/AlwaysBasicPreAuth.java
extensions/webdav/src/test/java/org/exist/webdav/CDataIntergationTest.java
extensions/webdav/src/test/java/org/exist/webdav/CopyTest.java
extensions/webdav/src/test/java/org/exist/webdav/DeleteTest.java
extensions/webdav/src/test/java/org/exist/webdav/RenameTest.java
extensions/webdav/src/test/java/org/exist/webdav/ReplaceTest.java
extensions/webdav/src/test/java/org/exist/webdav/StoreAndRetrieveTest.java
extensions/webdav/src/test/resources-filtered/conf.xml
extensions/webdav/src/test/resources/log4j2.xml
extensions/webdav/src/test/resources/standalone-webapp/WEB-INF/controller-config.xml
extensions/webdav/src/test/resources/standalone-webapp/WEB-INF/web.xml

Backport of https://github.com/eXist-db/exist/pull/4230
Closes https://github.com/eXist-db/exist/issues/4213

[5.x.x] XML documents were stored incorrectly by WebDAV

---

exist-core/src/main/java/org/exist/xquery/value/Sequence.java
exist-core/src/test/xquery/util/document-id.xqm

Backport of https://github.com/eXist-db/exist/pull/4270
Closes https://github.com/eXist-db/exist/issues/4262

[5.x.x] Fix regression in util:document-id

---

exist-core/src/main/java/org/exist/xquery/value/Sequence.java
exist-core/src/test/xquery/util/document-id.xqm

Closes https://github.com/eXist-db/exist/issues/4262

Fix regression in util:document-id

---

exist-core/src/main/java/org/exist/collections/triggers/XQueryTrigger.java
exist-core/src/main/java/org/exist/security/EffectiveSubject.java
exist-core/src/main/java/org/exist/xquery/LibraryModuleRoot.java
exist-core/src/main/java/org/exist/xquery/XQuery.java
exist-core/src/main/java/org/exist/xquery/functions/securitymanager/IdFunction.java
exist-core/src/test/java/org/exist/collections/triggers/XQueryTriggerSetGidTest.java
exist-core/src/test/java/org/exist/collections/triggers/XQueryTriggerSetUidTest.java
exist-core/src/test/java/org/exist/collections/triggers/XQueryTriggerTest.java
exist-core/src/test/java/org/exist/xquery/functions/securitymanager/IdFunctionTest.java

Backport of https://github.com/eXist-db/exist/pull/4274

[5.x.x] Fix a security privilege escalation issue with XQueryTrigger

---

exist-core/src/test/java/org/exist/xquery/XQueryIsLibraryModuleTest.java

Small fix to a small issue ;-)

Fix license header (previously eXist 4.x.x syntax)

---

exist-core/pom.xml

Backport of https://github.com/eXist-db/exist/pull/4306

[5.x.x] Update to Xerces 2.12.2

---

exist-core/src/main/java/org/exist/source/URLSource.java
exist-parent/pom.xml

Backport of https://github.com/eXist-db/exist/pull/4291

[5.x.x] Send a valid HTTP Accept Header

---

exist-core/src/test/java/xquery/xquery3/XQuery3Tests.java

Addresses a simple regression introduced accidentally in 6e3696a4e

Reinstate all XQuery 3 tests

---

exist-core/src/test/java/xquery/xquery3/XQuery3Tests.java

Addresses a simple regression introduced accidentally in 6e3696a4

[5.x.x] Reinstate all XQuery 3 tests

---

exist-core/src/main/java/org/exist/xquery/functions/request/GetData.java
exist-core/src/test/java/org/exist/xquery/functions/request/GetDataTest.java

Closes https://github.com/eXist-db/exist/issues/4336

request:get-data#0 should support Chunked Transfer Encoding

---

exist-core/src/main/java/org/exist/xquery/functions/request/GetData.java

Backport of https://github.com/eXist-db/exist/pull/3261

[4.x.x] Reinstate code for a historical Jetty bugfix

---

exist-core/src/main/java/org/exist/resolver/ResolverFactory.java
exist-core/src/main/java/org/exist/resolver/XercesXmlResolverAdapter.java
exist-core/src/main/java/org/exist/validation/Validator.java

This was missing from https://github.com/eXist-db/exist/pull/4320 and fixes the Windows test failures.

[4.x.x] Fix catalog uris when using Windows Paths

---

.github/workflows/ci-xqts.yml
exist-distribution/pom.xml
exist-parent/pom.xml
exist-xqts/LGPL-21-license.txt
exist-xqts/pom.xml
pom.xml

This will run the `exist-xqts-runner` against eXist-db in CI, and attach the XQTS results as an artifact of the build.

Run XQTS against eXist-db in CI

---

exist-core/src/main/java/org/exist/client/QueryDialog.java

Previously when opening the Query Dialog of the Java Admin Client, it would attempt to get the details of every Collection in the database **before** showing the dialog. The names of the Collections were then placed into the `Context` Combo Box, and then finally the dialog was rendered to the user.
Obtaining the name of every collection from the Java Admin Client involves making one XML:DB API call per-Collection, when using the Remote API this means, one XML-RPC HTTP call for each Collection name. If your database had more than a handful of collections, this meant opening the Query Dialog could be *very* slow.
This PR makes opening the Query Dialog now almost instantaneous. It does this by making two improvements:
1. The List of Collection names does not need to be gathered before …

Improve performance of JAC Query Dialog

---

exist-core/src/main/java/org/exist/client/QueryDialog.java

Backport of https://github.com/eXist-db/exist/pull/4356

[5.x.x] Improve performance of JAC Query Dialog

---

exist-core/src/main/java/org/exist/xquery/XPathException.java
exist-core/src/main/java/org/exist/xquery/functions/xmldb/XMLDBAbstractCollectionManipulator.java
exist-core/src/main/java/org/exist/xquery/functions/xmldb/XMLDBAuthenticate.java
exist-core/src/main/java/org/exist/xquery/functions/xmldb/XMLDBCopy.java
exist-core/src/main/java/org/exist/xquery/functions/xmldb/XMLDBGetMimeType.java
exist-core/src/main/java/org/exist/xquery/functions/xmldb/XMLDBHasLock.java
exist-core/src/main/java/org/exist/xquery/functions/xmldb/XMLDBMove.java
exist-core/src/main/java/org/exist/xquery/functions/xmldb/XMLDBRemove.java
exist-core/src/main/java/org/exist/xquery/functions/xmldb/XMLDBRename.java
exist-core/src/main/java/org/exist/xquery/functions/xmldb/XMLDBSetMimeType.java
exist-core/src/main/java/org/exist/xquery/functions/xmldb/XMLDBSize.java
exist-core/src/main/java/org/exist/xquery/functions/xmldb/XMLDBStore.java

Backport of https://github.com/eXist-db/exist/pull/4352

[5.x.x] Capture xs:anyURI error details in XMLDB Module

---

exist-core/src/main/java/org/exist/xquery/XPathException.java
exist-core/src/main/java/org/exist/xquery/functions/xmldb/XMLDBAbstractCollectionManipulator.java
exist-core/src/main/java/org/exist/xquery/functions/xmldb/XMLDBCopy.java
exist-core/src/main/java/org/exist/xquery/functions/xmldb/XMLDBDocument.java
exist-core/src/main/java/org/exist/xquery/functions/xmldb/XMLDBGetMimeType.java
exist-core/src/main/java/org/exist/xquery/functions/xmldb/XMLDBHasLock.java
exist-core/src/main/java/org/exist/xquery/functions/xmldb/XMLDBMove.java
exist-core/src/main/java/org/exist/xquery/functions/xmldb/XMLDBRemove.java
exist-core/src/main/java/org/exist/xquery/functions/xmldb/XMLDBRename.java
exist-core/src/main/java/org/exist/xquery/functions/xmldb/XMLDBSetMimeType.java
exist-core/src/main/java/org/exist/xquery/functions/xmldb/XMLDBSetResourcePermissions.java
exist-core/src/main/java/org/exist/xquery/functions/xmldb/XMLDBSize.java
exist-core/src/main/java/org/exist/xquery/functions/xmldb/XMLDBStore.java

Backport of https://github.com/eXist-db/exist/pull/4352

[4.x.x] Capture xs:anyURI error details in XMLDB Module

---

exist-core/src/main/java/org/exist/xquery/functions/system/AsUser.java
exist-core/src/main/java/org/exist/xquery/functions/system/SystemModule.java
exist-core/src/test/java/xquery/system/SystemTests.java
exist-core/src/test/xquery/system/as-user.xqm

* Reduce unnecessary logging to `trace` level
* Add `system:function-as-user#3` so that you can execute a function as opposed to a "code block"

Improvements to system:as-user

---

schema/collection.xconf.xsd

Backport of https://github.com/eXist-db/exist/pull/4362

[4.x.x] Add missing entity-resolver elements to the Schema for collection.xconf

---

schema/collection.xconf.xsd

These were previously missing.

Add missing entity-resolver elements to the Schema for collection.xconf

---

exist-core/src/main/java/org/exist/http/servlets/XSLTServlet.java
exist-core/src/main/java/org/exist/xquery/functions/transform/Transform.java
exist-core/src/main/java/org/exist/xslt/XSLTErrorsListener.java

Backport of https://github.com/eXist-db/exist/pull/4372

[4.x.x] Improve XSLT errors

---

exist-core/src/main/java/org/exist/http/servlets/XSLTServlet.java
exist-core/src/main/java/org/exist/xquery/functions/transform/Transform.java
exist-core/src/main/java/org/exist/xslt/XSLTErrorsListener.java

Backport of https://github.com/eXist-db/exist/pull/4372

[5.x.x] Improve XSLT errors

---

exist-core/src/main/java/org/exist/http/servlets/AbstractExistHttpServlet.java
exist-core/src/main/java/org/exist/http/servlets/BasicAuthenticator.java
exist-core/src/main/java/org/exist/http/urlrewrite/XQueryURLRewrite.java
exist-core/src/test/java/org/exist/http/RESTServiceTest.java

Backport of https://github.com/eXist-db/exist/pull/4375

[4.x.x] Do not override Bearer Authentication with Basic Authentication

---

exist-core/src/main/java/org/exist/http/servlets/AbstractExistHttpServlet.java
exist-core/src/main/java/org/exist/http/servlets/BasicAuthenticator.java
exist-core/src/main/java/org/exist/http/urlrewrite/XQueryURLRewrite.java
exist-core/src/test/java/org/exist/http/RESTServiceTest.java

Backport of https://github.com/eXist-db/exist/pull/4375

[5.x.x] Do not override Bearer Authentication with Basic Authentication

---

exist-core/src/main/java/org/exist/backup/restore/AbstractRestoreHandler.java
exist-core/src/test/java/org/exist/backup/XMLDBRestoreTest.java

Backport of https://github.com/eXist-db/exist/pull/4390

[5.x.x] Fix additional issues with ResourceType and MediaType during Restore

---

exist-core/src/main/java/org/exist/xquery/DynamicNameCheck.java
exist-core/src/main/java/org/exist/xquery/NameTest.java
exist-core/src/test/xquery/node-tests.xqm

Closes https://github.com/eXist-db/exist/issues/3463

Fix the Node Test for document-node(element(name))

---

exist-core/src/main/java/org/exist/xquery/DynamicNameCheck.java
exist-core/src/main/java/org/exist/xquery/NameTest.java
exist-core/src/test/xquery/node-tests.xqm

Backport of https://github.com/eXist-db/exist/pull/4395

[5.x.x] Fix the Node Test for document-node(element(name))

---

extensions/modules/sql/pom.xml

Upgrade H2 database dependency used within tests in order to fix security issue

[upgrade] Upgrade H2 to 2.1.10

---

exist-core/src/main/java/org/exist/xquery/XPathUtil.java
exist-core/src/test/java/org/exist/xmldb/DeclareVariableTest.java

Closes https://github.com/eXist-db/exist/issues/4413

Allow BigDecimal and BigInteger values to be declared via XML:DB API

---

exist-core/src/main/java/org/exist/xquery/XPathUtil.java
exist-core/src/test/java/org/exist/xmldb/DeclareVariableTest.java

Backport of https://github.com/eXist-db/exist/pull/4418

[5.x.x] Allow BigDecimal and BigInteger values to be declared via XML:DB API

---

exist-core/src/main/java/org/exist/xquery/XPathUtil.java
exist-core/src/test/java/org/exist/xmldb/DeclareVariableTest.java

Backport of https://github.com/eXist-db/exist/pull/4418

[4.x.x] Allow BigDecimal and BigInteger values to be declared via XML:DB API

---

.idea/runConfigurations/Java_Admin_Client.xml
.idea/runConfigurations/Jetty_Server.xml

Needs updating since the last release.

Update IntelliJ IDEA IDE config for eXist-db 5.5.0-SNAPSHOT

---

exist-core/src/main/java/org/exist/dom/memtree/NodeImpl.java
exist-core/src/main/java/org/exist/dom/persistent/AVLTreeNodeSet.java
exist-core/src/main/java/org/exist/dom/persistent/EmptyNodeSet.java
exist-core/src/main/java/org/exist/dom/persistent/ExtArrayNodeSet.java
exist-core/src/main/java/org/exist/dom/persistent/NewArrayNodeSet.java
exist-core/src/main/java/org/exist/dom/persistent/NodeProxy.java
exist-core/src/main/java/org/exist/dom/persistent/SortedNodeSet.java
exist-core/src/main/java/org/exist/dom/persistent/VirtualNodeSet.java
exist-core/src/main/java/org/exist/xquery/FunctionCall.java
exist-core/src/main/java/org/exist/xquery/RangeSequence.java
exist-core/src/main/java/org/exist/xquery/functions/array/ArrayType.java
exist-core/src/main/java/org/exist/xquery/functions/map/MapType.java
exist-core/src/main/java/org/exist/xquery/value/ArrayListValueSequence.java
exist-core/src/main/java/org/exist/xquery/value/AtomicValue.java
exist-core/src/main/java/org/exist/xquery/value/BinaryValueFromFile.java
exist-core/src/main/java/org/exist/xquery/value/BinaryValueFromInputStream.java
exist-core/src/main/java/org/exist/xquery/value/EmptySequence.java
exist-core/src/main/java/org/exist/xquery/value/OrderedValueSequence.java
exist-core/src/main/java/org/exist/xquery/value/PreorderedValueSequence.java
exist-core/src/main/java/org/exist/xquery/value/Sequence.java
exist-core/src/main/java/org/exist/xquery/value/SubSequence.java
exist-core/src/main/java/org/exist/xquery/value/ValueSequence.java

Forward port of https://github.com/eXist-db/exist/pull/4408

Improve out-of-scope detection for binary variables

---

exist-core/src/main/java/org/exist/dom/memtree/NodeImpl.java
exist-core/src/main/java/org/exist/dom/persistent/AVLTreeNodeSet.java
exist-core/src/main/java/org/exist/dom/persistent/EmptyNodeSet.java
exist-core/src/main/java/org/exist/dom/persistent/ExtArrayNodeSet.java
exist-core/src/main/java/org/exist/dom/persistent/NewArrayNodeSet.java
exist-core/src/main/java/org/exist/dom/persistent/NodeProxy.java
exist-core/src/main/java/org/exist/dom/persistent/SortedNodeSet.java
exist-core/src/main/java/org/exist/dom/persistent/VirtualNodeSet.java
exist-core/src/main/java/org/exist/xquery/FunctionCall.java
exist-core/src/main/java/org/exist/xquery/RangeSequence.java
exist-core/src/main/java/org/exist/xquery/functions/array/ArrayType.java
exist-core/src/main/java/org/exist/xquery/functions/map/MapType.java
exist-core/src/main/java/org/exist/xquery/value/ArrayListValueSequence.java
exist-core/src/main/java/org/exist/xquery/value/AtomicValue.java
exist-core/src/main/java/org/exist/xquery/value/BinaryValueFromFile.java
exist-core/src/main/java/org/exist/xquery/value/BinaryValueFromInputStream.java
exist-core/src/main/java/org/exist/xquery/value/EmptySequence.java
exist-core/src/main/java/org/exist/xquery/value/OrderedValueSequence.java
exist-core/src/main/java/org/exist/xquery/value/PreorderedValueSequence.java
exist-core/src/main/java/org/exist/xquery/value/Sequence.java
exist-core/src/main/java/org/exist/xquery/value/SubSequence.java
exist-core/src/main/java/org/exist/xquery/value/ValueSequence.java

Forward port of https://github.com/eXist-db/exist/pull/4408

[5.x.x] Improve out-of-scope detection for binary variables

---

exist-core/src/main/java/org/exist/xquery/ValueComparison.java
exist-core/src/main/java/org/exist/xquery/value/DecimalValue.java
exist-core/src/main/java/org/exist/xquery/value/FloatValue.java
exist-core/src/test/java/xquery/numericOp/NumericOpTests.java
exist-core/src/test/xquery/numericOp/numeric-add.xqm
exist-core/src/test/xquery/numericOp/numeric-divide.xqm
exist-core/src/test/xquery/numericOp/numeric-equal.xqm
exist-core/src/test/xquery/numericOp/numeric-greater-than-or-equal.xqm
exist-core/src/test/xquery/numericOp/numeric-greater-than.xqm
exist-core/src/test/xquery/numericOp/numeric-integer-divide.xqm
exist-core/src/test/xquery/numericOp/numeric-less-than-or-equal.xqm
exist-core/src/test/xquery/numericOp/numeric-less-than.xqm
exist-core/src/test/xquery/numericOp/numeric-mod.xqm
exist-core/src/test/xquery/numericOp/numeric-multiply.xqm
exist-core/src/test/xquery/numericOp/numeric-not-equal.xqm
exist-core/src/test/xquery/numericOp/numeric-subtract.xqm

Backport of https://github.com/eXist-db/exist/pull/4433

[5.x.x] Fix numerous bugs in numeric operations

---

build/scripts/junit.xml
exist-core/src/main/java/org/exist/xquery/value/FloatValue.java
exist-core/src/test/java/xquery/numericOp/NumericOpTests.java
exist-core/src/test/xquery/numericOp/numeric-add.xqm
exist-core/src/test/xquery/numericOp/numeric-divide.xqm
exist-core/src/test/xquery/numericOp/numeric-equal.xqm
exist-core/src/test/xquery/numericOp/numeric-greater-than-or-equal.xqm
exist-core/src/test/xquery/numericOp/numeric-greater-than.xqm
exist-core/src/test/xquery/numericOp/numeric-integer-divide.xqm
exist-core/src/test/xquery/numericOp/numeric-less-than-or-equal.xqm
exist-core/src/test/xquery/numericOp/numeric-less-than.xqm
exist-core/src/test/xquery/numericOp/numeric-mod.xqm
exist-core/src/test/xquery/numericOp/numeric-multiply.xqm
exist-core/src/test/xquery/numericOp/numeric-not-equal.xqm
exist-core/src/test/xquery/numericOp/numeric-subtract.xqm

Backport of https://github.com/eXist-db/exist/pull/4433

[4.x.x] Fix numerous bugs in numeric operations

---

exist-core-jmh/pom.xml
exist-core-jmh/src/main/java/org/exist/xquery/utils/StringJoinBenchmark.java
exist-core/src/main/java/org/exist/xquery/DynamicFunctionCall.java
exist-core/src/main/java/org/exist/xquery/Predicate.java
exist-core/src/main/java/org/exist/xquery/functions/array/ArrayType.java
exist-core/src/main/java/org/exist/xquery/functions/map/AbstractMapType.java
exist-core/src/main/java/org/exist/xquery/value/FunctionReference.java
exist-core/src/test/xquery/xquery3/fnRefs.xql

Closes https://github.com/eXist-db/exist/issues/4412

Fix the use of Function Reference from with a Predicate

---

exist-core/src/main/java/org/exist/xquery/DynamicFunctionCall.java
exist-core/src/main/java/org/exist/xquery/Predicate.java
exist-core/src/main/java/org/exist/xquery/functions/array/ArrayType.java
exist-core/src/main/java/org/exist/xquery/functions/map/AbstractMapType.java
exist-core/src/main/java/org/exist/xquery/value/FunctionReference.java
exist-core/src/test/xquery/xquery3/fnRefs.xql

Backport of https://github.com/eXist-db/exist/pull/4414

[5.x.x] Fix the use of Function Reference from with a Predicate

---

exist-core/src/main/java/org/exist/dom/memtree/NodeImpl.java
exist-core/src/main/java/org/exist/dom/persistent/NodeProxy.java
exist-core/src/main/java/org/exist/xquery/DeferredFunctionCall.java
exist-core/src/main/java/org/exist/xquery/ModuleContext.java
exist-core/src/main/java/org/exist/xquery/VariableImpl.java
exist-core/src/main/java/org/exist/xquery/XQueryContext.java
exist-core/src/main/java/org/exist/xquery/value/AbstractSequence.java
exist-core/src/main/java/org/exist/xquery/value/ArrayListValueSequence.java
exist-core/src/main/java/org/exist/xquery/value/AtomicValue.java
exist-core/src/main/java/org/exist/xquery/value/BinaryValueFromFile.java
exist-core/src/main/java/org/exist/xquery/value/BinaryValueFromInputStream.java
exist-core/src/main/java/org/exist/xquery/value/Item.java
exist-core/src/main/java/org/exist/xquery/value/Sequence.java
exist-core/src/main/java/org/exist/xquery/value/SubSequence.java
exist-core/src/main/java/org/exist/xquery/value/ValueSequence.java

Fixes a regression introduced in 1e91318

Avoid an NPE when disposing Binary Values

---

exist-core/src/main/java/org/exist/dom/memtree/NodeImpl.java
exist-core/src/main/java/org/exist/dom/persistent/NodeProxy.java
exist-core/src/main/java/org/exist/xquery/DeferredFunctionCall.java
exist-core/src/main/java/org/exist/xquery/ModuleContext.java
exist-core/src/main/java/org/exist/xquery/VariableImpl.java
exist-core/src/main/java/org/exist/xquery/XQueryContext.java
exist-core/src/main/java/org/exist/xquery/value/AbstractSequence.java
exist-core/src/main/java/org/exist/xquery/value/ArrayListValueSequence.java
exist-core/src/main/java/org/exist/xquery/value/AtomicValue.java
exist-core/src/main/java/org/exist/xquery/value/BinaryValueFromFile.java
exist-core/src/main/java/org/exist/xquery/value/BinaryValueFromInputStream.java
exist-core/src/main/java/org/exist/xquery/value/Item.java
exist-core/src/main/java/org/exist/xquery/value/Sequence.java
exist-core/src/main/java/org/exist/xquery/value/SubSequence.java
exist-core/src/main/java/org/exist/xquery/value/ValueSequence.java

Backport of https://github.com/eXist-db/exist/pull/4462

[5.x.x] Avoid an NPE when disposing Binary Values

---

exist-core/src/main/java/org/exist/dom/memtree/NodeImpl.java
exist-core/src/main/java/org/exist/dom/persistent/NodeProxy.java
exist-core/src/main/java/org/exist/xquery/DeferredFunctionCall.java
exist-core/src/main/java/org/exist/xquery/ModuleContext.java
exist-core/src/main/java/org/exist/xquery/VariableImpl.java
exist-core/src/main/java/org/exist/xquery/XQueryContext.java
exist-core/src/main/java/org/exist/xquery/value/AbstractSequence.java
exist-core/src/main/java/org/exist/xquery/value/AtomicValue.java
exist-core/src/main/java/org/exist/xquery/value/BinaryValueFromFile.java
exist-core/src/main/java/org/exist/xquery/value/BinaryValueFromInputStream.java
exist-core/src/main/java/org/exist/xquery/value/Item.java
exist-core/src/main/java/org/exist/xquery/value/Sequence.java
exist-core/src/main/java/org/exist/xquery/value/SubSequence.java
exist-core/src/main/java/org/exist/xquery/value/ValueSequence.java

Backport of https://github.com/eXist-db/exist/pull/4462

[4.x.x] Avoid an NPE when disposing Binary Values

---

exist-core/src/main/java/org/exist/client/QueryDialog.java

Avoid an NPE in the Query Dialog

Report null results instead of throwing NPE

---

exist-core/src/main/java/org/exist/client/QueryDialog.java

Backport of https://github.com/eXist-db/exist/pull/4488

[4.x.x] Report null results instead of throwing NPE

---

exist-core/src/test/xquery/npt.xqm

Closes https://github.com/eXist-db/exist/issues/1892
----

Tests to show that Path expression with nested positional predicate succeeds on database node

---

exist-core/src/main/java/org/exist/client/QueryDialog.java

Thank you for your contribution to eXist-db! 
To help the community judge your pull request (PR), please include the following:
- A (short) description of the content of changes.
- A context reference to a [Github Issue](https://github.com/eXist-db/exist/issues), a message in the [eXist-open mailinglist](http://exist-open.markmail.org), or a [specification](https://www.w3.org/TR/xquery-31/).
- Tests. The [XQSuite - Annotation-based Test Framework for XQuery](http://exist-db.org/exist/apps/doc/xqsuite.xml) makes it very easy for you to create tests. These tests can be executed from the [eXide editor](http://exist-db.org/exist/apps/eXide/index.html) via XQuery > Run as Test.
Your PR will be tested using [GitHub Actions](https://github.com/eXist-db/exist/actions) against a number of …

Import the ErrorCodes class

---

exist-core/src/main/antlr/org/exist/xquery/parser/XQuery.g
exist-core/src/test/java/org/exist/xquery/ReservedNamesConflictTest.java
exist-core/src/test/xquery/reserved-names.xqm

Closes https://github.com/eXist-db/exist/issues/2381

Add missing XQuery Reserved Names

---

exist-core/src/main/java/org/exist/Namespaces.java
exist-core/src/main/java/org/exist/dom/memtree/DocumentImpl.java
exist-core/src/main/java/org/exist/dom/memtree/ElementImpl.java
exist-core/src/main/java/org/exist/xquery/functions/fn/FnModule.java
exist-core/src/main/java/org/exist/xquery/functions/fn/FunElementWithId.java
exist-core/src/main/java/org/exist/xquery/functions/fn/FunId.java
exist-core/src/test/xquery/xquery3/fnElementWithId.xqm
exist-core/src/test/xquery/xquery3/fnId.xqm

Implemented the `fn:element-with-id` function.
* https://github.com/eXist-db/exist/issues/3635
* https://www.w3.org/TR/xpath-functions-31/#func-element-with-id
Added tests: `exist-core/src/test/xquery/xquery3/fnElementWithId.xqm`
---

[feature] Implement the fn:element-with-id function

---

exist-core/src/main/java/org/exist/xquery/value/BinaryValueFromFile.java

Backport of https://github.com/eXist-db/exist/pull/4521

[4.x.x] fix resource leak (and file lock)

---

exist-core/src/main/java/org/exist/xquery/value/BinaryValueFromFile.java

Backport of https://github.com/eXist-db/exist/pull/4521

[5.x.x] fix resource leak (and file lock)

---

exist-core/pom.xml
exist-parent/pom.xml

Switch from alpha version to final Log4j bridge implementation.

[enhancement] Use final log4j-slf4j2-impl bridge

---

exist-core/src/main/java/org/exist/storage/BrokerPool.java

A Boolean only has two static instances True or False, and they are different instances depending on the value, and so synchronising on a Boolean actually leads to synchronising on one or two global instances which is not what was intended.

Should never synchronize on a Boolean

---

exist-core/src/test/xquery/unparsed-text.xql

Backport of https://github.com/eXist-db/exist/pull/4543

[5.x.x] Change URL for two unparsed-text tests

---

exist-core/src/main/java/org/exist/xquery/LocationStep.java
exist-core/src/test/xquery/document-nodes.xq

Backport of https://github.com/eXist-db/exist/pull/4548

[4.x.x] Fix issues with document-node lookups on various axis

---

exist-core/src/main/java/org/exist/xquery/LocationStep.java
exist-core/src/test/xquery/document-nodes.xq

Backport of https://github.com/eXist-db/exist/pull/4548

[5.x.x] Fix issues with document-node lookups on various axis

---

extensions/modules/mail/pom.xml
extensions/modules/mail/src/main/java/org/exist/xquery/modules/mail/SendEmailFunction.java
extensions/modules/mail/src/test/java/org/exist/xquery/modules/mail/SendEmailIT.java
extensions/modules/mail/src/test/java/org/exist/xquery/modules/mail/WriteMessageTest.java
extensions/modules/mail/src/test/resources-filtered/conf.xml

1. Emails with text, and html messages, and with attachments were not correctly serialized.
2. Make sure that header parameters that have non-token characters are correctly quoted.
3. Be polite and tell the SMTP server when we have finished.

Fix issues with SMTP dialogue in the Mail Module when sending emails.

---

exist-core/pom.xml
exist-core/src/main/java/org/exist/repo/ExistRepository.java
exist-core/src/main/java/org/exist/storage/BrokerPool.java
exist-core/src/main/java/org/exist/test/runner/XQueryTestRunner.java
exist-core/src/main/java/org/exist/util/MapUtil.java
exist-core/src/main/java/org/exist/xquery/ModuleContext.java
exist-core/src/main/java/org/exist/xquery/XQueryContext.java
exist-core/src/main/java/org/exist/xquery/XQueryWatchDog.java
exist-core/src/test/resources-filtered/conf.xml
exist-core/src/test/xquery/xsuite-declare-xqsuite.xqm
exist-core/src/test/xquery/xsuite-import-xqsuite-location.xqm
exist-core/src/test/xquery/xsuite-import-xqsuite-no-location.xqm

Closes https://github.com/eXist-db/exist/issues/4588

Fixes an issue with XSuite not being able to run some formulations of XQsuite

---

exist-core/pom.xml
exist-core/src/main/java/org/exist/repo/ExistRepository.java
exist-core/src/main/java/org/exist/storage/BrokerPool.java
exist-core/src/main/java/org/exist/test/runner/XQueryTestRunner.java
exist-core/src/main/java/org/exist/util/MapUtil.java
exist-core/src/main/java/org/exist/xquery/ModuleContext.java
exist-core/src/main/java/org/exist/xquery/XQueryContext.java
exist-core/src/main/java/org/exist/xquery/XQueryWatchDog.java
exist-core/src/test/resources-filtered/conf.xml
exist-core/src/test/xquery/xsuite-declare-xqsuite.xqm
exist-core/src/test/xquery/xsuite-import-xqsuite-location.xqm
exist-core/src/test/xquery/xsuite-import-xqsuite-no-location.xqm

Backport of https://github.com/eXist-db/exist/pull/4589
Closes https://github.com/eXist-db/exist/issues/4588

[5.x.x] Fixes an issue with XSuite not being able to run some formulations of XQsuite

---

exist-jetty-config/src/main/resources/org/exist/jetty/etc/jetty-annotations.xml
exist-jetty-config/src/main/resources/org/exist/jetty/etc/jetty-bytebufferpool.xml
exist-jetty-config/src/main/resources/org/exist/jetty/etc/jetty-deploy.xml
exist-jetty-config/src/main/resources/org/exist/jetty/etc/jetty-gzip.xml
exist-jetty-config/src/main/resources/org/exist/jetty/etc/jetty-http.xml
exist-jetty-config/src/main/resources/org/exist/jetty/etc/jetty-https.xml
exist-jetty-config/src/main/resources/org/exist/jetty/etc/jetty-jaas.xml
exist-jetty-config/src/main/resources/org/exist/jetty/etc/jetty-jmx.xml
exist-jetty-config/src/main/resources/org/exist/jetty/etc/jetty-logging.xml
exist-jetty-config/src/main/resources/org/exist/jetty/etc/jetty-requestlog.xml
exist-jetty-config/src/main/resources/org/exist/jetty/etc/jetty-ssl-context.xml
exist-jetty-config/src/main/resources/org/exist/jetty/etc/jetty-ssl.xml
exist-jetty-config/src/main/resources/org/exist/jetty/etc/jetty-threadpool.xml
exist-jetty-config/src/main/resources/org/exist/jetty/etc/jetty.xml
exist-jetty-config/src/main/resources/org/exist/jetty/etc/standalone-jetty-deploy.xml
exist-jetty-config/src/main/resources/org/exist/jetty/etc/standalone-jetty-http.xml
exist-jetty-config/src/main/resources/org/exist/jetty/etc/standalone-jetty-ssl.xml
exist-jetty-config/src/main/resources/org/exist/jetty/etc/standalone-jetty.xml
exist-jetty-config/src/main/resources/org/exist/jetty/etc/standalone-webapps/exist-webapp-context.xml
exist-jetty-config/src/main/resources/org/exist/jetty/etc/webapps/exist-webapp-context.xml

Jetty dtd references must now use https instead of http

---

exist-core/src/test/java/org/exist/storage/CopyCollectionTest.java

Result of live community code review . chasing a recurring and unpredictable build error

[bugfix] add delay so timing of collections are subtle different

---

exist-core/src/test/java/org/exist/storage/CopyCollectionTest.java

[ignore] Add comments to yesterdays commit

---

exist-core/src/main/java/org/exist/xquery/value/Sequence.java

Just a small deduplication of Sequence class static methods.

[refactor] Sequence.of

---

exist-core/src/main/java/org/exist/http/RESTServer.java

Closes https://github.com/eXist-db/exist/issues/4639

Correct the response code of the REST Server when executing an invalid stored query

---

exist-core/src/test/java/org/exist/validation/CollectionConfigurationValidationModeTest.java

Looks like the W3C decision to redirect all http requests to https requests has bitten us again.

[4.x.x] Fix http redirect schema test

---

exist-core/src/test/java/org/exist/validation/CollectionConfigurationValidationModeTest.java

Forward port of https://github.com/eXist-db/exist/pull/4679

Fix http redirect schema test

---

exist-core/src/test/java/org/exist/validation/CollectionConfigurationValidationModeTest.java

Forward port of https://github.com/eXist-db/exist/pull/4679

[5.x.x] Fix http redirect schema test

---

exist-versioning-release.md

Forward port of https://github.com/eXist-db/exist/pull/4676

Also build the IzPack installer

---

exist-core/src/main/java/org/exist/launcher/WindowsServiceManager.java
exist-core/src/test/java/org/exist/launcher/WindowsServiceManagerTest.java

Closes https://github.com/eXist-db/exist/issues/4528

Windows Service installer - prunsrv.exe expects memory to be supplied as an integer

---

.idea/runConfigurations/Java_Admin_Client.xml
.idea/runConfigurations/Jetty_Server.xml
.idea/runConfigurations/Local_Jetty_Server.xml
exist-core/src/main/java/org/exist/http/RESTServer.java
exist-core/src/main/java/org/exist/storage/serializers/Serializer.java
exist-core/src/main/java/org/exist/storage/serializers/XIncludeFilter.java
exist-core/src/main/java/org/exist/util/serializer/AbstractSerializer.java
exist-core/src/main/java/org/exist/util/serializer/CharacterMappingWriter.java
exist-core/src/main/java/org/exist/util/serializer/SerializerObjectFactory.java
exist-core/src/main/java/org/exist/xquery/util/SerializerUtils.java
exist-core/src/test/java/org/exist/http/RESTServiceTest.java

Closes https://github.com/eXist-db/exist/issues/4691

Ensure that XSLT stylesheets are only compiled once when used from an xsl-pi in the REST Server

---

exist-core/src/main/java/org/exist/http/RESTServer.java
exist-core/src/main/java/org/exist/storage/serializers/Serializer.java
exist-core/src/main/java/org/exist/storage/serializers/XIncludeFilter.java
exist-core/src/main/java/org/exist/util/serializer/SerializerObjectFactory.java
exist-core/src/test/java/org/exist/http/RESTServiceTest.java

Backport of https://github.com/eXist-db/exist/pull/4708

[5.x.x] Ensure that XSLT stylesheets are only compiled once when used from an xsl-pi in the REST Server

---

exist-core/src/main/java/org/exist/storage/serializers/Serializer.java
exist-core/src/main/java/org/exist/storage/serializers/XIncludeFilter.java
exist-core/src/main/java/org/exist/util/serializer/SerializerObjectFactory.java
exist-core/src/test/java/org/exist/http/RESTServiceTest.java

Backport of https://github.com/eXist-db/exist/pull/4708

[4.x.x] Ensure that XSLT stylesheets are only compiled once when used from an xsl-pi in the REST Server

---

exist-xqts/pom.xml

Update to exist-xqts-runner 1.2.0

---

exist-core/src/main/java/org/exist/http/RESTServer.java

Closes https://github.com/eXist-db/exist/issues/4639
**NOTE** this changes a public API and so must wait for a major release such as 7.0.0.
This is a redo of https://github.com/eXist-db/exist/pull/4640

Correct the response code of the REST Server when executing an invalid stored query (2)

---

.github/dependabot.yml

Enables `dependabot` updates for `github-actions`.

[feature] Adds dependabot updates for github actions

---

exist-distribution/src/main/config/conf.xml

[bugfix] Change XML processing defaults for new major release

---

exist-core/src/main/resources/org/exist/xquery/lib/xqsuite/xqsuite.xql

Extract function test:safe-effective-boolean-value.

[refactor] XQSuite for readability

---

extensions/indexes/lucene/src/main/java/org/exist/indexing/lucene/DefaultTextExtractor.java
extensions/indexes/lucene/src/main/java/org/exist/indexing/lucene/LuceneConfig.java
extensions/indexes/lucene/src/main/java/org/exist/indexing/lucene/LuceneIndexConfig.java

Small optimisations to the Lucene Index Worker

Small optimisations to the Lucene Index Worker

---

exist-core/src/main/resources/org/exist/xquery/lib/xqsuite/examples.xql
exist-core/src/main/resources/org/exist/xquery/lib/xqsuite/xqsuite.xql

Backport of https://github.com/eXist-db/exist/pull/4799.

[6.x.x] [fix] XQSuite assertXPath annotation: Support default element namespace

---

exist-jetty-config/src/main/resources/webapp/WEB-INF/controller-config.xml

The controller-config.xml file defines mappings for request paths and their target servlets or application roots. 
This PR removes legacy mappings, including:
- servlets:
- betterForm
- applications: 
- /library
- /tamboti
- /solutions
- https://exist-db.org/exist/apps/doc/urlrewrite#controller-mappings
Note: a PR is in preparation which will update the URL Rewriting article's excerpts for the controller-config.xml file to conform to this PR.
n/a

Clean up controller-config to remove legacy paths

---

exist-jetty-config/src/main/resources/webapp/WEB-INF/controller-config.xml

Building on #4806, this PR improves the inline documentation in the controller-config.xml document. It does not change the order or contents of the elements in this config file. It merely updates and adds information to the inline comments.
https://exist-db.org/exist/apps/doc/urlrewrite#controller-mappings
N/A

Improve controller-config inline comments

---

.github/workflows/ci-xqts.yml
exist-parent/pom.xml
exist-xqts/src/main/xslt/compare-results.xslt

Attempt at comparing results of previous XQTS run against this run.
See - https://github.com/eXist-db/exist/issues/3632
----

Compare this XQTS run with previous XQTS run

---

.github/dependabot.yml

Fixed the dependabot definition for github actions.

Fixes dependabot definition

---

exist-core/src/main/java/org/exist/http/AuditTrailSessionListener.java
exist-core/src/main/java/org/exist/http/RESTServer.java
exist-core/src/main/java/org/exist/http/urlrewrite/XQueryURLRewrite.java
exist-core/src/main/java/org/exist/scheduler/UserXQueryJob.java
exist-core/src/main/java/org/exist/security/internal/SMEvents.java
exist-core/src/main/java/org/exist/source/BinarySource.java
exist-core/src/main/java/org/exist/source/DBSource.java
exist-core/src/main/java/org/exist/source/FileSource.java
exist-core/src/main/java/org/exist/source/Source.java
exist-core/src/main/java/org/exist/source/SourceFactory.java
exist-core/src/main/java/org/exist/source/StringSource.java
exist-core/src/main/java/org/exist/source/URLSource.java
exist-core/src/main/java/org/exist/storage/XQueryPool.java
exist-core/src/main/java/org/exist/storage/serializers/XIncludeFilter.java
exist-core/src/main/java/org/exist/xmldb/LocalXPathQueryService.java
exist-core/src/main/java/org/exist/xmlrpc/RpcConnection.java
exist-core/src/main/java/org/exist/xquery/ExternalModule.java
exist-core/src/main/java/org/exist/xquery/ExternalModuleImpl.java
exist-core/src/main/java/org/exist/xquery/XQueryContext.java
exist-core/src/main/java/org/exist/xquery/functions/util/Eval.java
exist-core/src/test/java/org/exist/source/SourceFactoryTest.java
exist-core/src/test/java/org/exist/xquery/XQueryContextAttributesTest.java
extensions/exquery/restxq/src/main/java/org/exist/extensions/exquery/restxq/impl/XQueryCompiler.java
extensions/xqdoc/src/main/java/org/exist/xqdoc/xquery/Scan.java

Simplifies an interface used for providing XQuery to eXist-db by removing its dependency on DBBroker.

Simplify Source interface

---

exist-distribution/pom.xml

Backport of https://github.com/eXist-db/exist/pull/4750

[6.x.x] [build] add missing dependency to copy-maven-plugin

---

exist-core/src/main/java/org/exist/repo/ClasspathHelper.java
exist-core/src/main/java/org/exist/repo/ExistPkgExtension.java

Backport of https://github.com/eXist-db/exist/pull/4902

[5.x.x] Ensure that EXPath packages installed in $EXIST_HOME/data/expathrepo are filesystem portable

---

exist-core/src/main/java/org/exist/management/impl/ExistMBean.java
exist-core/src/main/java/org/exist/management/impl/JMXAgent.java
exist-core/src/main/java/org/exist/management/impl/PerInstanceMBean.java
exist-core/src/main/java/org/exist/management/impl/ProcessReport.java
exist-core/src/main/java/org/exist/management/impl/ProcessReportMXBean.java
exist-core/src/main/java/org/exist/management/impl/RecentQueryHistory.java
exist-core/src/main/java/org/exist/management/impl/RunningQuery.java
exist-core/src/main/java/org/exist/management/impl/SystemInfo.java

Backport of https://github.com/eXist-db/exist/pull/4963

[6.x.x] Improve JMX output

---

exist-core/src/main/java/org/exist/Namespaces.java
exist-core/src/main/java/org/exist/interpreter/Context.java
exist-core/src/main/java/org/exist/util/MapUtil.java
exist-core/src/main/java/org/exist/xquery/Optimizer.java
exist-core/src/main/java/org/exist/xquery/XQueryContext.java
exist-core/src/main/java/org/exist/xquery/pragmas/ForceIndexUse.java
exist-core/src/main/java/org/exist/xquery/pragmas/NoIndexPragma.java
exist-core/src/main/java/org/exist/xquery/pragmas/Optimize.java
exist-core/src/main/java/org/exist/xquery/pragmas/ProfilePragma.java
exist-core/src/main/java/org/exist/xquery/pragmas/TimerPragma.java

additional cleanup refactorings 
refs #4836 
no new tests were added

Further cleanup XQueryContext

---

exist-core/src/main/java/org/exist/xquery/XQueryContext.java
exist-core/src/main/java/org/exist/xquery/functions/request/GetData.java
exist-core/src/test/java/org/exist/xquery/functions/request/GetData2Test.java
extensions/exquery/restxq/src/main/java/org/exist/extensions/exquery/restxq/impl/RestXqServiceImpl.java

Forward port of https://github.com/eXist-db/exist/pull/4978

InputStream#available() should not be used to determine if there is data available

---

exist-core/src/main/java/org/exist/xquery/functions/securitymanager/GroupManagementFunction.java
exist-core/src/main/java/org/exist/xquery/functions/system/FunctionTrace.java
exist-core/src/main/java/org/exist/xquery/functions/system/Shutdown.java
exist-core/src/main/java/org/exist/xquery/functions/system/TriggerSystemTask.java
exist-core/src/main/java/org/exist/xquery/functions/transform/Transform.java
exist-core/src/main/java/org/exist/xquery/functions/util/LogFunction.java
exist-core/src/main/java/org/exist/xquery/functions/util/Profile.java
exist-core/src/main/java/org/exist/xquery/functions/util/PrologFunctions.java
exist-core/src/main/java/org/exist/xquery/functions/xmldb/XMLDBDefragment.java
exist-core/src/main/java/org/exist/xquery/functions/xmldb/XMLDBMove.java
exist-core/src/main/java/org/exist/xquery/functions/xmldb/XMLDBRemove.java
exist-core/src/main/java/org/exist/xquery/functions/xmldb/XMLDBRename.java
exist-core/src/test/java/org/exist/storage/util/PauseFunction.java
extensions/modules/mail/src/main/java/org/exist/xquery/modules/mail/SendEmailFunction.java

[5.x.x] Correct function signatures that return empty sequences

---

exist-core/src/main/java/org/exist/http/servlets/EXistServlet.java

Backport of https://github.com/eXist-db/exist/pull/4991

[6.x.x] Log exception if the response is already committed

---

.github/workflows/ci-test.yml

build: upgrade mavend

---

exist-core/src/main/java/org/exist/client/InteractiveClient.java
exist-core/src/main/java/org/exist/repo/ExistRepository.java
exist-core/src/main/java/org/exist/util/Configuration.java
exist-core/src/main/java/org/exist/util/ConfigurationHelper.java
exist-core/src/main/java/org/exist/util/SingleInstanceConfiguration.java
exist-core/src/main/java/org/exist/xquery/XQueryContext.java
exist-parent/pom.xml

Forward port of https://github.com/eXist-db/exist/pull/5012

Fix an issue with XQuery transient imports within EXPath Package

---

exist-docker/src/main/resources-filtered/Dockerfile-DEBUG

Backport of https://github.com/eXist-db/exist/pull/5007

[6.x.x] Allow the user to override the JDWP Suspend at Docker build time

---

exist-distribution/pom.xml

[5.x.x] update copy-maven-plugin settings

---

exist-core/src/main/java/org/exist/dom/QName.java
exist-core/src/main/java/org/exist/storage/NodePath.java
exist-core/src/main/java/org/exist/xquery/functions/inspect/InspectFunctionHelper.java
exist-core/src/main/java/org/exist/xquery/functions/inspect/InspectModule.java
exist-core/src/main/java/org/exist/xquery/functions/util/DescribeFunction.java
exist-core/src/test/java/org/exist/storage/NodePathTest.java

Forward port of https://github.com/eXist-db/exist/pull/5046

Fix a bug in Node Path equality

---

exist-core/src/main/java/org/exist/dom/QName.java
exist-core/src/main/java/org/exist/storage/NodePath.java
exist-core/src/main/java/org/exist/xquery/functions/inspect/InspectFunctionHelper.java
exist-core/src/main/java/org/exist/xquery/functions/inspect/InspectModule.java
exist-core/src/main/java/org/exist/xquery/functions/util/DescribeFunction.java
exist-core/src/test/java/org/exist/storage/NodePathTest.java

Backport of https://github.com/eXist-db/exist/pull/5046

[5.x.x] Fix a bug in Node Path equality

---

.github/workflows/ci-test.yml
exist-core/src/test/java/org/exist/storage/lock/CollectionLocksTest.java

Tries to fix the Windows Maven daemon timeout issue

[bugfix] increase the maven daemon timeout

---

exist-parent/pom.xml

[5.x.x] update settings for dependency-check-maven

---

CONTRIBUTING.md

This PR add few naming conventions for the contributing.md

[doc] commit naming convention

---

exist-core/src/main/java/org/exist/xmldb/RemoteCollection.java
exist-core/src/main/java/org/exist/xmlrpc/RpcAPI.java
exist-core/src/main/java/org/exist/xmlrpc/RpcConnection.java
exist-core/src/test/java/org/exist/xmlrpc/MimeTypeTest.java

This is a backport of PR #5068 for the `develop-6.x.x` branch.

[6.x.x] Parameterise the XML-RPC parse method with the Media Type

---

exist-core/pom.xml
exist-core/src/main/java/org/exist/xquery/AbstractPragma.java
exist-core/src/main/java/org/exist/xquery/ExtensionExpression.java
exist-core/src/main/java/org/exist/xquery/Optimizer.java
exist-core/src/main/java/org/exist/xquery/Option.java
exist-core/src/main/java/org/exist/xquery/Pragma.java
exist-core/src/main/java/org/exist/xquery/XQueryContext.java
exist-core/src/main/java/org/exist/xquery/pragmas/ForceIndexUse.java
exist-core/src/main/java/org/exist/xquery/pragmas/NoIndexPragma.java
exist-core/src/main/java/org/exist/xquery/pragmas/Optimize.java
exist-core/src/main/java/org/exist/xquery/pragmas/ProfilePragma.java
exist-core/src/main/java/org/exist/xquery/pragmas/TimePragma.java
exist-core/src/main/java/org/exist/xquery/pragmas/TimerPragma.java
extensions/indexes/range/pom.xml
extensions/indexes/range/src/main/java/org/exist/xquery/modules/range/OptimizeFieldPragma.java

Forward port of https://github.com/eXist-db/exist/pull/5077

New exist:time XQuery Pragma

---

exist-core/src/main/java/org/exist/xquery/pragmas/TimePragma.java

Forward port of https://github.com/eXist-db/exist/pull/5081

[bugfix] Avoid NPE in exist:time pragma

---

exist-parent/pom.xml

Fixes the java.lang.NoClassDefFoundError:
org/junit/platform/engine/support/store/NamespacedHierarchicalStore$CloseAction

[bugfix] Rollback maven-surefire-plugin

---

schema/collection.xconf.xsd
schema/conf.xsd
schema/controller-config.xsd
schema/descriptor.xsd
schema/expath-pkg-extensions/cxan.xsd
schema/expath-pkg-extensions/exist.xsd
schema/expath-pkg-extensions/repo.xsd
schema/expath-pkg.xsd
schema/mime-types.xsd
schema/security-manager.xsd
schema/server.xsd
schema/users.xsd

Backport of https://github.com/eXist-db/exist/pull/5113

Add Schema for EXPath Packaging System

---

exist-core/pom.xml
exist-parent/pom.xml
extensions/contentextraction/pom.xml
extensions/exquery/restxq/pom.xml
extensions/indexes/lucene/pom.xml
extensions/indexes/spatial/pom.xml
extensions/webdav/pom.xml

credits to  @reinhapa 
replaces #5163

[ci] Fix surefire plugin configuration.

---

exist-core/src/main/java/org/exist/xmldb/DatabaseImpl.java
exist-core/src/test/java/org/exist/storage/lock/CollectionLocksTest.java

- Use more readable switch statement
- Increase timeout in order for less windows builds to fail

[refactor] Code clean up, stabalize test

---

exist-core/pom.xml

- Fixes known vulnerability using an newer library
- Fixed a wrong version variable

[bugfix] Fixed vunerable lib & wrong variable name

---

exist-installer/src/main/izpack/UnixShortcutSpec.xml
exist-installer/src/main/izpack/userInput.xml

Removed some more missplaced configuration tags after full validation.

[bugfix] Fixes missplaced izPack config tags

---

exist-distribution/src/main/config/conf.xml
schema/conf.xsd

Added all avaliable attribute documentation from the example XML conf file to the XSD to be available within a schema based editor.

[doc] Enhances XSD documentation

---

.github/workflows/ci-test.yml
exist-parent/pom.xml

Thank you for your contribution to eXist-db!

[ci] Adds NIST NVD API key

---

extensions/indexes/range/src/main/java/org/exist/indexing/range/RangeIndexConfigAttributeCondition.java

- less indentation
- use final variables where possible
- return early
- remove this. where possible
- switch negated conditions where it made sense
Followup PR to #5246

[refactor] RangeIndexConfigAttributeCondition for readability

---

.github/workflows/ci-test.yml

Upgrade to latest mvnd (supporting mvn 3.x)

[feature] Upgrade to latest mvnd (supporting mvn 3.x)

---

.github/workflows/ci-test.yml
exist-parent/pom.xml

Upgrade all build related maven plugins.
macOS build is expected to fail, this is addressed in #5385

[ci] Upgrade all build related maven plugins

---

exist-parent/pom.xml
extensions/indexes/spatial/pom.xml
extensions/webdav/pom.xml

Make sure the latest jdom(1) jar is used, i.s.o. 2 different older versions
Backport of #5393

[bugfix] 6xx Make sure the latest jdom(1) jar is used

---

exist-parent/pom.xml

Combines #5408  and #5409 into one pull request

Combines two Dependabot JUnit merge Requests into one

---

exist-core/src/main/java/org/exist/collections/triggers/XQueryTrigger.java

Forward port of https://github.com/eXist-db/exist/pull/5481

Fix an issue where XQuery Trigger state may leak

---

exist-core/src/main/java/org/exist/collections/triggers/XQueryTrigger.java

Closes https://github.com/eXist-db/exist/issues/5459

[6.x.x] Fix an issue where XQuery Trigger state may leak

---

exist-core/src/main/java/org/exist/collections/triggers/XQueryTrigger.java

Backport of https://github.com/eXist-db/exist/pull/5481

 [5.x.x] Fix an issue where XQuery Trigger state may leak

---

exist-core/src/test/java/org/exist/storage/StoreResourceTest.java

Test may complete in 1ms or less so we need to account for that

Fix flaky storage test timing

---

exist-core/src/test/java/org/exist/storage/StoreResourceTest.java

Backport of https://github.com/eXist-db/exist/pull/5491

[6.x.x] Fix flaky storage test timing

---

extensions/modules/xslfo/pom.xml

Rewrite of original dependabot PRs
covers #5489 #5488 and #5486

Bump org.apache.xmlgraphics.* from 2.9 to 2.10

---

extensions/indexes/range/src/test/xquery/range/optimizer.xql

https://github.com/eXist-db/exist/pull/4910
Closes https://github.com/eXist-db/exist/issues/5496

Fix failing Range Index test after merge of https://github.com/eXist-db/exist/pull/4910

---

extensions/modules/sql/src/main/java/org/exist/xquery/modules/sql/ExecuteFunction.java
extensions/modules/sql/src/test/java/org/exist/xquery/modules/sql/ExecuteIT.java

Forward port of https://github.com/eXist-db/exist/pull/5186

Allow setting the namespace on the result of sql:execute

---

extensions/modules/xslfo/pom.xml

Bump org.apache.xmlgraphics:fop-core from 2.9 to 2.10 in /extensions/modules/xslfo

---

.github/workflows/ci-test.yml

GitHub Secrets can not be access from Pull Requests, see: https://github.com/eXist-db/exist/settings/secrets/actions

Fix CI issues with PR that require GitHub Secrets

---

exist-core/src/main/java/org/exist/webstart/JnlpJarFiles.java

Waiting for stacktrace. should fix #5544

[bugfix] Repair JNLP interface, use correct BC library

---

exist-core/src/main/java/org/exist/webstart/JnlpJarFiles.java

[6.x.x] Repair JNLP interface, use correct BC library

---

exist-core/src/test/java/org/exist/xquery/functions/transform/TransformFromPkgTest.java

- load the module from existdb instead of an external source
- test with and without xmldb: scheme
- fix template under test to actually do something
- ensure that the output is checked for correctness

[hotfix] fix and extend TransformFromPkgTest

---

extensions/webdav/pom.xml

- run tests -> OK
- login webdav -> OK

[bugfix] upgrade transient library commons-beanutils

---

.github/workflows/ci-deploy.yml
exist-docker/pom.xml
exist-docker/src/main/resources-filtered/Dockerfile
exist-docker/src/main/resources-filtered/Dockerfile-DEBUG

we are being bitten by see fabric8io/docker-maven-plugin#1289

Backport multi arch 5533

---

exist-core/src/main/java/org/exist/source/SourceFactory.java
exist-core/src/main/java/org/exist/xquery/XQueryContext.java
exist-core/src/test/java/org/exist/xquery/ModuleImportTest.java
exist-core/src/test/resources-filtered/org/exist/xquery/conf.xml

[6.x.x] allow module imports in one-off xqueries

---

exist-core/src/main/java/org/exist/xslt/XsltURIResolverHelper.java
exist-core/src/test/java/org/exist/xquery/functions/transform/ImportStylesheetTest.java

[6.x.x] registered import-uris have precedence

---

.github/workflows/ci-snapshots.yml

hopefully this will work
see #5603

[fix] snapshot CI config

---

exist-core/src/main/java/org/exist/client/ClientFrame.java
exist-core/src/main/java/org/exist/client/CollectionXConf.java

Small fix:  added error messages when exceptions arise in ClientFrame, as well as a minor fix in CollectionXConf to follow Java's convention
This was suggested by SonarCloud

[bugfix] Add Catch exceptions in JavaClient

---

.idea/runConfigurations/Java_Admin_Client.xml
.idea/runConfigurations/Jetty_Server.xml
.idea/runConfigurations/Local_Jetty_Server.xml

Configure IntelliJ runconfig files to enforce java21

[bugfix] Configure IntelliJ runconfig files to enforce java21

---

exist-core/src/test/java/org/exist/backup/RestoreAppsTest.java
exist-core/src/test/java/org/exist/config/mapping/ConfigurableTest.java
exist-core/src/test/java/org/exist/security/AbstractSecurityManagerRoundtripTest.java
exist-core/src/test/java/org/exist/storage/NativeBrokerLockingTest.java
exist-core/src/test/java/org/exist/storage/journal/JournalTest.java
exist-core/src/test/java/org/exist/storage/lock/LockManagerTest.java
exist-core/src/test/java/org/exist/storage/structural/NativeStructuralIndexWorkerTest.java
exist-core/src/test/java/org/exist/util/serializer/EXISerializerTest.java
exist-core/src/test/java/org/exist/xmldb/ResourceTest.java
exist-core/src/test/java/org/exist/xquery/RestBinariesTest.java
extensions/indexes/lucene/src/test/java/org/exist/indexing/lucene/AnalyzerConfigTest.java
extensions/indexes/range/src/test/java/org/exist/indexing/range/RangeIndexConfigTest.java
extensions/modules/file/src/test/java/org/exist/xquery/modules/file/RestBinariesTest.java
extensions/modules/mail/src/test/java/org/exist/xquery/modules/mail/WriteMessageTest.java

Make code better readable
Splitup of original PR

[refactor] Use SequencedCollection API of Java21

---

exist-installer/src/main/izpack/UnixShortcutSpec.xml
exist-installer/src/main/izpack/custom.eng.xml
exist-installer/src/main/izpack/install.xml
exist-installer/src/main/izpack/shortcutSpec.xml
exist-installer/src/main/izpack/userInput.xml
exist-parent/pom.xml

Update IzPack to 5.2.4 to fix #5661

[6.x.x] Update IzPack to 5.2.4

---

exist-core/pom.xml
exist-parent/pom.xml
extensions/modules/compression/pom.xml

This version of jetty removes a potential 'weakness'

[library] upgrade of jetty and additional libraries

---

.github/workflows/ci-test.yml
exist-parent/pom.xml

Switch nexus develop

---

exist-installer/pom.xml

We would otherwise potentially leak secrets with the next release

[build] only include specific props into izpack installer

---

exist-distribution/pom.xml

[ignore] update appbundler-maven-plugin to v3.2.0

---

exist-parent/pom.xml

Combines dependabot JUnit library updates

---

exist-core/pom.xml

Bump com.fasterxml.jackson.core:jackson-core to 2.19.1
Sync of #5769

[6.x] Bump com.fasterxml.jackson.core:jackson-core  to 2.19.1

---

exist-parent/pom.xml

Combines #5778 and #5779 in order to pass the build correctly.

Combines the Dependabot JUnit updates

---

README.md

Adds Javadoc badge and clean up the backers plain html link.

[doc] Adds JavaDoc/clean up backers badge

---

exist-parent/pom.xml

[ci] Revise output maven enforcer plugin.

---

extensions/indexes/lucene/src/main/java/org/exist/indexing/lucene/AbstractFieldConfig.java
extensions/indexes/lucene/src/main/java/org/exist/indexing/lucene/AnalyzerConfig.java
extensions/indexes/range/pom.xml
extensions/indexes/range/src/test/java/org/exist/indexing/range/RangeIndexConfigTest.java
extensions/indexes/range/src/test/resources/logback-test.xml

* The if condition was flipped in the last change to this class without flipping the result.
* The expression is now set in the constructor and not initialized.
* The if-condition in doBuild was simplified
see also the failing tests in xst https://github.com/eXist-db/xst/actions/runs/16530086813/job/46753072716?pr=289

[fix] AbstractFieldConfig recognizes expressions again
