src/org/exist/util/serializer/HTML5Writer.java
src/org/exist/util/serializer/IndentingXMLWriter.java
src/org/exist/util/serializer/SAXSerializer.java
src/org/exist/util/serializer/TEXTWriter.java
src/org/exist/util/serializer/XHTML5Writer.java
src/org/exist/util/serializer/XHTMLWriter.java
src/org/exist/util/serializer/XMLWriter.java
test/src/xquery/serializer.xql
test/src/xquery/suite.xql

Improved html5 serialiser which respects the html5 syntax (as expected by most external tools):
* void elements like input, meta or img never have content and must not be closed by an end tag
* script and style are "raw text" elements whose content should not be escaped
* attributes with name=value (like checked="checked") are output as empty attributes without value
The html5 serializer will **not produce well-formed xml**. Use the xhtml5 serializer if you need the output to be well-formed.
Future todo: use the version serialisation property to distinguish between html serialisers.

Improved HTML5 serialiser [reworked: AR]

---

src/org/exist/storage/NativeBroker.java

This reduces the frequency of statistics printed to the log when performing a database sync. Stats will now be printed at most once every 10 minutes.

[feature] Print statistics to log only once every ~10 mins

---

extensions/indexes/lucene/test/src/xquery/lucene/queries.xml

Also renamed some XML query tests which do not use XML syntax

test for ea9fd6a (Support for Regex within Spans in Lucene)

---

extensions/indexes/lucene/src/org/exist/indexing/lucene/XMLToQuery.java

I recently updated from eXist 2.1 to 2.2 and I came across the problem that Regex queries are no longer supported within Span queries.
Given that the class SpanRegexQuery was deprecated in Lucene 4.0 and is no longer available in exist 2.2, I propose to use the replacement class provided by lucene: SpanMultiTermQueryWrapper<RegexQuery>(new RegexQuery()) to keep supporting the use of Regex within Spans queries.
This has fixed the issue for me, hope you consider ir.
Kind regards.

Support for Regex within Spans in Lucene

---

extensions/svn/extension.xml
extensions/svn/src/org/exist/versioning/svn/internal/wc/SVNMergeDriver.java
extensions/svn/src/org/exist/versioning/svn/internal/wc/SVNPropertiesManager.java
extensions/svn/src/org/exist/versioning/svn/internal/wc/SVNTreeConflictUtil.java
extensions/svn/src/org/exist/versioning/svn/internal/wc/admin/SVNTranslator.java
extensions/svn/src/org/exist/versioning/svn/old/ExportEditor.java
extensions/svn/src/org/exist/versioning/svn/wc/SVNWCClient.java

Updating svn extension library svnkit to version 1.8.8 to support jdk7u75+ and jdk8u31+. Please remove your current EXIST_HOME/lib/user/{svnkit,svnkit-cli}.jar to update on build.

Updating svn extension library svnkit to version 1.8.8

---

src/org/exist/xquery/TryCatchExpression.java
test/src/xquery/TestRunner.java
test/src/xquery/xquery3/xq3_trycatch.xml

There were several XDM typing issues with the `$err` variables bound within the `catch` expression of a *try/catch* block. In particular the `xs:QName` for `$err:code` was incorrectly processed as an `xs:string` resulting in lost namespace information.

Bugfix try/catch

---

src/org/exist/storage/XQueryPool.java
src/org/exist/xquery/XQueryContext.java

Deadlocks occurred when an XQuery module was saved and another thread tried to execute it at the same time. The issue is caused by the restxq trigger trying to check for cached modules while the collection is still locked. Fix: we effectively disabled caching of library modules long ago, so the cache lookup will never find anything. Yet it synchronizes on the query pool. Removing this old code fixes the issue.

[bugfix] Deadlock when saving XQuery module

---

src/org/exist/xquery/value/BinaryValueFromBinaryString.java

fix BinaryValueFromBinaryString use standard ByteArrayInputString instead overriding InputStream (avoid NPE in some cases)

fix BinaryValueFromBinaryString

---

conf.xml.tmpl
src/org/exist/protocolhandler/URLStreamHandlerStartupTrigger.java
src/org/exist/protocolhandler/eXistURLStreamHandlerFactory.java
src/org/exist/util/Configuration.java

This ensures that the URL Stream Handler is just registered once within the JVM. In particular, this stops a whole bunch of junk log output when running the test suite.

Register eXists URL Stream Handler just once

---

src/org/exist/storage/BrokerPool.java

Scheduler must be shutdown before entering the `synchronized` block as it represents other threads which are potentially trying to take brokers (e.g. call `BrokerPool#get(...)` which will block on its `synchronized` block)... thus leading to a deadlock!
Closes https://github.com/eXist-db/exist/issues/464

Fix shutdown deadlock

---

src/org/exist/storage/BrokerPool.java

Scheduler must be shutdown before taking the exclusive TransactionManager lock. Otherwise scheduled task threads which try to also obtain the lock may deadlock.

Further shutdown deadlock fix.

---

src/org/exist/xquery/LocationStep.java
test/src/xquery/selfAxis.xml

Wrong dependency leads to incorrect query result in combination with boolean operator: a unrooted path expression depends on the context item. Difficult to reproduce, but the issue does show up when using the bang operator (see test).

[bugfix] Wrong dependency leads to incorrect query result

---

src/org/exist/xquery/XQueryContext.java
src/org/exist/xquery/functions/util/Eval.java

Do not build the initial document set for the eval context until it is required. Most of the initialization time for the eval context was spent here, keeping other threads blocked.

[performance] Fix severe bottleneck in util:eval

---

mime-types.xml.tmpl

[ODD](http://en.wikipedia.org/wiki/Text_Encoding_Initiative#ODD) is an XML-based vocabulary for defining schemas for Text Encoding Initiative (TEI) projects.  ODD should be treated as XML syntax but until this pull request was treated as a binary format.

add .odd as an XML file extension

---

extensions/debuggee/test/org/exist/debugger/DebuggerTest.java
extensions/indexes/lucene/test/src/org/exist/indexing/lucene/LuceneIndexTest.java
src/org/exist/util/function/BiFunctionE.java
src/org/exist/util/function/Either.java
src/org/exist/util/function/FunctionE.java
src/org/exist/util/function/TriFunctionE.java
src/org/exist/xmldb/AbstractEXistResource.java
src/org/exist/xmldb/AbstractLocal.java
src/org/exist/xmldb/AbstractLocalService.java
src/org/exist/xmldb/CollectionManagementServiceImpl.java
src/org/exist/xmldb/ExtendedResource.java
src/org/exist/xmldb/LocalBinaryResource.java
src/org/exist/xmldb/LocalCollection.java
src/org/exist/xmldb/LocalCollectionManagementService.java
src/org/exist/xmldb/LocalDatabaseInstanceManager.java
src/org/exist/xmldb/LocalIndexQueryService.java
src/org/exist/xmldb/LocalResourceSet.java
src/org/exist/xmldb/LocalUserManagementService.java
src/org/exist/xmldb/LocalXMLResource.java
src/org/exist/xmldb/LocalXPathQueryService.java
src/org/exist/xmldb/LocalXUpdateQueryService.java
src/org/exist/xmldb/function/LocalXmldbCollectionFunction.java
src/org/exist/xmldb/function/LocalXmldbDocumentFunction.java
src/org/exist/xmldb/function/LocalXmldbFunction.java
test/src/org/exist/collections/triggers/SAXTriggerTest.java
test/src/org/exist/security/XMLDBSecurityTest.java
test/src/org/exist/xquery/JavaFunctionsTest.java

This is a refactor of the server-side implementation of the XML:DB Local API. Through the use of Java 8 lambda expressions we the following advantages:
1) A huge reduction in code, including the removal of duplicated code.
2) Correct use of `Broker`/`Txn`/`Lock`. The lambda expressions ensure that when we take a resource we always return it.
3) Correct User security. The lambda expressions ensure that the correct cached XML:DB user credentials are applied to the correct operation.
4) Consistent exception handling. For example, we handle `PermissionDeniedException` in one place and that always leads to a `ErrorCodes.PERMISSION_DENIED` for the `XMLDBException`.
I plan to shortly also apply similar mechanisms to the XML:DB Remote API.

Cleaned up the XML:DB Local API implementation

---

test/src/org/exist/http/RESTServiceTest.java
test/src/org/exist/security/RestApiSecurityTest.java
test/src/org/exist/xmldb/RemoteDBTest.java

Under extreme circumstances these wait loops can cause the test-suite to hang forever. They are also not actually needed as demonstrated elsewhere in the test-suite codebase.

[bugfix] Avoid potential lock-up when running test-suite

---

.gitignore

This jar was added with #480 to `extensions/svn/extension.xml`

Ignore sequence-library.jar from svn extension

---

extensions/indexes/lucene/src/org/exist/indexing/lucene/LuceneIndexWorker.java
extensions/indexes/lucene/src/org/exist/xquery/modules/lucene/LuceneModule.java
extensions/indexes/lucene/src/org/exist/xquery/modules/lucene/Search.java
extensions/indexes/lucene/test/src/xquery/lucene/plain-ft-functions.xml

* getFieldContent still uses old Lucene API: fails for larger data sets or returns random result
* related: extend ft:search to optionally return selected field content of hits for sorting and display
Closes #562

LuceneIndexWorker.getFieldContent using old API

---

extensions/indexes/lucene/src/org/exist/indexing/lucene/LuceneUtil.java
extensions/indexes/lucene/test/src/org/exist/indexing/lucene/LuceneIndexTest.java
extensions/indexes/lucene/test/src/xquery/lucene/queries.xml

(or fail with maxClauseCount exceeded) but chooses the most suitable one depending on terms and docs quote which the static one does not do.

[bugfix] Make sure the query rewriter does not silently fail 

---

src/org/exist/security/PermissionFactory.java

A quick fix for several NullPointerExceptions when dealing with users without groups. 
I saw there are related tickets (I have not checked whether this patch may help there, too), and this may not be the whole deal, but it is still an improvement.
I just had this patch hanging around for a while, so I thought a pull request was in order.

CLI: removed NPEs for users without group

---

src/org/exist/client/InteractiveClient.java
src/org/exist/client/security/EditUserDialog.java
src/org/exist/client/security/UserManagerDialog.java

* Don't reconnect unless we are changing the logged-in users password
* Only reconnect once when changing the logged-in users password
* Only reconnect when changing the logged-in users password, not also to change group membership
* Don't allow users to be added without a group (console mode).

Admin client user fixes

---

src/org/exist/xquery/ConcatExpr.java
src/org/exist/xquery/FilteredExpression.java
test/src/xquery/optimizer/optimizer.xql

Simplify context expression only if it is a PathExpr. Added test case.
Issue introduced by 138f187

[bugfix] Fix issue with filtered expression

---

src/org/exist/dom/memtree/MemTreeBuilder.java
test/src/org/exist/dom/memtree/DocumentBuilderReceiverTest.java

Explicit namespace prefix got reset to empty namespace. Added test case.
Issue was introduced by 4d3802895cf42c670c6e483c6309f2f5357ca33c

[bugfix] Fix regression in MemTreeBuilder

---

extensions/indexes/lucene/src/org/exist/indexing/lucene/LuceneIndex.java
extensions/indexes/lucene/src/org/exist/indexing/lucene/LuceneIndexWorker.java
extensions/indexes/lucene/src/org/exist/indexing/lucene/LuceneMatchListener.java
extensions/indexes/lucene/src/org/exist/indexing/lucene/QueryDocuments.java
extensions/indexes/lucene/src/org/exist/indexing/lucene/QueryNodes.java
extensions/indexes/lucene/src/org/exist/indexing/lucene/XMLToQuery.java
extensions/indexes/lucene/src/org/exist/xquery/modules/lucene/Search.java
extensions/indexes/range/src/org/exist/indexing/range/RangeIndexWorker.java

Reloading index searchers/readers after every commit to a writer caused a considerable delay, resulting in bad performance and limited scalability when batch-updating a lot of data. Lucene's NRT architecture fixes this and leads to simpler code. Batch-updates should become a lot faster (from 500ms down to 50ms per update in my test case).

[performance] Switch lucene-based indexes to "near realtime" search.

---

extensions/contentextraction/ivy.xml

a lot new eps are pulled in; after stripping down 82megs remain :-/
It is an upgrade from 1.5 -> 1.8:
changelog:
https://tika.apache.org/1.6/index.html
https://tika.apache.org/1.7/index.html
https://tika.apache.org/1.8/index.html

Upgrade Tika library to v1.8 

---

src/org/exist/storage/serializers/EXistOutputKeys.java
src/org/exist/util/serializer/json/JSONSerializer.java

Adding possiblity to output JSON array in JSONSerializer for single items of all types with outputkey json-array-output, eg, declare option exist:serialize "method=json json-array-output=yes"; or util:declare-option.

Make it possible to output JSON array for single items of all types

---

src/org/exist/scheduler/impl/QuartzSchedulerImpl.java
src/org/exist/scheduler/impl/ShutdownTask.java
src/org/exist/xmldb/LocalDatabaseInstanceManager.java
src/org/exist/xmlrpc/RpcConnection.java

Fixes deadlock issue when using Quartz to schedule the database shutdown and also switched XML:DB Local API to use same approach as XML-RPC/XML:DB
Remote API.
Closes https://github.com/eXist-db/exist/issues/602

Fix bin/shutdown.sh not shutting down the database

---

src/org/exist/xmldb/DatabaseInstanceManager.java
src/org/exist/xmldb/LocalDatabaseInstanceManager.java
src/org/exist/xmldb/RemoteDatabaseInstanceManager.java
src/org/exist/xmlrpc/RpcConnection.java

Ensure Synchronous shutdown is also possible, as using async all the time can cause issues if it is too slow (for example in the
JUnit tests)

[bugfix] Fix Synchronous shutdown

---

bin/functions.d/eXist-settings.sh

by setting binary-files=text for grep.

[bugfix] Make test in set_locale_lang not fail with too many arguments error

---

extensions/indexes/range/src/org/exist/indexing/range/RangeIndex.java
extensions/indexes/range/src/org/exist/indexing/range/RangeIndexWorker.java
extensions/indexes/range/src/org/exist/xquery/modules/range/FieldLookup.java
extensions/indexes/range/src/org/exist/xquery/modules/range/Lookup.java
extensions/indexes/range/src/org/exist/xquery/modules/range/RangeIndexModule.java
extensions/indexes/range/src/org/exist/xquery/modules/range/RangeQueryRewriter.java
extensions/indexes/range/test/src/xquery/optimizer.xql

Optimiser did rewrite comparisons using the != or ne operator. However, the index did not support this operator and replaced it by =, leading to wrong query results!

[bugfix] New range index incorrectly processed != like =

---

build.properties
build/scripts/build-impl.xml
src/org/exist/repo/ClasspathHelper.java
src/org/exist/repo/Deployment.java
src/org/exist/system.properties

Avoid installing incompatible Java packages from the package repo. Right now there is no protection against installing a xar package containing incompatible Java libraries.
This PR handles two scenarios:
1. the user tries to install an incompatible xar package: enforce checks of semver-min/-max during deployment. Refuse to deploy a package which indicates to be incompatible with the current eXistdb build.
2. the user updates an eXistdb built from git and has some old xar packages installed: this is the worst case because it will likely mess up the class loader, leading to a broken eXist install. Fix: make the class loader ignore jars from packages defining a version dependency not compatible with the semver of the current eXistdb build.
With this PR, package authors can finally provide …

Better expath compatibility checks

---

extensions/exquery/restxq/src/main/java/org/exist/extensions/exquery/restxq/impl/ExistXqueryRegistry.java

reexamineModulesWithResolvedDependencies:293 logged information with a missing space:
> Dependant '/db/apps/hsg/api/content.xqm' has been resolved. Dependency on: /db/apps/hsg/api/urls.xqmwas removed
This adds a space, e.g., between "urls.xqm" and "was"

add missing space in log output

---

src/org/exist/xquery/value/ValueSequence.java

ValueSequence keeps reference to query variable, which is thus not garbage collected. This dramatically increases the memory footprint of the sequence and may easily lead to out of memory issues if the sequence is stored into e.g. an HTTP session. Fix by cleaning up the reference when the sequence runs out of scope.
A small fix with huge impact... Closes #574

[bugfix] Memory leak in ValueSequence

---

extensions/indexes/lucene/src/org/exist/indexing/lucene/LuceneUtil.java

Lucene automatically rewrites prefix queries matching more than a few hundred index terms. Match highlighting thus failed for those queries, leading to inconsistent behaviour.

[bugfix] Match highlighting failed for lucene prefix query

---

src/org/exist/xquery/LocationStep.java
src/org/exist/xquery/Optimizer.java
test/src/xquery/optimizer/optimizer.xql

An expression like /a/b/(c)[. = "d"] wasn't optimized though that's easily possible.
Closes #522

[performance] Remove extra parentheses around context node

---

src/org/exist/management/impl/ProcessReport.java
src/org/exist/management/impl/ProcessReportMBean.java
src/org/exist/storage/ProcessMonitor.java
src/org/exist/xquery/XQuery.java
src/org/exist/xquery/XQueryWatchDog.java

Fix and extend JMX interface to provide more information required to diagnose bottlenecks on a live production system: 
1. use DelayQueue for recent query log, so it shows all queries during the past X minutes which were slower than X ms (configurable)
2. add thread names, so query stacks, lock manager output and thread dumps can be connected
3. optional: log the URI which triggered an xquery where possible
The changes were made during the past months while analyzing runtime issues on real production systems. They fill in some missing bits and pieces which are required to diagnose performance and concurrency issues.
monex 0.8 is able to display the additional information, though any jmx client will work (or just call /exist/status to get an XML dump).

JMX interface enhancements

---

src/org/exist/dom/persistent/NodeProxy.java
src/org/exist/storage/structural/NativeStructuralIndexWorker.java
src/org/exist/xquery/value/NodeValue.java
src/org/exist/xquery/value/SequenceType.java

Sequence type checks cause node names to be loaded repeatedly. Results in severe performance loss in recursive functions if parameters are typed (as they should be), because the same nodes may be loaded over and over again. 
Fix by caching the node name where available. Preserve known node names when using structural index lookup.

[performance] Sequence type checks

---

src/org/exist/storage/structural/NativeStructuralIndexWorker.java

NPE in structural index caused by 3410c6b. Forgot to commit the change, sorry. Test suite fails.

NPE in structural index

---

src/org/exist/xquery/functions/fn/FunNormalizeUnicode.java
test/src/xquery/fn.xql
test/src/xquery/suite.xql

normalize-unicode had no effect even though icu4j was called. Java now supports normalization out of the box, so replace the current, complex code which depends on icu4j being installed. java.text.Normalizer is straightforward to use and works as expected.
Closes #443

normalize-unicode fix

---

src/org/exist/xquery/XQueryContext.java
test/src/xquery/xquery3/higher-order.xml

Closure variables were restored in reverse order when calling inline function, so variable lookups got messed up. Closes #683

Closure variable bug

---

src/org/exist/xquery/FunctionCall.java
test/src/xquery/arrays/arrays.xql

If execution of a function is deferred (tail optimization), its parameters need to be copied to protect them against overwriting.
Closes #679

Function parameters overwritten

---

src/org/exist/collections/Collection.java
src/org/exist/repo/Deployment.java

Storing a binary resource caused a deadlock when the after*Document trigger was called, in particular if that trigger tried to lock another collection (as the restxq trigger inevitably does when compiling imported modules). The deadlock occurs most often when installing xar packages into the db (because many XQuery scripts are updated), but it may also be triggered in other situations.
Fix: Collection.addBinaryResource must release the collection lock before calling any after* triggers. Instead it keeps a read lock on the document to prevent concurrent modification.
Also, the package collection should not remain locked while files are being installed. This is another source of potential deadlocks, but at least limits concurrency.

Deadlock when storing binary resource

---

src/org/exist/xquery/PathExpr.java

Additional checks to prevent ArrayIndexOutOfBounds in PathExpr which may happen after my commit 5ad1022 (thanks to @zwobit for fixing)

ArrayIndexOutOfBounds in PathExpr

---

src/org/exist/xquery/functions/array/ArrayType.java
test/src/xquery/arrays/arrays.xql

array:tail([1,[2,3]]) should return [[2, 3]].
Closes #695

[bugfix] array:tail incorrectly unwraps nested array.

---

installer/scripts/build.bat

Was missed from - https://github.com/eXist-db/exist/commit/e6027f3c19ae21acf61fbe65d74a3c04152394f8

[bugfix] Correct CLASSPATH for building src from a Windows install

---

src/org/exist/storage/CreateBinaryLoggable.java
src/org/exist/storage/NativeBroker.java
src/org/exist/storage/RenameBinaryLoggable.java
src/org/exist/storage/UpdateBinaryLoggable.java
src/org/exist/storage/btree/BTAbstractLoggable.java
src/org/exist/storage/btree/BTree.java
src/org/exist/storage/dom/AddLinkLoggable.java
src/org/exist/storage/dom/AddMovedValueLoggable.java
src/org/exist/storage/dom/AddValueLoggable.java
src/org/exist/storage/dom/CreatePageLoggable.java
src/org/exist/storage/dom/DOMFile.java
src/org/exist/storage/dom/InsertValueLoggable.java
src/org/exist/storage/dom/RemoveEmptyPageLoggable.java
src/org/exist/storage/dom/RemoveOverflowLoggable.java
src/org/exist/storage/dom/RemovePageLoggable.java
src/org/exist/storage/dom/RemoveValueLoggable.java
src/org/exist/storage/dom/SplitPageLoggable.java
src/org/exist/storage/dom/UpdateHeaderLoggable.java
src/org/exist/storage/dom/UpdateLinkLoggable.java
src/org/exist/storage/dom/UpdateValueLoggable.java
src/org/exist/storage/dom/WriteOverflowPageLoggable.java
src/org/exist/storage/index/AbstractBFileLoggable.java
src/org/exist/storage/index/BFile.java
src/org/exist/storage/journal/AbstractLoggable.java
src/org/exist/storage/journal/LogEntryTypes.java
src/org/exist/storage/txn/Checkpoint.java
src/org/exist/storage/txn/TxnAbort.java
src/org/exist/storage/txn/TxnCommit.java
src/org/exist/storage/txn/TxnStart.java

Java 8 provide method references; As the Enumeration of Loggable sub-classes is statically known and their constructors fixed, we can instead use a method reference to the constructor of each Loggable to avoid the expensive use of reflection at runtime.

Removes the need of reflection for Loggables

---

src/org/exist/backup/Backup.java
src/org/exist/backup/FileSystemBackupDescriptor.java

Under some circumstances after the move to NIO.2 the backup/restore process can fail when it is misused in such a way that it resolves absolute paths against relative paths. There were no tests for such behaviour. Anyway here are some improvements to make it even more robust.

[bugfix] Small fixes to Backup/Restore process

---

build/scripts/junit.xml

otherwise nobody will notice test failures on regular testsuite runs.

Make sure NativeBrokerTest is run when using testsuite ant target test

---

build/scripts/build-impl.xml
installer/vm.properties
src/org/exist/launcher/Launcher.java
src/org/exist/launcher/LauncherWrapper.java
src/org/exist/launcher/SplashScreen.java
src/org/exist/launcher/UtilityPanel.java
src/org/exist/start/start.config
tools/wrapper/bin/control.bat
tools/wrapper/conf/java.policy
vm.properties

With recent Java and Windows versions, the OS is no longer sending a signal to eXist before shutting down, thus causing a crash and a recovery run. The only really reliable method to avoid this is to register eXist as a service. Most new users won't be aware of it though (or do not read the documentation), and get a bad impression.
I have thus extended the desktop launcher to automatically check on startup if eXist has already been installed as a service. If not, the launcher will ask if it should do so. After installation, the service can be controlled from the system tray menu. Advanced users which do not start eXist via the launcher can be expected to know how to install a service.
Tested on win8 and 10. Other operating systems are not affected. Java service wrapper is used to interact …

Windows shutdown issues: launch as service

---

src/org/exist/storage/journal/Journal.java

The first attempt at trying to fix a file handle leak issue on `fs.journal`.

Make sure to close all file descriptors

---

extensions/exquery/restxq/src/main/java/org/exist/extensions/exquery/restxq/impl/xquery/UriFunctions.java
extensions/exquery/restxq/src/main/java/org/exist/extensions/exquery/restxq/impl/xquery/exist/RegistryFunctions.java

The `inspect` module uses reflection to enumerate or access function modules. eXide expects all function modules to be publicly enumerable, and so this change fixes that issue.

Function classes must have `public` visibility

---

src/org/exist/client/ClientFrame.java

Makes it much easier to view the complete error message and/or stack trace in the Java Admin Client when something unexpected happens.

Wrap long errors and stack traces and add a scroll bar

---

src/org/exist/repo/Deployment.java

A library package does not have a target collection. Avoid NPE in this case.

[bugfix] NPE when removing a library package

---

extensions/modules/src/org/exist/xquery/modules/file/Sync.java

Also fix occasional ArrayIndexOutOfBounds caused by out-of-sequence calls to MemTreeBuilder.endElement upon exception.

[bugfix] Repair file:sync: needs REPLACE_EXISTING flag on file copy.

---

src/org/exist/repo/Deployment.java
src/org/exist/xquery/functions/xmldb/XMLDBModule.java
src/org/exist/xquery/functions/xmldb/XMLDBStore.java

support for resources directories in repo.xml, if storing html fails try as binary in deployment.
**Cherry picked version of https://github.com/eXist-db/exist/pull/727 with current develop:**
repo.xml sample:
```
<?xml version="1.0" encoding="UTF-8"?>
<meta xmlns="http://exist-db.org/xquery/repo">
<description>eXistdb some app</description>
<author>eXist Solutions</author>
<website/>
<status>alpha</status>
<license>BSD-2-Clause</license>
<copyright>true</copyright>
<type>application</type>
<target>someapp</target>
<resources path="bower_components" type="binary"/>
<resources path="app/elements" type="binary"/>
</meta>
```

Support for resources in repo.xml (replaces PR #727)

---

src/org/exist/xquery/OpNumeric.java
src/org/exist/xquery/Predicate.java

cause performance loss as the operation is evaluated once per context item, which is completely unnecessary. The performance issue becomes dramatic when running generated XQuery code, e.g. as produced by the REX parser generator. A query took hours instead of a few milliseconds after my fix.
The performance issue was introduced by #86.

[performance] Numeric operators inside filter expression

---

build.properties

Relabel internal RC2 to 3.0.2 [this is not visible anyway to users] ; this is highly required to get my extensions to work ; there is a long standing conflict with my extensions due to API changes between RC1 and RC2 ;
"3.0.2" helps me/us to continue developing extensions, without over and over again explaining our users that RC2 extension are not perse compatible with RC1. This unclearness + conflict is bad for us!
As discussed in weekly telco. Please pull-in ASAP. And please don't use 'puristic' arguments, this is the best and pragmatic solution.

Bump exist version to upcoming RC2

---

build/scripts/build-impl.xml
build/scripts/installer.xml
build/scripts/macosx.xml
build/scripts/setup.xml

Changing to correct name for jar file, now only in one place. Makes ant only builds happy.

Unifying the asocat lib handling. 

---

src/org/exist/xquery/functions/map/AbstractMapType.java
src/org/exist/xquery/functions/map/MapFunction.java
src/org/exist/xquery/functions/map/MapModule.java
src/org/exist/xquery/functions/map/MapType.java
src/org/exist/xquery/functions/map/SingleKeyMapType.java
src/org/exist/xquery/lib/xqsuite/xqsuite.xql
test/src/xquery/maps/maps.xql

1. Corrected the function name `map:for-each-entry` to `map:for-each`
2. Removed `map:new` in favour of `map:merge`
3. Implemented missing function `map:size`
4. Implemented missing function `map:put`
We should now have the correct functions from XPath 3.1 for maps.

Various improvements to XPath 3.1 Map functions

---

tools/jetty/etc/standalone/WEB-INF/controller-config.xml

"WebDAVServlet" seems to be deprecated since 1.4.1 and is currently disabled in
./web.xml for stand-alone jetty.

[bugfix] Fixed URL rewriting for webdav in stand-alone mode.

---

src/org/exist/xmldb/XmldbURI.java
test/src/org/exist/xmldb/XmldbURITest.java

when XmldbURI created without any exception lastSegment must not raise any too

when XmldbURI created without any exception lastSegment must not raise any too

---

extensions/modules/src/org/exist/xquery/modules/xslfo/ApacheFopProcessorAdapter.java

Schema "xmldb:exist:" does not do it, "file:" does -- should be fine, as it seems to be dropped anyways.

java.net.URI picky about what is absolute

---

nbproject/project.properties

Makes netbeans compile without errors on the annotations.

Adding jcip annotations library to netbeans project too.

---

src/org/exist/client/NewResourceDialog.java
src/org/exist/start/Classpath.java
src/org/exist/start/EXistClassLoader.java
src/org/exist/start/LatestFileResolver.java
src/org/exist/start/Main.java
src/org/exist/start/ServiceDaemon.java
src/org/exist/util/function/OptionalUtil.java
tools/wrapper/src/org/exist/wrapper/Main.java

When running `client`/`jetty` from `org.exist.start.Main` eXist did not recognised the new log4j2 jar files as it's definition of `%latest%` in `org/exist/start/start.config` was too narrow.

Improve %latest% in start.config

---

extensions/modules/src/org/exist/xquery/modules/xslfo/ApacheFopProcessorAdapter.java
extensions/modules/src/org/exist/xquery/modules/xslfo/RenderFunction.java
src/org/exist/xquery/functions/transform/Transform.java

We now support:
* http
* https
* file
* exist
URL schemes from inside FO. You can use `exist://localhost/db` to refer to the root collection of the local database.
Note, Apache FOP does not seem to respect it's `font-base` config parameter, and so you will need to use absolute paths for each font that you wish to embed, see: http://fop-users.markmail.org/search/?q=#query:+page:1+mid:gmsajwfwr2la7qxu+state:results
Should improve on https://github.com/eXist-db/exist/pull/912 and https://github.com/eXist-db/exist/pull/914.
@hungerburg Any comments on this?

Make sure that URLs inside a FO are correctly resolved

---

src/org/exist/xquery/XQueryContext.java
test/src/org/exist/xquery/XQueryContextTest.java

BinaryValue's were not closed after an XQuery was executed more than once (i.e. if the XQueryContext was recycled).
I think this one must have been around for quite some time.

[bugfix] Fix an issue where we were leaking file handles and memory.

---

src/org/exist/dom/persistent/NewArrayNodeSet.java
test/src/xquery/axes.xql
test/src/xquery/suite.xql

returned duplicate nodes in rare cases (if applied to deeply nested elements of same name). Fix by making sure the node set is correctly sorted in document order. 
For performance reasons, node sets returned by a structural index lookup are not sorted automatically, because we can normally assume the nodes are already in document order. However, this needs to be tested for edge cases like the one shown in the test.
Closes https://github.com/eXistSolutions/hsg-shell/issues/133

[bugfix] Combination of two descendant axis lookups in an XPath

---

src/org/exist/storage/BrokerPool.java
src/org/exist/storage/DBBroker.java
src/org/exist/util/Stacktrace.java
src/org/exist/util/TraceableStateChange.java
src/org/exist/util/TraceableStateChanges.java
src/org/exist/util/function/Either.java

Note - These utilities are only ever enabled when the logging level is set to TRACE

Utilities for trace logging the history of broker leases and broker subject changes

---

extensions/indexes/range/src/org/exist/indexing/range/RangeIndexWorker.java
extensions/indexes/range/test/src/xquery/optimizer.xql

when used on filter expression, e.g. $x[range:matches(., "y")]. Closes #873.

[bugfix] New range index returns empty sequence

---

src/org/exist/storage/index/BTreeStore.java

BTreeStore used by structure index, but I find no reasons why not switch BTreeStore in general to MultiReadReentrantLock

Structure index: change lock to MultiReadReentrantLock

---

extensions/betterform/main/etc/MergeWebXML.xsl

the Betterform XSLT clearly creates an invalid web.xml document ; we missed that for a long time :-) 
we should/could consider to sync this back to the 2.x  atleast LTS;
question for @JoernT @zwobit  ..... does this change now enable caching whilst it was maybe disabled in the past?

make web.xml valid. fixes #924

---

extensions/contentextraction/ivy.xml

Accidentally asm.jar appeared again ; this jar file conflicts with jetty8 and should thus not be downloaded; as a bonus the file has been reformatted

Remove asm.jar from download

---

src/org/exist/storage/NativeBroker.java
src/org/exist/storage/NativeValueIndex.java

The calls to System.gc date back to the early days and are definitely unnecessary today. They dramatically slow down the reindexing process. Stress testing did not show any negative effects after dropping those calls.

[performance] Remove two calls to System.gc and excessive logging.

---

src/org/exist/xquery/BasicExpressionVisitor.java
src/org/exist/xquery/DefaultExpressionVisitor.java
src/org/exist/xquery/ExpressionVisitor.java
src/org/exist/xquery/FunctionCall.java
src/org/exist/xquery/OpSimpleMap.java
src/org/exist/xquery/functions/fn/FunHeadTail.java
src/org/exist/xquery/value/AbstractSequence.java
test/src/org/exist/xquery/DeferredFunctionCallTest.java

1. query optimizer did not descend into simple map operator expressions, so any code called below it would not be optimized. As a consequence, available range index were not used
2. recursive functions were not re-analyzed after optimization, which again results in range indexes not being used properly

Fixes to query optimizer and range index not being used

---

src/org/exist/xquery/Profiler.java
src/org/exist/xquery/functions/util/Compile.java

Profiling stats only included the name of the called class for built-in functions. This is useless for profiling: instead you want to see the source location from where the function was called.
Also includes a small memory leak fix for function util:compile.

XQuery profiler should track location of function call, not called class

---

src/org/exist/storage/DBBroker.java
test/src/org/exist/storage/MoveOverwriteCollectionTest.java
test/src/org/exist/storage/MoveOverwriteResourceTest.java

Currently > 98.2% of the eXist code base uses `TransactionManager#beginTransaction`, this PR reverts the recent introduction of the 4 calls to `DBBroker#beginTx`, and removes the then unused `DBBroker#beginTx`.
My reasoning is that I would rather not introduce a second way alongside the original. I understand that the current approach could be improved, however if a new approach is decided upon there should be a refactoring commit to completely switch from one to the other; until then I would like us to stick to a single approach. One of the reasons being that I have substantial outstanding work in this area, which starts with https://github.com/adamretter/exist/tree/txn-thread, locally I also have major transaction redesign work and more recently the PR …

[refactor] Use TransactionManager#beginTransaction instead of DBBroker#beginTx

---

bin/functions.d/eXist-settings.sh
src/org/exist/jetty/JettyStart.java
src/org/exist/start/Main.java

Previously `EXIST_HOME` / `exist.home`, and subsequently `jetty.home` and could look like for example:
```bash
[eXist Home : /Users/aretter/code/exist-git/bin/..] 
[jetty.home : /Users/aretter/code/exist-git/bin/../tools/jetty]
```
these changes ensure the paths are normalized, so the paths now correctly look like:
```bash
[eXist Home : /Users/aretter/code/exist-git] 
[jetty.home : /Users/aretter/code/exist-git/tools/jetty]
```

[bugfix] Make sure to normalize exist.home

---

src/org/exist/storage/txn/Txn.java

It is used by the Replication extension only;
For now I'd like to restore it; I'd propose to mark it deprecated and find a better way ASAP. We can't throw it away right now :-(

Reintroducing the 'origin' field of a transaction.

---

build/scripts/installer.xml
build/scripts/setup.xml

Ant scripts to download xars for installer and autodeploy should pass eXist-db version to get the correct app packages matching this version.

Small fix to ant scripts for installer

---

build/scripts/dist.xml

The build was failing on the dist step:
> BUILD FAILED
> /Users/joe/workspace/exist/build/scripts/dist.xml:331: /Users/joe/workspace/exist/dist/eXist-db-3.0.RC2/yajsw/bin does not exist.
This fixes the path to yajsw, allowing the build to complete successfully

Fix path to yajsw in dist build target

---

build/scripts/macosx.xml
installer/scripts/setup.bat
src/org/exist/launcher/ConfigurationDialog.java
src/org/exist/launcher/ConfigurationUtility.java
src/org/exist/launcher/Launcher.java
src/org/exist/launcher/LauncherWrapper.java
src/org/exist/launcher/jetty.xsl

Launching eXist installed as Mac app failed due to whitespaces in path names. 
* changed LauncherWrapper to pass arguments to the Java command separately instead to avoid space issues
* configuration dialog is now shown on first startup before eXist is launched, thus avoiding problems with a restart 
* tested installer and service management on windows 10. minor fix concerning jetty temp directory
Closes #1069

Fix OS X app launcher

---

tools/jetty/webapps/exist-webapp-context.xml

Jetty should scan jars provided by installed expath packages, so they can provide additional servlets without modifying eXist core. This used to work previously but failed after the Jetty 9 update.

Small fix to jetty configuration

---

src/org/exist/xquery/TryCatchExpression.java

The inner try/catch shouldn't mess with an XPathException if it doesn't catch it.
Closes https://github.com/eXist-db/exist/issues/745

[bugfix] Fix nested try/catch

---

build.properties
build/scripts/jarsigner.xml

This allows the jarsigner properties to be overriden in `local.build.properties`.
I would like this so that it makes producing signed jars from on the nightly builds server easier as `local.build.properties` is not under the control of Git and so I can have this point to a keystore outside of `$EXIST_HOME` without worrying about doing a git pull and getting merge conflicts.

[refactor] Extract jarsigner props to build.properties

---

test/src/xquery/dates/format-dates.xql

adapted from table at https://www.w3.org/TR/xpath-functions-31/#rules-for-datetime-formatting

add tests for Z presentation modifier

---

test/src/xquery/dates/format-dates.xql

Thanks to @adamretter for spotting this.

correct expected test result

---

test/src/xquery/maps/maps.xql

This adds a test for the problem reported in #1108 relating to map wildcard lookups.

Add test for #1108 - map wildcard lookup

---

src/org/exist/xquery/Lookup.java
test/src/xquery/arrays/arrays.xql
test/src/xquery/maps/maps.xql
test/src/xquery/xinclude/xinclude.xml

Fixes an issue where a wildcard lookup on a map would previously return the keys, whereas it should have returned the values.

Bugfix lookup wildcard

---

extensions/build.properties

The URL for the memcached Jar download has changed since GoogleCode is effectively retired.

Memcached download

---

mime-types.xml.tmpl

For JavaScript, see https://tools.ietf.org/html/rfc4329 (via http://stackoverflow.com/questions/9664282/difference-between-application-x-javascript-and-text-javascript-content-types)
For Markdown, see https://tools.ietf.org/html/rfc7763 (via http://stackoverflow.com/questions/10701983/what-is-the-mime-type-for-markdown)

Correct mime-type names for JavaScript & Markdown

---

src/org/exist/xquery/lib/kwic.xql

Main fix is that the callback function was previously not applied to all text nodes in `kwic:truncate-following`

Further fixes to the KWIC module

---

extensions/indexes/range/src/org/exist/indexing/range/ComplexRangeIndexConfigElement.java
extensions/indexes/range/src/org/exist/indexing/range/RangeIndex.java
extensions/indexes/range/src/org/exist/indexing/range/RangeIndexAnalyzer.java
extensions/indexes/range/src/org/exist/indexing/range/RangeIndexConfigElement.java
extensions/indexes/range/src/org/exist/indexing/range/RangeIndexWorker.java
extensions/indexes/range/src/org/exist/xquery/modules/range/Lookup.java
extensions/indexes/range/src/org/exist/xquery/modules/range/RangeIndexModule.java
extensions/indexes/range/test/src/xquery/optimizer.xql

1. fix issue with byte reference becoming invalid; 
2. throw error when using fn:contains, fn:starts-with or fn:ends-with on a collated index. A collated index is not suitable for substring matching.
3. generalize analyzer configuration so arbitrary lucene token filters can be plugged into it via collection.xconf (see test cases). It would also be possible to extend this to pass in optional parameters, but looking at the token filters which might apply to a range index, there are hardly any useful ones for the time being, so I skipped this
4. fix wrong gt, ge, lt, le comparison for analyzed strings
5. extended test cases
Closes #1055, #1098.

Range index bug fixes and enhancements

---

src/org/exist/xquery/functions/fn/FunAnalyzeString.java
test/src/xquery/xquery3/fn.xql

as seen in FunMatches.java#L528, an 'x' flag in regular expressions should be interpreted as Pattern.COMMENTS

fix 'x' flag parsing

---

installer/install.xml.tmpl

These must be retained, only ( * ) is in the (former) installer
./tools/jetty/tmp/.DO_NOT_DELETE
./tools/yajsw/tmp/.DO_NOT_DELETE
./webapp/WEB-INF/data/.DO_NOT_DELETE (*)
./webapp/WEB-INF/logs/.DO_NOT_DELETE

Retain temp files and directories. Fixes  #1187

---

extensions/indexes/range/src/org/exist/indexing/range/conversion/DateConverter.java
extensions/indexes/range/test/src/xquery/types.xql

In our project we have to deal with dates BC, like "-300" or "-0004-03-29" that, when indexed, have to be normalized using the DateConverter (which should definitely be documented somewhere... utter happiness ensued when I stumbled upon this while digging through the sources 😄 )
These changes make the converter work correctly with negative (BC) dates. Would be excellent if this could go into 3.0.

Fix BC dates in the range index DateConverter

---

tools/yajsw/bin/installDaemon.sh
tools/yajsw/templates/systemd.vm

`systemctl --user` is inhertently insecure (and as such unsupported in RHEL derived distributions); Instead install eXist as a system service
Users should now run `tools/yajsw/bin/installDaemon.sh` as a user that has `sudo` privileges (or as root) and follow the instructions to install eXist with systemd.
...I think when systemd shuts down the service it is not stopping eXist gracefully, there is still possibly something wrong with our YAJSW config. However we can deal with that in a subsequent PR.

Fixes the installation of systemd for YAJSW

---

src/org/exist/storage/lock/MultiReadReentrantLock.java
src/org/exist/storage/lock/ReentrantReadWriteLock.java

One commit fixes an issue that was recently introduced as a regression. The other is a guard against possible misuse.

Small bugfix to Locks

---

src/org/exist/http/servlets/XQueryServlet.java
webapp/WEB-INF/web.xml.tmpl

Detailed error messages from the XQueryServlet can be disabled by setting a parameter in `web.xml`:
```xml
<init-param>
<param-name>hide-error-messages</param-name>
<param-value>false</param-value>
</init-param>
```
This should be set in production to avoid an exploitable XSS vulnerability.

[feature] Config parameter to hide error messages from the XQueryServlet response

---

extensions/indexes/lucene/src/org/exist/indexing/lucene/PlainTextHighlighter.java

Just close it in finally and all is good. Exception:
```
Caused by: java.lang.IllegalStateException: TokenStream contract violation: close() call missing
at org.apache.lucene.analysis.Tokenizer.setReader(Tokenizer.java:90)
at org.apache.lucene.analysis.Analyzer$TokenStreamComponents.setReader(Analyzer.java:323)
at org.apache.lucene.analysis.standard.StandardAnalyzer$1.setReader(StandardAnalyzer.java:133)
at org.apache.lucene.analysis.Analyzer.tokenStream(Analyzer.java:147)
at org.exist.indexing.lucene.PlainTextHighlighter.getOffsets(PlainTextHighlighter.java:68)
at org.exist.indexing.lucene.LuceneIndexWorker$1.collect(LuceneIndexWorker.java:741)
```

[bugfix] Lucene occasionally throws exception upon unclosed token stream

---

src/org/exist/backup/ExportGUI.java
src/org/exist/backup/SystemExport.java
test/src/org/exist/backup/SystemExportImportTest.java

System export to a zip failed because the output stream got closed after writing the first document. Extended tests to prevent further regressions. Closes #1175

Fix export to zip

---

bin/client.bat
bin/functions.d/eXist-settings.sh
bin/run.bat
bin/server.bat
bin/startup.bat
build/scripts/build-impl.xml
build/scripts/macosx.xml
installer/UnixShortcutSpec.xml
installer/userInput.xml
src/org/exist/launcher/vm.properties
tools/yajsw/src/org/exist/yajsw/Main.java
vm.properties

Increase the default used by the installer for Java max memory from 1024m to 2048m. Most computers today should have >4gb main memory. Giving just 1gb to eXist easily results in out of memory issues and crashes.
Also fix a ClassCastException popping up during startup/shutdown.

Increase max memory default and cache size, small fixes

---

build/scripts/dist.xml

This should fix https://github.com/eXist-db/exist/issues/1215

include required jars for contentextraction module in WAR build

---

src/org/exist/source/SourceFactory.java

InvalidPathException is thrown while probing locations in SourceFactory. Issue only pops up when running tests on windows.
Closes #1217 and #1041

Resolving XQuery modules or loading documents from disk fails

---

src/org/exist/storage/ProcessMonitor.java
src/org/exist/xquery/PathExpr.java
src/org/exist/xquery/VariableDeclaration.java
test/src/xquery/axes.xql

A variable declaration should not return a context sequence, not even an empty one or followup expressions may start from a wrong context.
Closes #1114.

Fix variable declaration

---

src/org/exist/xquery/functions/transform/Transform.java

added 4th argument, moved 4th -> 5th.
----
Applies an XSL stylesheet to the node tree passed as first argument. The stylesheet is specified in the second argument. This should either be an URI or a node. If it is an URI, it can either point to an external location or to an XSL stored in the db by using the 'xmldb:' scheme. Stylesheets are cached unless they were just created from an XML fragment and not from a complete document. Stylesheet parameters may be passed in the third argument using an XML fragment with the following structure: <parameters><param name="param-name" value="param-value"/></parameters>. There are two special parameters named "exist:stop-on-warn" and "exist:stop-on-error". If set to value "yes", eXist will generate an XQuery error if the XSL processor reports a …

Fix xslt transform description to as-is codebase state

---

extensions/indexes/range/test/src/xquery/index-keys.xql
extensions/indexes/range/test/src/xquery/suite-index-keys.xql

Add test showing problem with dynamic context in range:index-keys-for-field

---

src/org/exist/xquery/xqdoc/parser/XQDocParser.g
src/org/exist/xquery/xqdoc/parser/XQDocParser.java

Fixes a StringIndexOutOfBoundsException in XQDocParser. fixes https://github.com/eXist-db/exist/issues/1220
I am not sure if other files need to be checked in too? ./build.sh generates a few more files…. not yet in the archive.

Fixes a StringIndexOutOfBoundsException in XQDocParser. 

---

extensions/indexes/range/src/org/exist/xquery/modules/range/RangeQueryRewriter.java
extensions/indexes/range/test/src/xquery/optimizer.xql

Fix query optimizer to not rewrite query using new range index if context step is on a reverse axis. Results will be wrong. Closes #1238.
Add test cases.

[bugfix] Range index query optimizer fix

---

extensions/indexes/range/src/org/exist/indexing/range/ComplexRangeIndexConfigElement.java
extensions/indexes/range/src/org/exist/indexing/range/RangeIndexConfig.java
extensions/indexes/range/src/org/exist/indexing/range/RangeIndexConfigCondition.java
extensions/indexes/range/src/org/exist/indexing/range/RangeIndexWorker.java
extensions/indexes/range/src/org/exist/xquery/modules/range/OptimizeFieldPragma.java
extensions/indexes/range/test/src/xquery/conditions.xql
extensions/indexes/range/test/src/xquery/suite-conditions.xql

This adds the possibility to add an attribute condition on complex range index config elements:
```xml
<create qname="tei:note">
<condition attribute="type" value="text_type" />
<field name="text_type" type="xs:string" case="no"></field>
</create>
```
Will only store the text of the `tei:note` element in the `text_type`field if it has an attribute named "type" with the value "text_type". 
Queries like
```xq
tei:note[@type="text_type"][.="some text type"] 
```
will be rewritten to 
```xq
tei:note[range:field("text_type", "eq", "some text type")] 
```
I tried to add as little complexity as possible to keep the performance impact at a minimum, especially if there are no conditions defined. If anyone has any suggestions for some benchmarks  I could do let me know...
_Background_: In a project …

[feature] conditional range index configs based on an attribute value

---

src/org/exist/xquery/ForExpr.java
test/src/xquery/xquery3/groupby.xql

always call `preEval` for all `FLWORClause` except `WhereClause`

---

extensions/modules/src/org/exist/xquery/modules/sql/ExecuteFunction.java
test/src/org/exist/xquery/modules/sql/ExecuteFunctionTest.java
test/src/xquery/modules/sql/suite.xql

The results created by sql:execute contain '&amp;lt;' instead of '<', the same problem exists for '>' and '&'.
Ticket #1199 
Java Unit Test of ExecuteFunction, the database is mocked, no further dependencies introduced

Unit test and fix for #1199

---

src/org/exist/xquery/BasicFunction.java
src/org/exist/xquery/functions/fn/FnHasChildren.java
src/org/exist/xquery/functions/fn/FnInnerMost.java
src/org/exist/xquery/functions/fn/FnModule.java
src/org/exist/xquery/functions/fn/FnOuterMost.java
test/src/xquery/xquery3/fn.xql

Implements from XPath Functions and Operators 3.0:
```xquery
fn:has-children() as xs:boolean
fn:has-children($node as node()?) as xs:boolean
fn:innermost($nodes as node()*) as node()*
fn:outermost($nodes as node()*) as node()*
```

Some more F+O 3.1 functions

---

extensions/modules/src/org/exist/xquery/modules/expathrepo/InstallFunction.java

if url is xml resource then it get read-locked
(similar to #1264 )

make sure to unlock xml resource

---

test/src/xquery/xquery3/typeswitch.xql

This PR adds a failing test (with `%test:pending` annotation) demonstrating the problem documented at https://github.com/eXist-db/exist/issues/1155.

Add test showing bug in typeswitch - eXist allows invalid "empty()" check

---

src/org/exist/xquery/parser/XQuery.g
src/org/exist/xquery/parser/XQueryLexer.java
test/src/xquery/xquery3/strconstr.xql

Make sure special chars do not need to be escaped and character entities are not expanded.
Closes #1317

Do not interpret quotes as string literals inside string constructor

---

extensions/indexes/range/src/org/exist/indexing/range/ComplexRangeIndexConfigElement.java
extensions/indexes/range/src/org/exist/indexing/range/RangeIndex.java
extensions/indexes/range/src/org/exist/indexing/range/RangeIndexConfigAttributeCondition.java
extensions/indexes/range/src/org/exist/indexing/range/RangeIndexConfigCondition.java
extensions/indexes/range/src/org/exist/xquery/modules/range/OptimizeFieldPragma.java
extensions/indexes/range/src/org/exist/xquery/modules/range/RangeQueryRewriter.java
extensions/indexes/range/test/src/xquery/conditions.xql

This adds a few extensions to the attribute range index condition introduced in #1233:
- ability to specify an operator for the condition, implemented operators are`eq, ne, lt, gt, le, ge, starts-with, ends-with, contains, matches`. Can be specified using an `operator` attribute on the `condition` element. If the attribute is missing, `eq` is assumed as default.
- case insensitive comparison by specifing `case="no"` on the `condition` element
- numeric comparison by specifing `numeric="yes"`. When enabled, `01.0` will equal `1` and `2` will be less than `110`, for example. By default, string matching is assumed. The rewriter will respect the type of the value (string, numeric) when matching a condition to a predicate.
- rewriting improvements:
- the order of attribute name and value can …

[feature] extend range index conditions

---

extensions/indexes/lucene/src/org/exist/xquery/modules/lucene/QueryField.java
extensions/indexes/lucene/test/src/xquery/lucene/query-field.xql
extensions/indexes/lucene/test/src/xquery/lucene/suite-query-field.xql

I've noticed that ft:query-field is not evaluated only once for the context sequence, but once for each item in the context sequence. For example, given an index named "testField" on the qname `test` with a collection with test1.xml and test2.xml both containing the following data:
```xml
<test>
<p>Rüsselsheim</p>
<p>Russelsheim</p>
<p>Māori</p>
<p>Maori</p>
</test>
````
the query `/test[ft:query-field("testField", "Rüsselsheim", <options/>)]` will execute ft:query-field two times instead of only once. While this still leads to the correct results, the performance is not as good as it could be for larger context sequences. I've included an xquery test demonstrating this.
This code fixes the issue by making the function only depend on the context sequence. Please be aware that I don't …

[fix?] Lucene index – make query-field only depend on the context sequence

---

src/org/exist/jetty/ServerShutdown.java

There was a small mistake in the arguments definitions for the shutdown command line tools. This corrects that.

[bugfix] Correct the args definitions for shutdown command line tools

---

src/org/exist/launcher/Launcher.java

Capitalize "dashboard" in menu bar entry, "Open dashboard".
The name of the app is capitalized, "Dashboard": https://github.com/eXist-db/dashboard/blob/master/repo.xml#L3
It is also capitalized in the tool window: https://github.com/eXist-db/exist/blob/develop/src/org/exist/launcher/UtilityPanel.java#L75.
The capitalized version will look better alongside the other non-lower-case app resources in the eXist menu bar: eXide, Java Admin Client, and Monitoring and Profiling.

Capitalize "dashboard" in menu bar entry

---

src/org/exist/security/UnixStylePermission.java

it can happen when account or group can't be found by id because of storage corruption or missing account or group
```
java.lang.NullPointerException: null
at org.exist.webdav.ExistCollection.initMetadata(ExistCollection.java:120) ~[exist-webdav.jar:?]
at org.exist.webdav.MiltonCollection.<init>(MiltonCollection.java:123) ~[exist-webdav.jar:?]
at org.exist.webdav.MiltonCollection.getCollectionResources(MiltonCollection.java:157) ~[exist-webdav.jar:?]
at org.exist.webdav.MiltonCollection.getChildren(MiltonCollection.java:177) ~[exist-webdav.jar:?]
```

avoid NPE on Permissions getOwner and getGroup calls

---

src/org/exist/client/InteractiveClient.java
src/org/exist/webstart/JnlpJarFiles.java

A null pointer exception appears when starting the Java client via webstart. The stack trace:
```
java.lang.NullPointerException
at java.util.Properties$LineReader.readLine(Properties.java:434)
at java.util.Properties.load0(Properties.java:353)
at java.util.Properties.load(Properties.java:341)
at org.exist.client.InteractiveClient.loadClientProperties(InteractiveClient.java:1833)
at org.exist.client.InteractiveClient.run(InteractiveClient.java:2116)
at org.exist.client.InteractiveClient.main(InteractiveClient.java:237)
```
The code does not handle null-values for the stream. As a result the application crashes.
*no one* can start the client right now via webstart, so I'd label it as rather significant
- http://markmail.org/message/zofbibpuko5aqh4u 
- start exist-db
- browse to portal.
- …

Java Client cannot be started via Java Webstart: NPE and missing JAR

---

extensions/webdav/src/org/exist/webdav/ExistCollection.java

`IOException` hidden and `ConflictException` is not raise on `IOException`

do not hide IOException at webdav createCollection

---

src/org/exist/xquery/XQueryContext.java

On several servers I saw memory consumption increasing slowly over time. Stress testing revealed instances of BinaryValueFromInputStream staying in memory and building up over weeks until eXist would eventually crash.
Debugging showed the registered XQueryContext.BinaryValueCleanupTask is never executed because cleanupTasks list is cleared too early (in XQueryContext.reset). Thus when XQueryContext.runCleanupTasks is called, the list of tasks is already empty.
The fix is simple: clear cleanupTasks after tasks have been executed, not before.

Slow memory leak

---

src/org/exist/xquery/functions/map/MapExpr.java

Analyzing a heap dump from one of @joewiz servers, I found another memory leak: the literal constructor for maps does not implement resetState for its subexpressions, so any data held in those expressions is not cleared.
Fix is quite simple: overwrite resetState and pass it on to all subexpressions.

[bugfix] Memory leak: map constructor

---

tools/yajsw/bin/installDaemon.sh

When executed by a regular user, the installation of the systemd unit configuration file fails trying to write to a protected space (`/etc/systemd/system`). This patch ensures that the file is created as the superuser.

Fix creation of the systemd unit configuration file.

---

src/org/exist/collections/CollectionConfiguration.java
src/org/exist/collections/triggers/AbstractTriggerProxy.java
src/org/exist/collections/triggers/CollectionTriggerProxy.java
src/org/exist/collections/triggers/DocumentTriggerProxy.java
src/org/exist/collections/triggers/TriggerProxy.java
src/org/exist/storage/serializers/CustomMatchListenerFactory.java

Somewhere in the past someone commented out the code in `CollectionConfiguration#triggerRegistered` which broke the `VersioningFilter`, see: https://github.com/eXist-db/xquery-versioning-module/issues/6
I have reimplemented that very simple code. This PR consists of two commits, the first is just mechanical cleanup and can be ignored, the second is the actual bugfix.

CollectionConfiguration#triggerRegistered was previously disabled

---

extensions/modules/src/org/exist/xquery/modules/persistentlogin/PersistentLogin.java

Quick fix to disable sequential token re-creation in PersistentLogin, which was creating problems with AJAX. I left the token re-creation code, not sure if this should be made configurable.
https://trello.com/c/p8CLLdNs/46-review-persistent-login-module-and-create-best-practice-recommendation-to-use-in-our-apps
Compiled and manually verified. Also ran "./build.sh test"

disable seqential token re-creation by default

---

bin/functions.d/getopt-settings.sh
bin/server.sh
bin/startup.sh

This is supposed for standalone deployments to be controlled by systemd and alike services.
in order to let systemd supervise and control the process it needs to be aware of its pid which is not the case when the `server.sh` script launches Java as a subprocess.
in parts i also changed the indentation to be more comprehendable.

Adds --forking and --pidfile options to server.sh

---

src/org/exist/dom/persistent/DefaultDocumentSet.java
src/org/exist/dom/persistent/DocumentSet.java
src/org/exist/dom/persistent/EmptyDocumentSet.java
test/src/org/exist/dom/persistent/DefaultDocumentSetTest.java

1. Fixes a bug in `DefaultDocumentSet#contains`, see https://github.com/eXist-db/exist/issues/1406
2. Optimises `contains` between two `DeafultDocumentSets`
2. Optimises `equalDocs` between two `DeafultDocumentSets`
@wolfgangmm I would like your thoughts on why we have not encountered this bug in `DefaultDocumentSet#contains` before in XQuery.

Bug fix and optimise in DefaultDocumentSet

---

extensions/indexes/lucene/src/org/exist/indexing/lucene/LuceneMatchListener.java
test/src/xquery/ft-match.xql
test/src/xquery/suite.xql

When using "ignore" in a Lucene index definition, an empty string was returned by the match highlighter if the name of the ignored element happened to be the same as that of the root element indexed. 
Using "ignore" on nested structures is a common use case, e.g. in TEI where `div` elements tend to be nested. So an index definition like
```xml
<text qname="div">
<ignore qname="div"/>
</text>
```
makes sense. One only wants content in the top-level div to be queried, while content in nested divs will produce separate matches. This approach failed though as the match highlighter did ignore the entire outer div, returning an empty string.
Note that the indexer does correctly ignore the nested divs.

[bugfix] Lucene match highlighting of ignored nodes

---

build.properties
build/scripts/macosx.xml

Assuming you have a "Developer ID Application" certificate from Apple for MacOS. You can now create a signed .app/.dmg package by:
1) Ensure that `$EXIST_HOME/local.build.properties` contains a line like:
```
mac.codesign.identity=Developer ID Application: Your Megacorp Here
```
but replace `Your Megacorp Here` with the identity of your certificate.
2) Run `./build.sh app-signed`. Note the signing will only take place on a MacOS system, as there are currently no 3rd party tools for signing Mac packages on other platforms.

Allow anyone with a valid certificate to create a signed package for MacOS

---

src/org/exist/xquery/functions/fn/FunReplace.java
test/src/xquery/xquery3/arrowop.xql

[bugfix] fn:replace arguments not cleared when dynamically called. Closes #1357

[bugfix] fn:replace with arrow operator

---

bin/functions.d/getopt-settings.sh

i was looking for a way to provide Jetty configuration per cli-options. this variable seemed to point into the right direction, but leads nowhere.

Removes unused JETTYCONTAINER_OPTS

---

src/org/exist/util/io/CachingFilterInputStream.java
test/src/org/exist/util/io/CachingFilterInputStreamTest.java

This was previously a problem for the `bin:part` function in the EXPath Binary Module

[bugfix] CachingFilterInputStream#skip previously set the wrong srcOffset

---

src/org/exist/storage/serializers/EXistOutputKeys.java
src/org/exist/util/serializer/json/JSONObject.java
src/org/exist/util/serializer/json/JSONWriter.java
test/src/org/exist/util/serializer/json/JSONWriterTest.java

Adds the option to discard whitespace text nodes when serializing XML/XDM to JSON.
Useful in the [exist-algolia-index](https://github.com/BCDH/exist-algolia-index).

[feature] Added ExistOutputKeys.JSON_IGNORE_WHITESPACE_TEXT_NODES

---

extensions/modules/src/org/exist/xquery/modules/xslfo/ApacheFopProcessorAdapter.java
src/org/exist/http/servlets/XSLTServlet.java
src/org/exist/xquery/functions/transform/EXistURIResolver.java
src/org/exist/xquery/functions/transform/Transform.java
src/org/exist/xquery/functions/transform/TransformModule.java
src/org/exist/xslt/EXistURIResolver.java
src/org/exist/xslt/Stylesheet.java
src/org/exist/xslt/StylesheetResolverAndCompiler.java
src/org/exist/xslt/StylesheetUri.java
src/org/exist/xslt/TemplatesFactory.java
src/org/exist/xslt/TransformerFactoryAllocator.java
src/org/exist/xslt/XSLTErrorsListener.java
test/src/org/exist/xquery/TransformTest.java
test/src/org/exist/xslt/TransformerFactoryAllocatorTest.java

inline xsl stylesheets caching and compiling between XSLTServlet and xquery `transform` function;
[bugfix] avoid concurrent use of different variables: DBBroker, ErrorListener, SAXTransformerFactory (and it attributes).
close #1312

XSL stylesheet caching and compiling bugfixes

---

src/org/exist/xquery/FunctionDSL.java

A small DSL which makes defining Functions in Java code much simpler and more readable.
It allows you to define functions signatures by using a DSL like:
```java
private static final String FS_INSERT_BEFORE_NAME = "insert-before";
static final FunctionSignature FS_INSERT_BEFORE = functionSignature(
FS_INSERT_BEFORE_NAME,
"Returns a specified part of binary data.",
returnsOpt(Type.BASE64_BINARY),
optParam("in", Type.BASE64_BINARY, "The binary data"),
param("offset", Type.INTEGER, "The offset to insert at"),
optParam("extra", Type.BASE64_BINARY, "The binary data to insert")
);
```
If you have a function, that is "overloaded" with multiple arity applications possible, you can define it by using a DSL like:
```java
private static final String FS_PART_NAME = "part";
private static final …
```

[feature] A DSL which simplifies the definition of functions

---

src/org/exist/xquery/XPathErrorProvider.java
src/org/exist/xquery/XPathException.java

Exceptions thrown by XQuery functions are eventually wrapped up into an `XPathException` which has an `ErrorCodes.ErrorCode`, this change allows the originating exception to provide an `ErrorCode` if one is not otherwise explicitly provided.
Such a mechanism allows extension modules to provide correct error codes. An example usage is the `expath-bin-module` extension, you can see it in use here: https://github.com/eXist-db/expath-bin-module/blob/master/src/main/java/org/exist/xquery/modules/expath/bin/RegionFilterInputStream.java#L166

[feature] Provide an extension mechanism for extension modules to provide valid XPath/XQuery error codes

---

extensions/webdav/src/org/exist/webdav/ByteCountOutputStream.java
extensions/webdav/src/org/exist/webdav/ExistCollection.java
extensions/webdav/src/org/exist/webdav/ExistDocument.java
extensions/webdav/src/org/exist/webdav/ExistResource.java
extensions/webdav/src/org/exist/webdav/ExistResourceFactory.java
extensions/webdav/src/org/exist/webdav/MiltonCollection.java
extensions/webdav/src/org/exist/webdav/MiltonDocument.java
extensions/webdav/src/org/exist/webdav/MiltonResource.java
extensions/webdav/src/org/exist/webdav/MiltonWebDAVServlet.java
extensions/webdav/src/org/exist/webdav/exceptions/CollectionDoesNotExistException.java
extensions/webdav/src/org/exist/webdav/exceptions/CollectionExistsException.java
extensions/webdav/src/org/exist/webdav/exceptions/DocumentAlreadyLockedException.java
extensions/webdav/src/org/exist/webdav/exceptions/DocumentNotLockedException.java
extensions/webdav/src/org/exist/webdav/exceptions/EXistWebdavException.java

The webDAV code used hardcoded settings which could by (optionally) changed by using a properties files. With this change the default serialisation parameters are used as defined in config.xml
Fixes https://github.com/eXist-db/exist/issues/1437 reported by @wsalesky

WebDAV: use global serialisation parameters

---

build/scripts/jarsigner.xml

This is needed to be able to produce a release on a clean checkout.

[bugfix] Check the extensions folder exists before signing, fails on clean checkout otherwise

---

src/org/exist/xquery/functions/array/ArrayFunction.java

The function doc for `array:for-each-pair()` contained a simple typo: the 2nd parameter, "The second array to process", was called "array1" instead of "array2." This commit fixes the typo, renaming this parameter "array2."
n/a
n/a

Correct param name in array:for-each-pair

---

src/org/exist/util/io/AbstractFilterInputStreamCache.java
src/org/exist/util/io/CachingFilterInputStream.java
src/org/exist/util/io/FilterInputStreamCache.java
src/org/exist/xquery/value/BinaryValue.java
src/org/exist/xquery/value/BinaryValueFromBinaryString.java
src/org/exist/xquery/value/BinaryValueFromFile.java
src/org/exist/xquery/value/BinaryValueFromInputStream.java
test/src/org/exist/util/io/CachingFilterInputStreamTest.java
test/src/org/exist/xquery/value/BinaryValueFromInputStreamTest.java

This is an alternative fix for to https://github.com/eXist-db/exist/pull/1470.
Rather than navigating the query AST to determine when values are out of scope as in #1470, we instead reference count the number of `BinaryValueInputStreams` that are sharing the same underlying cache. The underlying cache is then only closed when the reference count finally reaches zero i.e., when the last `XQueryContext#popLocalVariable` occurs which references the shared cache.

[bugfix] Switch to reference counting for caches shared between binary values

---

log4j2.xml
src/org/exist/launcher/Launcher.java
src/org/exist/launcher/LauncherWrapper.java
src/org/exist/launcher/ServiceManager.java
src/org/exist/start/start.config
tools/yajsw/bin/installDaemon.sh
vm.properties

eXist's system tray launcher used the yajsw Java libraries to control eXist as a service. On a Mac this led to random crashes of the Java VM, likely due to library dependencies required by yajsw.  The .dmg install was thus plain unusable for most Mac users (for the last two releases of eXist).
This PR refactors the launcher to not rely on yajsw directly and thus avoid any jar dependencies on it. Instead it manages services by calling the external shell/bat scripts. Removing the yajsw dependency fixed the instability on Mac.

Fix random crashes on Mac

---

src/org/exist/xquery/AbstractInternalModule.java
src/org/exist/xquery/ExternalModuleImpl.java
src/org/exist/xquery/functions/request/RequestModule.java
src/org/exist/xquery/functions/response/ResponseModule.java
src/org/exist/xquery/functions/session/SessionModule.java
src/org/exist/xquery/functions/util/Eval.java
test/src/org/exist/xquery/CleanupTest.java

This PR fixes two regressions introduced by #1477:
1. in certain scenarios, the HTTP request, response and session variables were cleared before an XQuery was completed, thus causing errors. This mainly applies to the use of `util:eval`. This PR solves the issue and chooses a more general approach, by cleaning up *any* global variable declared in an internal module, thus making sure variables are always cleared (even if the module author did not think of it).
2. the changes to module cleanup in #1477 result in `resetState` being repeatedly called on module functions, which turned out to be very expensive (for complex queries there is now a measurable delay between finishing the query and returning the HTTP response). Further investigations showed that explicitely calling `resetState` on …

Fix two regressions introduced by memory leak PR

---

src/org/exist/xquery/ModuleContext.java
test/src/org/exist/xquery/CleanupTest.java
test/src/org/exist/xquery/TestModule.java

This is a follow up on #1512 and #1477: imported modules are now cleaned up properly, which resulted in a performance deterioration visible on some apps making heavy use of modules. The root cause of this could be tracked down to old, unnecessary code in `ModuleContext`, resulting in every module being cleaned up several times, thus slowing down queries by up to factor 2. Modules should only track the modules they actually import, not every module available to the root context.
I carefully removed the relevant code, trying to not touch unrelated sections. Test cases have been extended to cover the corresponding cases. There are also additional tests missing in #1512.

Fix module cleanup performance

---

src/org/exist/storage/NativeBroker.java

Address 2 bugs:
- storeTempResource must hold write lock on collection
- avoid NPE removeCollection (possible only when storage corrupted)
address bugfixes of #1296

Write operations without lock and possible NPE fix

---

bin/backup.bat
bin/batch.d/get_opts.bat
bin/client.bat
bin/server.bat
bin/shutdown.bat
bin/startup.bat

Previously unquoting a quoted environment variable would cause errors like: `The system cannot find the file C:\Programs`.  This now correctly unquotes the variables.
Closes: https://github.com/eXist-db/exist/issues/1504

[bugfix] Fix various Windows batch file issues

---

src/org/exist/util/PatternFactory.java

As suggested by @ben-manes. See https://github.com/eXist-db/exist/pull/1508#issuecomment-323216121

[refactor] Switched away from Weak References for values in the Regex Pattern Cache

---

src/org/exist/xquery/functions/fn/FunMatches.java
src/org/exist/xquery/functions/fn/FunReplace.java
src/org/exist/xquery/functions/fn/FunTokenize.java
test/src/xquery/regex.xml

Previouisly we did not correctly implement the `x` flag for various XQuery regular expression functions, and we did not implement `q` at all. This now implements both, hopefully correctly.
Reported by @joewiz https://github.com/eXist-db/exist/pull/1530#issuecomment-325690846

Fix for XQuery regex flags `q` and `x`

---

extensions/indexes/lucene/src/org/exist/indexing/lucene/LuceneIndexWorker.java
test/src/org/exist/xquery/update/AbstractTestUpdate.java
test/src/org/exist/xquery/update/UpdateValueTest.java

Fix NPE when updating an attribute on a namespaced element which has a lucene index defined. See test case for details.

[bugfix] Fix NPE when updating an attribute

---

.classpath
build/scripts/installer.xml
src/org/exist/launcher/ServiceManager.java
src/org/exist/util/HtmlToXmlParser.java
src/org/exist/xquery/functions/xmldb/XMLDBStore.java
src/org/exist/xquery/value/ValueSequence.java

To compile with Eclipse
1. Correct .classpath :
replace 'lib/core/cglib-nodep-**2.2.2**.jar' with "lib/core/cglib-nodep-**3.1**.jar"/>
replace 'lib/core/commons-io-**2.4**.jar' with "lib/core/commons-io-**2.5**.jar"/> ...
replace kind="**src**" path="lib/core/j8fu-**1.0**.jar" with kind="**lib**" path="lib/core/j8fu-1.4.1.jar"..
Then Eclipse complains about typos :
2. Logger cannot be resolved to a type /eXist/src/org/exist/util/HtmlToXmlParser.java
Replace `import org.apache.log4j.LogManager;` by `import org.apache.**logging**.log4j.LogManager;`
3. Logger cannot be resolved to a type /exist/launcher/ServiceManager.java
Replace `import org.apache.log4j.LogManager;` by `import org.apache.**logging**.log4j.LogManager;`
4. The type NodeTest is ambiguous …

Correct classpath an typos to compile with Eclipse.

---

build/scripts/macosx.xml

Nightly builds had stopped as there was not enough space pre-allocated in the DMG

Increases the DMG image size when building on Linux

---

src/org/exist/util/serializer/json/JSONObject.java
test/src/org/exist/util/serializer/json/JSONWriterTest.java

The tests added in `test/src/org/exist/util/serializer/json/JSONWriterTest.java` show that `JSONWriterTest#serializesMixedContent_whenAttrsPresent()` would previously correctly serialize mixed content, but if you removed the attributes from the elemnents, as in `JSONWriterTest#serializesMixedContent`, then the text nodes would be incorrectly skipped. This bugfix fixes that issue.

Previously Mixed-Content was not correctly serialized to JSON

---

extensions/modules/src/org/exist/xquery/modules/simpleql/SimpleQLLexer.java

The commit 967f48a directly modified some generated code, however you have to modify the `.g` file which generates the code and not the code itself.

[bugfix] Undo change to autogenerated code caused by 967f48a

---

build/scripts/build-impl.xml
build/scripts/jarsigner.xml

This now seems to be required by IzPack installer when installing. Unfortunately something changed in the `extensions` or signing of the extensions which broke the installer. This now fixes the installer and as such the downloads for then nightly builds.

We should also sign exist extensions!

---

tools/jetty/etc/jetty.xml
tools/jetty/etc/standalone-jetty.xml
tools/jetty/tmp/.DO_NOT_DELETE
tools/jetty/webapps/exist-webapp-context.xml

Jetty was creating the folder `$EXIST_HOME/file:/<$EXIST_HOME>/tools/jetty/etc` on some platforms. Note the recursive `$EXIST_HOME`!
I see no reason why we don't just allow Jetty to use Java's temp folder, which is the default for Jetty anyway.
As reported by @joewiz Can you test please?

Don't try and manually set a Jetty temp folder

---

src/org/exist/xquery/functions/util/Eval.java

The sample `<static-context>` element in the function documentation for `util:eval-with-context` contained a typo causing it to be malformed XML.
n/a
n/a

fix typo in util:eval-with-context fundoc

---

build/scripts/build-impl.xml

All `<delete>` tasks in clean-related targets use the `@failonerror="no"` attribute, to allow the task to proceed and complete even if any of the named directories are not present. This PR applies this attribute to the delete tasks in the `clean-default-data-dir` target. 
n/a
n/a

Allow clean-default-data-dir to complete if any dirs are not present

---

src/org/exist/xquery/functions/util/Eval.java
test/src/org/exist/xquery/functions/util/EvalTest.java

The final parameter of the 4-arity version of `util:eval-with-context()` is typed as `item()`, but in practice, errors are raised if anything but a `node()` is supplied. This PR fixes this problem and adds a test.
The motivation is to be able to run QT3 tests that require a context item to be set as part of the query environment, e.g., https://github.com/LeoWoerteler/QT3TS/blob/master/prod/ContextItemDecl.xml#L98-L108. To run this test via an XQuery test suite runner, we'd need to be able to run queries like this:
```xquery
util:eval-with-context(".", (), false(), "London")
```
Before this PR, eXist would return this error:
> org.exist.xquery.value.StringValue cannot be cast to org.exist.xquery.value.NodeValue
But, of course, a string value is a valid `item()`.
See …

[bugfix] Fix util:eval-with-context#4

---

src/org/exist/xquery/functions/fn/FunDoc.java
test/src/xquery/fn.xql

The return type of `fn:doc()` should be `document-node()?`. This PR corrects the return type in eXist, which was `node()?` - and could lead people to mistakenly believe that the function return other kinds of nodes, such as elements.
- https://www.w3.org/TR/xpath-functions/#func-doc
- https://www.w3.org/TR/xpath-functions-30/#func-doc
- https://www.w3.org/TR/xpath-functions-31/#func-doc
XQSuite

Fix fn:doc return type

---

.travis.yml

As well as building on Linux on Travis CI, we can also build on Mac OSX to ensure correct cross-platform behaviour.

Add support for building on OSX (as well as Linux) on Travis CI

---

src/org/exist/http/RESTServer.java
src/org/exist/http/SessionManager.java

Previously the Session Manager which cached query results for the REST Server was not thread-safe, yet was accessed from at least two concurrent threads, and possibly more if there was more than one concurrent user. This PR both fixed the concurrency issues, and also simplifies the implementation.

Make SessionManager thread-safe

---

src/org/exist/xmlrpc/QueryResultCache.java
src/org/exist/xmlrpc/XmldbRequestProcessorFactory.java

Previously the  cache of `XmldbRequestProcessorFactory` which cached query results for the XML RPC Server was not thread-safe.
This PR both fixed the concurrency issues, and also simplifies the implementation.
Very similar to https://github.com/eXist-db/exist/pull/1580

Make XML RPC Query Result Cache thread-safe

---

test/src/xquery/fn.xql

PR #1593 included two new XQSuite tests for the `fn:doc` function. Mistakenly, I gave these two tests the same name. This PR gives each test a unique name.
#1593.
n/a

Provide unique names for XQSuite tests

---

src/org/exist/xquery/ErrorCodes.java
src/org/exist/xquery/functions/fn/FnFormatNumbers.java
test/src/xquery/numbers/format-numbers.xql

1. Corrects the F&O XQuery error code 
2. Fixes an issue with decimal formatting reported by David Birnbaum, i.e.: `format-number(0,'#0.00')`

Fixes a couple bugs in fn:format-number

---

src/org/exist/xquery/ArrowOperator.java
test/src/xquery/xquery3/arrowop.xql

Defer function lookup until query has been parsed entirely. Fixes #1622.

Arrow operator fails to find function

---

extensions/indexes/range/src/org/exist/indexing/range/RangeIndexConfigElement.java
extensions/indexes/range/test/src/xquery/types.xql

Range index should included nested content into index key by default - unless configured otherwise. This corresponds to the documented behaviour, but current version behaved the opposite way. See included test case.

Range index: include nested content by default

---

.idea/compiler.xml

Missed from the update of AspectJ

Fix aspecttools path for IntelliJ ultimate

---

extensions/indexes/lucene/src/org/exist/indexing/lucene/analyzers/NoDiacriticsStandardAnalyzer.java
extensions/indexes/lucene/test/src/xquery/lucene/analyzers.xql

Enhancement to the noDiacriticsAnalyzer for Lucene to filter out vowels in languages such as Syriac, Hebrew, and Arabic. It also strips some additional diacritic characters not handled by the ASCIIFoldingFilter, see Pinyin test cases for examples. 
Change swaps in ICUFoldingFilter in place of the ASCIIFoldingFilter. Test cases for Syriac, Hebrew, Arabic and Pinyin added to the analyzers.xql tests. 
See discussion here: http://exist-open.markmail.org/message/recx6njwbqt6sshd?q=ICU4j+for+the+No+Diacritics+Analyzer
And related issue here: https://github.com/srophe/syriac-corpus-app/issues/36
Tests added to $EXIST_HOME/extensions/indexes/lucene/test/src/xquery/lucene/analyzers.xql
Results of junit testsuite 
Tests | Failures | Errors | Skipped | Success rate | Time
-- | -- | -- | -- | -- | -- …

Enhancement to the noDiacriticsAnalyzer for Lucene.

---

src/org/exist/xquery/value/Type.java
test/src/xquery/suite.xql
test/src/xquery/types.xql

Update `map -> map(*)` and `empty() -> empty-sequence()` according to spec.
and: `element(*)`, `function(*)` and `array(*)`
https://www.w3.org/TR/xquery-31/#doc-xquery31-SequenceType
https://www.w3.org/TR/xquery-31/#doc-xquery31-MapTest
- existing tets suite --> OK
- pending: additional test to show progression
@wolfgangmm is this a correct approach?

Update map -> map(*) and empty() -> empty-sequence() according to spec.

---

src/org/exist/xmldb/LocalCollectionManagementService.java

Relaxes the WRITE_LOCK to a READ_LOCK when copying a local collection with XML:DB API

[bugfix] When copying a Collection we only need a READ_LOCK on the source collection

---

src/org/exist/backup/SystemExport.java
src/org/exist/collections/MutableCollection.java
src/org/exist/dom/persistent/DocumentImpl.java
src/org/exist/storage/DBBroker.java
src/org/exist/storage/NativeBroker.java

Previously, `DocumentImpl#getMetadata()` would lazy-load metadata from `collections.dbx` using code like the following:
```java
public DocumentMetadata getMetadata() {
if(metadata == null) {
// require a WRITE_LOCK as we are going to modify our state
try(final ManagedDocumentLock docLock = pool.getLockManager().acquireDocumentWriteLock_BAK(getURI());
final DBBroker broker = pool.getBroker()) {
// double-check now under lock!
if(metadata == null) {
broker.getResourceMetadata(this);
}
} catch(final EXistException | LockException e) {
LOG.error("Error while loading document metadata: " + e.getMessage(), e);
}
}
return metadata;
}
```
`Broker#getResourceMetadata(Collection)` after opening `collections.dbx` would then call `DocumentImpl#readDocumentmeta(VariableByteInput)`:
```java
public void …
```

DocumentImpl metadata should not be lazy-loaded.

---

extensions/fluent/src/org/exist/fluent/QueryService.java
src/org/exist/dom/persistent/DefaultDocumentSet.java
src/org/exist/dom/persistent/DocumentSet.java
src/org/exist/dom/persistent/EmptyDocumentSet.java
src/org/exist/dom/persistent/ExtArrayNodeSet.java
src/org/exist/dom/persistent/NewArrayNodeSet.java
src/org/exist/dom/persistent/NodeProxy.java
src/org/exist/xquery/RootNode.java
src/org/exist/xquery/functions/util/LockFunction.java
src/org/exist/xquery/functions/xmldb/XMLDBDocument.java
src/org/exist/xquery/update/Modification.java
src/org/exist/xupdate/Modification.java

`DocumentSet#lock` can throw a lock exception. If that occurs, it may have only locked some of the documents within the document set, the corresponding call to `DocumentSet#unlock` would attempt to release locks on all documents; that is incorrect as it could release locks that it doesn't own!
We now record the actual locks taken, and only release those that we acquired.

Ensure that we unlock the same documents we lock

---

build/scripts/dist.xml
build/scripts/installer.xml
build/scripts/junit.xml
build/scripts/minimal.xml
tools/yajsw/build.xml

Ant seems to work a little differently on Windows. Fixes an issue introduced when we removed `-Djava.endorsed.dir`

Fix the Windows Ant build

---

test/src/org/exist/http/RESTServiceTest.java

Running the `RESTServiceTest.java` tests in parallel causes a deadlock in eXist-db to be encountered. That is quite worrying, and we need to ultimately fix the cause of the deadlock, however for now, we just need to get the test suite running again.

[bugfix] deadlock caused by RESTServiceTest

---

src/org/exist/xquery/value/Type.java

In XQuery 3.1, the previously "numeric" datatype was renamed to "xs:numeric":
> The type `xs:numeric` is defined as a union type whose member types are (in order) `xs:double`, `xs:float`, and `xs:decimal`. 
This PR adopts the new name, while preserving the old one for backward compatibility. (For example, the test at https://github.com/eXist-db/exist/blob/develop/test/src/xquery/numbers/format-numbers.xql#L11, which still references `numeric` as a datatype, still passes after this PR. Running `inspect:inspect-function` on this function, its return type is now reported as `<argument type="xs:numeric" cardinality="exactly one" var="number"/>` rather than `@type="numeric"`.)
Fixing this will help align eXist's function documentation with the XQuery F&O 3.1 spec. 
- XQuery 3.1: …

adopt XQuery 3.1 xs:numeric union datatype

---

src/org/exist/xquery/functions/math/NoParamFunctions.java
src/org/exist/xquery/functions/math/OneParamFunctions.java
src/org/exist/xquery/functions/math/TwoParamFunctions.java

This PR fixes a problem with functions in the math module: they did not identify their namespace prefix to functions like `inspect:inspect-function`. 
For example, `inspect:inspect-function(math:pi#0)` would return `@name="pi"` instead of `@name="math:pi"`. In contrast, all modules (other than the default function namespace) module would return, e.g., `@name="array:size"`, `"map:merge"`, etc.
With this PR, math module functions now correctly report their namespace prefix to `inspect:inspect-function`, returning `@name="math:pi"`.
- https://www.w3.org/TR/xpath-functions-31/#namespace-prefixes
- https://www.w3.org/TR/xpath-functions-31/#trigonometry
- Well, the math module currently has none of its own tests whatsoever besides the QT3 tests which probably wouldn't test introspectability. I …

Ensure math functions report their ns prefix

---

src/org/exist/security/PermissionFactory.java
src/org/exist/storage/NativeBroker.java
src/org/exist/storage/txn/Txn.java
src/org/exist/xmlrpc/RpcConnection.java
test/src/org/exist/storage/MoveResourceTest.java
test/src/org/exist/storage/RecoveryTest.java
test/src/org/exist/storage/RecoveryTest3.java
test/src/org/exist/storage/ReindexTest.java

This simple change greatly simplifies lock release code when locks need to be associated with the transaction lifecycle.
Previously moving lock ownership to a transaction was error prone and likely to lead to complex and possibly incorrect release semantics. This small refactoring opens the door to using ARM (Automatic Resource Management) for lock leases.

[refactor] Moving lock ownership is dangerous

---

src/org/exist/source/AbstractSource.java
src/org/exist/source/FileSource.java
src/org/exist/source/Source.java
src/org/exist/source/SourceFactory.java
src/org/exist/source/URLSource.java
src/org/exist/xquery/ErrorCodes.java
src/org/exist/xquery/functions/fn/FnModule.java
src/org/exist/xquery/functions/fn/FunUnparsedText.java
test/src/xquery/arrays/unparsed-text.xql
test/src/xquery/suite.xql
test/src/xquery/unparsed-text.xql

Implements `fn:unparsed-text`, `fn:unparsed-text-lines` and `fn:unparsed-text-available` for resources stored in the db as well as retrieved from external URIs.

Implement fn:unparsed-text and related functions

---

installer/apps.properties

Version 0.4.9 of the dashboard drops the non-functional usermanager. As discussed during last teleconf, the new working usermanager has to be added to the distribution instead.

Add new user manager to distribution

---

extensions/indexes/sort/test/src/xquery/sort/tests.xml
src/org/exist/xquery/functions/fn/FnHasChildren.java
src/org/exist/xquery/functions/inspect/ModuleFunctions.java
test/src/org/exist/test/ExistEmbeddedServer.java
test/src/xquery/xquery3/fn.xql

1. Fixed the tests for `fn:inner-most` and `fn:outer-most`. The functions only accept a sequence!
2. Fixed `fn:has-children§`:
1. `()/has-children()` now correctly returns `false`.
2. `has-children()` on a non-node item, now returns the correct error code.
3. ExistEmbeddedServer now correctly sets the journal-dir for temporary storage. Previously set the wrong property.
4. `insepect:module-functions` now correctly sets the source, which is needed for system trace functions.

Several small fixes

---

test/src/org/exist/test/ExistEmbeddedServer.java
test/src/org/exist/test/ExistXmldbEmbeddedServer.java
test/src/org/exist/test/TransactionTestDSL.java
test/src/org/exist/test/runner/XMLTestRunner.java
test/src/org/exist/test/runner/XQueryTestRunner.java

Get rid of compiler warnings:
```
compile-testkit:
[mkdir] Created dir: /....../exist/test/classes
[echo] Compiling with Java 1.8 from 1.8 source to 1.8 target, debug on, optimize on, deprecation off
[javac] Compiling 17 source files to /....../exist/test/classes
[javac] /....../exist/test/src/org/exist/test/runner/XMLTestRunner.java:124: warning: non-varargs call of varargs method with inexact argument type for last parameter;
[javac]         final Description description = Description.createSuiteDescription(getSuiteName(), null);
[javac]                                                                                            ^
[javac]   cast to Annotation for a varargs call
[javac]   cast to Annotation[] for a non-varargs call and to suppress this warning
[javac] …
```

Some minor improvements ; reducing nr of compile warnings

---

extensions/indexes/range/test/src/xquery/field-type.xql
extensions/indexes/range/test/src/xquery/index-keys.xql
src/org/exist/xquery/functions/map/AbstractMapType.java
src/org/exist/xquery/lib/xqsuite/xqsuite.xql
test/src/org/exist/test/runner/ExtTestErrorFunction.java

I saw some strange things with the Range Index tests written in XQuery and realised that XSuite (and previously TestRunner) were not reporting errors that occurred during `%test:setUp` or `%test:tearDown` to JUnit, in fact the tests appeared to pass fine.
I have now fixed that, and also that showed some problems with the cleanup of some tests written in XQuery, so I fixed that too!
Cheers.

Some further test fixes

---

src/org/exist/xquery/functions/fn/JSON.java

While investigating test suite failures on windows, I found json-doc does not properly close the input stream on the resource after reading.

[bugfix] Close input stream in fn:json-doc

---

src/org/exist/Indexer.java
src/org/exist/repo/Deployment.java

A long standing bug in `Indexer` caused 0-byte documents to appear in database collections. The bug occurs rather randomly and is hard to reproduce. As I finally figured out, the 0-byte document was created due to the element stack used by Indexer being messed up. Closer inspection revealed a weird if condition checking the element qname in endElement (and only there) in a wrong way. This (probably very old) code seems to be completely unnecessary if we assume that a document with incorrect element hierarchy should be rejected by the parser. I thus vote for removing it completely.
The PR also fixes a small issue in package deployment which unfortunately did hide the 0-byte bug during deployment. The code for handling HTML5 documents catched all exceptions.

Random 0-byte XML docs in db

---

tools/yajsw/conf/wrapper.conf.in

Explicitly set TMP directory for wrapper. Required as Windows tends to cleanup temporary files aggressively. Fixes #1702

Explicitly set TMP directory for wrapper

---

src/org/exist/Indexer.java
src/org/exist/xquery/DynamicAttributeConstructor.java
test/src/xquery/xmlid.xql

Improves #1360 and addresses #540. Testing against saxon and basex showed that both are much more permissive about xml:id in constructed documents, which makes sense because it is quite common e.g. when writing XSLT stylesheets to declare an xml:id whose value is not strictly a valid NCName. Storing documents like this in eXist resulted in an error, causing trouble for XSLT users. Also, the check in eXist (based on xerces code), did not allow some unicode characters which were added in later versions of the spec.
The XQuery spec says an implementation MAY trigger an error on an invalid xml:id when constructing a document, but does not require it. Included tests have been run against saxon and basex to make sure we see the same behaviour on all implementations.

[bugfix] Align xml:id handling with saxon and basex

---

extensions/modules/src/org/exist/xquery/modules/compression/AbstractCompressFunction.java

Fix exception in compression module: size of binary resource might be reported as -1 if unknown and should thus not be passed on the FastByteArrayOutputStream.

Fix java.lang.IllegalArgumentException thrown by FastByteArrayOutputStream

---

README

Spotted a typo.
- The URL http://exist-db.org/quickstart.html returns a 404
- The correct URL is https://exist-db.org/exist/apps/doc/quickstart.xml
n/a

Fix link to "quick start" docs

---

src/org/exist/collections/triggers/XQueryTrigger.java
src/org/exist/http/RESTServer.java
src/org/exist/storage/BackupSystemTask.java
src/org/exist/storage/BrokerPool.java
src/org/exist/storage/DataBackup.java
src/org/exist/storage/NativeBroker.java
src/org/exist/storage/NativeValueIndex.java
src/org/exist/storage/journal/FileSyncThread.java
src/org/exist/storage/journal/Journal.java
src/org/exist/storage/lock/ReentrantReadWriteLock.java
src/org/exist/storage/serializers/Serializer.java
src/org/exist/storage/txn/Checkpoint.java
src/org/exist/util/Configuration.java
src/org/exist/util/io/Resource.java

Closes https://github.com/eXist-db/exist/pull/886

Rebased small fixes.

---

src/org/exist/xquery/lib/xqsuite/xqsuite.xql

- `assertTrue` and `assertFalse` failures were reported as `assertExists` failures
- `assertError` failures did not show the actual result
n/a
Before, the following test:
```xquery
xquery version "3.1";
module namespace xqst = "xqsuite-tests";
declare namespace test = "http://exist-db.org/xquery/xqsuite";
declare 
%test:assertFalse 
function xqst:true() {
true()
};
declare 
%test:assertTrue 
function xqst:false() {
false()
};
declare 
%test:assertError("exerr:ERROR")
function xqst:valid() {
1
};
```
would return this (notice how the `failure/@message` for the first 2 tests are wrong and how the 3rd case tells us what was expected but not the actual result):
```xml
<testsuites>
<testsuite package="xqsuite-tests" timestamp="2018-05-02T00:14:33.219-04:00" failures="3" pending="0" tests="3" …
```

Fix xqsuite results

---

test/src/org/exist/test/runner/XMLTestRunner.java
test/src/org/exist/test/runner/XQueryTestRunner.java

This eases the cases where `exist-testkit.jar` is used from other eXist-db based Java projects for executing XQuery and XML tests against eXist-db used XQSuite etc.

Load XSuite resources from classpath

---

extensions/indexes/lucene/src/org/exist/indexing/lucene/AnalyzerConfig.java
extensions/indexes/lucene/src/org/exist/indexing/lucene/ClassicQueryParserWrapper.java
extensions/indexes/lucene/src/org/exist/indexing/lucene/QueryParserWrapper.java
extensions/indexes/range/src/org/exist/indexing/range/RangeIndexAnalyzer.java
src/org/exist/config/Configurator.java
src/org/exist/config/mapper/Constructor.java
src/org/exist/http/RESTServer.java
src/org/exist/plugin/PluginsManagerImpl.java
src/org/exist/repo/ExistRepository.java
src/org/exist/storage/BrokerFactory.java
src/org/exist/util/io/FilterInputStreamCacheFactory.java
src/org/exist/xquery/Function.java
src/org/exist/xquery/XQueryContext.java
src/org/exist/xquery/util/NumberFormatter.java
src/org/exist/xquery/value/BinaryValueType.java

Rather than using reflection to construct objects, since Java 8+ we have several more options available to us, which can be more performant (and possibly safer). For a basic performance comparison see: https://stackoverflow.com/questions/19557829/faster-alternatives-to-javas-reflection#19563000
I have opted to use the `LambdaMetaFactory` approach as much as possible. Apart from direct construction, it is suggested to offer the best performance.
These changes also seem to reduce the:
```
WARNING: An illegal reflective access operation has occurred
```
warnings on JDK 9+.

Replaced reflective construction with Constructor functions

---

src/org/exist/xquery/functions/util/Eval.java
test/src/xquery/util/eval-with-context.xql

Enables setting the timeout option via `util:eval-with-context` to kill a query after the timeout has been reached. 
Before this PR, the following query would not time out. 
```xquery
xquery version "3.1";
let $context :=
<static-context>
<timeout value="1"/>
</static-context>
return
util:eval-with-context("sum(1 to 10000000)", $context, false() )
```
With this PR, the query correctly times out, with the following error:
> exerr:ERROR Error while evaluating expression: sum(1 to 10000000). The query exceeded the predefined timeout and has been killed. [at line 8, column 5]
- The function documentation for util:eval-with-context http://exist-db.org/exist/apps/fundocs/view.html?uri=http://exist-db.org/xquery/util#eval-with-context.3 indicates the method for setting static context options
- …

set timeout via util:eval-with-context

---

build/scripts/build-impl.xml

Just prints out the exact JVM version during the build. Useful for reproducing issues shown on CI where we didn't before exactly which JVM versions are running.

[feature] Display the exact Java version whilst building

---

src/org/exist/xmldb/RemoteCollection.java
test/src/org/exist/xmldb/RemoteCollectionTest.java

Make a stream out of a string to avoid an NPE when uploading a file with the Java client. 
ToDo: add test
See original issue : A NPE occurs when a (large) *XML* document is uploaded into the database.
junit test (to be added)

Fix NPE when uploading (large) document from Java client

---

.github/PULL_REQUEST_TEMPLATE.md

- add AppVeyor
- running full test suite is no longer mandatory, now that the full test is run on the CI servers (assuming we merge https://github.com/eXist-db/exist/pull/1887)
- trim instructions
- https://github.com/eXist-db/exist/pull/1887
n/a

Update test suite info in PR Template

---

src/org/exist/xquery/lib/xqsuite/xqsuite.xql
test/src/org/exist/test/runner/ExtTestAssumptionFailedFunction.java
test/src/xquery/unparsed-text.xql

Some XQuery tests previously depended on various websites. Unfortunately that then causes those tests to fail when you don't have any internet access. I have now implemented an annotation `%test:assumeInternetAccess` which allows you to make sure that your test is only run when Internet Access is available.

Added %test:assumeInternetAccess to XQSuite

---

src/org/exist/xmldb/RemoteCollection.java

1. Don't allocate an entire chunk of memory if we know we won't use it all.
2. Don't compress chunks which are so small, the compression overhead would result in a larger chunk overall.

Small improvements to XML:DB Remote Collection

---

src/org/exist/util/io/TemporaryFileManager.java

Memory Mapped files cannot be reused for normal I/O of filesystem operations on Microsoft Windows.

Fix an issue with recycling of temp files.

---

extensions/modules/src/org/exist/xquery/modules/compression/AbstractExtractFunction.java
extensions/modules/src/org/exist/xquery/modules/compression/CompressionModule.java
extensions/modules/src/org/exist/xquery/modules/compression/EntryFunctions.java
extensions/modules/src/org/exist/xquery/modules/compression/UnTarFunction.java
extensions/modules/src/org/exist/xquery/modules/compression/UnZipFunction.java
extensions/modules/src/org/exist/xquery/modules/file/DirectoryCreate.java
src/org/exist/backup/ZipArchiveBackupDescriptor.java
src/org/exist/client/InteractiveClient.java
src/org/exist/repo/RepoBackup.java
src/org/exist/util/Compressor.java

Firstly I would like to thank the "**[Snyk Security Research Team](http://snyk.io)**" for reporting this issue to us. They provided both the insight to the problem and details of a suggested fix.
This PR also adds some additional functions to the Compression Module:
1. `compression:no-filter#2` and `compression:no-filter#3`. These functions can be used when the user does not want to filter anything from the archive they are uncompressing.
2. `compression:fs-store-entry3#1`, `compression:fs-store-entry4#1`, `compression:fs-store-entry3#1`, and `compression:db-store-entry4#1`. These functions can be used when the user wants to write the entries in the archive to either the filesystem or the database. Both of these functions offer in-built protection against the archive exit attack.
3. …

Security fixes to mitigate Zip/Tar file exit attacks when decompressing archives.

---

extensions/exquery/restxq/src/main/java/org/exist/extensions/exquery/restxq/impl/ResourceFunctionExecutorImpl.java
extensions/indexes/ngram/src/org/exist/xquery/modules/ngram/HighlightMatches.java
extensions/indexes/range/src/org/exist/xquery/modules/range/IndexKeys.java
extensions/modules/src/org/exist/xquery/modules/compression/AbstractExtractFunction.java
extensions/modules/src/org/exist/xquery/modules/persistentlogin/PersistentLoginFunctions.java
src/org/exist/xquery/ArrowOperator.java
src/org/exist/xquery/DynamicFunctionCall.java
src/org/exist/xquery/InlineFunction.java
src/org/exist/xquery/UserDefinedFunction.java
src/org/exist/xquery/XQueryContext.java
src/org/exist/xquery/functions/array/ArrayFunction.java
src/org/exist/xquery/functions/fn/FunHigherOrderFun.java
src/org/exist/xquery/functions/fn/FunSort.java
src/org/exist/xquery/functions/map/MapFunction.java
src/org/exist/xquery/functions/util/CallFunction.java
src/org/exist/xquery/functions/util/IndexKeys.java
src/org/exist/xquery/value/FunctionReference.java

Most functions which take a function item as argument are leaking memory. This includes nearly all functions on arrays and maps, but also `for-each` and similar. The memory leak will at least result in higher memory consumption but frequently leads to a complete system breakdown on production servers facing higher traffic.
The PR does two things to fix the issue:
1. `FunctionReference` now implements `Closable` so the caller can make sure temporary objects are cleared after the function item was used. Existing code will continue to work, but all core functions have been changed accordingly.
2. above change leads to issues with closures in inline functions. Those should not be cleared until the very end of query execution. I have thus decoupled the lifecycle of closures, which makes sure …

Memory leak in higher-order functions

---

src/org/exist/collections/MutableCollection.java
src/org/exist/dom/persistent/BinaryDocument.java
src/org/exist/dom/persistent/DocumentImpl.java
src/org/exist/security/Permission.java
src/org/exist/security/SimpleACLPermission.java
src/org/exist/security/UnixStylePermission.java
src/org/exist/security/internal/aider/UnixStylePermissionAider.java
src/org/exist/storage/NativeBroker.java
test/src/org/exist/dom/persistent/DocumentImplTest.java
test/src/org/exist/storage/AllStorageTests.java
test/src/org/exist/storage/CopyCollectionTest.java
test/src/org/exist/storage/CopyResourceTest.java

It seems we still had some issues with permissions not being set in the correct POSIX like way.
Prior to this PR:
1. Documents:
1. Documents copied by the DBA (when not overwriting an existing document), would end up with the DBA user and group as the owner.
2. Documents copied (when not overwriting an existing document), did not also copy the mode from the source document.
3. Documents copied over an existing document, would have the wrong creation time and mode.
2. Collections:
1. Collections copied by  anyone (when not overwriting an existing Collection), would have the wrong mode.
This PR includes a small API change and so requires a major release line, e.g. 5.0.0.

Fix security issues with doc/collection mode/owner during copy

---

conf.xml.tmpl
src/org/exist/collections/Collection.java
src/org/exist/collections/MutableCollection.java
src/org/exist/repo/Deployment.java
src/org/exist/security/PermissionFactory.java
src/org/exist/storage/DBBroker.java
src/org/exist/storage/NativeBroker.java
src/org/exist/util/Configuration.java
src/org/exist/xmldb/EXistCollectionManagementService.java
src/org/exist/xmldb/LocalCollectionManagementService.java
src/org/exist/xmldb/RemoteCollectionManagementService.java
src/org/exist/xmlrpc/RpcAPI.java
src/org/exist/xmlrpc/RpcConnection.java
src/org/exist/xquery/functions/securitymanager/PermissionsFunction.java
src/org/exist/xquery/functions/xmldb/XMLDBCopy.java
src/org/exist/xquery/functions/xmldb/XMLDBModule.java
test/src/org/exist/storage/CopyCollectionTest.java
test/src/org/exist/storage/CopyResourceTest.java

Requires #1888 and #1893 first.
This provided a feature for preserving attributes when copying a file. The rules of which attributes are preserved and when, is very similar to passing the `--preserve` flag to the GNU or BSD `cp` commands.
Our Collections and Documents have a "Created Time" of which there is no direct equivalent in POSIX.1-2017 (Issue 7, 2018 edition). As such I have based the behaviour on the `btime` (or "birth time") attribute which is present in MacOS X HFS+ and APFS.

Implement preserve for copy

---

src/org/exist/xmldb/LocalXMLResource.java
test/src/org/exist/xmldb/LocalXMLResourceDOMTest.java
test/src/org/exist/xmldb/XmldbLocalTests.java

Nodes returned by `LocalXMLResource#contentAsDOM()` were previously artificially restricted by wrapping them in an interface generated proxy. It seemed like a good idea at the time, but some users have reported bugs with reusing the nodes between queries. This fixes that.

Do not restrict the XML:DB API Local nodes

---

src/org/exist/xquery/functions/fn/FunIndexOf.java

According to https://www.w3.org/TR/xpath-functions-31/#func-index-of, `fn:index-of` should return `xs:integer*` (`ZERO_OR_MORE`), but eXist had return `xs:integer?` (`ZERO_OR_ONE`). 
- XQuery F&O 1.0: https://www.w3.org/TR/xquery-operators/#func-index-of
- XQuery F&O 3.1 https://www.w3.org/TR/xpath-functions-31/#func-index-of
- Function mismatches in eXist: https://github.com/eXist-db/exist/issues/1714 and https://gist.github.com/joewiz/78b1827971a3c1c5dec8fc2d13dec8b2#file-signature-mismatches_results-xml-L351-L369
- exist-open thread: https://exist-open.markmail.org/thread/6h77llsoi76hyxgy
Forthcoming. As discussed with @wolfgangmm and @adamretter, the QT3 test suite will be integrated very soon.

[bugfix] index-of should return xs:integer*

---

src/org/exist/util/serializer/HTML5Writer.java
test/src/org/exist/util/serializer/HTML5WriterTest.java

This PR fixes #777 by introducing a list of attribute names which are considered [boolean ](http://w3c.github.io/html/infrastructure.html#boolean-attribute)as per the html 5 specification and are therefore collapsed it their value is equal to their name.
This PR also fixes a case where the attribute name is not written at all in the `HTML5Writer.attribute(QName, String)` function. Please let me know if you want me to split this up into a separate PR.
Finally, this PR adds test cases to test the new behavior.

[bugfix] Only omit values for attributes which are considered boolean in HTML5Writer

---

src/org/exist/util/serializer/HTML5Writer.java
test/src/org/exist/util/serializer/HTML5WriterTest.java

Back-port of https://github.com/eXist-db/exist/pull/1933

(4.x.x) [bugfix] Only omit values for attributes which are considered boolean in HTML5Writer

---

src/org/exist/util/serializer/HTML5Writer.java
test/src/org/exist/util/serializer/HTML5WriterTest.java

Back-port of https://github.com/eXist-db/exist/pull/1933

(5.0.0) [bugfix] Only omit values for boolean attributes in HTML5Writer

---

extensions/indexes/ngram/src/org/exist/xquery/modules/ngram/NGramSearch.java
src/org/exist/xquery/FunctionCall.java
src/org/exist/xquery/VariableDeclaration.java
src/org/exist/xquery/XQueryContext.java
src/org/exist/xquery/functions/fn/FunReplace.java
src/org/exist/xquery/parser/XQuery.g
src/org/exist/xquery/parser/XQueryParser.java
src/org/exist/xquery/parser/XQueryTree.g
src/org/exist/xquery/parser/XQueryTreeParser.java
src/org/exist/xquery/value/AbstractSequence.java
src/org/exist/xquery/value/OrderedDurationValue.java

Avoids the horrible and incorrect `exerr:ERROR` in a number of situations, by using the correct error codes.

Use ErrorCodes for XQuery Errors

---

exist-versioning-release.md

* exist-db.org website package versions no longer follow eXist-db versions
* Added a step for updating the Wikipedia page
* Added a step to explicitly mention updating the Homebrew packages.

[doc] Added steps for Wikipedia and make Homebrew explicit

---

appveyor.yml

Okay this one is now fixed and ready to land.

Enabled JDK 9 on AppVeyor Ubuntu

---

build/scripts/jarsigner.xml

Fix java10 *java.lang.SecurityException: class "javax.annotation.Nullable"'s signer information does not match signer information of other classes in the same package"*
```
HTTP ERROR 500
Problem accessing /exist/apps/dashboard/index.html. Reason:
Server Error
Caused by:
javax.servlet.ServletException: org.eclipse.jetty.servlet.ServletHolder$1: java.lang.SecurityException: class "javax.annotation.Nullable"'s signer information does not match signer information of other classes in the same package
at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146)
at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:724)
at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
at …
```

(4.x.x) Fix Java10 signing problem

---

src/org/exist/xquery/XQueryContext.java
src/org/exist/xquery/util/DocUtils.java
test/src/org/exist/dom/memtree/DocumentImplTest.java
test/src/org/exist/xquery/functions/fn/DocTest.java

Implements basic support for https://www.w3.org/TR/xpath-31/#dt-available-docs
We need this to be able to execute the XQTS correctly.

Basic support for available documents of Dynamic Context

---

src/org/exist/dom/memtree/MemTreeBuilder.java
test/src/org/exist/dom/memtree/MemtreeBuilderTest.java

Previously if you used the `SAXAdapter` for the `MemtreeBuilder` with a SAX parser which is not namespace aware, then the elements in the Memtree would all have empty element names, which is obviously invalid! This fixes that.

Fixes an issue when constructing MemTrees via SAX parsers

---

src/org/exist/xquery/value/AbstractSequence.java

Backport of https://github.com/eXist-db/exist/pull/2002
Fixed the build of `develop-5.0.0`.

(5.0.0) Fix an issue where AbstractSequence#convertTo(int) was returning an empty sequence when it should not

---

src/org/exist/xquery/value/AbstractSequence.java

Backport of https://github.com/eXist-db/exist/pull/2002
Fixes the build of `develop-4.x.x`.

(4.x.x) Fix an issue where AbstractSequence#convertTo(int) was returning an empty sequence when it should not

---

src/org/exist/xmldb/LocalXMLResource.java

@dizzzz it seems like there was more than one PR merged to 4.x.x which had problems. This I hope is the last fix that we need to get 4.x.x passing the JUnit tests again.
NOTE: this issue doesn't occur in `5.0.0` or `develop`, because we dropped the `exportInternalNode(final Node node)` function from there. Although I plan to reinstate it shortly, now I have a better approach.

(4.x.x) Fix a problem with node equality when using the DOM from the XML:DB Local API

---

.travis.yml

Caches Ivy and Maven dependencies between builds in Travis CI
**NOTE:** Assuming the CI passes, let's backport this before merging!

Cache dependencies between builds

---

build/scripts/setup.xml

When building eXist via `./build.sh`, packages listed in `$EXIST_HOME/build.properties` (or `local.build.properties`) are downloaded and placed into the `autodeploy` directory. The download is skipped if a xar file matching the package abbreviation is found. 
Until this PR, the information reported from this step in the build process (which can be seen with `ant -f build/scripts/setup.xml`) was quite limited, particularly in the case that a download was skipped because a file matching the package name was found:
```text
download:
download-xar:
```
This lack of information makes it difficult to troubleshoot problems in the process. This PR adds the following information about xars:
1. A message indicating what packages are going to be downloaded
2. A message indicating whether the download …

Improve reporting of xar downloads from package repo during build process

---

extensions/modules/src/org/exist/xquery/modules/scheduler/ScheduleFunctions.java

I've updated the function definitions to indicate that submitting a scheduled job via XQuery isn't persistent.
https://sourceforge.net/p/exist/mailman/message/36375333/
None. Should existing tests suffice?

Updated the function defintions for scheduling jobs via XQuery

---

build.properties
extensions/modules/src/org/exist/xquery/modules/compression/CompressionModule.java
extensions/modules/src/org/exist/xquery/modules/compression/DeflateFunction.java
extensions/modules/src/org/exist/xquery/modules/compression/InflateFunction.java
extensions/modules/src/org/exist/xquery/modules/compression/example-deflate.xql

------
This adds DEFLATE compression (RFC 1950 / 1951) to the existdb compression module.
RFC 1951 DEFLATE is required for the existdb SAMLv2 implementation in XQuery.
Ref: Section 3.4.4.1 "DEFLATE Encoding" in SAMLv2 standard documentation https://docs.oasis-open.org/security/saml/v2.0/saml-bindings-2.0-os.pdf
While there, implement RFC 1950 as well.
I'm not familiar with the testing framework. This PR includes an example XQuery "example-deflate.xql" that demonstrates usage and tests compression/uncompression against its own behavior. I can add interoperability tests against Perl's DEFLATE implementation, not sure how.
License follows the existing existdb license.

(4.x.x) Add DEFLATE compression (RFC 1950 / 1951) to compression module

---

src/org/exist/backup/ConsistencyCheck.java

A very simple two line fix, that ensures the consistency check considers all nodes in the document and not just the document element.

(4.x.x) Consistency check should check the entire document

---

bin/functions.d/getopt-settings.sh

This patch normalizes indentation of getopt-settings.sh, i.e. all tabs.
Rationale: make it easier to correct a bug in options processing…

indent getopt-settings.sh

---

bin/functions.d/getopt-settings.sh

Enable jmx and try to parse port ONLY when option matches at beginning of argument.

Correct jmx option parsing

---

extensions/modules/src/org/exist/xquery/modules/image/CropFunction.java

CropFunction.java has two errors:
1. It is presented as a x1,y1,x2,y2 set of bounding boxes, but java.awt.image.CropImageFilter has this signature:
public CropImageFilter(int x,
int y,
int w,
int h)
Constructs a CropImageFilter that extracts the absolute rectangular region of pixels from its source Image as specified by the x, y, w, and h parameters.
Parameters:
x - the x location of the top of the rectangle to be extracted
y - the y location of the top of the rectangle to be extracted
w - the width of the rectangle to be extracted
h - the height of the rectangle to be extracted
https://docs.oracle.com/javase/7/docs/api/java/awt/image/CropImageFilter.html
Thus, the last two parameters were misaligned. This commit converts the x2,y2 given through the xquery function into height and width …

Fix bugs in CropFunction

---

extensions/modules/src/org/exist/xquery/modules/sql/ExecuteFunction.java
test/src/org/exist/xquery/modules/sql/ExecuteFunctionTest.java

Fixes the following NPEs in sql:execute:
* missing sql:type attribute in sql:param element
* empty sql:param element (both in setParameters and error handling)
#2139 - NPEs in SQL module
JUnit tests for fixed behavior

Bugfix: Fixes in SQL module (#2139)

---

build/scripts/dist.xml

The `.tar.gz` and `.tar.bz` distributions were missing some source code files which are needed for rebuilding from source.

Add some missing files to the dist

---

conf.xml.tmpl
src/org/exist/util/Configuration.java
src/org/exist/util/XMLReaderPool.java
test/src/org/exist/util/XMLReaderSecurityTest.java

Adds the facility for configuring the XML parser from `conf.xml`. This allows the user to specify various options. It is suggested to use the commented options in `conf.xml` to secure the parser.

Add options for securing the XML Parser

---

conf.xml.tmpl
src/org/exist/util/Configuration.java
src/org/exist/util/XMLReaderPool.java
test/src/org/exist/util/XMLReaderSecurityTest.java

Backport of https://github.com/eXist-db/exist/pull/2145

(4.x.x) Add options for securing the XML Parser

---

.travis.yml

oracle java11 not yet supported by travis it seems 
close #2227

remove non lts oracle java versions

---

src/org/exist/xquery/OrderByClause.java
test/src/xquery/xquery3/flwor.xql

properly initialized due to lack of call to resetState after analyzing OrderByClause
Description
This issue manifested itself in my project, suddenly throwing NPE when using rather innocent filter expression. Lengthy investigation pointed to a problem in OrderByClause resetState cleanup which was not in line with other classes extending AbstractFLWORClause. This fix does bring it in line with the rest and fixes my problem.
Reference:
No issue has been filed afaik
Type of tests:
Test has been attached in this PR.

fixes an NPE resulting from expression using range index not being (4.x.x)

---

src/org/exist/xquery/OrderByClause.java
test/src/xquery/xquery3/flwor.xql

properly initialized due to lack of call to resetState after analyzing OrderByClause
Description
This issue manifested itself in my project, suddenly throwing NPE when using rather innocent filter expression. Lengthy investigation pointed to a problem in OrderByClause resetState cleanup which was not in line with other classes extending AbstractFLWORClause. This fix does bring it in line with the rest and fixes my problem.
Reference:
No issue has been filed afaik
Type of tests:
Test has been attached in this PR.

fixes an NPE resulting from expression using range index not being (5.0.0)

---

src/org/exist/management/impl/LockTable.java
src/org/exist/management/impl/LockTableMXBean.java
src/org/exist/security/PermissionFactory.java
src/org/exist/storage/lock/LockTable.java
src/org/exist/storage/lock/LockTableUtils.java
src/org/exist/storage/txn/Txn.java

1. We previously kept the lock for longer than necessary when changing permissions.
2. The JMX output for lock table dump can now also include stack trace info and provide an XML formatted response.

Fix an issue with lock lifetime when changing permissions

---

src/org/exist/security/PermissionFactory.java

Backport of https://github.com/eXist-db/exist/pull/2244

(4.x.x) Fix an issue with lock lifetime when changing permissions

---

.travis.yml

11 is LTS we can now enable it on Travis, where we had to remove oracle 9 and 10.

enable oracleJDK11 on travis

---

src/org/exist/start/LatestFileResolver.java

Needed to make a small change to the classloaded to recognize jars with `-patched` after their version number.

(4.x.x.) Fix a regression with loading the XML:DB API Jar via bin/startup

---

extensions/indexes/ngram/src/org/exist/indexing/ngram/NGramIndex.java
extensions/indexes/sort/src/org/exist/indexing/sort/SortIndex.java
src/org/exist/storage/NativeValueIndex.java
src/org/exist/storage/btree/BTree.java
src/org/exist/storage/btree/Paged.java
src/org/exist/storage/dom/DOMFile.java
src/org/exist/storage/index/BFile.java
src/org/exist/storage/index/CollectionStore.java
src/org/exist/storage/journal/AbstractLoggable.java
src/org/exist/storage/journal/Journal.java
src/org/exist/storage/journal/JournalManager.java
src/org/exist/storage/journal/JournalReader.java
src/org/exist/storage/journal/Loggable.java
src/org/exist/storage/journal/Lsn.java
src/org/exist/storage/recovery/RecoveryManager.java
src/org/exist/storage/structural/NativeStructuralIndex.java
src/org/exist/storage/txn/Checkpoint.java
test/src/org/exist/storage/RemoveCollectionTest.java
test/src/org/exist/storage/journal/LsnTest.java

Previously eXist-db would silently write bad entries to the Journal if the Journal file exceeded 2 GB. I recently added a check which would detect the situation and raise an error to avoid silent corruption.
I had two reports from different individuals, both saying they had encountered the error! It seems that it is relatively easy to store enough data into eXist-db in a single transaction to exceed the 2 GB limit. 
Previously the limit was caused by the use of 4 bytes for storing the file position of the Journal entry within the LSN (Log Sequence Number). I have now increased that to 8 bytes, which allows for Journal files as large as the JVM can support, i.e. 8,191 PB. It is unlikely that will ever be exceeded! ;-)
Unfortunately fixing this was not straightforward due to a number of …

(4.x.x) Remove the 2GB log file limit for the Journal

---

build/scripts/jarsigner.xml

Fixes an issue with signing/unsigning a build of eXist-db.
The BouncyCastle Jar contains additional signatures from the Legion of Bouncy Castle which should not be removed.

(4.x.x) Don't unsign the Bouncy Castle jar file

---

.travis.yml
README.md

remove `sudo` statement from travis to switch to VM builds following their recommendations
saucelab link and img are part of their open sauce deal *yay*

chore: add link to readme cleanup travis

---

.travis.yml

I am not certain why, but after Travis-CI's move from Ubuntu Trusty on their container architecture to Ubuntu Trusty on their GCE architecture, the build fails. Using Travis-CI's Ubuntu Xenial on GCE seems to work fine.

Move from Ubuntu Trusty to Xenial on Travis-CI

---

src/org/exist/source/SourceFactory.java
test/src/org/exist/source/SourceFactoryTest.java

Related to https://github.com/eXist-db/documentation/pull/291
Fixes a bug whereby XQuery Modules executed from the classpath cannot import modules from the same relative classpath location.

Improve classpath modules resolution

---

src/org/exist/source/SourceFactory.java
test/src/org/exist/source/SourceFactoryTest.java

Backport of https://github.com/eXist-db/exist/pull/2360

(4.x.x) Improve classpath modules resolution

---

src/org/exist/storage/BrokerPool.java
src/org/exist/storage/SystemTaskManager.java
src/org/exist/storage/journal/Journal.java
src/org/exist/storage/txn/TransactionManager.java
src/org/exist/storage/txn/Txn.java
test/src/org/exist/storage/txn/TxnTest.java

Closes https://github.com/eXist-db/exist/issues/2304
1. Fixes the potential concurrency safety issues in the current transaction manager.
2. New design is non-blocking lock-free.
3. New design does not need to acquire a broker from the Broker Pool for every transaction operation which improves throughput and reduces contention on the Broker Pool.
4. New design allows concurrent  begin, commit, abort operations reducing contention on the Transaction Manager and improving concurrency.
I believe that the design is correct and I have tried to explain it in the Javadoc and with liberal commenting of the code. I recommend that the core developers carefully review my use of Atomics in `TransactionManager` to make sure I have not accidentally introduced new race conditions.
Some testing in a …

(4.x.x) New implementation of the Transaction Manager

---

README
extensions/indexes/lucene/src/org/exist/indexing/lucene/LuceneConfig.java
extensions/indexes/lucene/src/org/exist/indexing/lucene/LuceneIndexConfig.java
extensions/indexes/lucene/src/org/exist/indexing/lucene/LuceneIndexWorker.java
extensions/indexes/lucene/src/org/exist/indexing/lucene/LuceneMatchListener.java
extensions/indexes/lucene/src/org/exist/indexing/lucene/NodePathPattern.java
extensions/indexes/lucene/test/src/org/exist/indexing/lucene/LuceneIndexTest.java
extensions/indexes/range/src/org/exist/indexing/range/RangeIndexWorker.java
src/org/exist/Indexer.java
src/org/exist/dom/persistent/StoredNode.java
src/org/exist/storage/NativeBroker.java
src/org/exist/storage/NodePath.java
src/org/exist/storage/NodePath2.java

Allow more elaborate XPath expressions in the Lucene index spec in collection.xconf (original PR #2169)
For more information, see the discussion in the original PR: https://github.com/eXist-db/exist/pull/2169

Allow more elaborate XPath expressions in the Lucene index spec (original PR #2169)

---

schema/collection.xconf.xsd

The collection xconf schema file lacked coverage for:
- the new conditional combined index feature’s `<condition>` element, which may contain `@attribute`, `@operator`, `@value`, `@case`, and `@numeric`
- `@type` and `@case` attributes for the new range index's `<create> element
This PR adds those and includes some cleanup of the xsd file to conform to the documentation.
- https://exist-db.org/exist/apps/doc/newrangeindex
- https://stackoverflow.com/questions/54105990/failure-of-conditional-combination-index-in-exist-db-range-index
- No automated tests included, but I manually tested against the xconf file contained in `extensions/indexes/range/test/src/xquery/conditions.xql` and my most complex xconf files.

Add coverage for new range index features to collection.xconf.xsd

---

src/org/exist/Indexer.java
src/org/exist/dom/QName.java
src/org/exist/dom/memtree/MemTreeBuilder.java
src/org/exist/util/XMLNames.java
src/org/exist/xquery/DynamicAttributeConstructor.java
src/org/exist/xquery/DynamicPIConstructor.java
src/org/exist/xquery/ElementConstructor.java
src/org/exist/xquery/NamespaceConstructor.java
src/org/exist/xquery/functions/fn/FunId.java
src/org/exist/xquery/functions/fn/FunIdRef.java
src/org/exist/xquery/functions/fn/FunQName.java
src/org/exist/xquery/value/StringValue.java
test/src/xquery/xmlid.xql

Fixes the failing tests on xml:id related functions demonstrated by #2142.
* `fn:id` lookups on in-memory documents basically never worked
* tests for NCName were wrong and are replaced by an implementation more closely following the character ranges defined in the specs (https://www.w3.org/TR/REC-xml/#NT-Name)
*Do **not** merge before all issues in #2142 have been addressed!*

(4.x.x) Fix failing xml:id tests by using proper checks for xs:NCName

---

extensions/indexes/lucene/src/org/exist/indexing/lucene/LuceneUtil.java
extensions/indexes/lucene/test/src/xquery/lucene/plain-ft-functions.xml
extensions/indexes/lucene/test/src/xquery/lucene/queries.xml

A lucene query like `ft:search("/db/binary/", "para:[even TO foobaar]")` would result in an `UnsupportedOperationException`. Fixed both: queries on standard and constructed indexes, added tests.

(4.x.x) Fix lucene term range queries

---

extensions/indexes/lucene/src/org/exist/indexing/lucene/LuceneUtil.java
extensions/indexes/lucene/test/src/xquery/lucene/plain-ft-functions.xml
extensions/indexes/lucene/test/src/xquery/lucene/queries.xml

Forward port of #2386
A lucene query like ft:search("/db/binary/", "para:[even TO foobaar]") would result in an UnsupportedOperationException. Fixed both: queries on standard and constructed indexes, added tests.

Fix lucene term range queries

---

extensions/indexes/lucene/src/org/exist/indexing/lucene/LuceneUtil.java
extensions/indexes/lucene/test/src/xquery/lucene/plain-ft-functions.xml
extensions/indexes/lucene/test/src/xquery/lucene/queries.xml

Forward port of #2386
A lucene query like ft:search("/db/binary/", "para:[even TO foobaar]") would result in an UnsupportedOperationException. Fixed both: queries on standard and constructed indexes, added tests.

(5.0.0) Fix lucene term range queries

---

.travis.yml

HipChat is dead. Long live Slack.
This switches our notifications from HipChat to Slack.

Send Travis notifications to Slack

---

src/test/xquery/unparsed-text.xql

(develop) Change github path to reflect new situation

---

src/test/xquery/unparsed-text.xql

(5xx) Change github path to reflect new situation

---

src/main/java/org/exist/xquery/functions/fn/FunUnparsedText.java
src/test/xquery/unparsed-text.xql

Prevent unhandled NPE in unparsed-text-available() for GitHub URL
```xquery
unparsed-text-available("https://raw.githubusercontent.com/eXist-db/exist/develop/src/test/xquery/READMEaaaa")
```

(develop) Prevent NPE in unparsed-text-available for GitHub URL

---

tools/yajsw/conf/wrapper.conf.in

requires #2500 
```
INFO|94578/5|Service eXist-db|19-02-19 20:55:20|error finding main method in class: org.exist.yajsw.Main : org.exist.yajsw.Main
INFO|wrapper|Service eXist-db|19-02-19 20:55:20|too many restarts 
INFO|94578/5|Service eXist-db|19-02-19 20:55:20|java.lang.ClassNotFoundException: org.exist.yajsw.Main
INFO|wrapper|Service eXist-db|19-02-19 20:55:20|too many restarts 
INFO|94578/5|Service eXist-db|19-02-19 20:55:20|no java main method found -> aborting
INFO|94578/5|Service eXist-db|19-02-19 20:55:20|        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
INFO|94578/5|Service eXist-db|19-02-19 20:55:20|        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
INFO|94578/5|Service eXist-db|19-02-19 20:55:20|        at …
```

(4xx) Update path to new location of yajsw classes

---

exist-core/src/main/java/org/exist/util/serializer/XMLWriter.java

Fix a memory leak introduced with 6e8d781fa3574896c51409cfbacbb9263a36b2a7. The leak becomes visible when serializing a larger amount of XML.

(4.x.x) XMLWriter is leaking instances of QName

---

exist-core/src/main/java/org/exist/util/serializer/XMLWriter.java

Fix a memory leak introduced with 6e8d781. The leak becomes visible when serializing a larger amount of XML. Port of  #2531

XMLWriter is leaking instances of QName

---

exist-core/src/main/java/org/exist/util/serializer/XMLWriter.java

Fix a memory leak introduced with 6e8d781. The leak becomes visible when serializing a larger amount of XML. Port of #2531

(develop-5.0.0) XMLWriter is leaking instances of QName

---

tools/yajsw/bin/installDaemon.sh

Fixes a regression introduced by https://github.com/eXist-db/exist/pull/2240

Fix the YAJSW installation

---

extensions/contentextraction/ivy.xml
extensions/modules/xslfo/ivy.xml

Backport of https://github.com/eXist-db/exist/pull/2558
**NOTE** if we plan to do a 4.6.2 release, we should wait until after that release, before merging this PR!

(4.x.x) Update to Tika version 1.20

---

.idea/libraries/jmh.xml
build.properties
build/scripts/build-impl.xml
build/scripts/jmh.xml
eXist-db.iml
exist-core-jmh/ivy.xml
exist-core-jmh/src/main/java/org/exist/storage/lock/LockTableBenchmark.java

This PR adds the ability to run JMH Benchmarks against eXist-db.
It also adds one JMH Benchmark for the `LockTable`.
I was previously using JMeter, which allowed me in combination with a profiler to identify where the bottleneck in eXist-db 5.0.0 is when compared to eXist-db 4.x.x. This revealed the fact that the `LockTable` was being overwhelmed, as it had 20 producers (20 brokers) and only one consumer to process the lock events... which could not keep up!
However, whilst JMeter is interesting, it shows far too much variance in results for it to be of use tuning small parts of the code base. JMH is a Microbenchmark which is designed for tightly measuring small functions, it also takes care of variation through *warmup* and allows one to run concurrent benchmarks with *N* threads.
To run …

JMH Benchmark

---

exist-core-jmh/src/main/java/org/exist/storage/lock/LockTableBenchmark.java

Benchmark previously had a small issue whereby the BTREE locks were only acquired and never released.

[bugfix] Make sure to release BTREE locks in Benchmark

---

exist-core-jmh/src/main/java/org/exist/storage/lock/LockTableBenchmark.java
exist-core/src/main/java/org/exist/collections/MutableCollection.java
exist-core/src/main/java/org/exist/storage/BrokerPool.java
exist-core/src/main/java/org/exist/storage/lock/Lock.java
exist-core/src/main/java/org/exist/storage/lock/LockEventJsonListener.java
exist-core/src/main/java/org/exist/storage/lock/LockEventLogListener.java
exist-core/src/main/java/org/exist/storage/lock/LockEventXmlListener.java
exist-core/src/main/java/org/exist/storage/lock/LockManager.java
exist-core/src/main/java/org/exist/storage/lock/LockTable.java
exist-core/src/main/java/org/exist/util/RingBuffer.java
exist-core/src/test/java/org/exist/storage/NativeBrokerLockingTest.java
exist-core/src/test/java/org/exist/storage/StartupLockingTest.java
exist-core/src/test/java/org/exist/storage/lock/CollectionLocksTest.java
exist-core/src/test/java/org/exist/storage/lock/DocumentLocksTest.java
exist-core/src/test/java/org/exist/storage/lock/LockManagerTest.java

Hopefully this resolves the performance issue of eXist-db 5.0.0 compared to 4.x.x.
For production, users also have the option of disabling the lock table by using the system property `-Dexist.locktable.disable=true`.

Improve the performance of the LockTable

---

exist-core/src/main/java/org/exist/collections/MutableCollection.java
exist-core/src/main/java/org/exist/dom/persistent/DocumentImpl.java
exist-core/src/test/java/org/exist/storage/AllStorageTests.java
exist-core/src/test/java/org/exist/storage/CopyResourceTest.java
exist-core/src/test/java/org/exist/storage/StoreBinaryTest.java
exist-core/src/test/java/org/exist/storage/StoreResourceTest.java

Previously a user who was not the owner of a binary, could not replace it even if they had permissions to do so, due to a bug in the code ordering of updating permissions.

Fix a permissions issue with replacing binary resources

---

build.properties
installer/apps.properties

- This PR replaces the [old dashboard](https://github.com/eXist-db/dashboard) with the [new dashboard](https://github.com/eXist-db/existdb-dashboard) for the purpose of populating the autodeploy directory during a normal and installer builds.
- This PR assumes the URL for accessing the dashboard app has not changed, as required by https://github.com/eXist-db/existdb-dashboard/issues/13 and fixed by https://github.com/eXist-db/existdb-dashboard/pull/14 (still awaiting merge at the moment).
Many developers have been using and testing the new dashboard and, as discussed in the January 7, 2018 community call, recommend that the new dashboard be included in the next 5.0.0-RC. (There are no current plans to backport this to the 4.x.x series.)
- [January 7, 2018 community …

[feature] Switch to the new dashboard

---

.classpath
extensions/xqdoc/src/test/java/xqdoc/XQDocTests.java

Fixes the Eclipse workspace compilation by adding missing source folders and correcting referred libraries within the `.classpath` file.

(4.x.x) Update Eclipse classpath to fix compilation

---

exist-core/src/main/java/org/exist/xquery/ExternalModule.java
exist-core/src/main/java/org/exist/xquery/ExternalModuleImpl.java
exist-core/src/main/java/org/exist/xquery/VariableDeclaration.java
exist-core/src/main/java/org/exist/xquery/functions/fn/LoadXQueryModule.java
exist-core/src/main/java/org/exist/xquery/functions/inspect/ModuleFunctions.java
exist-core/src/main/java/org/exist/xquery/functions/util/PrologFunctions.java
exist-core/src/test/xquery/xquery3/closure-in-maps.xql
exist-core/src/test/xquery/xquery3/dynamically-declared-vars.xql
exist-core/src/test/xquery/xquery3/load-xquery-module.xql

Trying to reproduce #1550 it turned out that globally declared variables are not properly analyzed when a module is loaded dynamically, e.g. via `load-xquery-module`. A statically loaded module would be analyzed during compilation. For dynamically loaded modules we thus need to call analyze one time on all declared variables. Not doing so causes a NPE on expressions used within the variable declaration, which depend on the analysis context. #2437 demonstrates the XQuery issue itself, while #1550 reports a wrong failure in XQSuite due to the same bug.
Closes #1550, #2437

Dynamically loaded module vars not analyzed

---

exist-core/src/test/java/org/exist/storage/RecoveryTest.java

Previously the `RecoveryTest` depended on the order of files listed from the filesystem, but did not sort them. This meant that the order of the files could vary across platforms and/or filesystems.
This caused the test to start failing for AppVeyor CI Ubuntu. This PR causes the test to always sort the list of files correctly.

Fix RecoveryTest determinism

---

test/src/xquery/literals-in-curlies.xql

back port of https://github.com/eXist-db/exist/pull/2375

(4.x.x) add testsuite for literals in curly braces

---

exist-core/src/main/java/org/exist/storage/BackupSystemTask.java
exist-core/src/main/java/org/exist/util/FileUtils.java

Closes #2387
A backup job as below is not limiting the number of backups in case when suffix is not equal with ".zip
```xml
<job type="system" class="org.exist.storage.BackupSystemTask" cron-trigger="0 0 3 ? * * *">
<parameter name="dir" value="/home/claudius/exist-db/backup" />
<parameter name="prefix" value="full-backup-" />
<parameter name="collection" value="/db" />
<parameter name="user" value="admin" />
<parameter name="password" value="password" />
<parameter name="zip-files-max" value="2" />
</job>
```
I would expect only two backups to be maintained.
Anyone can reproduce this issue, by using the above backup job in conf.xml.
- eXist-db 4.4.0 / ab5716180
- java version "1.8.0_191"
- ubuntu 18
- 64 bit
- How is eXist-db installed? - JAR installer

Fix purging of old zip backups

---

extensions/indexes/lucene/src/main/java/org/exist/indexing/lucene/LuceneIndexWorker.java
extensions/indexes/lucene/src/main/java/org/exist/xquery/modules/lucene/Query.java
extensions/indexes/lucene/src/main/java/org/exist/xquery/modules/lucene/QueryField.java
extensions/indexes/lucene/src/main/java/org/exist/xquery/modules/lucene/Search.java
extensions/indexes/lucene/src/test/xquery/lucene/binary.xql

4.x.x backport for https://github.com/eXist-db/exist/pull/2279
ft:search currently doesn't allow specifying options, which in particular makes leading-wildcard queries impossible on computed index fields
no issue has been registered so far afaik
Relevant test has been attached with this PR

(4.x.x) Feature/lucene search leading wildcard

---

extensions/indexes/lucene/src/main/java/org/exist/indexing/lucene/LuceneIndexWorker.java
extensions/indexes/lucene/src/main/java/org/exist/xquery/modules/lucene/Query.java
extensions/indexes/lucene/src/main/java/org/exist/xquery/modules/lucene/QueryField.java
extensions/indexes/lucene/src/main/java/org/exist/xquery/modules/lucene/Search.java
extensions/indexes/lucene/src/test/xquery/lucene/binary.xql

5.0.0 backport for #2279
ft:search currently doesn't allow specifying options, which in particular makes leading-wildcard queries impossible on computed index fields
no issue has been registered so far afaik
Relevant test has been attached with this PR

(5.0.0) Feature/lucene search leading wildcard

---

exist-core/src/main/resources/org/exist/xquery/lib/test.xq
exist-core/src/test/xquery/json.xml

Fixes an bug with serialization of `expected` values in XQSuite when CData sections are present in the `<expected>` element of tests expressed in XML.
This was backported from https://github.com/eXist-db/exist/pull/2603

(4.x.x) Fix an issue with XQSuite serialization of expected CData

---

exist-core/src/main/java/org/exist/util/io/MemoryContentsInputStream.java
exist-core/src/test/java/org/exist/util/io/MemoryContentsInputStreamTest.java

Remove a non visible illegal character from the `transferTo` method signature

(4.x.x) Remove illegal unicode character

---

exist-core/src/main/java/org/exist/util/io/MemoryContentsInputStream.java
exist-core/src/test/java/org/exist/util/io/MemoryContentsInputStreamTest.java

Remove a non visible illegal character from the `transferTo` method signature

Remove illegal unicode character

---

exist-core/src/main/java/org/exist/util/io/MemoryContentsInputStream.java
exist-core/src/test/java/org/exist/util/io/MemoryContentsInputStreamTest.java

Remove a non visible illegal character from the `transferTo` method signature

(5.0.0) Remove illegal unicode character

---

exist-core/src/main/java/org/exist/xquery/functions/xmldb/XMLDBCopy.java
exist-core/src/test/xquery/xmldb/copy-tests.xql
exist-core/src/test/xquery/xmldb/permission-tests.xql

Broken after removing deprecated functions. Add tests.

Fix xmldb:copy-resource/xmldb:copy-collection

---

exist-core/src/main/java/org/exist/dom/memtree/DocumentImpl.java
exist-core/src/test/xquery/xmlid.xql

Exception thrown when querying doc containing xml:id attribute in enclosed expression. Closes #2636

(4.x.x) Fix ArrayOutOfBoundsException with fn:id

---

exist-core/src/main/java/org/exist/dom/memtree/DocumentImpl.java
exist-core/src/test/xquery/xmlid.xql

Exception thrown when querying doc containing xml:id attribute in enclosed expression. Closes #2636

(5.0.0) Fix ArrayOutOfBoundsException with fn:id

---

exist-core/src/main/java/org/exist/dom/memtree/DocumentImpl.java
exist-core/src/test/xquery/xmlid.xql

Exception thrown when querying doc containing xml:id attribute in enclosed expression. Closes #2636

Fix ArrayOutOfBoundsException with fn:id

---

exist-core/src/main/java/org/exist/storage/NativeBroker.java
exist-core/src/main/java/org/exist/storage/NodePath.java
exist-core/src/test/java/org/exist/storage/ShutdownTest.java
extensions/indexes/lucene/src/main/java/org/exist/indexing/lucene/NodePathPattern.java
extensions/indexes/lucene/src/test/java/org/exist/indexing/lucene/LuceneIndexTest.java

Fixes an issue introduced by PR #2367: a lucene index configured with a match attribute should only be created for nodes matching the path, not all its descendant nodes.

Descendant nodes wrongly indexed, fix PR #2367

---

exist-core/src/main/java/org/exist/storage/NativeBroker.java
exist-core/src/test/java/org/exist/collections/AllCollectionTests.java
exist-core/src/test/java/org/exist/collections/OpenCollectionTest.java

Loading an existing collection fails on develop/5.0 when calling `DBBroker.openCollection` with a full XmldbURI (i.e. with scheme part). This manifests itself in issue #2691, where accessing the root of an app shows just a collection listing. The cause for this is that the collection is not found when searching for the controller. It is found later by the REST servlet though, because this uses an XmldbURI without scheme part.
The issue does not apply to 4.x.x. The uri is correctly processed there.
Closes #2691

Opening a collection using full XmldbURI (with scheme) fails.

---

appveyor.yml

Our #integrations channel does a nice job with notifications from GitHub and Travis CI, but it doesn’t show Appveyor CI. Appveyor CI isn’t available as an “app” in Slack, but they do offer directions for manually configuring notifications: https://www.appveyor.com/docs/notifications/#slack - which involves adding some entries here.

Add AppVeyor CI notification to Slack #integrations

---

exist-core/src/main/java/org/exist/collections/Collection.java
exist-core/src/main/java/org/exist/collections/CollectionCache.java
exist-core/src/main/java/org/exist/collections/MutableCollection.java

Manual port of 3da94f80ce2cb33684d354a98b6f16fa07bd59ae, which should address a deadlock recently reported on the list for 4.6.0: http://exist-open.markmail.org/thread/37alxcifbxknig6q. The issue seems blocking enough that it deserves a backport.

(4.x.x) Fix deadlock

---

exist-distribution/pom.xml

The plugin now correctly handles versions like `5.0.0-RC1`

Update the public-xar-repo-plugin

---

extensions/indexes/lucene/src/main/java/org/exist/indexing/lucene/LuceneIndexWorker.java
extensions/indexes/lucene/src/main/java/org/exist/indexing/lucene/LuceneMatch.java
extensions/indexes/lucene/src/main/java/org/exist/xquery/modules/lucene/Facets.java

Fix AlreadyClosedException when retrieving facets during a reindex. Previously we were postponing the actual facet computation until the user requested it via `ft:facets`. Internally lucene would potentially use an outdated reader for the computation though, which led to the exception.
Instead of postponing, compute facets immediately within the same lucene search context and thus using the same reader. Memory and performance-wise, the overhead is minimal.
Closes #2700

Lucene: fix AlreadyClosedException

---

exist-core/src/main/java/org/exist/launcher/ConfigurationDialog.java
exist-core/src/main/java/org/exist/launcher/LauncherWrapper.java

Fixes issue #1248. During first start, the launcher shows a configuration dialog and restarts after it is closed. The wrapper process kept running though.
Checked on OSX and Windows 10.

LauncherWrapper not exiting after first start

---

exist-core/src/main/java/org/exist/dom/persistent/CommentImpl.java
exist-core/src/test/java/org/exist/dom/persistent/CommentTest.java

Closes https://github.com/eXist-db/exist/issues/2728

The content of comments should not be escaped

---

exist-core/src/main/java/org/exist/dom/persistent/CommentImpl.java
exist-core/src/test/java/org/exist/dom/persistent/CommentTest.java

Backport of https://github.com/eXist-db/exist/pull/2739

(5.0.0) The content of comments should not be escaped

---

exist-core/src/main/java/org/exist/launcher/WindowsServiceManager.java

Auto-detection of `jvm.dll` needed by procrun does not work reliably across different JDK distributions (ok with Oracle, fails with Zulu and Amazon Corretto). We can easily determine the correct location from `JAVA_HOME` though.
Closes #2731
Tested on Windows 10 with Zulu 8 and 11, Amazon Corretto 11 and Oracle JDK 11.

Installing service fails with OpenJDK

---

exist-core/src/main/java/org/exist/util/io/VirtualTempPath.java
exist-core/src/test/java/org/exist/util/io/VirtualTempPathTest.java

Fixes the bug that `getBytes()` return a empty array if the `VirtualTempPath` has switched to a real file instead of using the in-memory model
Extended the `VirtualTempPathTest` to also check the correct behaviour of the `getBytes()` method for in-memory and real file case.

Fixes getBytes() method returning wrong data if switched to file

---

.travis.yml

If there is a particularly slow build, either due to resource constraints at Travis, or slow connectivity for downloading dependencies, then the install phase could take more than 10 minutes. Previously the install phase was quietened (with `-q`), unfortunately Travis will kill any job which doesn't produce output for more than 10 minutes.

Don't quieten Maven output on Travis-CI

---

build/scripts/macosx.xml

The macOS build file had a dependency on the full Xcode app for one of its command line tools, SetFile. This tool is available as part of the Xcode Command Line Tools, which can be installed without the full Xcode suite, using `xcode-select --install` — to receive the necessary command line tools at a fraction of the disk space needed. This PR allows systems without a full Xcode installation to build the 4.x.x macOS app (`./build.sh app`).
https://developer.apple.com/library/archive/technotes/tn2339/_index.html
Confirmed with local build on system without full Xcode installation, i.e., with only Xcode Command Line Tools installed.

(4.x.x) Remove dependency on full Xcode installation

---

exist-distribution/pom.xml

Port of #2790.
Bump appbundler-maven-plugin from 1.0.1 to 1.0.4
Bumps [appbundler-maven-plugin](https://github.com/evolvedbinary/appbundler-maven-plugin) from 1.0.1 to 1.0.4.
- [Release notes](https://github.com/evolvedbinary/appbundler-maven-plugin/releases)
- [Commits](https://github.com/evolvedbinary/appbundler-maven-plugin/compare/appbundler-maven-plugin-1.0.1...appbundler-maven-plugin-1.0.4)

(5.0.0) Bump appbundler-maven-plugin from 1.0.1 to 1.0.4

---

.idea/runConfigurations/Java_Admin_Client.xml
.idea/runConfigurations/Jetty_Server.xml

The "Jetty Server" run configuration in IntelliJ was previously not starting correctly in IntelliJ on the Mavenized version of eXist-db.

Fix IntelliJ shared run target for Jetty Server

---

exist-distribution/pom.xml
exist-parent/pom.xml

As discussed during last community call and in https://github.com/eXist-db/monex/pull/88, this PR enables websockets in the included Jetty. For JSR-356 compliant websockets on the server, two dependencies are required. Unfortunately they recursively pull in quite a few extra jars, including `websocket-client`, which seems unnecessary, but it's the documented approach.

[feature] Enable JSR-356 websocket support in jetty

---

exist-core/src/main/java/org/exist/xquery/Optimizer.java
extensions/indexes/range/src/test/xquery/range/optimizer.xql

Removes a buggy query rewrite, which can't work the way it was. This affects expressions like /a/b//c[d = 123]. The main optimization on c[d = 123] will still work as shown by the tests, but /a/b will be fully evaluated.
If users want a similar optimisation, where it is appropriate they can rewrite their query manually.
Closes #2786

Disable bad optimization

---

exist-core/src/main/java/org/exist/util/io/ByteArrayContent.java
exist-core/src/main/java/org/exist/util/io/ContentFile.java
exist-core/src/main/java/org/exist/util/io/VirtualTempPath.java
exist-core/src/main/java/org/exist/xmldb/AbstractRemoteResource.java
exist-core/src/main/java/org/exist/xmldb/RemoteCollection.java
exist-core/src/main/java/org/exist/xmldb/RemoteResourceSet.java
exist-core/src/main/java/org/exist/xmldb/RemoteXMLResource.java
exist-core/src/test/java/org/exist/util/io/ByteArrayContentTest.java

Adds `VirtualTempPath` usage to also update methods within `RemoteXMLResource` and others like `RemoteResourceSet` in order to use less file file I/O for small data values. This will increase the the performance mainly on Windows systems and generally reduce the disk I/O.
The implementation is a follow up on the already implemented issue #2592

Adds VirtualTempPath on set content methods

---

.travis.yml

oracle JDK11 is still used... it should not

(4.x.x) Dont use oracle JDK

---

exist-core/pom.xml

Backport of https://github.com/eXist-db/exist/pull/2854

(5.0.0) Update Multilock to the released version

---

exist-installer/src/main/izpack/jobs.xml
exist-installer/src/main/izpack/userInput.xml

This PR fixes two issues:
1. The data directory specified (within Dialog/unattended) is not set correctly
2. The admin password specified using unattended installation has been ignored
Manual installation test using the GUI dialog, specifying a different data directory and admin password.
Unattended installation using the following command: 
`-jar exist-installer/target/exist-installer-5.0.0-RC8-SNAPSHOT.jar -options exist.props`
where the content of `exist-props` was:
```
INSTALL_PATH=/opt/exist-test
dataDir=/opt/exist-data
adminPasswd=installTest
```

Fixes unattended installation with data directory & admin password

---

exist-installer/src/main/izpack/jobs.xml
exist-installer/src/main/izpack/userInput.xml

This PR fixes two issues:
1. The data directory specified (within Dialog/unattended) is not set correctly
2. The admin password specified using unattended installation has been ignored
Manual installation test using the GUI dialog, specifying a different data directory and admin password.
Unattended installation using the following command: 
`-jar exist-installer/target/exist-installer-5.0.0-RC8-SNAPSHOT.jar -options exist.props`
where the content of `exist-props` was:
```
INSTALL_PATH=/opt/exist-test
dataDir=/opt/exist-data
adminPasswd=installTest
```

(5.0.0) Fixes unattended installation with data directory & admin password

---

exist-core/src/main/java/org/exist/xquery/ErrorCodes.java
exist-core/src/main/java/org/exist/xquery/functions/fn/FnModule.java
exist-core/src/main/java/org/exist/xquery/functions/fn/FunParseIetfDate.java
exist-core/src/main/java/org/exist/xquery/functions/fn/FunString.java
exist-core/src/test/xquery/xquery3/parseIetfDate.xqm

Fully [spec](https://www.w3.org/XML/Group/qtspecs/specifications/xpath-functions-31/html/Overview.html#func-parse-ietf-date) compliant implementation of `fn:parse-ietf-date()` in java.
- add error code FORG0010
- add function to fn namespace
closes #2820
Xquery testsuite

feat (xquery): implement fn:parse-ietf-date()

---

exist-core/src/main/java/org/exist/xquery/ErrorCodes.java
exist-core/src/main/java/org/exist/xquery/functions/fn/FnModule.java
exist-core/src/main/java/org/exist/xquery/functions/fn/FunParseIetfDate.java
exist-core/src/main/java/org/exist/xquery/functions/fn/FunString.java
exist-core/src/test/xquery/xquery3/parseIetfDate.xqm

port of #2857 
Fully [spec](https://www.w3.org/XML/Group/qtspecs/specifications/xpath-functions-31/html/Overview.html#func-parse-ietf-date)
compliant implementation of `fn:parse-ietf-date()` in java.
- add error code FORG0010
- add function to fn namespace
- add testsuite

(5.0.0): implement fn:parse-ietf-date()

---

exist-ant/src/main/java/org/exist/ant/UserPasswordTask.java
exist-core/src/main/java/org/exist/client/security/UserDialog.java
exist-core/src/main/java/org/exist/config/ConfigurationDocumentTrigger.java
exist-core/src/main/java/org/exist/security/AbstractAccount.java
exist-core/src/main/java/org/exist/security/AbstractRealm.java
exist-core/src/main/java/org/exist/security/PermissionFactory.java
exist-core/src/main/java/org/exist/security/SecurityManager.java
exist-core/src/main/java/org/exist/security/internal/RealmImpl.java
exist-core/src/main/java/org/exist/security/internal/SecurityManagerImpl.java
exist-core/src/main/java/org/exist/security/internal/aider/UserAider.java
exist-core/src/main/java/org/exist/xquery/functions/securitymanager/FindGroupFunction.java
exist-core/src/main/java/org/exist/xquery/functions/securitymanager/GroupManagementFunction.java
exist-core/src/main/java/org/exist/xquery/functions/securitymanager/SecurityManagerModule.java
exist-core/src/test/java/org/exist/backup/XMLDBRestoreTest.java
exist-core/src/test/java/org/exist/security/AbstractAccountTest.java
exist-core/src/test/java/org/exist/security/AbstractSecurityManagerRoundtripTest.java
exist-core/src/test/java/org/exist/xquery/functions/securitymanager/AccountManagementFunctionRemoveAccountTest.java
exist-core/src/test/java/org/exist/xquery/functions/securitymanager/GroupManagementFunctionRemoveGroupTest.java
exist-core/src/test/java/org/exist/xquery/functions/securitymanager/GroupMembershipFunctionRemoveGroupMemberTest.java
exist-core/src/test/java/org/exist/xquery/functions/securitymanager/PermissionsFunctionChownTest.java

Previously there were several problems whereby accounts could end up without a group. Various parts of the system assumed that a group always had at least 1 group (i.e. a primary group). This has now been fixed, and accounts will always have at least 1 group, even if that is `nogroup`.
These previous problems could lead to NPEs and system instability.

Fix a number of security issues around user groups

---

exist-core/src/main/antlr/org/exist/xquery/parser/XQuery.g
exist-core/src/test/xquery/maps/maps.xql
exist-core/src/test/xquery/optimizer/optimizer.xql
exist-core/src/test/xquery/xquery3/inline.xml
exist-core/src/test/xquery/xquery3/recursion_calls.xml
extensions/modules/cache/src/test/xquery/modules/cache/cache.xqm

Fixes: #2887 
Constructing a map with `map { 'a': 1 }` works.
Using the draft syntax with `map { 'a':= 1}` will fail with
```
error found while executing expression: org.exist.xquery.XPathException: err:XPST0003 unexpected token: null [at line 1, column 10]
```
https://www.w3.org/TR/xquery-31/#prod-xquery31-MapConstructor
Added test to `exist-core/src/test/xquery/maps/maps.xql`

Remove XQuery draft Map constructor

---

installer/jobs.xml

This PR fixes a typo in the `Saxon-HE.jar` name for `<os family="windows"/>` in  `installer/jobs.xml`
Fixes [Issue #2895](https://github.com/eXist-db/exist/issues/2895)
Now the unattended installation under Windows (using an `autoinstaller.xml` file) passes.
Verified on our site on different windows machines.

(4.x.x) Use the correct name for the endorsed Saxon-HE.jar on Windows, too.

---

exist-core/pom.xml
exist-parent/pom.xml

The OSS Parent pom.xml is deprecated and should no longer be used.

(5.0.0) Remove OSS parent

---

exist-core/src/main/java/org/exist/xquery/UserSwitchingBasicFunction.java

If a user switching function was re-used via a function item, it was possible to leak users.
Closes https://github.com/eXist-db/exist/issues/2922

Fix user leak in XQuery User Switching functions

---

test/src/xquery/boolean-sequences.xql

Adds a test suite (xqsuite) for working with sequences of booleans.
This was done because of  https://github.com/eXist-db/exist/issues/2308

add testuite for boolean sequences

---

exist-core/src/main/java/org/exist/repo/Deployment.java
exist-distribution/pom.xml
exist-distribution/src/main/config/log4j2.xml

Closes https://github.com/eXist-db/exist/issues/2973
At auto-deploy time, package dependency ordering is not needed. The packages are just deployed as a bunch of files into the db regardless of any missing dependencies. The dependency resolution then occurs at runtime.

Add missing Semver.xq to autodeploy

---

extensions/webdav/src/main/java/org/exist/webdav/ExistResourceFactory.java

From the logs with fix: (fixes #3008)
```
2019-09-09 20:20:03,888 [main] INFO  (JettyStart.java [run]:285) - ----------------------------------------------------- 
2019-09-09 20:20:03,888 [main] INFO  (JettyStart.java [run]:286) - Server has started, listening on: 
2019-09-09 20:20:03,888 [main] INFO  (JettyStart.java [run]:288) -      http://10.0.10.11:8080/ 
2019-09-09 20:20:03,889 [main] INFO  (JettyStart.java [run]:288) -      https://10.0.10.11:8443/ 
2019-09-09 20:20:03,889 [main] INFO  (JettyStart.java [run]:291) - Configured contexts: 
2019-09-09 20:20:03,889 [main] INFO  (JettyStart.java [run]:297) -      /exist 
2019-09-09 20:20:03,890 [main] INFO  (JettyStart.java [run]:312) - '/exist/iprange' 
2019-09-09 20:20:03,890 [main] INFO  (JettyStart.java [run]:297) -      / …
```

Read webdav.properties from the etc directory when available.

---

exist-core/pom.xml
exist-core/src/test/java/org/exist/xquery/functions/util/ParseHtmlTest.java

The CyberNeko parser which we use by default for `util:parse-html` was missing from our list of dependencies.

Fix util:parse-html dependency

---

extensions/indexes/lucene/src/main/java/org/exist/indexing/lucene/NodePathPattern.java
extensions/indexes/lucene/src/test/java/org/exist/indexing/lucene/LuceneIndexTest.java

Added [@attr != value] predicate in XPath spec for Lucene index spec.
Previously only [@attr = value] was supported
Tests added too.
( see original https://github.com/eXist-db/exist/pull/2367 )

Addition to #2367: added [@attr != value] predicate

---

exist-distribution/src/main/scripts/create-dmg-mac.sh

Support for the option `hdiutil internet-enable` was dropped in MacOS catalina without replacement. According to manpage it was deprecated before.

[build] Fix create-dmg-mac.sh to work on catalina

---

exist-core/src/main/java/org/exist/xquery/LocationStep.java
exist-core/src/main/java/org/exist/xquery/Step.java
exist-core/src/test/xquery/optimizer/positional.xql

Static type checking for positional filter optimizations is difficult and has no added benefit, so switch back to dynamic checks. Added a test which shows the query failing before. See discussion at the bottom of #3075 for details. This PR is required for #3075 to have the desired effect.

Complement #3075: optimization was missed due to wrong static type

---

exist-core/src/main/java/org/exist/xslt/EXistDbInputSource.java
exist-core/src/main/java/org/exist/xslt/EXistDbSource.java
exist-core/src/main/java/org/exist/xslt/EXistDbXMLReader.java
exist-core/src/main/java/org/exist/xslt/EXistURIResolver.java
exist-core/src/main/java/org/exist/xslt/StylesheetResolverAndCompiler.java

This PR includes classes that handle internal documents referenced in the course of transformations under the transform::transform function using a Serializer under a SAXSource subclass instead of a subclass of DOMSource.  It's a response to the relatively slow performance of the DOMSource previously returned by EXistURIResolver as [reported here](https://github.com/eXist-db/exist/issues/3044), and is intended to treat documents included via xsl:doc() and xsl:include() the same way that the initial XML and XSL parameters to transform::transform are treated.  The performance for included files under these modifications is similar to the performance reading the same files when passed as initial parameters.
The modifications pass the existing transformation tests in my build environment. …

Add classes supporting a SAXSource for included database documents

---

.travis.yml
appveyor.yml
exist-ant/src/test/resources/log4j2.xml
exist-core-jcstress/pom.xml
exist-core-jcstress/src/main/java/org/exist/util/WeakLazyStripesStressTest.java
exist-core/src/main/java/org/exist/util/WeakLazyStripes.java
exist-core/src/test/resources/log4j2.xml
extensions/debuggee/src/test/resources/log4j2.xml
extensions/expath/src/test/resources/log4j2.xml
extensions/exquery/restxq/src/test/resources/log4j2.xml
extensions/indexes/lucene/src/test/resources/log4j2.xml
extensions/indexes/ngram/src/test/resources/log4j2.xml
extensions/indexes/range/src/test/resources/log4j2.xml
extensions/indexes/sort/src/test/resources/log4j2.xml
extensions/indexes/spatial/src/test/resources/log4j2.xml
extensions/modules/cache/src/test/resources/log4j2.xml
extensions/modules/compression/src/test/resources/log4j2.xml
extensions/modules/counter/src/test/resources/log4j2.xml
extensions/modules/expathrepo/src/test/resources/log4j2.xml
extensions/modules/file/src/test/resources/log4j2.xml
extensions/modules/persistentlogin/src/test/resources/log4j2.xml
extensions/security/activedirectory/src/test/resources/log4j2.xml
extensions/xqdoc/src/test/resources/log4j2.xml
pom.xml

Thanks very much to @paulmer for digging in and finding the cause:
Quoting @paulmer regarding `WeakLazyStripes`:
>The "get" method allocates a new lock if it finds that the weak reference matching the key has expired.  It then saves this new lock in the stripes hash (see getOptimistic, for example).  Then it proceeds to run drainClearedReferences().  If an expired reference with the same name as the lock just requested is on the refererenceQueue, drainClearedReferences will remove the reference to the newly created lock from the hash table.  A subsequent thread can then obtain a new lock for the same key even while the previous thread is still holding onto its lock.

Fix a race condition in WeakLazyStripes

---

exist-distribution/src/main/scripts/create-dmg-unix.sh

Checks whether the required tool is available, and if not, supplies the user with info for how to possibly install it.
As in the Java world, one is used to just clone a repo and then run `mvn install` and all works,
many might be lost when some *nix specific script fails, and would give up compiling entirely,
or loose some time looking for the solution online.

fail-fast on DMG creation if missing `/sbin/mkfs.hfsplus`

---

exist-core/src/main/java/org/exist/storage/ProcessMonitor.java

We were missing some synchronisation. This was shown by the test suite https://github.com/eXist-db/exist-xqts-runner

Avoid ConcurrentModificationException at shutdown

---

exist-parent/pom.xml

* Fixes an issue with SemVer comparison of package versions when restoring backups
Closes https://github.com/eXist-db/exist/issues/3118

Update pkg-java from 1.4.1 to 1.4.2

---

tools/yajsw/bin/installService.bat
tools/yajsw/bin/queryService.bat
tools/yajsw/bin/runConsole.bat
tools/yajsw/bin/startService.bat
tools/yajsw/bin/stopService.bat
tools/yajsw/bin/uninstallService.bat

Switches to the same drive as the script location in case of calling a script from an other drive. This fixes the command file not found error due to try to invoke subsequent calls on the wrong drive.

(4.x.x) Switch to script drive before calling subsequent commands

---

exist-core/src/main/java/org/exist/xquery/functions/fn/FnModule.java
exist-core/src/main/java/org/exist/xquery/functions/fn/JSON.java
exist-core/src/test/xquery/xquery3/json-to-xml.xql

Implemented fn:json-to-xml 
[Specification](https://www.w3.org/TR/xpath-functions-31/#func-json-to-xml)
XQSuite: exist-core/src/test/xquery/xquery3/json-to-xml.xql

[feature] implemented xquery function json-to-xml

---

exist-core/src/main/java/org/exist/storage/BrokerPool.java
exist-core/src/main/java/org/exist/storage/BrokerPools.java
exist-core/src/test/java/org/exist/storage/BrokerPoolsTest.java

Fixes a race condition when having multiple database instances and therefore multiple broker pools being shut down concurrently leading to a `ConcurrentModificationException`
`BrokerPoolsTest` reproducing the race condition

Fix concurrent modification shutting down multiple broker pools

---

exist-core/src/main/java/org/exist/storage/BrokerPool.java
exist-core/src/main/java/org/exist/storage/BrokerPools.java
exist-core/src/test/java/org/exist/storage/BrokerPoolsTest.java

Fixes a race condition when having multiple database instances and therefore multiple broker pools being shut down concurrently leading to a `ConcurrentModificationException`
`BrokerPoolsTest` reproducing the race condition
This is the backport of the following PR: https://github.com/eXist-db/exist/pull/3145

(4.x.x) Fix concurrent modification shutting down multiple broker pools

---

exist-core/src/test/java/org/exist/storage/BrokerPoolsTest.java

Fixes illegal characters in path (Backport of #3153)

(4.x-x) [bugfix] Fix illegal characters in directory name

---

exist-core/src/main/java/org/exist/storage/txn/TransactionManager.java

Fix a small livelock issue, backported from FusionDB.

Fix a livelock in TransactionManager

---

exist-core/src/main/java/org/exist/util/Leasable.java
exist-core/src/main/java/org/exist/xmldb/AbstractRemoteResource.java
exist-core/src/main/java/org/exist/xmldb/RemoteBinaryResource.java
exist-core/src/main/java/org/exist/xmldb/RemoteCallSite.java
exist-core/src/main/java/org/exist/xmldb/RemoteCollection.java
exist-core/src/main/java/org/exist/xmldb/RemoteCollectionManagementService.java
exist-core/src/main/java/org/exist/xmldb/RemoteDatabaseInstanceManager.java
exist-core/src/main/java/org/exist/xmldb/RemoteIndexQueryService.java
exist-core/src/main/java/org/exist/xmldb/RemoteResourceIterator.java
exist-core/src/main/java/org/exist/xmldb/RemoteResourceSet.java
exist-core/src/main/java/org/exist/xmldb/RemoteRestoreService.java
exist-core/src/main/java/org/exist/xmldb/RemoteUserManagementService.java
exist-core/src/main/java/org/exist/xmldb/RemoteXMLResource.java
exist-core/src/main/java/org/exist/xmldb/RemoteXPathQueryService.java
exist-core/src/main/java/org/exist/xmldb/RemoteXUpdateQueryService.java
exist-core/src/test/java/org/exist/util/LeasableTest.java
exist-core/src/test/java/org/exist/xmldb/RemoteCollectionTest.java

Implements the `Collection.isOpen()` method behaviour and also moved duplicated `XmlRpcClient` acces into a central method on the `RemoteCollection` eliminating repetitive implementations all over multiple places reducing the total amount of code.
Adds a new JUnit tests for the new implemented parts as the enhanced parts from `Leasable`

Implements isOpen() / close() methods on RemoteCollection

---

exist-core/src/main/java/org/exist/xquery/PathExpr.java

Closes https://github.com/eXist-db/exist/issues/2622

Make sure to log at the correct level

---

exist-core/src/main/java/org/exist/storage/statistics/IndexStatistics.java
exist-core/src/test/java/org/exist/storage/statistics/StatisticsIndexTest.java
exist-core/src/test/resources-filtered/org/exist/storage/statistics/conf.xml

Closes https://github.com/eXist-db/exist/issues/3193

Make sure to create the stats index before writing if it does not exist

---

exist-core/src/main/java/org/exist/management/AgentFactory.java
exist-core/src/main/java/org/exist/management/impl/JMXAgent.java
exist-core/src/main/java/org/exist/storage/BrokerPool.java
exist-core/src/main/java/org/exist/storage/BrokerPoolServicesManager.java
exist-core/src/main/java/org/exist/storage/ContentLoadingObserver.java
exist-core/src/main/java/org/exist/storage/DefaultCacheManager.java
exist-core/src/main/java/org/exist/storage/NativeBroker.java
exist-core/src/main/java/org/exist/storage/NativeValueIndex.java
exist-core/src/main/java/org/exist/storage/btree/BTree.java
exist-core/src/main/java/org/exist/storage/btree/Paged.java
exist-core/src/main/java/org/exist/storage/dom/DOMFile.java
exist-core/src/main/java/org/exist/storage/index/BFile.java
exist-core/src/main/java/org/exist/util/Lockable.java

Closes https://github.com/eXist-db/exist/pull/3170

Memory leak on shutdown

---

extensions/indexes/lucene/src/main/java/org/exist/indexing/lucene/LuceneConfig.java
extensions/indexes/lucene/src/main/java/org/exist/indexing/lucene/LuceneIndexWorker.java
extensions/indexes/lucene/src/main/java/org/exist/indexing/lucene/LuceneMatchListener.java
extensions/indexes/lucene/src/test/xquery/lucene/facets.xql
extensions/indexes/range/src/main/java/org/exist/indexing/range/RangeIndexConfig.java
extensions/indexes/range/src/main/java/org/exist/indexing/range/RangeIndexWorker.java

In specific cases a wrong lucene index config (potentially belonging to a different collection) was used when storing a document into a collection which did not define a lucene index at all. We need to make sure the config is cleared and set to an empty default before the worker is reused for storing another document. The same applies to the range index.

Lucene index fixes

---

exist-core/src/main/java/org/exist/util/FastStringBuffer.java
exist-core/src/main/java/org/exist/xquery/value/DayTimeDurationValue.java
exist-core/src/main/java/org/exist/xquery/value/DoubleValue.java
exist-core/src/main/java/org/exist/xquery/value/FloatValue.java
exist-core/src/test/java/org/exist/util/FastStringBufferTest.java

Improved performance by using native array copy
Synced code from saxonHE
Added tests

FastStringBuffer improvement

---

extensions/contentextraction/pom.xml
extensions/contentextraction/src/test/java/xquery/contentextraction/ContentExtractionTests.java
extensions/contentextraction/src/test/resources-filtered/conf.xml
extensions/contentextraction/src/test/resources/log4j2.xml
extensions/contentextraction/src/test/xquery/contentextraction/content-extraction.xq

Closes https://github.com/eXist-db/exist/issues/3166

Fix contentextraction on 5.x.x

---

exist-core/src/main/java/org/exist/storage/lock/LockManager.java
exist-core/src/main/java/org/exist/storage/lock/ManagedDocumentLock.java
exist-core/src/main/java/org/exist/util/Configuration.java
exist-core/src/test/java/org/exist/storage/lock/GetXMLResourceNoLockTest.java
exist-core/src/test/java/org/exist/storage/lock/LockManagerTest.java
exist-distribution/src/main/config/conf.xml

This adds a new option to `conf.xml`:
```xml
<document use-path-locks="false"/>
```
When this is enabled, document and collection locks participate in the same locking hierarchy. This means that it becomes impossible for deadlocks to occur between documents and collections.
This should likely be enabled by default in future.

Option to make Document locks hierarchical

---

exist-core/src/main/java/org/exist/util/WeakLazyStripes.java

A small issue where a *delete* from `stripes` was interleaved with a *read* without locking. 
Non-deterministic, and so incredibly hard to test for. Only appears under high concurrency.

Fix a concurrency issue in WeakLazyStripes

---

extensions/indexes/lucene/src/main/java/org/exist/indexing/lucene/LuceneFacetConfig.java
extensions/indexes/lucene/src/main/java/org/exist/indexing/lucene/LuceneIndexWorker.java
extensions/indexes/lucene/src/main/java/org/exist/xquery/modules/lucene/QueryOptions.java
extensions/indexes/lucene/src/test/resources-filtered/conf.xml
extensions/indexes/lucene/src/test/xquery/lucene/facets.xql

Extend hierarchical facets to accept multiple values passed in via an array.
Defining a hierarchical facet on a node, it is possible that a node is a member of multiple hierarchies at the same time. For example, a text could fall into several hierarchical subject categories like science/math or humanities/history. Currently this is not supported: we only allow a single hierarchical facet per dimension.
Multiple hierarchies can be easily described as an XQuery array of sequences like `[('science', 'math'), ('humanities', 'history')]`. This PR extends the facet indexer to check if the result of the XQuery expression to obtain the facet value is an array. If it is, it is treated as a multi-valued hierarchical facet.
See extended xqsuite test. …

Multi-valued hierarchical facets

---

.travis.yml

close #3224
`:release` should be build on tagged CI runs, this fixes that.

fix(travis): deploy on tagged builds

---

exist-core/src/main/java/org/exist/xquery/functions/map/AbstractMapType.java
exist-core/src/main/java/org/exist/xquery/functions/map/MapFunction.java
exist-core/src/main/java/org/exist/xquery/functions/map/MapType.java
exist-core/src/main/java/org/exist/xquery/functions/map/SingleKeyMapType.java
exist-core/src/test/xquery/maps/maps.xql

AbstractMapType.remove and all overrides now expect an array of
AtomicValues.
MapFunction.remove was adapted to take that into account.
fixes #1656 
Add tests to XQsuite to ensure sequences of keys can be deleted and
the changes do not break behaviour for non existing keys.

[fix] map:remove sequence of keys

---

exist-core/src/main/java/org/exist/xquery/functions/fn/FnRandomNumberGenerator.java
exist-core/src/test/xquery/xquery3/fnRandomNumberGenerator.xql

fixes https://github.com/eXist-db/exist/issues/3071
xqsuite

[bugfix] spec compliant random-number-generator

---

exist-core/src/main/java/org/exist/storage/BrokerPool.java
exist-jetty-config/src/main/resources/org/exist/jetty/etc/jetty-bytebufferpool.xml
exist-jetty-config/src/main/resources/org/exist/jetty/etc/jetty-gzip.xml
exist-jetty-config/src/main/resources/org/exist/jetty/etc/jetty-http.xml
exist-jetty-config/src/main/resources/org/exist/jetty/etc/jetty-https.xml
exist-jetty-config/src/main/resources/org/exist/jetty/etc/jetty-jaas.xml
exist-jetty-config/src/main/resources/org/exist/jetty/etc/jetty-jmx.xml
exist-jetty-config/src/main/resources/org/exist/jetty/etc/jetty-plus.xml
exist-jetty-config/src/main/resources/org/exist/jetty/etc/jetty-requestlog.xml
exist-jetty-config/src/main/resources/org/exist/jetty/etc/jetty-ssl-context.xml
exist-jetty-config/src/main/resources/org/exist/jetty/etc/jetty-ssl.xml
exist-jetty-config/src/main/resources/org/exist/jetty/etc/jetty-threadpool.xml
exist-jetty-config/src/main/resources/org/exist/jetty/etc/jetty.xml
exist-jetty-config/src/main/resources/org/exist/jetty/etc/standalone-jetty-http.xml
exist-jetty-config/src/main/resources/org/exist/jetty/etc/standalone-jetty-ssl.xml
exist-jetty-config/src/main/resources/org/exist/jetty/etc/standalone-jetty.xml
exist-jetty-config/src/main/resources/org/exist/jetty/etc/standalone.enabled-jetty-configs
exist-jetty-config/src/main/resources/org/exist/jetty/etc/standard.enabled-jetty-configs
exist-jetty-config/src/main/resources/org/exist/jetty/etc/webdefault.xml
extensions/modules/xslfo/pom.xml

The jetty config was out of date, this could lead to Jetty leaving sockets in a lingering `CLOSE_WAIT` state and then eventually running out of file descriptors.

Fix an issue with jetty closing sockets

---

exist-core/src/main/java/org/exist/xquery/functions/fn/FnRandomNumberGenerator.java

Cardinality according to the spec should be zero_or_one, not one.
With some small fixes to our XQTS runner, this now causes us to reach 86.36% compliance with the fn:random-number-generator tests in XQTS 3.1.

Fix the cardinality of fn:random-number-generator#1

---

extensions/indexes/lucene/src/main/java/org/exist/indexing/lucene/LuceneConfig.java
extensions/indexes/lucene/src/main/java/org/exist/indexing/lucene/LuceneIndexWorker.java
extensions/indexes/lucene/src/main/java/org/exist/xquery/modules/lucene/QueryOptions.java
extensions/indexes/lucene/src/test/xquery/lucene/analyzers.xml

Original from @sten1ee :
In our usage of eXist, we're utilising a 'State of the art' LuceneAnalyzer for Sanskrit language developed by our colleagues from BDRC It has several modes of operation, but the one that we use - 'lenient mode' - requires one Analyzer to be used during the indexing phase, but then a different (or a differently configured) one to be used during querying.
Currently, eXist does not provide support for this use case, but this PR is aiming to achieve this feat.
based on #2908, #2991 opened by @sten1ee 
testsuite in XML

[wip] [feat] distinct analyzers for indexing and querying with Lucene

---

exist-core/src/main/java/org/exist/xquery/functions/request/GetData.java

More reliable reading of HTTP body for `request:get-data()`

Reinstate code for a historical Jetty bugfix

---

exist-core/src/main/java/org/exist/security/AbstractUnixStylePermission.java
exist-core/src/test/java/org/exist/security/UnixStylePermissionTest.java

Closes https://github.com/eXist-db/exist/issues/3157
Previously when using a simple symbolic mode string for changing permissions, the sticky bit `t` (with execute bit), or `T` (without execute bit) was not recognised.

Correctly set the sticky bit when using a simple symbolic mode string

---

exist-core/src/main/java/org/exist/backup/restore/RestoreHandler.java

Closes https://github.com/eXist-db/exist/issues/3023
Previously the paths of any files that could not be restored and the reason why were shown in the Restore tool/dialog, however when the errors were written to the log the file paths were missing.

Include the path of any file that could not be restored in the log

---

exist-core/src/main/java/org/exist/collections/Collection.java
exist-core/src/main/java/org/exist/collections/LockedCollection.java
exist-core/src/main/java/org/exist/collections/MutableCollection.java
exist-core/src/main/java/org/exist/storage/NativeBroker.java
exist-core/src/test/xquery/indexing/indexes-base-uri.xq

Closes https://github.com/eXist-db/exist/issues/3040
The `DocumentImpl` caches the URI which is composed of both the Collection URI and Document name. When moving a Collection, the target collection's `DocumentImpl`'s did not have their cached URIs updated correctly.
This is only a problem in 5.x.x which optimised the Collection Move operation.

Document URI was incorrectly cached during a Collection Move

---

exist-core/src/main/java/org/exist/backup/DescriptorResourceCounter.java
exist-core/src/main/java/org/exist/backup/FileSystemBackupDescriptor.java
exist-core/src/main/java/org/exist/backup/GuiRestoreServiceTaskListener.java
exist-core/src/main/java/org/exist/backup/Main.java
exist-core/src/main/java/org/exist/backup/Restore.java
exist-core/src/main/java/org/exist/backup/RestoreDialog.java
exist-core/src/main/java/org/exist/backup/ZipArchiveBackupDescriptor.java
exist-core/src/main/java/org/exist/backup/restore/RestoreHandler.java
exist-core/src/main/java/org/exist/backup/restore/listener/AbstractRestoreListener.java
exist-core/src/main/java/org/exist/backup/restore/listener/RestoreListener.java
exist-core/src/main/java/org/exist/client/ClientFrame.java
exist-core/src/main/java/org/exist/util/FileUtils.java
exist-core/src/main/java/org/exist/xmldb/AbstractRestoreServiceTaskListener.java
exist-core/src/main/java/org/exist/xmldb/LocalRestoreService.java
exist-core/src/main/java/org/exist/xmldb/RemoteRestoreService.java
exist-core/src/main/java/org/exist/xmldb/RestoreServiceTaskListener.java
exist-core/src/main/java/org/exist/xmlrpc/RpcAPI.java
exist-core/src/main/java/org/exist/xmlrpc/RpcConnection.java
exist-core/src/test/java/org/exist/backup/RestoreAppsTest.java

Closes https://github.com/eXist-db/exist/issues/3024
* Allow the user to see the result of the restore process before dismissing the restore dialog.
* Improve/correct percentage display in Restore Dialog.
* Make sure to report Zip and Transfer process when restoring backups to a remote server, otherwise to the user the restore process can appear to be doing nothing.
* Get the correct total of files to be restored
* When skipping packages during restore (due to newer version), skipped documents must be counted too (for progress)

Fix reporting of Restored Documents when restoring a backup

---

exist-core/src/main/java/org/exist/xquery/NamedFunctionReference.java
exist-core/src/test/xquery/xquery3/fnRefs.xql

Closes https://github.com/eXist-db/exist/issues/1467

 fn:concat requires an arity of at least two when making a function reference

---

exist-core/src/main/java/org/exist/util/FileUtils.java
exist-core/src/main/java/org/exist/xmldb/RemoteRestoreService.java
exist-core/src/test/java/org/exist/backup/XMLDBRestoreTest.java

When restoring a backup folder via XML:RPC on Windows, the restore on the server-side failed. This was due to the Zip file which is transferred over XML:RPC containing `\` path separators, and the server expecting it to contain `/` path separators.
Closes https://github.com/eXist-db/exist/issues/3196

Fix restoring folder backups on Windows via XML:RPC

---

exist-docker/src/main/resources-filtered/Dockerfile

Closes https://github.com/eXist-db/exist/issues/3165
Previously the Docker HEALTHCHECK command would use the `admin` account to query the server. As @ambs pointed out, every sensible user is going to change the `admin` password, which means they then need to create custom Docker images. Instead, we now use the `guest` account by default which is unlikely to change.

Docker HEALTHCHECK should use `guest` account not `admin`

---

exist-core/src/test/java/org/exist/installer/JobsXmlConfigurationTest.java

This PR adds a long promised test which applies to the `develop-4.x.x` branch only.
See discussion on https://github.com/eXist-db/exist/pull/2896.

(4.x.x) Add a test to assert the integrity of installer/jobs.xml

---

exist-core/pom.xml

We published the offical XQJ RI to Maven Central. So we can now use that instead of our custom build on repo.evolvedbinary.com

Take the XQJ API dependency from Maven Central

---

exist-core/src/main/java/org/exist/client/ClientFrame.java
exist-core/src/main/java/org/exist/storage/NativeBroker.java
exist-core/src/main/java/org/exist/xmldb/EXistCollectionManagementService.java
exist-core/src/main/java/org/exist/xmldb/LocalCollectionManagementService.java
exist-core/src/main/java/org/exist/xmldb/RemoteCollectionManagementService.java
exist-core/src/test/java/org/exist/xmldb/DeleteCollectionTest.java
exist-core/src/test/java/org/exist/xmldb/MoveCollectionTest.java
exist-core/src/test/java/org/exist/xmldb/RenameCollectionTest.java

Renaming a Collection without moving it was broken in 5.2.0, this is due to a partial regression in an earlier security fix - 4897cc2
Closes https://github.com/eXist-db/exist/issues/3310

Fix renaming a Collection

---

exist-parent/pom.xml

Previously if you compiled eXist-db on JDK9+, you could not run the binary artifacts on Java 8. This PR by default makes all builds runtime compatible with Java 8.

Make builds runtime compatible with Java 8 when built on JDK9+

---

exist-core/src/main/java/org/exist/xquery/FunctionFactory.java
exist-core/src/main/java/org/exist/xquery/functions/util/Compile.java
exist-core/src/test/xquery/errors.xql

#3265 introduced an NPE in the `analyze` chain by adding the calling expression (which has a different context!) to the path expression passed to the parser. See the discussion in https://github.com/eXist-db/exist/pull/1520#issuecomment-604084477.
This PR fixes the original issue #1583 without polluting the context and reports the correct line numbers for errors. Some tests were added as well.

Fix  polluted context when dynamically compiling query

---

pom.xml

IzPack installer build is still disabled by default. Building it can be time consuming.
This PR allows it  be disabled with the Maven args `-P !installer`

Allow disabling building of the IzPack installer

---

exist-core/src/main/java/org/exist/numbering/DLN.java
exist-core/src/main/java/org/exist/numbering/DLNBase.java
exist-core/src/main/java/org/exist/numbering/NodeId.java
exist-core/src/main/java/org/exist/xquery/functions/util/GetFragmentBetween.java
exist-core/src/test/xquery/util/get-fragment-between.xqm

Closes https://github.com/eXist-db/exist/issues/2316
The following returns `true` as expected:
```Java
new DLN("1.1.1").equals(new DLN("1.1.1"))
```
However, the following unexpectedly returns `false`, when one would expect it to return `true`:
```java
Optional.of(new DLN("1.1.1").equals(Optional.of(new DLN("1.1.1"))))
```
This is due to a strange definition (and implementation) of `equals` in `NodeId`; I have removed this potentially dangerous pattern so that you get expected behaviour.
Most of the test I adapted from @joewiz. I would be happy if Joe could check he agrees with them still ;-)

Fix an issue with Java equality of DLN

---

exist-core/src/main/java/org/exist/config/Configurator.java
exist-core/src/main/java/org/exist/security/AbstractGroup.java
exist-core/src/main/java/org/exist/security/AbstractRealm.java
exist-core/src/test/java/org/exist/security/AbstractSecurityManagerRoundtripTest.java
exist-core/src/test/java/org/exist/security/LocalSecurityManagerRoundtripTest.java
exist-core/src/test/java/org/exist/security/RemoteSecurityManagerRoundtripTest.java

Closes https://github.com/eXist-db/exist/pull/1578
Previously you could add group managers, and save them. They were correctly persisted to the database. However, at the next database startup they were not loaded correctly and then removed from persistent storage; effectively that deleted any group managers... Ouch! Since at least 2017?!?

Group managers should be loaded from security database at startup

---

exist-core/src/main/java/org/exist/jetty/JettyStart.java
exist-core/src/main/java/org/exist/util/FileUtils.java

Output:
```
30 Mar 2020 19:54:38,255 [main] INFO  (JettyStart.java [run]:173) - Running with Java 1.8.0_242 [AdoptOpenJDK (OpenJDK 64-Bit Server VM) in /Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/jre] 
30 Mar 2020 19:54:38,257 [main] INFO  (JettyStart.java [run]:180) - Maximum amount of memory for JVM: 3641 MiB 
30 Mar 2020 19:54:38,258 [main] INFO  (JettyStart.java [run]:181) - Number of processors available to JVM: 8  
```

[Feature] Add memory and nr of processors information to startup log.

---

exist-core/src/main/java/org/exist/test/runner/XMLTestRunner.java
exist-core/src/main/java/org/exist/test/runner/XQueryTestRunner.java
exist-core/src/main/resources/org/exist/xquery/lib/test.xq
extensions/indexes/range/src/test/xquery/range/field-type.xql

Improves the naming of tests expressed in XQuery and XML.
Also:
* XML test suites are now prefixed `xmts`
* XQuery test suites are now prefixed `xqts`

Improve XQuery test naming

---

schema/collection.xconf.xsd

This PR registers elements added in the [Lucene facets & fields feature](https://exist-db.org/exist/apps/doc/lucene#facets-and-fields) released in eXist 5.  Before this PR, valid xconf files would raise schema validation errors in eXide.  The previous XSD itself raised errors in oXygen; this PR addresses those issues and makes other improvements that require XSD 1.1.
**Details:**
The xconf used in the facets & fields documentation in the previous link raised errors when validated against the previous schema, because of the new `<facet>` and `<field>` elements:
```xml
<collection xmlns="http://exist-db.org/collection-config/1.0">
<index xmlns:db="http://docbook.org/ns/docbook" xmlns:xs="http://www.w3.org/2001/XMLSchema">
<lucene>
<text qname="db:article">
<facet dimension="keyword" …
```

Update collection.xconf.xsd for eXist 5

---

exist-parent/pom.xml
extensions/images/pom.xml

Switches to secure (https) maven repositories where there is a secure repository. Also use new osgeo.org repository for `extensions/images/pom.xml`

Use secure maven repos where possible

---

.gitignore

- ignore `.DS_Store` (OSX)
- ignore `.settings/`, `.factorypath`, `.classpath` and `.project`
these are created when building on the command line and
gobble up `git status` output
- group patterns by type

[ignore] add os and build files to ignore

---

.travis.yml

Removes the no longer supported JDKs as from _openjdk.java.net_ in order to speed up the build feedback.

Reduces JDK pipeline to the LTS and last released versions

---

exist-core/src/main/java/org/exist/xquery/functions/util/GetNodeById.java
exist-core/src/test/xquery/util/document-id.xqm

`util:node-by-id` should be changed to always check if the node identified by its nodeId does actually exist within the document or return an empty sequence instead. Not checking may lead to an undesirable and confusing NPE as a follow up. Instead we want to be able to determine that the node was not found.
Fixes the NPE reported here: https://github.com/eXist-db/exist/pull/3363#issuecomment-616183051
Test included.

Small change to util:node-by-id to avoid unexpected NPE

---

exist-distribution/pom.xml
pom.xml

@line-o If you don't need the distribution archives, e.g. when testing/hacking locally. Then with this PR, setting `-P !build-dist-archives` can save ~40 seconds on each build (at least on my machine).

Offer further build profiles

---

.travis.yml

which is marked as deprecated, but the new syntax from #3396 doesn't work.
close #3395

use v1 syntax

---

README.md

The Slack link in our README wasn't an invite link. This should help people who haven't seen the link in exist-open join the Slack.
n/a
n/a

Add functioning invite link to eXist Cmty Slack

---

exist-core/src/main/java/org/exist/xquery/functions/fn/FunHigherOrderFun.java
exist-core/src/test/xquery/xquery3/fnHigherOrderFunctions.xql

Fixes #3358 ArrayOutOfBoundException when a function reference supplied to a higher order
function has the wrong arity. 
This will now throw error XPTY0004.
New method `funcRefHasDifferentArity` added to class `FunHigherOrderFun` for readability and code re-use.
https://www.w3.org/TR/xpath-functions/#func-filter
Error messages are in line with Saxon 10
A new XQSuite for higher order functions is added.
Old tests left in place for now.

[fix] java exception on higher order functions

---

exist-distribution/pom.xml

Can be disabled with profile `skip-build-dist-archives`.
Fixes a regression introduced in https://github.com/eXist-db/exist/pull/3386
Seems the docs were not merged last time, please could someone merge those too - https://github.com/eXist-db/documentation/pull/466

Make sure that dist-archives are built by default

---

exist-installer/pom.xml
exist-parent/pom.xml
exist-versioning-release.md

* Externalises some config (see the updated `exist-versioning-release.md` file).
* Adds a facility for signing the IzPack installer.

Improve signing of release artifacts

---

exist-parent/pom.xml

There seems to be an issue with Maven Surefire Plugin 3.0.0-M5 when running parallel builds.

Revert PR #3455 maven-surefire-plugin-3.0.0-M5

---

exist-core/src/main/java/org/exist/xquery/util/NumberFormatter.java
exist-core/src/test/xquery/dates/format-dates.xql

When formatting a dateTime or time using the `[P]` specifier in the picture string (for am/pm), times from 12:00-12:59 were rendered with “am” instead of “pm”. 
See https://www.w3.org/TR/xpath-functions-31/#rules-for-datetime-formatting.
Updated existing xqsuite tests for `[P]` specifier

[bugfix] Fix formatting of am/pm for 12 pm

---

exist-core/src/main/java/org/exist/backup/Main.java

A small fix for the Backup.Main, which enables the user to connect to a remote eXist server via SSL
Closes https://github.com/eXist-db/exist/issues/3434

Fix: enabling SSL via commandline arguments, when doing a backup/restore

---

exist-core/src/main/java/org/exist/xquery/PathExpr.java
exist-core/src/test/xquery/errors.xql

Closes #3473
An exception occurred during query execution: err:XPTY0004 Type error: cannot compare operands: xs:integer and xs:string [at line 1, column 3]

Catch exception and enrich exception with location information. 

---

exist-core/src/main/antlr/org/exist/xquery/parser/XQuery.g
exist-core/src/test/xquery/xquery3/concat.xql

Modify the XQuery grammar to recognize `||` as concatenation operator
only when outside of attribute or element content and string constructors.
Add and extend the test suite for concatenation operator tests.
Testing for concatenation and literal `||` in different mixed modes.
Fix some minor whitespace issues.
fixes #1828
xqsuite

[fix] concatenation dependend on mode

---

exist-core/src/main/java/org/exist/xquery/functions/fn/FunBaseURI.java
exist-core/src/test/java/org/exist/xquery/XQueryTest.java

Closes https://github.com/eXist-db/exist/issues/3497

fn:base-uri should not raise XPDY0002 when the context item is empty

---

exist-core/src/main/java/org/exist/xquery/AnalyzeContextInfo.java
exist-core/src/main/java/org/exist/xquery/functions/fn/FunStrLength.java
exist-core/src/test/java/org/exist/xquery/functions/fn/FunStrLengthTest.java

Closes https://github.com/eXist-db/exist/issues/3506
Related https://github.com/evolvedbinary/fusion-studio-api/issues/12
See the issue for details.

Fix an issue with the context item as an argument to fn:string-length inside a predicate

---

exist-core/src/main/java/org/exist/repo/ClasspathHelper.java

If a XAR does not specify that it requires a specific version of eXist-db. Then do not enforce eXist-db version 1.4.0 to 2.2.1. That doesn't make sense, as some packages e.g. functx, don't have a dependency on eXIst-db.
@wolfgangmm just want to check this one with you...

Fix EXPath XAR required eXist-db version calculation

---

exist-core/src/main/java/org/exist/client/QueryDialog.java

Previously when selecting a query from the history to restore to the query dialog, the query was incorrectly acquired.

Fix an issue in the query history in the Java Admin Client

---

exist-core/src/main/java/org/exist/xquery/functions/system/GetRunningXQueries.java
exist-core/src/test/java/org/exist/xquery/functions/system/GetRunningXQueriesTest.java

Allows the user to identify the query that asked for the list of running queries.

Add a caller attribute to the output of system:get-running-xqueries#0

---

exist-core/pom.xml
exist-core/src/main/java/org/exist/storage/NativeBroker.java
exist-core/src/test/java/org/exist/storage/MoveCollectionTest.java

Back-ported a fix from FusionDB. Previously Collections were not correctly persisted under certain move/rename conditions.

Collection must be persisted when renaming/moving

---

extensions/modules/file/src/main/java/org/exist/xquery/modules/file/DirectoryList.java

Added missing directoryScanner.scan() to fix repo:install-from-db. The bug can be reproduced by executing `ant deploy-one -Drepo-name=hsg-shell -Dxar=hsg-shell-0.2.xar` in https://github.com/HistoryAtState/hsg-project. The ant target calls `https://github.com/HistoryAtState/hsg-project/blob/master/build/deploy.xql` which triggers the exception ` java.lang.IllegalStateException: Must call scan() first`.

added missing directoryScanner.scan(); to fix repo:install-from-db

---

exist-core/src/main/antlr/org/exist/xquery/parser/XQuery.g
exist-core/src/test/xquery/function.xql

fixes #3551
- modify grammar rule functionBody to handle an empty function body
- add XQSuite tests to ensure this works for
- declared functions
- declared variables of type function(*)
- inline declarations
- function expressions

[fix] allow functions with empty body

---

exist-core/src/main/java/org/exist/util/hashtable/NamePool.java
exist-core/src/test/java/org/exist/util/hashtable/NamePoolTest.java

Fix where QName comparison in Namepool was not taking the actual namespace into account
Found during code inspection with Intellij.

Fix QName comparison Namepool.

---

extensions/modules/compression/src/main/java/org/exist/xquery/modules/compression/AbstractCompressFunction.java
extensions/modules/compression/src/test/xquery/modules/compression/zip-tests.xql

Bugfix: make sure 0 byte sized binary resources can be included in ZIP file. Fixes 3565

Bugfix: make sure 0 byte sized binary resources can be included in ZiPfile

---

exist-core/src/main/java/org/exist/xquery/functions/util/Base64Functions.java
exist-core/src/main/java/org/exist/xquery/functions/util/UtilModule.java
exist-core/src/test/java/org/exist/xquery/functions/util/Base64FunctionsTest.java

There is a number of use cases (data-url, JWT) where the data must be encoded as base64 url-safe.
This PR adds a new utility function adding this functionality.
Compare the output of 
```
util:base64-encode(".ÿd"),
util:base64-encode-url-safe(".ÿd")
```
Additionally, this PR deprecates `util:base64-encode#2`. The trim-parameter serves no purpose since the output cannot be chunked because of the encoder that is used internally.
The class is refactored for readability and the formatting is fixed.
[RFC4648](https://tools.ietf.org/html/rfc4648)
Java tests were added to the tests that were already existing, ensuring that the functionality will persist even when implementation changes in the future.

add util:base64-encode-url-safe

---

exist-core/src/main/antlr/org/exist/xquery/parser/XQuery.g
exist-core/src/main/antlr/org/exist/xquery/parser/XQueryTree.g
exist-core/src/test/java/org/exist/xquery/UnknownAtomicTypeTest.java

Type errors for types after `instance of`, `cast as`, `castable as` and similar expressions do not show line and column numbers.
add line and column for type errors after
fixes #3518 
jUnit tests were added 
You can also evaluate any of the following expressions in eXide to see the change
```
let $x as y := 0 return $x
```
```
function ($x as y) { $x }
```
```
<x /> instance of y
```
```
<x /> cast as
y
```
```
<x /> castable as y
```
```
<x />
treat as
y
```

line and column numbers in unknown-atomic-type errors

---

exist-core/src/main/java/org/exist/storage/BrokerPool.java
exist-core/src/main/java/org/exist/storage/RegexMatcher.java
exist-core/src/main/java/org/exist/util/PatternFactory.java
exist-core/src/main/java/org/exist/xquery/functions/fn/FunAnalyzeString.java
exist-core/src/main/java/org/exist/xquery/functions/fn/FunReplace.java
exist-core/src/main/java/org/exist/xquery/regex/RegexUtil.java
exist-core/src/test/xquery/regex.xml
exist-core/src/test/xquery/xquery3/forwhere.xml

In an attempt to fix some bugs with eXist-db's `fn:replace` and `fn:analyze-string`, these new versions just wrap the Saxon equivalents.
If people like this, we could also extend it to `fn:matches`.

fn:replace and fn:analyze-string are now implemented with Saxon

---

exist-core/src/main/java/org/exist/util/Configuration.java

The option in `conf.xml` <document use-path-locks="false"/> was previously ignored.

Enable conf.xml option document/@use-path-locks

---

exist-core/src/main/java/org/exist/http/servlets/EXistServlet.java
exist-core/src/main/java/org/exist/storage/NativeBroker.java

Performing HTTP operations via the REST API for which you were not authorised, or which generated an error would lead to unnecessary log messages like:
```
2020-11-01 08:13:16,537 [qtp1114375302-67] WARN (TransactionManager.java [close]:581) - Transaction was not committed or aborted, auto aborting!
```
This PR fixes that.

REST API should not always complain about aborted transactions

---

exist-core/pom.xml
exist-core/src/main/java/org/exist/http/servlets/HttpRequestWrapper.java
exist-core/src/main/java/org/exist/http/servlets/HttpResponseWrapper.java
exist-core/src/main/java/org/exist/http/servlets/HttpSessionWrapper.java
exist-core/src/main/java/org/exist/http/servlets/RequestWrapper.java
exist-core/src/main/java/org/exist/http/servlets/ResponseWrapper.java
exist-core/src/main/java/org/exist/http/servlets/SessionWrapper.java
exist-core/src/main/java/org/exist/xquery/XQueryContext.java
exist-core/src/main/java/org/exist/xquery/functions/session/Clear.java
exist-core/src/main/java/org/exist/xquery/functions/session/Create.java
exist-core/src/main/java/org/exist/xquery/functions/session/GetAttribute.java
exist-core/src/main/java/org/exist/xquery/functions/session/GetAttributeNames.java
exist-core/src/main/java/org/exist/xquery/functions/session/GetCreationTime.java
exist-core/src/main/java/org/exist/xquery/functions/session/GetID.java
exist-core/src/main/java/org/exist/xquery/functions/session/GetLastAccessedTime.java
exist-core/src/main/java/org/exist/xquery/functions/session/GetMaxInactiveInterval.java
exist-core/src/main/java/org/exist/xquery/functions/session/Invalidate.java
exist-core/src/main/java/org/exist/xquery/functions/session/RemoveAttribute.java
exist-core/src/main/java/org/exist/xquery/functions/session/SessionFunction.java
exist-core/src/main/java/org/exist/xquery/functions/session/SetAttribute.java
exist-core/src/main/java/org/exist/xquery/functions/session/SetCurrentUser.java
exist-core/src/main/java/org/exist/xquery/functions/session/SetMaxInactiveInterval.java
exist-core/src/main/java/org/exist/xquery/functions/xmldb/XMLDBAuthenticate.java
exist-core/src/test/java/org/exist/xquery/functions/session/AbstractSessionTest.java
exist-core/src/test/java/org/exist/xquery/functions/session/AttributeTest.java
exist-core/src/test/java/org/exist/xquery/functions/xmldb/AbstractXMLDBTest.java
exist-core/src/test/java/org/exist/xquery/functions/xmldb/XMLDBAuthenticateTest.java

Fixes an `IllegalStateException` which could occur when eXist-db tries to perform Http Session functions but the session has been invalidated (but not yet cleaned up by Jetty).
I back-ported these tests and fixes from FusionDB.
Closes https://github.com/eXist-db/exist/issues/3610

Avoid IllegalStateException in Http Session functions

---

exist-core/src/main/java/org/exist/client/CollectionXConf.java
exist-core/src/main/java/org/exist/collections/CollectionConfigurationManager.java
exist-core/src/main/java/org/exist/dom/persistent/DocumentImpl.java
exist-core/src/main/java/org/exist/storage/NativeBroker.java
exist-core/src/test/java/org/exist/collections/triggers/TriggerConfigTest.java
exist-core/src/test/java/org/exist/validation/CollectionConfigurationTest.java
exist-core/src/test/java/org/exist/validation/CollectionConfigurationValidationModeTest.java
exist-core/src/test/java/org/exist/xmldb/CollectionConfigurationTest.java
exist-core/src/test/java/org/exist/xquery/UnionTest.java
exist-core/src/test/java/org/exist/xquery/functions/validate/JaxpDtdCatalogTest.java
exist-core/src/test/java/org/exist/xquery/functions/validate/JaxpParseTest.java
exist-core/src/test/java/org/exist/xquery/functions/validate/JaxpXsdCatalogTest.java
exist-core/src/test/java/org/exist/xquery/functions/validate/JaxvTest.java
exist-core/src/test/java/org/exist/xquery/functions/validate/JingRelaxNgTest.java
exist-core/src/test/java/org/exist/xquery/functions/validate/JingSchematronTest.java
exist-core/src/test/java/org/exist/xquery/functions/validate/JingXsdTest.java
exist-core/src/test/java/org/exist/xquery/functions/validate/ParseDtdTestNOK.java
exist-core/src/test/java/org/exist/xquery/functions/validate/ParseXsdTestNOK.java
extensions/indexes/range/src/test/java/org/exist/indexing/range/RangeIndexConfigTest.java
extensions/modules/expathrepo/src/test/java/org/exist/repo/PackageTriggerTest.java

Log's a warning if an encountered Collection Configuration document (e.g. collection.xconf) is a Binary document instead of an XML Document.

Log a warning if a collection.xconf is binary

---

exist-core/src/main/java/org/exist/storage/NativeBroker.java
exist-core/src/main/java/org/exist/storage/lock/LockManager.java
exist-core/src/main/java/org/exist/xmlrpc/RpcConnection.java
exist-core/src/test/java/org/exist/collections/CollectionRemovalTest.java
exist-core/src/test/java/org/exist/collections/triggers/HistoryTriggerTest.java
exist-core/src/test/java/org/exist/config/TwoDatabasesTest.java
exist-core/src/test/java/org/exist/util/XMLReaderSecurityTest.java
exist-core/src/test/java/org/exist/xquery/functions/securitymanager/PermissionsFunctionChownTest.java
exist-core/src/test/resources-filtered/conf.xml
exist-core/src/test/resources-filtered/org/exist/storage/statistics/conf.xml
exist-core/src/test/resources-filtered/org/exist/xquery/functions/transform/conf.xml
extensions/indexes/lucene/src/test/resources-filtered/conf.xml
extensions/indexes/ngram/src/test/resources-filtered/conf.xml
extensions/indexes/range/src/test/resources-filtered/conf.xml
extensions/indexes/sort/src/test/resources-filtered/conf.xml
extensions/indexes/spatial/src/test/resources-filtered/conf.xml

The use of Path Locks for Documents has always been experimental. However, some issues have been reported when they are enabled by advanced users. This PR addresses those issues.
**NOTE:** I have tested this by running the full test-suite for eXist-db with `<document use-path-locks="false"/>` and then again with `<document use-path-locks="true"/>` set in `conf.xml`. All tests pass :-)

Fix NPE and Deadlock when Path Locks are used for Documents

---

exist-core/src/main/antlr/org/exist/xquery/parser/XQuery.g
exist-core/src/main/antlr/org/exist/xquery/parser/XQueryTree.g
exist-core/src/main/java/org/exist/xquery/ContextItemExpression.java
exist-core/src/main/java/org/exist/xquery/ValueComparison.java
exist-core/src/test/xquery/xquery3/bang.xql
exist-core/src/test/xquery/xquery3/filter-function-items-in-context.xql

Enable function items (functions, arrays, maps) to be used as values of the context item `.`
The map expression status applies to arrays as well
Unary lookup statements are not part of this PR but tracked in #1655
- `(map{"a":2}, map{"a":1})[?a > 1]` returns `map{"a":2}`
- `([1, 2], [2, 4])[?1 > 1]` returns `[2, 4]`
- `(map { 'key': 'value' }, map { 'key': 'other' }) ! ?key` returns `('value', 'other')`
fixes #3240 
XQsuite tests added

allow function types in context item

---

exist-core/src/main/resources/org/exist/xquery/lib/test.xq
exist-core/src/main/resources/org/exist/xquery/lib/xqsuite/xqsuite.xql

Pass on the original location and error when evaluating user-specified XPaths within the XQSuite.

Preserve original error message when using util:eval

---

exist-core/src/main/antlr/org/exist/xquery/parser/XQuery.g
exist-core/src/main/antlr/org/exist/xquery/parser/XQueryTree.g
exist-core/src/main/java/org/exist/xquery/EnclosedExpr.java
exist-core/src/main/java/org/exist/xquery/SequenceConstructor.java
exist-core/src/test/java/org/exist/xquery/FunctionTypeInElementContent.java
exist-core/src/test/java/org/exist/xquery/FunctionTypeInElementContentTest.java
exist-core/src/test/xquery/errors.xql

The queries below are all invalid because the element content contains expressions which will evaluate to function types. The error is thrown a) at run-time and b) without location information (line and column number).
```xquery
element foo { sum(?) },
element foo { map{} },
```
This PR fixes the XQuery parser so that location information is given when an error is raised and also checks each expression if the return type is known to be a function type at compilation time.
- Add `path` to XPathException thrown in EnclosedExpr (for dynamic errors, works only if location is preserved during compilation)
- Add method `addPathIfNotFunction` to SequenceConstructor to add a static type check for each path before it is added. Throws if a function type (map, array, function, partial ...) is found. …

[hotfix] add location info to element content errors

---

exist-core/src/main/java/org/exist/http/servlets/BasicAuthenticator.java

A common authentication strategy is the bearer token authentication.
- The client sends `Authorization: Bearer [bearer-token]` to the server
- The server processes the Authorization header contents
At the moment, exist-db throws an error with that header. 
The BasicAuthenticator class treats any Authorization header as a basic authentication attempt, regardless of the scheme (`Basic`, `Bearer`, ...).
This PR changes BasicAuthenticator to also check if the header value starts with `Basic` before attempting to authenticate using the Basic Authentication strategy.

[fix] basic authentication

---

exist-core/src/main/java/org/exist/xquery/functions/array/ArrayFunction.java
exist-core/src/test/xquery/arrays/arrays.xql

reimplement two missing Remove usecases; Found in XQTS. Added tests:
```xquery
declare
%test:assertEmpty
%test:assertEquals("a", "b", "c", "d")
function arr:remove3() {
array:remove(["a", "b", "c", "d"], ())?*
};
declare
%test:assertEquals("b", "d")
function arr:remove4() {
array:remove(["a", "b", "c", "d", "e"], (3,1,5))?*
};
```

[Bugfix] Array: extend remove() function to allow multiple deletes in one go. (XQTS)

---

exist-core/src/main/java/org/exist/xquery/functions/fn/FunUnparsedText.java
exist-core/src/main/java/org/exist/xquery/functions/fn/FunXmlToJson.java
exist-core/src/test/java/org/exist/xquery/functions/fn/FunUnparsedTextTest.java
exist-core/src/test/xquery/xquery3/xml-to-json.xql

A misc set of XQTS indicated fixes
- unparsed-text-lines: Gracefully handle situation where URL resource does not return any data (NPE avoidance)
- fn-xml-to-json: Fix to handle wrong formatted 'number' argument, Fixes xml-to-json-041

(Bugfix) misc XQTS reported issues

---

exist-distribution/src/main/config/conf.xml
schema/conf.xsd

Several changes were made to conf.xml in the commit below. This PR brings the conf.xml XSD into line with these changes. To help the instance stay aligned with the schema, this updates the schema location to point to the current (post-mavenization) location.
https://github.com/eXist-db/exist/commit/e1538307b3868b8280b92017c940f3a0070b4776#diff-145364ddf4d436154dde2de26ccc629285e6d349ba253bf1c657c3ecd8ee890c
n/a

Update conf.xml XSD to latest conf.xml changes; fix location

---

exist-core/pom.xml
exist-core/src/main/java/org/exist/LifeCycle.java
exist-core/src/main/java/org/exist/dom/persistent/SymbolTable.java
exist-core/src/main/java/org/exist/indexing/IndexManager.java
exist-core/src/main/java/org/exist/plugin/Plug.java
exist-core/src/main/java/org/exist/plugin/PluginsManagerImpl.java
exist-core/src/main/java/org/exist/storage/BrokerPool.java
exist-core/src/main/java/org/exist/storage/BrokerPoolService.java
exist-core/src/main/java/org/exist/storage/BrokerPoolServicesManager.java
exist-core/src/main/java/org/exist/storage/SystemTaskManager.java
exist-core/src/main/java/org/exist/storage/journal/Journal.java
exist-core/src/test/java/org/exist/storage/BrokerPoolServiceTest.java

Improves the API of BrokerPool Service to add additional life-cycle functions for starting and stopping Broker Pool services.
1. `BrokerPoolService#startPreSystem`
Permits activities that need to happen before the database enters system (single-user) mode during startup.
2. `BrokerPoolService#stopMultiUser`
Permits activities that need to happen before the database exits multi-user mode during shutdown.
NOTE: Even though this is an internal API, I have taken care to ensure that it is backwards compatible.

Broker pool service api

---

exist-distribution/pom.xml

This was removed by accident in https://github.com/eXist-db/exist/commit/0cb91e913467fb240d2d92901d26787ec4cc4778#diff-cdb817f2816641803dc3213d102cb5e244562e20f39fe7b0d939270306860172L729

Reinstate fix for output directory

---

exist-ant/src/test/resources-filtered/conf.xml
exist-core/src/main/java/org/exist/storage/XQueryPool.java
exist-core/src/main/java/org/exist/util/Configuration.java
exist-core/src/test/resources-filtered/conf.xml
exist-core/src/test/resources-filtered/org/exist/storage/statistics/conf.xml
exist-core/src/test/resources-filtered/org/exist/xquery/functions/transform/conf.xml
exist-distribution/src/main/config/conf.xml
extensions/contentextraction/src/test/resources-filtered/conf.xml
extensions/debuggee/src/test/resources-filtered/conf.xml
extensions/expath/src/test/resources-filtered/conf.xml
extensions/exquery/restxq/src/test/resources-filtered/conf.xml
extensions/indexes/lucene/src/test/resources-filtered/conf.xml
extensions/indexes/ngram/src/test/resources-filtered/conf.xml
extensions/indexes/range/src/test/resources-filtered/conf.xml
extensions/indexes/sort/src/test/resources-filtered/conf.xml
extensions/indexes/spatial/src/test/resources-filtered/conf.xml
extensions/modules/cache/src/test/resources-filtered/conf.xml
extensions/modules/compression/src/test/resources-filtered/conf.xml
extensions/modules/counter/src/test/resources-filtered/conf.xml
extensions/modules/expathrepo/src/test/resources-filtered/conf.xml
extensions/modules/file/src/test/resources-filtered/conf.xml
extensions/modules/persistentlogin/src/test/resources-filtered/conf.xml
extensions/modules/sql/src/test/resources-filtered/conf.xml
extensions/modules/xslfo/src/test/resources-filtered/conf.xml
extensions/xqdoc/src/test/resources-filtered/conf.xml
schema/conf.xsd

Backported from FusionDB
Closes https://github.com/eXist-db/exist/issues/3720

Remove timeout on Compiled XQuery Pool

---

exist-core/src/main/java/org/exist/backup/BackupDescriptor.java
exist-core/src/main/java/org/exist/backup/BackupDirectory.java
exist-core/src/main/java/org/exist/backup/ExportMain.java
exist-core/src/main/java/org/exist/backup/FileSystemBackupDescriptor.java
exist-core/src/main/java/org/exist/backup/Restore.java
exist-core/src/main/java/org/exist/backup/ZipArchiveBackupDescriptor.java
exist-core/src/main/java/org/exist/backup/restore/RestoreHandler.java
exist-core/src/main/java/org/exist/security/AbstractRealm.java
exist-core/src/main/java/org/exist/security/internal/SecurityManagerImpl.java
exist-core/src/test/java/org/exist/backup/XMLDBRestoreTest.java
exist-distribution/pom.xml

Closes https://github.com/eXist-db/exist/issues/3650
It absolutely blows my mind that until today only 2 people have recently reported this but yet the problem has been around for quite some time (at least 5.1.1 if not before). I wonder if anyone else is doing backups/restores of their databases?!?
---
This PR provides a fix that **only** addresses the problem for those users that restore full or incremental backups of the entire database, i.e. starting from `/db`.
Any partial restore that starts from `/db/system` or below and includes the users and groups will still not correctly load the groups before the users. Unfortunately solving such a thing with the current approach of the restore code is impossible, and the restore system itself needs rewriting to take a different approach. As …

Group membership is not correct immediately after restoring a backup

---

.github/workflows/build.yml

Enhances the github build action to do a matrix build using linux/mac/windows for the JDK version 8 & 11

Creates a build matrix on github actions

---

.github/workflows/sonarcloud.yml
exist-core/src/main/java/org/exist/xquery/functions/inspect/InspectFunction.java
exist-core/src/main/java/org/exist/xquery/functions/inspect/InspectModule.java
exist-core/src/main/java/org/exist/xquery/functions/inspect/ModuleFunctions.java
exist-parent/pom.xml

Fixes the SonarCloud integration with GitHub Actions.
**NOTE**: Previously SonarCloud Automated Analysis, and Manual Analysis (i.e. via CI) were enabled. You can only use one. Automated Analysis is not supported for Java projects, and so I disabled that in the SonarCloud dashboard. I believe it was the automated analysis that was previously (incorrectly) reporting 100% green for everything.

Fix GitHub Actions for SonarCloud

---

exist-core/src/main/java/org/exist/xquery/functions/system/GetRunningJobs.java

Fixes a simple typo in the error message of `system:get-running-jobs()`. 
(The original error message appears to have been copied and pasted from https://github.com/eXist-db/exist/blob/develop/exist-core/src/main/java/org/exist/xquery/functions/system/GetRunningXQueries.java#L74.)
n/a
n/a

Fix typo in error message for system:get-running-jobs

---

exist-core/src/main/java/org/exist/xquery/value/Type.java

Regression was caused by f69628d
With this the XQTS output is:

Fix a regression in finding the roots of the type hierarchy

---

exist-core/src/main/java/org/exist/xquery/LocationStep.java
exist-core/src/test/xquery/fn-position.xqm

```query
<a><b/></a>/b[true()]/position()
```
should return 1
With this PR applied it does.
fixes #3737
XQSuite tests in fn-position.xqm

[fix] fn:position() off-by-one after any predicate 

---

.github/workflows/ci.yml

Previously when a Docker Image was needed (i.e. a commit to `develop` or `merge`) eXist-db would be built twice during the workflow. This should remove that duplication, which means both less chance of failures, and less build minutes consumed.

Speed up CI when Docker Images are built

---

exist-core/src/main/java/org/exist/xquery/LetExpr.java
exist-core/src/main/java/org/exist/xquery/value/SequenceType.java
exist-core/src/test/xquery/errors.xql

Fixed #3628 
the query
```xquery
let $test as element(b)? := <a c="2"><d/></a> return $test
```
returns now
```
err:XPTY0004 Invalid type for variable $test. Expected element(b)?, got element(a)
```

Fix incomplete type error reporting

---

exist-core/src/main/java/org/exist/xquery/Predicate.java
exist-core/src/test/xquery/positional.xql

If the inner sequence in a predicate evaluates to an empty sequence, an empty sequence is returned.
fixes #3797
Saxon 10 HE and BaseX 9.5 as well as eXist-db versions > 5.3.0-SNAPSHOT all have this behaviour.
@dizzzz showed in #3800 a nicer condition with `Sequence#isEmpty` so I incorporated that.
Several tests added to positional.xql XQSuite

[bugfix] NPE on predicates with an empty sequence

---

extensions/indexes/spatial/pom.xml

The updated library `org.hsqldb:hsqldb` version 2.6.0 does require a later than JDK 8

Revert Merge pull request #3815

---

.github/workflows/ci-test.yml
README.md
exist-core/pom.xml
exist-parent/pom.xml
extensions/debuggee/pom.xml
extensions/modules/file/pom.xml
extensions/modules/persistentlogin/pom.xml

Adds support for Code Coverage reports with JaCoCo and also integrates Travis with Coveralls.io to report historical use/change of Code Coverage.
**NOTE**: There is a bug that this surfaces that we need to fix - https://github.com/jacoco/jacoco/issues/1042

Add Code Coverage

---

README.md

Switch downloads/releases URLs in the README from Bintray to GitHub Releases
https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/
n/a

Replace Bintray URLs with GitHub Releases

---

exist-core/pom.xml
exist-core/src/main/java/org/exist/xquery/modules/ModuleUtils.java
exist-distribution/src/main/config/conf.xml
extensions/modules/sql/pom.xml
extensions/modules/sql/src/main/java/org/exist/xquery/modules/sql/GetConnectionFunction.java
extensions/modules/sql/src/main/java/org/exist/xquery/modules/sql/SQLModule.java
extensions/modules/sql/src/test/java/org/exist/xquery/modules/sql/ConnectionIT.java
extensions/modules/sql/src/test/resources-filtered/conf.xml

This feature is backported from FusionDB to eXist-db at the request of @PieterLamers
It allows connection pools to be established via eXist-db's conf.xml for the SQL Module. The connections can then be obtained via `sql:get-connection-from-pool`.

Connection Pooling for SQL Module

---

exist-core/src/main/java/org/exist/xquery/CastExpression.java

Previous to this change, this pattern was flagged as a memory-use issue by several analysis tools.

Remove object retained by inner-class via back-reference

---

exist-distribution/src/main/config/conf.xml
extensions/modules/cache/pom.xml
extensions/modules/cache/src/main/java/org/exist/xquery/modules/cache/CacheConfig.java
extensions/modules/cache/src/main/java/org/exist/xquery/modules/cache/CacheFunctions.java
extensions/modules/cache/src/main/java/org/exist/xquery/modules/cache/CacheModule.java
extensions/modules/cache/src/test/resources-filtered/conf.xml

Previously Caches for use with the XQuery Cache Module in eXist-db could be created on-demand when the cache was first operated on. When such a cache was lazily created it had no bounds on its size, meaning that it could grow without limit until consuming all memory and causing an OutOfMemoryError.
This PR:
1. Adds configurable bounds for lazily created caches via `conf.xml`
2. Adds a sensible default bounds to `conf.xml` for lazily created caches.
3. Adds an option to disable lazily created caches entirely. I would generally recommend using this in any serious application.
4. Adds further options for configuring security aspects of lazily created caches via `conf.xml`
NOTE: That before this PR, several DoS attacks against eXist-db were possible by misusing the cache either …

Lazily created caches should be bounded

---

exist-core/src/main/java/org/exist/xquery/modules/ModuleUtils.java
extensions/modules/mail/src/main/java/org/exist/xquery/modules/mail/MailModule.java
extensions/modules/sql/pom.xml
extensions/modules/sql/src/main/java/org/exist/xquery/modules/sql/CloseConnectionFunction.java
extensions/modules/sql/src/main/java/org/exist/xquery/modules/sql/GetConnectionFunction.java
extensions/modules/sql/src/main/java/org/exist/xquery/modules/sql/SQLModule.java
extensions/modules/sql/src/test/java/org/exist/xquery/modules/sql/ConnectionIT.java
extensions/modules/sql/src/test/java/org/exist/xquery/modules/sql/ConnectionPoolIT.java
extensions/modules/sql/src/test/java/org/exist/xquery/modules/sql/H2DatabaseResource.java
extensions/modules/sql/src/test/java/org/exist/xquery/modules/sql/Util.java
extensions/modules/sql/src/test/resources-filtered/conf.xml

Allows the user to explicitly close (or return to a pool) a SQL connection before the XQuery completes, this is useful when working with Connection pools.

Backport of sql:close-connection from FusionDB

---

.github/workflows/ci-test.yml

It's easy when you know how ;-)
I expect this to fail in the PR for the GitHub Action `(JDK 8 / ubuntu-latest) Test`, as it won't be able to access the secrets. I have tested this change in a different project, and once merged it did work there.

Specify the COVERALLS_TOKEN in the correct way for CI

---

.github/workflows/ci-test.yml

The settings we have here work perfectly well in other repositories I have setup with GitHub actions. At the moment I am at a complete loss as to explain why they don't work in this repository. As a last-ditch attempt, I am trying to set some additional env variables, see: https://github.com/trautonen/coveralls-maven-plugin/issues/136

Further attempt to get Coveralls plugin working

---

extensions/modules/expathrepo/src/main/java/org/exist/xquery/modules/expathrepo/GetResource.java

`repo:get-resource` now throws an XPathException if the resource does not exist
https://github.com/eXist-db/exist/issues/3895
none

[bugfix] throw error in `repo:get-resource` if file does not exist

---

exist-core/src/main/java/org/exist/storage/NativeBroker.java
exist-core/src/test/xquery/guest.xql

fixes #3505 
added tests @joewiz

[bugfix] Block creation of collection by guest  #3505

---

exist-core/pom.xml
exist-core/src/main/java/org/exist/xquery/XQueryContext.java
exist-core/src/test/java/org/exist/xquery/XQueryContextAttributesTest.java
extensions/modules/sql/pom.xml
extensions/modules/sql/src/main/java/org/exist/xquery/modules/sql/CloseConnectionFunction.java
extensions/modules/sql/src/main/java/org/exist/xquery/modules/sql/ExecuteFunction.java
extensions/modules/sql/src/main/java/org/exist/xquery/modules/sql/GetConnectionFunction.java
extensions/modules/sql/src/main/java/org/exist/xquery/modules/sql/GetJNDIConnectionFunction.java
extensions/modules/sql/src/main/java/org/exist/xquery/modules/sql/PrepareFunction.java
extensions/modules/sql/src/main/java/org/exist/xquery/modules/sql/SQLModule.java
extensions/modules/sql/src/main/java/org/exist/xquery/modules/sql/SQLUtils.java
extensions/modules/sql/src/test/java/org/exist/xquery/modules/sql/ConnectionIT.java
extensions/modules/sql/src/test/java/org/exist/xquery/modules/sql/ConnectionPoolIT.java
extensions/modules/sql/src/test/java/org/exist/xquery/modules/sql/ImplicitConnectionCloseIT.java
extensions/modules/sql/src/test/java/org/exist/xquery/modules/sql/JndiConnectionIT.java

Closes https://github.com/eXist-db/exist/issues/3889
Previously Library Modules were reset with the wrong context, i.e. they were provided with the Main Module's context and not the Library Module's Context.
This meant that not all resources stored in context variables were correctly cleaned up, therefore leaking resources and memory. In addition *reset* was previously called more than once for the same module which was unnecessary; therefore we should also see a small performance improvement from this fix.
Many thanks to @xatapult and @pieterlamers for their patience in reporting this and helping to track down the issue.
As a result all SQL Connections should now also be correctly and implicitly closed when a query finishes execution.

Cleanup all module contexts

---

.github/workflows/ci-build.yml
.github/workflows/ci-docs.yml
.github/workflows/ci-test.yml

Drop J15, build and test on J16. Failures will not impact the overall result if they occur on J16 (yet). 
Build javadocs on J11 and J16 both are failing, ignore all failures of doc building, we still get the news of whats wrong.
I dropped J8 from the docs, as these haven't been deployed anywhere from what i could tell, correct me if i m wrong. 
supsersedes #3840

fix(ci): add J16 and allow failures

---

exist-distribution/pom.xml

- remove **markdown** and **shared** package
there is no longer a bundle app that depends on it
- add new dependency to **templating** library module used by most of
the bundled application packages

[feat] change packages bundled with existdb

---

exist-installer/src/main/izpack/install.xml
extensions/modules/expathrepo/src/test/xquery/modules/expathrepo/deployment.xql

apparently #3939 was not setting the new dependencies at two crucial locations

[hotfix] include templating in installer and tests

---

exist-distribution/pom.xml
exist-installer/pom.xml
exist-parent/pom.xml
exist-versioning-release.md

Replaces bintray mvn plugin with github-release-plugin by de.jutzig
To create a draft release call: `mvn -DskipTests -Dgithub.draft=true github-release:release` in $EXIST/exist-distribution or $EXIST/exist-installer. 
The plugin is configured to be executed in the maven "deploy" phase which will be process during `mvn release:perform`.
Documentation has been added to https://github.com/eXist-db/exist/blob/develop/exist-versioning-release.md (see changed files). 
* https://github.com/jutzig/github-release-plugin
* none
Missing tests. The plugin has been tested on other repositories and has successfully worked for eXist-db documentation (https://github.com/eXist-db/documentation/blob/master/pom.xml). **But** I have not setup a test env to check if this will really work on the first try. …

[feature] switched releasing via mvn from bintray to github-releases

---

exist-docker/pom.xml

Revert the pom.xml of exist-docker to its state before the botched release.
`mvn release:rollback` did not catch it.

[hotfix] fix docker pom (manual rollback)

---

exist-distribution/pom.xml
exist-installer/pom.xml

This stoped the github-release-plugin trying to publish `SNAPSHOT`s to GitHub Releases. This should fix the problem with the Nightly Builds service.

Only run the github-release-plugin when mvn release:perform is performed

---

exist-start/pom.xml
exist-start/src/main/java/org/exist/start/CompatibleJavaVersionCheck.java
exist-start/src/test/java/org/exist/start/CompatibleJavaVersionCheckTest.java

Previously only major versions were checked, however @StephanMa pointed out that the JDK issue that eXist-db suffers from is now fixed in 15.0.2.
JDK 15.0.2 should now pass the checks.
See https://github.com/eXist-db/exist/issues/3375

Make the Compatible Java Version Check more fine-grained

---

exist-ant/pom.xml
exist-core/pom.xml
exist-core/src/test/java/org/exist/test/runner/AbstractTestRunnerTest.java
exist-core/src/test/java/org/exist/test/runner/XMLTestRunnerTest.java
exist-core/src/test/java/org/exist/test/runner/XQueryTestRunnerTest.java
exist-parent/pom.xml
extensions/contentextraction/pom.xml
extensions/debuggee/pom.xml
extensions/expath/pom.xml
extensions/exquery/restxq/pom.xml
extensions/indexes/lucene/pom.xml
extensions/indexes/ngram/pom.xml
extensions/indexes/range/pom.xml
extensions/indexes/sort/pom.xml
extensions/indexes/spatial/pom.xml
extensions/modules/cache/pom.xml
extensions/modules/compression/pom.xml
extensions/modules/counter/pom.xml
extensions/modules/expathrepo/pom.xml
extensions/modules/file/pom.xml
extensions/modules/sql/pom.xml
extensions/modules/xslfo/pom.xml
extensions/security/activedirectory/pom.xml
extensions/security/ldap/pom.xml
extensions/xqdoc/pom.xml

Implements the  #3321 feature.

Adds JUnit 5 test support

---

exist-core/pom.xml
exist-core/src/test/java/org/exist/xquery/value/BifurcanMapTest.java
exist-core/src/test/xquery/maps/MapsLookup.xml
exist-core/src/test/xquery/maps/maps.xql

Closes https://github.com/eXist-db/exist/pull/3725
This contains just the test improvements from https://github.com/eXist-db/exist/pull/3738.
After this is merged we can rebase https://github.com/eXist-db/exist/pull/3738 and decide if we want to extract `map:merge#2` without changing implicit map:merge ordering for 5.x.x too...

Further Map Immutability Tests

---

exist-core/src/main/java/org/exist/xquery/DefaultExpressionVisitor.java
exist-core/src/main/java/org/exist/xquery/LocationStep.java
exist-core/src/main/java/org/exist/xquery/Optimizer.java
exist-core/src/main/java/org/exist/xquery/Step.java
exist-core/src/main/java/org/exist/xquery/pragmas/Optimize.java
exist-core/src/test/java/org/exist/xquery/LocationStepTest.java
extensions/indexes/range/src/main/java/org/exist/xquery/modules/range/OptimizeFieldPragma.java
extensions/indexes/range/src/main/java/org/exist/xquery/modules/range/RangeQueryRewriter.java

* Removes unnecessary use of `CopyOnWriteArrayList` in code that is non-concurrent
* Optimised for the case where there are no or very few predicates on each step - which is typical in XQuery!
* Uses zero memory to store predicates when there are no predicates on a path step
* Reduces unnecessary processing per step

Simplify storage of predicates for a step

---

exist-core/src/main/java/org/exist/xquery/functions/map/MapFunction.java
exist-core/src/main/java/org/exist/xquery/functions/map/MapModule.java
exist-core/src/test/xquery/maps/maps.xql

This takes just the map:merge#2 function from https://github.com/eXist-db/exist/pull/3738 but preserves the incorrect behaviour of eXist-db choosing the Merge Last strategy (whereas the spec says the stratergy should be Merge First).
This is suitable for inclusion in 5.x.x.

Implement map:merge#2

---

exist-core/src/main/java/org/exist/source/DBSource.java

Fixes #4009 by skip access check in case of `validate(int)` method called and no subject is available on the broker instance. In case of calling the method `validate(Subject, int)` without valid subject will lead to a `PermissionDeniedException`
Signed-off-by: Patrick Reinhart <patrick@reini.net>

[fix] NoOp validate() if subject is unavailable

---

exist-core/src/main/antlr/org/exist/xquery/parser/XQuery.g
exist-core/src/main/java/org/exist/xquery/Lookup.java
exist-core/src/main/java/org/exist/xquery/functions/map/MapExpr.java
exist-core/src/test/xquery/maps/mapsLookup.xql
exist-core/src/test/xquery/xquery3/bang.xql

Allow unary lookups in function calls, (anywhere) in predicates and after the simple map operator.
The XQuery grammar now
- wraps unary lookups in a parenthesised expression that is removed in the optimisation phase
- function argument recognises a unary lookup first before attempting to match argument placeholder (`?`)
Examples:
```xquery
([1, 2], ["a", "b"]) ! string-join(?*, "|")
```
```xquery
(map{1: 1}, map{1: 3}, map{1: 2})[1 > ?1] ! ?1
```
**Additional change:** correct the syntax of a dumped map expression to use current syntax.
For the second example that produces:
```
DEBUG (XQuery.java [compile]:143) - Query diagnostics:
(
map {1 : 1}, map {1 : 3}, map {1 : 2}
) [1 > ?1] ! ?1
```
fixes #1655 
fixes #3491 
Relevant XQuery 3.1 specification: [3.11.3.1 Unary …

[fix] unary lookups

---

exist-core/src/main/java/org/exist/dom/memtree/DocumentImpl.java
exist-core/src/main/java/org/exist/dom/memtree/ElementImpl.java
exist-core/src/main/java/org/exist/dom/memtree/MemTreeBuilder.java
exist-core/src/test/java/org/exist/dom/memtree/DocumentImplTest.java
exist-core/src/test/java/org/exist/dom/memtree/MemtreeTest.java

Previously it was impossible to get all child nodes of the document.
This PR also adds a lot of tests for the memtree aspect.

Small fixes to in-memory DOM

---

exist-docker/src/main/resources-filtered/Dockerfile

close #4027
deb package was renamed https://packages.debian.org/stretch/ttf-dejavu-core 
restores old functionality, `deploy.yml` on CI should run without errors again.

fix(Docker): rename dejavu font package

---

exist-parent/pom.xml

We are kindly offering this service to the eXist-db community.
This should help with builds in CI that get errors due to the dependency-check-plugin exhausting the GitHub quota for access to nvd.nist.gov.

Switch to Evolved Binary's mirror of nvd.nist.gov

---

exist-core/src/main/java/org/exist/storage/serializers/NativeSerializer.java
exist-core/src/main/java/org/exist/storage/serializers/Serializer.java
exist-core/src/main/java/org/exist/xquery/util/SerializerUtils.java
exist-core/src/test/xquery/xquery3/serialize.xql
extensions/indexes/lucene/src/test/xquery/lucene/serialize.xql

Implementation of eXist-specific serialization parameters 
Closes https://github.com/eXist-db/exist/issues/2394
Documentation https://github.com/eXist-db/documentation/pull/672
You can now directly apply the serialization parameter using `fn:serialize`
```xquery
fn:serialize($node, map { xs:QName("exist:expand-xincludes") : false() })
```

Add eXist specific serialization options to fn:serialize

---

exist-core/src/main/antlr/org/exist/xquery/parser/XQuery.g
exist-core/src/test/xquery/xquery3/empty-direct-constructor.xqm

Allow empty expressions in both direct element and attribute constructors.
Example:
```xquery
<el
at="{ (: empty attribute constructor :) }">
{ (: empty element constructor :) }
</el>
```
fixes #4088
XQSuite tests included

[bugfix] allow empty enclosed expressions

---

exist-core/src/test/java/org/exist/storage/lock/CollectionLocksTest.java

Increase time out again in order to to the slower windows CI agents to complete.
This PR is precondition for #4095 to pass,

[test] Increase timeout again for slower CI VMs

---

exist-core/src/main/java/org/exist/webstart/JnlpServlet.java
exist-parent/pom.xml

Update the aspectj library to version 1.9.8-M1
Fix compatibility by providing Typehints in JnlpServlet.java

[upgrade] switch to aspectj version 1.9.8-M1

---

exist-versioning-release.md

Updates the documentation to account for changes in Homebrew, including the deeper integration of Caskroom into Homebrew (now "Homebrew Cask"), the deprecation of the `brew cask` commands [in Homebrew 2.6.0](https://brew.sh/2020/12/01/homebrew-2.6.0/), the [deprecation of the old `cask-repair` utility](https://github.com/vitorgalvao/tiny-scripts/commit/09b68e4d83fa56e3a22f127f18f18f7816ccd548#diff-47b6313694b8a6f736f1a394498f41d0a0088b1ddf3277b1758d2bf7385e043f), and the creation of the new standard `brew bump-cask-pr` utility recommended in [Homebrew Cask's CONTRIBUTING directions](https://github.com/Homebrew/homebrew-cask/blob/master/CONTRIBUTING.md).
Closes https://github.com/eXist-db/exist/issues/4118
n/a

Update Homebrew release directions

---

exist-ant/pom.xml
exist-core/pom.xml
exist-parent/pom.xml
extensions/contentextraction/pom.xml
extensions/expath/pom.xml
extensions/exquery/restxq/pom.xml
extensions/indexes/lucene/pom.xml
extensions/indexes/ngram/pom.xml
extensions/indexes/range/pom.xml
extensions/indexes/sort/pom.xml
extensions/indexes/spatial/pom.xml
extensions/modules/cache/pom.xml
extensions/modules/compression/pom.xml
extensions/modules/counter/pom.xml
extensions/modules/expathrepo/pom.xml
extensions/modules/file/pom.xml
extensions/modules/sql/pom.xml
extensions/modules/xslfo/pom.xml
extensions/security/activedirectory/pom.xml
extensions/security/ldap/pom.xml
extensions/xqdoc/pom.xml

Previously there was a dependency on `junit-jupiter-api`, but we instead need  `junit-vintage-engine` on the classpath to run the tests with JUnit5.

Run JUnit 4 tests via JUnit 5

---

exist-core/src/main/java/org/exist/storage/NativeValueIndex.java
exist-core/src/test/java/org/exist/storage/NativeValueIndexTest.java

Previously eXist-db would log lots of errors when indexing empty strings as integers, e.g.:
```
ERROR (NativeValueIndex.java [convertToAtomic]:1051) - Node value '' cannot be converted to xs:integer - which implies the Node was empty!
```
This PR changes the behaviour so that if a Node is empty, i.e. there is no value, then the NativeValueIndex will simply ignore it.
However, if the Node has a non-empty value that cannot be converted to an integer, then the error is instead now logged as a warning.
Thanks to @joewiz who reported the error to me.

Don't attempt an impossible conversion in NativeValueIndex

---

exist-core/src/main/java/org/exist/dom/memtree/MemTreeBuilder.java
exist-core/src/main/java/org/exist/xmldb/LocalXMLResource.java
exist-core/src/main/java/org/exist/xquery/functions/util/Expand.java
exist-core/src/test/java/org/exist/xquery/functions/util/ExpandTest.java
exist-core/src/test/xquery/serialization.xml
exist-core/src/test/xquery/util/expand.xqm

Previously `util:expand` did not handle Document or AttributeNodes correctly.
Closes https://github.com/eXist-db/exist/issues/1562
Closes https://github.com/eXist-db/exist/issues/1486
For Document Nodes instead it would just return the first node from the document. If the first node was an element, you likely would not have noticed a problem (as it is a container of child nodes), however if the first node was a comment, text node, or processing instruction, then you would not see any of the other descendant nodes of the document.
For example, previously:
```xquery
let $doc1 := document { <doc2>doc2</doc2> }
let $doc1-uri := xmldb:store("/db", "doc1.xml", $doc1, "application/xml")
return
util:expand(doc($doc1-uri))
```
would incorrectly return only the first node in the document, i.e.: …

util:expand must handle Document and Attribute Nodes correctly

---

exist-core/src/main/java/org/exist/dom/memtree/DocumentImpl.java
exist-core/src/main/java/org/exist/xquery/functions/fn/FunGenerateId.java
exist-core/src/test/java/xquery/xquery3/XQuery3Tests.java
exist-core/src/test/xquery/xquery3/generate-id.xqm

Closes https://github.com/eXist-db/exist/issues/4150

fn:generate-id must provide unique IDs for unique Nodes

---

exist-core/pom.xml
exist-distribution/pom.xml
exist-distribution/src/app/entitlements.plist
exist-distribution/src/main/scripts/codesign-jansi-mac.sh
exist-parent/pom.xml
exist-versioning-release.md

At the request of @joewiz I have backported from FusionDB to eXist-db the functionality for notarizing the Apple macOS DMG.
Closes https://github.com/eXist-db/exist/issues/3961

Notarize macOS DMG

---

exist-docker/src/main/resources-filtered/Dockerfile

`gcr.io/distroless/java:8` is no longer maintained, which means that it no longer receives updated Java8 patch versions.
As `gcr.io/distroless/java:8` is based on Debian Stretch, we can simply overwrite the JRE in the GCR Docker Image with the latest Java 8 JRE from Debian Stretch which is still receiving updates.

Use the latest JRE 8 in the Docker Image

---

exist-core/src/main/java/org/exist/xquery/LocationStep.java
exist-core/src/test/xquery/axes-persistent-nodes.xqm

existdb handles positional predicates on abbreviated steps differently than other predicates. 
But the check if the special handling was needed also included predicates that filtered (`ExecutionMode.Boolean`), which is the root cause of the issue with following and preceding axes.
fixes #4085
XQSuite provided by @joewiz in exist-core/src/test/xquery/axes-persistent-nodes.xqm

fix following/preceding axes after predicate on abbreviated step

---

exist-core/src/main/java/org/exist/storage/blob/BlobStoreImpl.java
exist-core/src/main/java/org/exist/storage/journal/Journal.java
exist-core/src/main/java/org/exist/storage/journal/JournalManager.java
exist-core/src/main/java/org/exist/storage/journal/JournalReader.java
exist-core/src/main/java/org/exist/storage/recovery/RecoveryManager.java
exist-core/src/main/java/org/exist/test/runner/XQueryTestRunner.java
exist-core/src/test/java/org/exist/storage/journal/AbstractJournalTest.java
exist-core/src/test/java/org/exist/storage/journal/JournalTest.java

Closes https://github.com/eXist-db/exist/issues/4189
Addresses the following bugs:
1. Previously `Journal#findLastFile(Stream)` would incorrectly find the first file instead of the last file, it now correctly finds the last file.
2. Each Journal file is assigned an increasing number. Previously, if you reached the maximum number of `32767` then eXist-db would throw an exception and stop in an in-consistent state with no ability to move forward. As there is typically only one or two journal files in existence simultaneously, we now simply wrap around to `0` when we exceed `32767`.
3. The Journal and JournalManager had insufficient synchronisation for concurrent operations. This means that eXist-db could potentially produce a corrupt journal. Should a crash occur, eXist-db would either not …

Fix Journal Bugs

---

eXist-db.iml

As 4.x.x uses Ant, unless we remove the GeoSpatial index from the IntelliJ project file, it is not possible to compile eXist-db 4.x.x in IntelliJ after a fresh clone of the code.

[4.x.x] Remove GeoSpatial Index from IntelliJ project

---

exist-core/src/test/java/org/exist/storage/CopyCollectionTest.java
exist-core/src/test/java/org/exist/storage/MoveCollectionTest.java

This is a forward port of the eXist-db 4.x.x tests in https://github.com/eXist-db/exist/pull/4201 to show that the Rename and Move operations identified in eXist-db 4.x.x do not impact 5.x.x.

Test Collection Rename and Move operations

---

exist-core/pom.xml
exist-core/src/main/java/org/exist/xquery/util/SerializerUtils.java
exist-parent/pom.xml
extensions/modules/file/pom.xml
extensions/modules/file/src/main/java/org/exist/xquery/modules/file/Sync.java
extensions/modules/file/src/test/resources/util/fixtures.xqm
extensions/modules/file/src/test/resources/util/helper.xqm
extensions/modules/file/src/test/xquery/modules/file/read-binary.xqm
extensions/modules/file/src/test/xquery/modules/file/serialize.xqm
extensions/modules/file/src/test/xquery/modules/file/sync.xqm
extensions/modules/file/src/test/xquery/modules/file/syncmod.xqm

Improve `file:sync`
The third parameter can now be either an xs:dateTime (kept for backwards compatibility) or a map.
The map has three keys at the moment:
- prune `xs:boolean` flag to control if surplus files on the filesystem should be removed
- exclude `xs:string*` sequence of glob patterns with support of `*`, `?`, `**` placeholders. Files that match will not be removed from disk ~~nor synced to the filesystem~~.
- after `xs:dateTime?` synchronise only files newer than the dateTime provided
Example:
```xquery
file:sync("/db/apps/my-app", "/Users/me/projects/my-app", map {
"after": current-dateTime() - xs:dayTimeDuration("PT1D"), (: changes in the last day :)
"excludes": (".git", ".env"), (: leave local settings and version control untouched  :)
"prune": true() (: remove anything not …
```

Improve file:sync

---

exist-core/pom.xml
exist-core/src/main/java/org/exist/management/TaskStatus.java
exist-core/src/main/java/org/exist/security/internal/aider/ACEAider.java
exist-core/src/main/java/org/exist/xmlrpc/ACEAiderParser.java
exist-core/src/main/java/org/exist/xmlrpc/ACEAiderSerializer.java
exist-core/src/main/java/org/exist/xmlrpc/ExistRpcTypeFactory.java
exist-core/src/main/java/org/exist/xmlrpc/TupleParser.java
exist-parent/pom.xml

Update to Apache XML-RPC with latest Security Patches from Evolved Binary.
Addresses CVE-2019-17570 and CVE-2016-5002
**Note** - This PR changes XML-RPC API (and therefore also the XML:DB remote API).
Previously eXist-db was relying on the in-built Java Serialization for communicating ACL's, unfortunately that facility is inherently insecure. This PR now adds a custom XML-RPC Serializer and Parser for ACLs to ensure this is secure; the upshot is that the wire-protocol has to change to support this. This means users of the XML-RPC and XML:DB APIs (e.g. Java Admin Client, oXygen XML Editor, etc) will need to upgrade their libraries as this is not backwards compatible.
Closes https://github.com/eXist-db/exist/issues/3063

Update Apache XML-RPC

---

exist-core/pom.xml
exist-jetty-config/src/main/resources/org/exist/jetty/etc/jetty-annotations.xml
exist-jetty-config/src/main/resources/org/exist/jetty/etc/standalone.enabled-jetty-configs
exist-jetty-config/src/main/resources/org/exist/jetty/etc/standard.enabled-jetty-configs

Restores jetty-annotations, ~~jetty-jndi, and jetty-plus~~ - libraries that Monex's Remote Console pane requires to be in place.
https://github.com/eXist-db/monex/issues/175#issuecomment-1025252020
None included, but I tested by opening http://localhost:8080/exist/apps/monex/console.html and confirming that Monex's Remote Console now displays, "Connected" - whereas previously it could never connect and instead displayed "Disconnected."

Restore libraries required for Monex's Remote Console pane

---

exist-core/pom.xml
exist-jetty-config/src/main/resources/org/exist/jetty/etc/jetty-annotations.xml
exist-jetty-config/src/main/resources/org/exist/jetty/etc/standalone.enabled-jetty-configs
exist-jetty-config/src/main/resources/org/exist/jetty/etc/standard.enabled-jetty-configs

Port #4215 to 5.x.x
#4215
As mentioned in #4215:
> None included, but I tested by opening http://localhost:8080/exist/apps/monex/console.html and confirming that Monex's Remote Console now displays, "Connected" - whereas previously it could never connect and instead displayed "Disconnected."

(5.x.x) Restore libraries required for Monex's Remote Console pane

---

.github/workflows/sonarcloud.yml

Generates required `jacoco.xml` coverage files used by SonarQube quality reports.

[bugfix] generate required jacoco xml report files

---

exist-ant/pom.xml
exist-core/pom.xml
exist-parent/pom.xml
extensions/expath/pom.xml
extensions/indexes/lucene/pom.xml
extensions/indexes/ngram/pom.xml
extensions/indexes/range/pom.xml
extensions/indexes/sort/pom.xml
extensions/indexes/spatial/pom.xml
extensions/modules/cache/pom.xml
extensions/modules/compression/pom.xml
extensions/modules/counter/pom.xml
extensions/modules/expathrepo/pom.xml
extensions/modules/file/pom.xml
extensions/modules/sql/pom.xml
extensions/modules/xslfo/pom.xml
extensions/security/activedirectory/pom.xml
extensions/security/ldap/pom.xml
extensions/webdav/pom.xml
extensions/xqdoc/pom.xml

Cleans up unused dependency declarations of `junit-vintage-engine` as its defined within the surefire plugin.

[cleanup] removes non used junit-vintage-engine

---

exist-jetty-config/src/main/resources/org/exist/jetty/etc/jetty-http.xml
exist-jetty-config/src/main/resources/org/exist/jetty/etc/jetty-ssl.xml
exist-jetty-config/src/main/resources/org/exist/jetty/etc/standalone-jetty-http.xml
exist-jetty-config/src/main/resources/org/exist/jetty/etc/standalone-jetty-ssl.xml

This unifies handling of jetty variables set via JAVA_OPTS environment variable.
The following jetty Properties can now be set via JAVA_OPTS: [jetty.host, jetty.port, ssl.port, jetty.http.host, jetty.http.port, jetty.ssl.host, jetty.ssl.port].
to clarify: the PR enables e.g. the following inside an existdb home directory
```
$ JAVA_OPTS='-Djetty.host=127.0.0.2 -Djetty.http.port=9999' ./bin/startup.sh
```
or putting the options directly on the java command
```
$ /usr/bin/java ... \
-Djetty.host=127.0.0.2 \
-Djetty.http.port=9999 \
... org.codehaus.mojo.appassembler.booter.AppassemblerBooter
```

Import jetty Properties from SystemProperties

---

extensions/modules/file/src/main/java/org/exist/xquery/modules/file/Sync.java
extensions/modules/file/src/test/xquery/modules/file/sync-serialize.xqm

Pass additional serialization options in the options parameter
to control how XML files are written to disk.
Example:
XML declarations are written to files synchronized to disk. You can overwrite that
by calling
```xquery
file:sync('/db/test', '/my/test/folder', map { "omit-xml-declaration": true()})
```

[feature] allow to set serialization options in file:sync#3

---

.idea/runConfigurations/Java_Admin_Client.xml
.idea/runConfigurations/Jetty_Server.xml

Allows to run Jetty Server and Admin Client from Intellij IDEA
Otherwise it fails with a non-descriptive Error:
```
StatusLogger Reconfiguration failed: No configuration found for '18b4aac2' at 'null' in 'null'
19:09:26.711 [main] ERROR org.exist.jetty.JettyStart - Unable to find configuration file on classpath!
Process finished with exit code 0
```

[fix] IDEA runconfiguration

---

.idea/runConfigurations/Local_Jetty_Server.xml

The run configuration to start the jetty server within the IDEA IDE that ships with eXist-db exposes the server to the local network (by binding to 0.0.0.0).
A new configuration named "Local Jetty Server" is added which only binds to the host IP `127.0.0.1` aka localhost.
This was made possible by #4196, which adds recognition of the option `jetty.host`.
It is absolutely unnecessary to expose a development instance running inside an IDE to the internet in most cases.

[sec] add run configuration for local jetty server

---

exist-core/src/main/java/org/exist/xquery/functions/util/GetNodeById.java
exist-core/src/test/xquery/util/document-id.xqm

Backport of https://github.com/eXist-db/exist/pull/4270
Closes https://github.com/eXist-db/exist/issues/4262

[4.x.x] Fix regression in util:document-id

---

exist-docker/src/main/resources-filtered/Dockerfile

closes #4245
Improves the allocation and use of memory under Docker. This was back-ported from FusionDB where it has been in production for some time.
1. You can use more of the available memory
2. You are unlikely to exceed the available memory under normal operation (which previously resulted in an OutOfMemoryError)

Use newer Java 8 JVM memory options for better Docker compatibility

---

exist-docker/src/main/resources-filtered/Dockerfile

Backport of https://github.com/eXist-db/exist/pull/4281

[5.x.x] Use newer Java 8 JVM memory options for better compatibility with Docker

---

exist-core/src/main/java/org/exist/collections/triggers/XQueryTrigger.java
exist-core/src/main/java/org/exist/security/EffectiveSubject.java
exist-core/src/main/java/org/exist/xquery/LibraryModuleRoot.java
exist-core/src/main/java/org/exist/xquery/XQuery.java
exist-core/src/main/java/org/exist/xquery/functions/securitymanager/IdFunction.java
exist-core/src/test/java/org/exist/collections/triggers/XQueryTriggerSetGidTest.java
exist-core/src/test/java/org/exist/collections/triggers/XQueryTriggerSetUidTest.java
exist-core/src/test/java/org/exist/collections/triggers/XQueryTriggerTest.java
exist-core/src/test/java/org/exist/xquery/functions/securitymanager/IdFunctionTest.java

This fixes a security issue with XQueryTrigger, and also as a nice consequence enables setUid and setGid to be used on XQuery Triggers that are stored as modules in the database.

Fix a security privilege escalation issue with XQueryTrigger

---

exist-core/src/main/java/org/exist/xquery/util/SerializerUtils.java
exist-core/src/test/java/xquery/xquery3/XQuery3Tests.java
exist-core/src/test/xquery/unparsed-text.xql
extensions/modules/file/src/main/java/org/exist/xquery/modules/file/Sync.java
extensions/modules/file/src/test/resources/util/fixtures.xqm
extensions/modules/file/src/test/resources/util/helper.xqm
extensions/modules/file/src/test/xquery/modules/file/sync-serialize.xqm

With this PR applied the file module tests reliably pass. It also sets the correct default encoding `UTF-8` where needed and reinstates the full XQuery3 test suite.
CI tests fail on Windows 
XQSuite

Fix default encoding and file module tests on Windows

---

exist-core-jmh/pom.xml
exist-core-jmh/src/main/java/org/exist/storage/lock/LockTableBenchmark.java
exist-core-jmh/src/main/java/org/exist/xquery/utils/URIUtilsBenchmark.java
exist-core/pom.xml
exist-core/src/main/java/org/exist/xquery/util/URIUtils.java
exist-core/src/test/java/org/exist/xquery/util/URIUtilsTest.java

This optimises the URI Encoding of Path Components in eXist-db, and specifically affects `fn:encode-for-uri`.
Through using the YourKit Java Profiler, we found that a great deal of time in a specific XQuery was unexpectedly taken up by the `fn:encode-for-uri` XQuery function. A quick examination of the code found it to be correct, yet definetly sub-optimal.
By adding JMH Tests for this in `URIUtilsBenchmark.java` we are able to confidently show that before this PR, the throughput of `URIUtils#encodeForURI(String)` (which is used by `fn:encode-for-uri`) was:
```
293623.937 ± 16251.838  ops/s
```
This PR increases the throughput to:
```
2056617.057 ± 56774.934  ops/s
``` 
Overall performance is increased by a factor of `~7x` (or `~600%` if you prefer)!
Such techniques could be applied to …

Optimise URI Encoding of Path Components

---

.github/workflows/ci-test.yml

The caching key is built hashing all pomfiles (as fileHash).
That is in line with the current strategy.
- was : `${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}`
- is  : `setup-java-${{ platform }}-${{ packageManager }}-${{ fileHash }}`
Documentation: https://github.com/actions/setup-java#caching-packages-dependencies

Use builtin maven-cache of setup-java action

---

extensions/modules/xslfo/src/main/java/org/exist/xquery/modules/xslfo/RenderFunction.java

Without this it can be very hard to diagnose when your XSL:FO processor is misconfigured.

Log xsl:fo render errors to exist.log

---

extensions/modules/file/src/main/java/org/exist/xquery/modules/file/Sync.java
extensions/modules/file/src/test/resources/util/fixtures.xqm
extensions/modules/file/src/test/resources/util/helper.xqm
extensions/modules/file/src/test/xquery/modules/file/sync.xqm

- Sync.saveFile checks for modification of resource in a more readable and
safer way while also returning even earlier than before
- add test that runs file:sync twice and ensures nothing is written to disk
- add test with multiple exclude patterns
- fix expectation in tests that were false positives before,
due to the issue in helper:assert-sync-result
- fix and enhance helper:assert-sync-result to
- throw when empty sequence is expected but something was returned
- add label to each test so that it is clear where the error occurred
- helper:create-db-resource does not set modified time (is unnecessary)
- $fixtures:mod-date is now equal to current time
Fixes #4321
XQSuite

[bugfix] file:sync#3 updates only changed files

---

exist-core/src/main/java/org/exist/xquery/functions/request/GetData.java
exist-core/src/test/java/org/exist/xquery/functions/request/GetDataTest.java

Backport of https://github.com/eXist-db/exist/pull/4337

[5.x.x] request:get-data#0 should support Chunked Transfer Encoding

---

exist-core/src/main/java/org/exist/resolver/ResolverFactory.java

This was missing from https://github.com/eXist-db/exist/pull/4328 and fixes the Windows test failures.

Fix catalog uris when using Windows Paths

---

exist-parent/pom.xml

Fixes the build, as this was inadvertently missed from https://github.com/eXist-db/exist/pull/4333

License file for exist-xqts distro needs to be excluded from license checks

---

exist-core/src/main/java/org/exist/xquery/XPathException.java
exist-core/src/main/java/org/exist/xquery/functions/xmldb/XMLDBAbstractCollectionManipulator.java
exist-core/src/main/java/org/exist/xquery/functions/xmldb/XMLDBAuthenticate.java
exist-core/src/main/java/org/exist/xquery/functions/xmldb/XMLDBCopy.java
exist-core/src/main/java/org/exist/xquery/functions/xmldb/XMLDBGetMimeType.java
exist-core/src/main/java/org/exist/xquery/functions/xmldb/XMLDBHasLock.java
exist-core/src/main/java/org/exist/xquery/functions/xmldb/XMLDBMove.java
exist-core/src/main/java/org/exist/xquery/functions/xmldb/XMLDBRemove.java
exist-core/src/main/java/org/exist/xquery/functions/xmldb/XMLDBRename.java
exist-core/src/main/java/org/exist/xquery/functions/xmldb/XMLDBSetMimeType.java
exist-core/src/main/java/org/exist/xquery/functions/xmldb/XMLDBSize.java
exist-core/src/main/java/org/exist/xquery/functions/xmldb/XMLDBStore.java

Various functions in the xmldb XQuery extension module internally construct xs:anyURI. Previously, if this construction failed, the error raised in your XQuery would not contain the line-number, column-number, or source. This PR fixes that by capturing the location information and setting it on the XPathException (which is behind the XQuery Error).

Capture xs:anyURI error details in XMLDB Module

---

schema/collection.xconf.xsd

Backport of https://github.com/eXist-db/exist/pull/4362

[5.x.x] Add missing entity-resolver elements to the Schema for collection.xconf

---

extensions/indexes/lucene/src/test/java/org/exist/indexing/lucene/ConcurrencyTest.java

Backport of https://github.com/eXist-db/exist/pull/4369

[4.x.x] Limit the number of hardware threads to a max of 16 in some tests

---

exist-core/src/test/java/org/exist/collections/ConcurrencyTest.java
extensions/indexes/lucene/src/test/java/org/exist/indexing/lucene/ConcurrencyTest.java

Backport of https://github.com/eXist-db/exist/pull/4369

[5.x.x] Limit the number of hardware threads to a max of 16 in some tests

---

exist-core/src/test/java/org/exist/collections/ConcurrencyTest.java
extensions/indexes/lucene/src/test/java/org/exist/indexing/lucene/ConcurrencyTest.java

In these tests I have observed deadlocks on my machine which has 128 hardware threads. We should revisit this later...

Limit the number of hardware threads to a max of 16 in some tests

---

exist-core/src/main/java/org/exist/http/servlets/AbstractExistHttpServlet.java
exist-core/src/main/java/org/exist/http/servlets/BasicAuthenticator.java
exist-core/src/main/java/org/exist/http/urlrewrite/XQueryURLRewrite.java
exist-core/src/test/java/org/exist/http/RESTServiceTest.java

Previously Bearer Authentication was incorrectly intercepted by the `AbstractExistHttpServlet` and/or XQuery Controller (`XQueryURLRewrite`), which made custom handling of Bearer Authentication (e.g. OAuth, JWT, etc.) impossible from XQuery.
It is now possible to work with Bearer Authentication tokens directly in XQuery, so you may implement your own authentication schemes in XQuery if you wish.

Do not override Bearer Authentication with Basic Authentication

---

exist-core/src/main/java/org/exist/http/servlets/XSLTServlet.java
exist-core/src/main/java/org/exist/xquery/functions/transform/Transform.java
exist-core/src/main/java/org/exist/xslt/XSLTErrorsListener.java

Previously errors that could be raised in XSLT transformations (by Saxon) and appear in eXist-db's log file did not include information about where the error occurred. This PR simply includes the location information provided by the `TransformerException`.

Improve XSLT errors

---

exist-core/src/main/java/org/exist/backup/restore/RestoreHandler.java
exist-core/src/test/java/org/exist/backup/XMLDBRestoreTest.java

Fixes #4368 by using the resource type defined by the backup meta data if it differs the one defined on the mime type definition.
The current implementation does always calculate the resource type (`XMLResource`/`BinaryResource`) based on the bakcup meta data content type using the `MimeTable` instance. In the failing case the resulting resource type will be set to `XMLResource` using the currently defined type for `text/html` within the `mime-types.xml` instead of the resource type `BinaryResource` that is defined in the backup meta data. This leads to the fact that the restore task will change the resource type to a different one as has being wrote to the backup.

[bugfix] override resource type from backup metadata

---

exist-core/src/main/java/org/exist/backup/restore/RestoreHandler.java
exist-core/src/test/java/org/exist/backup/XMLDBRestoreTest.java

Fixes #4368 by using the resource type defined by the backup meta data if it differs the one defined on the mime type definition.
The current implementation does always calculate the resource type (`XMLResource`/`BinaryResource`) based on the bakcup meta data content type using the `MimeTable` instance. In the failing case the resulting resource type will be set to `XMLResource` using the currently defined type for `text/html` within the `mime-types.xml` instead of the resource type `BinaryResource` that is defined in the backup meta data. This leads to the fact that the restore task will change the resource type to a different one as has being wrote to the backup.

[5.x.x] override resource type from backup metadata

---

.github/workflows/ci-docs.yml
.github/workflows/ci-xqts.yml

Restrict the GitHub token permissions only to the required ones; this way, even if the attackers will succeed in compromising your workflow, they won’t be able to do much.
- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
[Keeping your GitHub Actions and workflows secure Part 1: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)
Signed-off-by: naveen <172697+naveensrinivasan@users.noreply.github.com>

chore: Set permissions for GitHub actions

---

exist-core/src/main/java/org/exist/dom/memtree/DocumentImpl.java
exist-core/src/main/java/org/exist/dom/memtree/NodeImpl.java
exist-core/src/main/java/org/exist/dom/persistent/AVLTreeNodeSet.java
exist-core/src/main/java/org/exist/dom/persistent/EmptyNodeSet.java
exist-core/src/main/java/org/exist/dom/persistent/ExtArrayNodeSet.java
exist-core/src/main/java/org/exist/dom/persistent/NewArrayNodeSet.java
exist-core/src/main/java/org/exist/dom/persistent/NodeProxy.java
exist-core/src/main/java/org/exist/dom/persistent/SortedNodeSet.java
exist-core/src/main/java/org/exist/dom/persistent/VirtualNodeSet.java
exist-core/src/main/java/org/exist/xquery/FunctionCall.java
exist-core/src/main/java/org/exist/xquery/RangeSequence.java
exist-core/src/main/java/org/exist/xquery/functions/array/ArrayType.java
exist-core/src/main/java/org/exist/xquery/functions/map/MapExpr.java
exist-core/src/main/java/org/exist/xquery/functions/map/MapType.java
exist-core/src/main/java/org/exist/xquery/value/AtomicValue.java
exist-core/src/main/java/org/exist/xquery/value/BinaryValueFromFile.java
exist-core/src/main/java/org/exist/xquery/value/BinaryValueFromInputStream.java
exist-core/src/main/java/org/exist/xquery/value/EmptySequence.java
exist-core/src/main/java/org/exist/xquery/value/OrderedValueSequence.java
exist-core/src/main/java/org/exist/xquery/value/PreorderedValueSequence.java
exist-core/src/main/java/org/exist/xquery/value/Sequence.java
exist-core/src/main/java/org/exist/xquery/value/SubSequence.java
exist-core/src/main/java/org/exist/xquery/value/ValueSequence.java

This PR fixes *some* cases where `xs:base64Binary` value variables within an XQuery are cleared before they should be.
If you have a function which returns a Map containing an `xs:base64Binary` (specifically the result of an EXPath HTTP Client response), and then you try and use that value in a calling function you will encounter an error where the temporary file backing the xs:base64Binary value has incorrectly already been deleted.
What is happening is:
1. The EXPath HTTP Client response constructs an `xs:base64Binary` value using `org.exist.xquery.value.BinaryValueFromFile`.
2. `BinaryValueFromFile` stores the binary data in a temporary file.
3. When the xs:base64BinaryValue is returned from the function inside a Map, eXist-db does not recognise it is inside a Map, and so incorrectly …

[4.x.x] Improve out-of-scope detection for binary variables

---

exist-core/src/main/java/org/exist/xquery/functions/fn/FunMatches.java
exist-core/src/main/java/org/exist/xquery/functions/fn/FunTokenize.java
exist-core/src/test/xquery/regex.xml

Replace java Regex with Saxon  for `fn:matches`
#3633 

Use Saxon for fn:matches regular expression handling.

---

exist-core/src/main/java/org/exist/xquery/OpNumeric.java
exist-core/src/test/java/org/exist/xquery/XQueryTest.java

Fix #3441.
This open source contribution to the eXist-db project was commissioned by the Office of the Historian, U.S. Department of State, https://history.state.gov/

Fix div operator error when arg is a variable.

---

exist-core/src/main/java/org/exist/xquery/ValueComparison.java
exist-core/src/main/java/org/exist/xquery/value/DecimalValue.java
exist-core/src/main/java/org/exist/xquery/value/FloatValue.java
exist-core/src/test/java/xquery/numericOp/NumericOpTests.java
exist-core/src/test/xquery/numericOp/numeric-add.xqm
exist-core/src/test/xquery/numericOp/numeric-divide.xqm
exist-core/src/test/xquery/numericOp/numeric-equal.xqm
exist-core/src/test/xquery/numericOp/numeric-greater-than-or-equal.xqm
exist-core/src/test/xquery/numericOp/numeric-greater-than.xqm
exist-core/src/test/xquery/numericOp/numeric-integer-divide.xqm
exist-core/src/test/xquery/numericOp/numeric-less-than-or-equal.xqm
exist-core/src/test/xquery/numericOp/numeric-less-than.xqm
exist-core/src/test/xquery/numericOp/numeric-mod.xqm
exist-core/src/test/xquery/numericOp/numeric-multiply.xqm
exist-core/src/test/xquery/numericOp/numeric-not-equal.xqm
exist-core/src/test/xquery/numericOp/numeric-subtract.xqm

It seems eXist-db had quite a lot of bugs in its numeric operations, most of these were around missing type promotions. This PR adds 72 tests and a bunch of fixes.
This was previously leading to false negatives in seemingly unrelated XQTS tests.
Closes https://github.com/eXist-db/exist-xqts-runner/issues/23
https://i.pinimg.com/originals/9f/7d/89/9f7d89ea2c67cb6cb0daf85fa7e52e0a.png

Fix numerous bugs in numeric operations

---

exist-core/src/main/java/org/exist/xquery/value/StringValue.java
exist-core/src/test/xquery/xquery3/castable.xqm

Fix #3390
This open source contribution to the eXist-db project was commissioned by the Office of the Historian, U.S. Department of State, https://history.state.gov/

Don't allow xs:string to be cast as xs:QName

---

bin/server.sh
bin/startup.sh

It appears that these were correctly handled previously in all `bin/*.sh` scripts but not the `startup.sh` and `server.sh` scripts. This PR now causes these to correctly handle Windows paths that have spaces in them.

[4.x.x] Ensure that spaces in Windows paths for startup.sh and server.sh are correctly quoted

---

exist-core/src/main/java/org/exist/xquery/functions/fn/FnModule.java
exist-core/src/main/java/org/exist/xquery/functions/fn/FunCollationKey.java
exist-core/src/main/java/org/exist/xquery/value/BinaryValue.java
exist-core/src/test/xquery/xquery3/fnCodepointEqual.xqm
exist-core/src/test/xquery/xquery3/fnCollationKey.xqm
extensions/modules/compression/src/test/xquery/modules/compression/zip-tests.xql

Implementation of the [`fn:collation-key()`](https://www.w3.org/TR/xpath-functions-31/#func-collation-key) function.
* https://github.com/eXist-db/exist/issues/3635
* `exist-core/src/test/xquery/xquery3/fnCollationKey.xqm`
This passes all XQTS tests for `fn-collation-key` apart from the two tests: `collation-key-105` and `collation-key-206`. These tests require that eXist-db supports the `merge-last` option when calling `map:merge`. These remaining two tests tests should pass once the PR https://github.com/eXist-db/exist/pull/3738 is merged to eXist-db.
--

Implement the fn:collation-key XQuery function

---

exist-core/src/main/java/org/exist/xquery/value/DateTimeValue.java
exist-core/src/test/xquery/dates/convert-dates.xqm

Fixes the calculation of:
```xquery
xs:dateTimeStamp(“2022-08-10T12:36:51.723+02:00”) - xs:dateTimeStamp(“2022-07-10T12:36:51.723+02:00")
```
and
```xquery
xs:dateTime(“2022-08-10T12:36:51.723+02:00”) - xs:dateTimeStamp(“2022-07-10T12:36:51.723+02:00")
```
This was missing from PR https://github.com/eXist-db/exist/pull/4393

Implement minus unary operator for xs:dateTimeStamp

---

exist-core/src/main/java/org/exist/client/QueryDialog.java

Backport of https://github.com/eXist-db/exist/pull/4488

[5.x.x] Report null results instead of throwing NPE

---

exist-core/src/main/java/org/exist/xquery/AbstractExpression.java
exist-core/src/main/java/org/exist/xquery/DebuggableExpression.java
exist-core/src/main/java/org/exist/xquery/Expression.java
exist-core/src/main/java/org/exist/xquery/PathExpr.java
exist-core/src/main/java/org/exist/xquery/TextConstructor.java
exist-core/src/main/java/org/exist/xquery/functions/fn/FunLocalName.java
exist-core/src/main/java/org/exist/xquery/value/Sequence.java
exist-core/src/test/java/org/exist/xquery/XQueryFunctionsTest.java
exist-core/src/test/xquery/fn.xql

Closes https://github.com/eXist-db/exist/issues/4466
Previously eXist-db was doing more work than it needed, i.e. it was evaluating path steps on empty sequences. This led to both incorrect results and sub-optimal performance. eXist-db also has some tests for this previous behaviour which were incorrect, these tests have also been corrected.

Corrects issues with fn:local-name and unnecessary evaluation of path steps on empty sequences

---

exist-core/src/main/antlr/org/exist/xquery/parser/XQueryTree.g
exist-core/src/main/java/org/exist/xquery/DynamicFunctionCall.java
exist-core/src/main/java/org/exist/xquery/EnclosedExpr.java
exist-core/src/main/java/org/exist/xquery/value/FunctionReference.java
exist-core/src/test/java/org/exist/xquery/FunctionTypeInElementContentTest.java
exist-core/src/test/xquery/errors.xql

Add location information to map expressions, and pass this information to the `XQTY0105` exception that occurs when an enclosed expression contains a function item
https://github.com/eXist-db/exist/issues/3623
`subexpression-in-enclosed-expression-evaluates-to-map` and `enclosed-expression-evaluates-to-map` in `exist-core\src\test\xquery\errors.xql`
--

[bugfix] Add missing location information in errors for functions inside element constructors (err:XQTY0105)

---

exist-core/src/main/java/org/exist/xquery/ErrorCodes.java
exist-core/src/main/java/org/exist/xquery/XQueryContext.java
exist-core/src/main/java/org/exist/xquery/functions/fn/FnModule.java
exist-core/src/main/java/org/exist/xquery/functions/fn/FunUriCollection.java
exist-core/src/test/xquery/xquery3/fnUriCollection.xqm

Implement the `fn:uri-collection` function
* https://github.com/eXist-db/exist/issues/3635
* https://www.w3.org/TR/xpath-functions-31/#func-uri-collection
Added `exist-core/src/test/xquery/xquery3/fnUriCollection.xqm` tests
There are only two failing XQTS tests which are `uri-collection-901` and `uri-collection-903`, however these look like problems with the tests themselves and can be ignored for now, see: https://github.com/w3c/qt3tests/issues/43
---

[feature] Implement the fn:uri-collection function

---

exist-core/src/main/java/org/exist/http/RESTServer.java
exist-core/src/main/java/org/exist/http/servlets/EXistServlet.java
exist-core/src/test/java/org/exist/http/RESTServiceTest.java

this Fixes: https://github.com/eXist-db/exist/issues/4458
as mentioned in the issue above the rest client was unable to handle filenames with special characters. This fixes that for all HTTP request GET,POST,PUT,DELETE
now storing resource like 
```xquery
xquery version "3.1";
xmldb:create-collection("/db","AéB"),
xmldb:store(xmldb:encode("/db/AéB"), xmldb:encode("AéB.xml"), <foo/>)
```
and performing operations on it from the rest client works fine eg:
GET: http://localhost:8080/exist/rest/db/A%C3%A9B/A%C3%A9B.xml

fix Rest client file encoding 

---

exist-core/src/main/java/org/exist/storage/serializers/EXistOutputKeys.java
exist-core/src/main/java/org/exist/util/serializer/IndentingXMLWriter.java
exist-core/src/main/java/org/exist/util/serializer/json/JSONSerializer.java
exist-core/src/main/java/org/exist/xquery/util/SerializerUtils.java
exist-core/src/test/xquery/xquery3/serialize.xql
extensions/modules/file/src/main/java/org/exist/xquery/modules/file/Sync.java
extensions/modules/file/src/test/xquery/modules/file/serialize.xqm
extensions/modules/file/src/test/xquery/modules/file/sync-serialize.xqm

Introduce new serialization option `exist:insert-final-newline` for XML _and_ JSON files.
If set to true a blank-line will be added at the end of a document. This is helpful when working with `git`, `diff` and 
other command line tools.
**Example:**
```xquery
serialize(
map{ "a": 1 },
map {
"method": "json",
"exist:insert-final-newline": true()
}
)
```
will result in 
```json
{"a": 1}
\n
```
Note the newline at the end.
Tests: 
- XQSuite tests
- Tested to work in `fn:serialize`, `file:sync` (only XML) and `file:serialize`
- Adds first tests for `file:serialize` and `file:serialize-binary`. 
This PR also fixes a regression where only one Suite in XQuery3Tests was run.

[enhancement] add serialization option that inserts final newline

---

exist-core/pom.xml
exist-parent/pom.xml

Fixes warnings of missing SLF4J provider implementation. This dependency will change again as soon there is a final version of Log4j available later.

bugfix: use correct implementation for slf4j 2.0.0

---

exist-core/src/main/java/org/exist/xquery/value/BinaryValueFromFile.java

This PR fixes a resource leak, which kept file handles around until they are garbage collected. This results in an incorrect file lock in Windows.
This fixes a resource leak in `org.exist.xquery.value.BinaryValueFromFile`, which causes file handles to hang around.
Under Windows, this means that most editors cannot save such a file, once the handle has been created, because they consider the file locked. Under Linux, vi (and apparently, nano) have no problem. However, the resource leak still exists.
The problem occurs in line 64 of `BinaryValueFromFile.java`:
```
this.channel = new RandomAccessFile(file.toFile(), "r").getChannel();
```
The creation of the `RandomAccessFile` object creates the file handle. Because the `RandomAccessFile` object is not kept, its close() method can never be …

fix resource leak (and file lock)

---

exist-core/src/test/xquery/unparsed-text.xql

refs #4542
This is just a quick patch!
Two pending tests were added `upt:non-existent-redirect` and `upt:unparsed-text-available-non-existent-redirect` which will pass when the redirect is followed _or_ an HTTP status code in the 3XX range is treated as an error.

[hotfix] change URL for two unparsed-text tests

---

exist-core/src/main/java/org/exist/storage/ValueIndexFactory.java
exist-core/src/main/java/org/exist/util/ByteConversion.java
exist-core/src/main/java/org/exist/xquery/value/DateTimeValue.java
exist-core/src/main/java/org/exist/xquery/value/DateValue.java
exist-core/src/main/java/org/exist/xquery/value/DecimalValue.java
exist-core/src/main/java/org/exist/xquery/value/DoubleValue.java
exist-core/src/main/java/org/exist/xquery/value/FloatValue.java
exist-core/src/main/java/org/exist/xquery/value/IntegerValue.java
exist-core/src/main/java/org/exist/xquery/value/TimeUtils.java
exist-core/src/main/java/org/exist/xquery/value/TimeValue.java
extensions/indexes/lucene/pom.xml
extensions/indexes/lucene/src/main/java/org/exist/indexing/lucene/LuceneFieldConfig.java
extensions/indexes/lucene/src/main/java/org/exist/indexing/lucene/LuceneIndexWorker.java
extensions/indexes/lucene/src/main/java/org/exist/indexing/lucene/LuceneMatch.java
extensions/indexes/lucene/src/main/java/org/exist/xquery/modules/lucene/Field.java
extensions/indexes/lucene/src/main/java/org/exist/xquery/modules/lucene/LuceneModule.java
extensions/indexes/lucene/src/main/java/org/exist/xquery/modules/lucene/QueryOptions.java
extensions/indexes/lucene/src/test/xquery/lucene/facets.xql

revised version of #4253
This PR will address 3 problems when using Lucene fields for sorting or iterating large node sets (> 100.000 elements):
1. eXist-db quickly runs out of memory: this happens as `ft:query` retrieves the fields for the entire result set at once and keeps them attached to each item in the set, no matter if the fields content is in fact accessed or not
2. Because fields are retrieved at query time, users have to know in advance which fields will be required later and list them in the `ft:query` options
3. Fixing 1 and 2 will further slow down field-based sort operations on large node sets. In general, those operations were already slow, but performance will degrade even more if we do not preload the fields.
The PR effectively fixes 1 by not preloading any fields. …

Field perf revised

---

exist-core/src/main/java/org/exist/xquery/functions/fn/transform/TreeUtils.java
exist-core/src/test/xquery/xquery3/transform/fnTransformRegression1.xqm

The fn:transform code to find the path to the node within the document, for hashing the stylesheet cache, didn’t expect a document. Test for that case explicitly, and in the case of a document the URI of the document can serve as the path.
Passing an eXist stored document as the stylesheet node to `fn:transform` fails with a ClassCastException.
`{ ... "stylesheet-node":doc("/db/regression-test-1/stylesheet.xsl") ... }`
An XSuite regression unit test is included in this checkin.

[bugfix] fn:transform stylesheet document crash

---

exist-core/src/main/java/org/exist/xquery/LocationStep.java
exist-core/src/test/xquery/document-nodes.xq

Appears to have been caused by over zealous optimisations.
The fixes should not impact general performance at all.
Closes https://github.com/eXist-db/exist/issues/4546

Fix issues with document-node lookups on various axis

---

exist-core/src/main/java/org/exist/storage/serializers/Serializer.java

Closes https://github.com/eXist-db/documentation/issues/265 and Closes https://github.com/eXist-db/exist/issues/3233
this feature was added in https://github.com/eXist-db/exist/commit/0cda7b6387aa4fb8ff82e6bb14a4de81bb210f74 and it was both `undocumented` and `untested` when trying to provide documentation for it we tried testing it, it didn't work as intended.
this feature is better removed as it doesn't work.

remove exist-serialize option

---

exist-core/src/main/java/org/exist/dom/memtree/NodeImpl.java
exist-core/src/main/java/org/exist/dom/persistent/AttrImpl.java
exist-core/src/main/java/org/exist/dom/persistent/ElementImpl.java
exist-core/src/main/java/org/exist/xquery/ErrorCodes.java
exist-core/src/main/java/org/exist/xquery/update/Insert.java
exist-core/src/test/xquery/xquery3/bindingConflict.xqm

Report an error (`XUDY0023`) when an insertion is attempted with a node or attribute name in a namespace that conflicts with one which exists in the document.
Closes https://github.com/eXist-db/exist/issues/1482
See https://www.w3.org/TR/xquery-update-30/#dt-conflict
Recursively check node/attributes inserted into a document for namespace conflicts. This change does not look at namespaces introduced in the subtrees being inserted, it appears these correctly respect the namespace in the subtree rather than the declared namespace in the XQuery context in which the insertion happens.
Added unit tests in `binidingConflict.xqm` for correct reporting of binding conflict errors

[bugfix] - namespace binding conflict errors

---

exist-core/src/main/java/org/exist/http/servlets/HttpRequestWrapper.java

This could improve performance when uploading a large number of smaller files by reducing IO traffic.
Even after running instances with this patch applied we could see no negative effects. And less code is always less code to maintain.
The below assumption was not reproducible in our testing.
~~Setting the SizeThreshhold to a low value can lead to
Unexpected EOF errors when decoding  multipart messages.~~

[hotfix] use DiskFileItemFactory default threshhold

---

exist-core/src/test/xquery/unparsed-text.xql

Backport of https://github.com/eXist-db/exist/pull/4543

[4.x.x] Change URL for two unparsed-text tests

---

exist-core/src/main/java/org/exist/http/servlets/HttpRequestWrapper.java

This reverts commit c22ffe0ce3daf7034ec9069d86da8b42ae366b74.
It turns out that payloads in body encoded as  multipart/form-data have to be written to disk in order to be available in XQuery context. This is the reason the DiskFileItemFactory threshhold has to be zero.
Apparently, there are no tests covering this case. It was only revealed through testing Roaster against current develop.

[hotfix] multipart body contents in XQuery

---

exist-core/src/main/java/org/exist/xquery/functions/array/ArrayConstructor.java
exist-core/src/test/xquery/arrays/arrays.xql

Fixes #3472
the expression `array {}` was returning `Index 0 out of bounds for length 0`
now with this fix it returns `[]` as it should
This open source contribution to the [exist](https://github.com/eXist-db/exist) project was commissioned by the Office of the Historian, U.S. Department of State, https://history.state.gov/.

Fix empty array constructor

---

exist-docker/pom.xml

Concatenate the mailcap files from bcmail and jakarta.mail together when shading the Uber Jar for Docker, previously one would overwrite the other.
Closes https://github.com/eXist-db/exist/issues/4600

Fix mail:send-email via Java API in Docker

---

exist-core/src/main/java/org/exist/repo/ExistRepository.java
exist-core/src/main/java/org/exist/xquery/Function.java
exist-core/src/main/java/org/exist/xquery/XQueryContext.java

We use 4.x.x with custom `org/exist/xquery/Function`s. 
This works fine on JDK 11. 
As soon as we use JDK 17, we get OutOfMemory in the Non-heap region (Lambdas from `org/exist/xquery/Function`).
6 does not show the problem.
If we pick the commit: 
4ec61b0af9d5cec91ebcfe7c3a79bef9d1155555 
([bugfix] EXPath Repo classes must be instantiable via reflection, however LamdaMetafactory cannot cross classloader boundaries. As only EXPath Repo classes are now loaded by the EXistClassLoader everything else is loaded by a URLClassLoader (via AppAssemblerBooter), we have to use reflection instead of invokeDynamic to load EXPath Jar Modules) 
from develop, the OutOfMemory goes away.
Forensics done together with @reinhapa.

[4.x.x] Prevent OutOfMemory on JDK 17 when loading EXPath Modules

---

exist-jetty-config/src/main/resources/org/exist/jetty/etc/jetty-annotations.xml
exist-jetty-config/src/main/resources/org/exist/jetty/etc/jetty-bytebufferpool.xml
exist-jetty-config/src/main/resources/org/exist/jetty/etc/jetty-deploy.xml
exist-jetty-config/src/main/resources/org/exist/jetty/etc/jetty-gzip.xml
exist-jetty-config/src/main/resources/org/exist/jetty/etc/jetty-http.xml
exist-jetty-config/src/main/resources/org/exist/jetty/etc/jetty-https.xml
exist-jetty-config/src/main/resources/org/exist/jetty/etc/jetty-jaas.xml
exist-jetty-config/src/main/resources/org/exist/jetty/etc/jetty-jmx.xml
exist-jetty-config/src/main/resources/org/exist/jetty/etc/jetty-logging.xml
exist-jetty-config/src/main/resources/org/exist/jetty/etc/jetty-requestlog.xml
exist-jetty-config/src/main/resources/org/exist/jetty/etc/jetty-ssl-context.xml
exist-jetty-config/src/main/resources/org/exist/jetty/etc/jetty-ssl.xml
exist-jetty-config/src/main/resources/org/exist/jetty/etc/jetty-threadpool.xml
exist-jetty-config/src/main/resources/org/exist/jetty/etc/jetty.xml
exist-jetty-config/src/main/resources/org/exist/jetty/etc/standalone-jetty-deploy.xml
exist-jetty-config/src/main/resources/org/exist/jetty/etc/standalone-jetty-http.xml
exist-jetty-config/src/main/resources/org/exist/jetty/etc/standalone-jetty-ssl.xml
exist-jetty-config/src/main/resources/org/exist/jetty/etc/standalone-jetty.xml
exist-jetty-config/src/main/resources/org/exist/jetty/etc/standalone-webapps/exist-webapp-context.xml
exist-jetty-config/src/main/resources/org/exist/jetty/etc/webapps/exist-webapp-context.xml

[5.x.x] Jetty dtd references must now use https instead of http

---

tools/jetty/etc/jetty-annotations.xml
tools/jetty/etc/jetty-deploy.xml
tools/jetty/etc/jetty-gzip.xml
tools/jetty/etc/jetty-http.xml
tools/jetty/etc/jetty-https.xml
tools/jetty/etc/jetty-jaas.xml
tools/jetty/etc/jetty-jmx.xml
tools/jetty/etc/jetty-logging.xml
tools/jetty/etc/jetty-plus.xml
tools/jetty/etc/jetty-requestlog.xml
tools/jetty/etc/jetty-ssl-context.xml
tools/jetty/etc/jetty-ssl.xml
tools/jetty/etc/jetty.xml
tools/jetty/etc/standalone-jetty-deploy.xml
tools/jetty/etc/standalone-jetty-http.xml
tools/jetty/etc/standalone-jetty-ssl.xml
tools/jetty/etc/standalone-jetty.xml
tools/jetty/standalone-webapps/exist-webapp-context.xml
tools/jetty/webapps/exist-webapp-context.xml

It seems that the DTD inside the jetty-configuration files are now no longer available via http. Redirect does work inside browser but not during build process. Changed DTD references to https does solve the issue.
Mentioned on Slack
Just do build eXist now. Building process went through

[4.x.x] Jetty dtd references must now use https instead of http

---

exist-core/src/main/java/org/exist/xquery/functions/map/AbstractMapType.java
exist-core/src/main/java/org/exist/xquery/functions/map/MapFunction.java
exist-core/src/main/java/org/exist/xquery/functions/map/MapType.java
exist-core/src/main/java/org/exist/xquery/functions/map/SingleKeyMapType.java
exist-core/src/test/xquery/maps/maps.xqm

- support options `map{ "duplicates": "combine" }` and `map{ "duplicates": "reject" }`
Cherry-picked 3 commits from #3738 and squashed them 
These enhancements are non-breaking and can be merged in to develop before the next major release. 
- allow an empty options map passed to map:merge#2 - fixes #4620

allow all options in map:merge#2

---

exist-core/src/main/java/org/exist/collections/triggers/XQueryTrigger.java
exist-core/src/main/java/org/exist/dom/persistent/SortedNodeSet.java
exist-core/src/main/java/org/exist/repo/Deployment.java
exist-core/src/main/java/org/exist/security/internal/SMEvents.java
exist-core/src/main/java/org/exist/storage/NotificationService.java
exist-core/src/main/java/org/exist/test/runner/AbstractTestRunner.java
exist-core/src/main/java/org/exist/test/runner/XQueryTestRunner.java
exist-core/src/main/java/org/exist/validation/internal/DatabaseResources.java
exist-core/src/main/java/org/exist/xquery/FunctionCall.java
exist-core/src/main/java/org/exist/xquery/ModuleContext.java
exist-core/src/main/java/org/exist/xquery/XQuery.java
exist-core/src/main/java/org/exist/xquery/XQueryContext.java
exist-core/src/main/java/org/exist/xquery/functions/fn/LoadXQueryModule.java
exist-core/src/main/java/org/exist/xquery/functions/inspect/InspectModule.java
exist-core/src/main/java/org/exist/xquery/functions/inspect/ModuleFunctions.java
exist-core/src/main/java/org/exist/xquery/functions/util/Compile.java
exist-core/src/main/java/org/exist/xquery/functions/util/Eval.java
exist-core/src/main/java/org/exist/xquery/functions/util/ModuleInfo.java
exist-core/src/main/java/org/exist/xupdate/XUpdateProcessor.java

This PR fixes a memory leak in eXist-db that can quickly cause all available memory to be consumed.
This came about due to Listeners subscribing to events produced by a running XQuery never being reset between executions of the query. Thus the list of listeners per-query grew indefinitely. 
The cause of this was due to several XQuery expressions not being reset and cleaned up after the query was executed. In particular these XQuery functions were incorrectly implemented and therefore failed to clean up after themselves and could contribute to the memory leak:
* `inspect:module-functions`
* `inspect:module-functions-by-uri`
* `inspect:inspect-module`
* `inspect:inspect-module-uri`
* `util:eval`
* `util:compile`
* `util:module-info`
* `fn:load-xquery-module`
----
Thanks to @PieterLamers for …

Fix Memory leaks caused by XQuery context and update listener leaks

---

extensions/indexes/lucene/src/main/java/org/exist/indexing/lucene/AnalyzerConfig.java
extensions/indexes/lucene/src/test/java/org/exist/indexing/lucene/AnalyzerConfigTest.java

currently per docs the analyzer config should accept primitive types as `int` & `char`
and this was not the case 
when using `int` as param type in the analyzer config it gets converted to `Integer` then checks against the existing `int` constructor which yields `no constructor found` error
this fixes it 
thanks to @adamretter for providing the fix code

[bugfix] analyzer conf doesn't accept primitives

---

exist-core/src/main/java/org/exist/test/runner/AbstractTestRunner.java
exist-core/src/main/java/org/exist/test/runner/ExtTestAssumptionFailedFunction.java
exist-core/src/main/java/org/exist/test/runner/ExtTestErrorFunction.java
exist-core/src/main/java/org/exist/test/runner/ExtTestFailureFunction.java
exist-core/src/main/java/org/exist/test/runner/ExtTestFinishedFunction.java
exist-core/src/main/java/org/exist/test/runner/ExtTestIgnoredFunction.java
exist-core/src/main/java/org/exist/test/runner/ExtTestStartedFunction.java
exist-core/src/main/java/org/exist/test/runner/JUnitIntegrationFunction.java
exist-core/src/main/java/org/exist/test/runner/XMLTestRunner.java
exist-core/src/main/java/org/exist/test/runner/XQueryTestRunner.java
exist-core/src/main/java/org/exist/xquery/functions/fn/FunUnparsedText.java
exist-parent/pom.xml

Fix an issue where XSuite tests had the wrong uniqueId; this caused one failing test to make some subequent tests also appear like they were failing
fixes https://github.com/eXist-db/exist/issues/4538

Fix a bug in XSuite reporting too many failures

---

.github/workflows/ci-test.yml

Should now pass the `COVERALLS_TOKEN` correctly from Github Secrets.

Fix CI use of Coveralls Code Coverage

---

exist-core/src/main/java/org/exist/xquery/functions/util/BuiltinFunctions.java

The function description contained a copy-paste typo - likely from the function description of `util:registered-functions()`.
n/a
n/a

fix function description of util:declared-variables

---

exist-core/pom.xml
exist-core/src/main/java/org/exist/dom/persistent/NodeProxy.java
exist-core/src/main/java/org/exist/xquery/Predicate.java
exist-core/src/main/java/org/exist/xquery/functions/array/ArrayType.java
exist-core/src/main/java/org/exist/xquery/functions/map/MapType.java
exist-core/src/main/java/org/exist/xquery/value/BinaryValue.java
exist-core/src/test/xquery/binary-value.xqm
exist-core/src/test/xquery/pathExpression_operators.xml

Previously if an `xs:base64Binary` or `xs:hexBinary` value was constructed dynamically in XQuery and bound to a variable (e.g. from `util:binary-doc`, `http:send-request, etc.) and that value was then returned within a Map or Array, the variable binding (and therefore the value) would be destroyed prematurely as the XQuery engine believed that the variable binding was no longer needed.
This caused numerous issues with error messages such as "The underlying InputStream has been closed" when trying to work with binary values.
Fixing this also revealed a further issue with retrieving parent document-nodes of NodeProxy objects (stored nodes), and an invalid Union Operator test in the test suite, which I have also corrected.

Fix issues with binary files being closed whilst they are still needed

---

exist-core/src/main/java/org/exist/util/serializer/HTML5Writer.java
exist-core/src/test/xquery/xquery3/serialize.xql

According to the XSLT and XQuery Serialization 3.1 spec, in the HTML Output Method, the text node descendants of all elements are to be escaped, except two: `<script>` and `<style>`:
> The HTML output method **MUST NOT** perform escaping for any text node descendant, nor for any attribute of an element node descendant, of a `script` or `style` element.
eXist's HTML 5 serializer extended this behavior to 2 additional elements: `<textarea>` and `<title>`. As a result their text node descendants are serialized in an unescaped form.
This PR fixes the error by removing `<textarea>` and `<title>` from this list and limiting this behavior to the two elements prescribed in the spec: `<script>` and `<style>`.
https://www.w3.org/TR/xslt-xquery-serialization-31/#html-output
XQSuite

[BUG] HTML5 serializer should escape contents of title and textarea elements

---

build.properties
build/scripts/installer.xml
build/scripts/setup.xml
installer/apps.properties

Previously a different set of apps was provided in the DMG and Installer, to that in the dist archives. This was because there were two list of apps present, this consolidates on a single list of the apps to ship.

[4.x.x] Canonical source of apps

---

exist-versioning-release.md

An additional option is needed in the instructions to ensure the IzPack installer is also released.

[5.x.x] Also build the IzPack installer

---

exist-core-jcstress/pom.xml
exist-core-jmh/pom.xml

Fixes the version numbers in missed POM files after the last release.

[bugfix] corrects version number on missed POMs

---

.gitignore

closes #4694
Two POMs are created during packaging
- exist-core-jcstress/depedency-reduced-pom.xml
- exist-core-jmh/dependency-reduced-pom.xml
These files are show up as untracked afterwards and might therefore be committed in error.

[fix] ignore temporary POMs

---

.github/ISSUE_TEMPLATE/bug_report.md

add a hint that the context can be conveniently gathered using `xst info`
see https://github.com/eXist-db/xst/pull/49

[ignore] add hint to issue template context section

---

exist-core/src/main/java/org/exist/xquery/functions/fn/FunSerialize.java
exist-core/src/main/java/org/exist/xquery/functions/util/Eval.java
exist-core/src/main/java/org/exist/xquery/util/SerializerUtils.java
exist-core/src/test/java/xquery/xquery3/XQuery3Tests.java
exist-core/src/test/xquery/xquery3/serialize.xql

- apply item separator _after_ string normalisation: fixes #4702
- allow empty item separator: fixes #4704
- skip empty values: fixes #4705
- item-separator applies to array members: fixes #4706 
Note:
The provided test cases by @peterstadler had an expected value of `"<a>foo</a><b>bar</b>"`
This had to be changed to `"<a>foo</a> <b>bar</b>"` because of the _changed_ default item separator. 
https://www.w3.org/TR/xslt-xquery-serialization-31/#serdm
XQSuite tests

[hotfix] fn:serialize issues

---

exist-distribution/pom.xml

running `bin/start.sh`
```
25 May 2021 22:45:06,742 [main] INFO  (JettyStart.java [run]:287) - ----------------------------------------------------- 
25 May 2021 22:45:06,742 [main] INFO  (JettyStart.java [run]:288) - Server has started, listening on: 
25 May 2021 22:45:06,742 [main] INFO  (JettyStart.java [run]:290) - http://127.0.0.1:8080/ 
25 May 2021 22:45:06,742 [main] INFO  (JettyStart.java [run]:290) - https://127.0.0.1:8443/ 
25 May 2021 22:45:06,743 [main] INFO  (JettyStart.java [run]:293) - Configured contexts: 
25 May 2021 22:45:06,743 [main] INFO  (JettyStart.java [run]:299) - /exist (eXist XML Database) 
25 May 2021 22:45:06,744 [main] INFO  (JettyStart.java [run]:299) - / (eXist-db portal) 
25 May 2021 22:45:06,745 [main] INFO  (JettyStart.java [run]:323) - …
```

[feature] Remove IPrange filter to be deployed automagically.

---

extensions/expath/src/main/java/org/expath/exist/HttpClientModule.java

The EXPath HTTP Client specification uses the namespace prefix `http`. eXist's implementation uses a different prefix, `hc`. 
While module namespace prefixes are mere convention, there is no good reason for eXist to use a different prefix than the spec does. As a result of this mismatch, eXist users are understandably confused when they search the function documentation for "http" and find no hits, as in this exchange from Slack last week: 
> I did notice that http-client function docs are missing from fundocs on exist-db.org. Is that known  or where they never in there?
>
> search for `hc`
>
> ah
... Or when they invoke the `http:send-request` function and encounter the error:
> Invalid qname `http:send-request`. No namespace defined for prefix `http`. QName is invalid: INVALID_PREFIX …

Align EXPath HTTP Client namespace prefix with spec convention (change "hc" to "http")

---

exist-core/pom.xml
exist-core/src/main/java/org/exist/xquery/XQueryContext.java
exist-core/src/test/xquery/order.xqm

At the moment eXist-db implements `empty greatest` as the default ordering in XQuery.
The spec says it is `implementation defined`. However, Saxon and BaseX both implement `empty least` as the default. IMHO `empty least` is the most likely *expected* behaviour.
In the interest of improved interoperability for XQuery users. This PR switched eXist-db from `empty greatest` to `empty least` as the default behaviour.
This isn't technically an API change, rather it is an internal behaviour change. Therefore it is a Semver minor change. But... if anyone thinks it should be a major release feature (i.e. 6.0.0), then let's hear your arguments ;-)

Switch to `empty least` as default ordering behaviour in XQuery

---

exist-core/src/main/java/org/exist/storage/DBBroker.java
exist-core/src/main/java/org/exist/storage/NativeBroker.java
exist-core/src/main/java/org/exist/storage/NativeValueIndex.java

Previously `DBBroker` was an Abstract Class, however for as long as I can remember there has only been a single sub-class which is `NativeBroker`. Whilst eXist-db was originally designed to have different brokers (e.g. MySQL as an option), that ability has long since disappeared. The mixing of code between DBBroker and NativeBroker was confusing.
DBBroker should have been an interface and now is.
PR https://github.com/eXist-db/exist/pull/3992 should be merged first ideally.
**NOTE** - These changes are API *backwards compatible* at the source level only! They are not backwards compatible at the *compilation level*. That is to say that libraries compiled against versions of eXist-db before this change may (if they use this class) raise the error :
```java …
```

Refactor DBBroker into an Interface

---

exist-core/src/main/java/org/exist/dom/QName.java
exist-core/src/main/java/org/exist/dom/persistent/StoredNode.java
exist-core/src/test/java/org/exist/xquery/AbstractDescendantOrSelfNodeKindTest.java

fixes #4740
Do not log an error each time typeswitch is called on a CDATA section.
This also fixes an NPE when trying to get the name of a stored CDATA section
```xquery
doc('has-cdata.html')//script/node()/name()
```
With an in-memory CDATA section this returns an empty xs:string
```xquery
<a><![CDATA[ a ]]></a>/node()/name()
```
When this PR is merged an empty xs:string is also returned for stored CDATA sections.

[bugfix] NPE on qname of CDATA section

---

exist-distribution/pom.xml

The [copy maven plugin](https://github.com/Antibrumm/copy-maven-plugin/tree/copy-maven-plugin-1.0.0)
did not run without specifying additional dependencies
- override `commons-io` version to the one used by existdb (2.4.0-> 2.11.0)
- add dependency on `org.codehaus.plexus` 1.1 (also used by appassembler)
fixes #4749 
none

[build] add missing dependency to copy-maven-plugin

---

.github/workflows/ci-xqts.yml

closes #4707
By adding a new step into the XQTS workflow that checks for the existence of the temporary folder
the workflow now signals failure if no output was created.
This approach was discussed and agreed on the community call on 6.2.2023

CI: test xqts workflow

---

.github/workflows/ci-docs.yml

Javadoc fails due to a unkown SNAPSHOT version used.

[bugfix] Install current eXist binaries before javadoc

---

exist-xqts/pom.xml

Using the snapshot version should enable the XQTS tests again until the final eXist 7.0.0 has been released.
This fixes #4733

Use exist-xqts-runner Snapshot version in order to use eXist-db 7.0.0-SNAPSHOT

---

exist-core/pom.xml
exist-core/src/main/java/org/exist/collections/MutableCollection.java
exist-core/src/main/java/org/exist/storage/lock/LockGroup.java
exist-core/src/main/java/org/exist/storage/lock/LockManager.java
exist-core/src/main/java/org/exist/storage/lock/LockedPath.java
exist-core/src/main/java/org/exist/storage/lock/ManagedCollectionLock.java
exist-core/src/main/java/org/exist/storage/lock/ManagedDocumentLock.java
exist-core/src/main/java/org/exist/storage/lock/ManagedLock.java
exist-core/src/main/java/org/exist/storage/lock/ManagedLockGroupDocumentLock.java
exist-core/src/main/java/org/exist/storage/lock/ManagedSingleLockDocumentLock.java

Backported from FusionDB - improvements in the area of Collection and Document locks - some small reductions in the number of object allocations, less array copies, and ultimately less GC.

Lock object optimisation

---

extensions/indexes/indexes-integration-tests/pom.xml
extensions/indexes/indexes-integration-tests/src/test/java/xquery/indexing/tests/IndexingTests.java
extensions/indexes/indexes-integration-tests/src/test/resources-filtered/conf.xml
extensions/indexes/indexes-integration-tests/src/test/resources/log4j2.xml
extensions/indexes/indexes-integration-tests/src/test/xquery/indexing/tests/exist-matches.xqm
extensions/indexes/lucene/src/main/java/org/exist/indexing/lucene/LuceneMatchListener.java
extensions/indexes/pom.xml

Closes #2102
This PR prevents `scanMatches` from trying to find a match when there is no index configured, so it no longer results in an NPE.
You can now run:
```xquery
xquery version "3.1";
(: setup :)
let $data := 
<root>
<x>Hello </x> (: note the extra space we added to the x element here to get a match:)
<y>Hello</y>
</root>
let $xconf := 
<collection xmlns="http://exist-db.org/collection-config/1.0">
<index>
<lucene>
<text qname="x"/>
</lucene>
<ngram qname="y"/>
</index>
</collection>
let $xconf-col := xmldb:create-collection("/db/system/config/db", "temp")
let $store-xconf := xmldb:store($xconf-col, "collection.xconf", $xconf)
let $data-col := xmldb:create-collection("/db", "temp")
let $store-data := xmldb:store($data-col, "test.xml", $data)
(: the heart of the test :)
let $q := …
```

Hotfix for NPE in LuceneMatchListener.scanMatches when expanding node containing both Lucene & NGram matches

---

exist-core/src/test/xquery/xquery3/serialize.xql

fn:serialize tests with method adaptive _have_ to return strings
reinstate tests modified in #4622 and add two extra
XQSuite tests

[test] fix and add adaptive serialization tests

---

exist-core/src/main/java/org/exist/client/ClientFrame.java
exist-core/src/main/java/org/exist/client/InteractiveClient.java

1. Avoid IllegalArgumentException when formatting Instant retrieved via XML:DB API. This was accidentally caused by the update to the new XML:DB API.
2. Do not attempt to close already closed Collection after removing resources, avoids XMLDBException.

Small fixes for the Java Admin Client

---

exist-core/src/main/java/org/exist/repo/Deployment.java
exist-core/src/main/java/org/exist/security/AbstractUnixStylePermission.java
exist-core/src/test/java/org/exist/security/UnixStylePermissionTest.java

Xquery modules and collections have to be set as executable on installation if the mode set in conf.xml or in the permission element in repo.xml does not set it. With this PR applied this will be limited to the owner if the group or others cannot read or write the resource or collection.
refs #4686
Completes a TODO in the code.
Junit-Tests

[fix] permissions on install

---

exist-core/src/main/java/org/exist/backup/ExportGUI.java
exist-core/src/main/java/org/exist/backup/ExportMain.java
exist-core/src/main/java/org/exist/backup/Main.java
exist-core/src/main/java/org/exist/client/CommandlineOptions.java
exist-core/src/main/java/org/exist/jetty/JettyStart.java
exist-core/src/main/java/org/exist/jetty/ServerShutdown.java
exist-core/src/main/java/org/exist/launcher/LauncherWrapper.java
exist-core/src/main/java/org/exist/management/client/JMXClient.java
exist-core/src/main/java/org/exist/util/OSUtil.java
exist-distribution/pom.xml
exist-start/src/main/java/org/exist/start/Main.java

1. Previously `jmxclient.sh|.bat` would exit with an error.
2. Some `.sh|.bat` scripts did not have a CLI `--help` option, this has now been added to all.
3. Previously the usage text when passing `--help` at the CLI would show the application name as `AppAssemblerBooter` this has now been corrected.

Fix some issues with CLI args

---

exist-core/src/main/resources/org/exist/xquery/lib/xqsuite/examples.xql
exist-core/src/main/resources/org/exist/xquery/lib/xqsuite/xqsuite.xql

XQSuite's `assertXPath` annotation failed to account for results whose in-scope-namespaces changed the default element namespace (e.g., `<x xmlns="foo"/>`. As a result, users are forced to result to wildcards or Clark notation to select elements (e.g., `%test:assertXPath("$result/self::*:x")` or `%test:assertXPath("$result/self::Q{foo}x")`).
This PR adjusts how XQSuite detects namespaces in elements in functions' return values, and constructs a default element namespace declaration. In the example scenario described above, a test author could create the annotation, `%test:assertXPath("$result/self::x")`.
https://markmail.org/message/oxsuzh5elgtxlx23
XQSuite

[fix] XQSuite assertXPath annotation: Support default element namespace

---

extensions/modules/mail/src/main/java/org/exist/xquery/modules/mail/MailModule.java
extensions/modules/mail/src/main/java/org/exist/xquery/modules/mail/MailSessionFunctions.java
extensions/modules/mail/src/test/java/org/exist/xquery/modules/mail/SendEmailIT.java

This PR adds the XQuery function `mail:get-mail-session#2`, which adds authentication to the existing function.
It is the same as #4801, which is for the 6.x.x branch.
```
mail:get-mail-session($properties as element()?, $authentication as element()) as xs:long?
```
Opens a JavaMail session with authentication.
**Parameters:**
$properties? An optional JavaMail session properties in the form <properties><property name="" value=""/></properties>. The JavaMail properties are spelled out in Appendix A of the JavaMail specifications.
$authentication The username and password for authentication in the form <authentication username="" password=""/>.
**Returns:**
xs:long? : an xs:long representing the session handle.
Pieter Lamers from _John Benjamins Publishing Company_ asked me to make this. …

Add mail:get-mail-session#2 with authentication

---

exist-parent/pom.xml

Bumps license-maven-plugin from 4.0.rc1 to 4.2
Cherry-pick of #4829 including fix to pass build

build(deps): bump license-maven-plugin from 4.0.rc1 to 4.2

---

exist-parent/pom.xml

This reverts commit b6c8ed0af820a3b3cae50b48de5d35f3b666f671.
As builds are failing with exceptions caused by:
```
java.lang.NoClassDefFoundError: Could not initialize class net.sf.cglib.proxy.Enhancer
```
see: https://github.com/eXist-db/exist/pull/4852/checks#step:6:1178

Revert "build(deps): bump jacoco-maven-plugin from 0.8.8 to 0.8.9"

---

exist-core/src/main/java/org/exist/xquery/value/SubSequence.java
exist-core/src/test/xquery/subsequence.xq

Backport of #4850 
#4830 
XQSuite tests

[6.x.x] tails of subsequences off by one

---

extensions/indexes/lucene/src/main/java/org/exist/indexing/lucene/LuceneIndex.java

Corrects the capitalisation and spelling of 'Lucene' in error messages

Correct the capitalisation and spelling of 'Lucene' in error messages

---

exist-core/src/main/java/org/exist/launcher/ConfigurationDialog.java
exist-core/src/main/java/org/exist/launcher/ConfigurationUtility.java
exist-core/src/main/resources/org/exist/launcher/jetty.xsl

Updated jetty-http.xml and jetty-ssl.xml were being written by the configurator with a bad DTD, which on subsequent read by the configurator caused an exception, so that the NEXT versions of jetty-http.xml and jetty-ssl.xml were made empty. This then caused a startup crash.
1. Fix the DTD reference.
Also, configurator was reading the wrong field(s) for the http configuration, so
2. make configurator read the correct fields for jetty http configuration, so that subsequent edits of an already re-configured jetty don’t end up re-introducing the default (8080)
Closes https://github.com/eXist-db/exist/issues/4729
Unfortunately it is not simple to automate this testing. We have built a test distribution with the changes, installed it (`java -jar …

[fix] jetty configuration changes don't stick, and eventually crash eXist-db

---

.github/workflows/ci-deploy.yml
exist-docker/src/main/resources-filtered/Dockerfile

remove superfluous layers see experimental builds if it works
close #4894

Fix docker builds

---

exist-core/src/main/java/org/exist/xquery/functions/fn/FunAnalyzeString.java
exist-core/src/main/java/org/exist/xquery/functions/fn/FunMatches.java
exist-core/src/main/java/org/exist/xquery/functions/fn/FunReplace.java
exist-core/src/test/xquery/xquery3/matches.xqm
exist-core/src/test/xquery/xquery3/replace.xqm

Read the error code raised by the Saxon regular expression implementation.
This will now correctly raise FORX0002 when the pattern is invalid.
https://www.w3.org/TR/xpath-functions-31/#func-matches
added XQSuite tests

[bugfix] fn:matches error codes

---

exist-core/src/main/java/org/exist/repo/ClasspathHelper.java
exist-core/src/main/java/org/exist/repo/ExistPkgExtension.java

Backport of https://github.com/eXist-db/exist/pull/4902

[6.x.x] Ensure that EXPath packages installed in $EXIST_HOME/data/expathrepo are filesystem portable

---

exist-core/src/main/java/org/exist/repo/ClasspathHelper.java
exist-core/src/main/java/org/exist/repo/ExistPkgExtension.java

Closes https://github.com/eXist-db/exist/issues/4901
Previously classpath locations were stored as absolute paths, they are now stored as relative paths. Care has been taken to ensure that the code remains backwards compatible with existing eXist-db data dirs that are already using absolute paths.

Ensure that EXPath packages installed in $EXIST_HOME/data/expathrepo are filesystem portable

---

.github/workflows/ci-deploy.yml
.github/workflows/ci-test.yml
.github/workflows/ci-xqts.yml
.github/workflows/sonarcloud.yml

Follows on from https://github.com/eXist-db/exist/pull/4852

Further improvements to GitHub Actions config

---

exist-distribution/src/main/config/conf.xml
extensions/indexes/indexes-integration-tests/src/test/java/org/exist/indexing/EnforceIndexUseTest.java
schema/conf.xsd

Fixes #4884 
As discussed in #4884 we want to make the default value to be `strict`.
---
This open source contribution to the [exist](https://github.com/eXist-db/exist) project was commissioned by the Office of the Historian, U.S. Department of State, https://history.state.gov/.

[hotfix] set enforce-index-use default value to strict

---

exist-core/src/main/antlr/org/exist/xquery/parser/XQuery.g
exist-core/src/test/java/org/exist/http/RESTServiceTest.java
exist-core/src/test/java/org/exist/xquery/XPathQueryTest.java
exist-core/src/test/java/org/exist/xquery/XQueryFunctionsTest.java
exist-core/src/test/java/org/exist/xquery/XQueryTest.java
exist-core/src/test/java/org/exist/xquery/functions/util/EvalTest.java

This syntax has been deprecated in eXist [since 2006](https://github.com/eXist-db/exist/commit/1b99e4544d00d4c5602eb8b777498a6b2e30691f), and not allowed in XQuery [since 1.0](https://www.w3.org/TR/2010/REC-xquery-20101214/#id-variable-declarations).
As a breaking change, this needs to wait until a major release. I've tagged it as belonging to eXist 7.0.0.
I searched all eXist stock apps, as well as my own collection of app and library packages, and found none using the deprecated syntax.
- See above
- Updated tests included

Remove pre-1.0 syntax for variable declarations

---

exist-core/src/main/java/org/exist/xquery/value/UntypedAtomicValue.java
exist-core/src/test/xquery/xquery3/castable-untyped-atomic.xqm

It appears perfectly acceptable for UntypedAtomicValue.convertTo to convert to subtypes of Type.STRING as StringValue(… value, requiredType). The conversion was omitted, and the omission was breaking “castable as” for Type.NCNAME in particular.
These conversions are already acceptable for StringValue(s), and are borrowed from there.
Closes https://github.com/eXist-db/exist/issues/4518
xquery unit test added which tests a variety of atomic values `castable as` an NCName successfully. Failing prior to the code change.

[fix] castable as for untyped atomic value(s)

---

exist-distribution/pom.xml

Closes https://github.com/eXist-db/exist/pull/4779
Closes https://github.com/Antibrumm/copy-maven-plugin/issues/7

Use newer copy-maven-plugin which does not have CVE issues with its dependencies

---

exist-parent/pom.xml

This resolves an issue whereby we previously had multiple transient versions of jakarta activation which broke assembly of the exist-xqts-runner against eXist-db 7.0.0-SNAPSHOT.

Upgrade from JAXB 3 to JAXB 4

---

exist-core/src/main/java/org/exist/xquery/functions/fn/transform/Convert.java
exist-core/src/test/java/xquery/xquery3/XQuery3Tests.java
exist-core/src/test/xquery/xquery3/transform/fnTransformRegressionDocAsParameter.xqm

It was previously not possible to pass nodes (e.g. documents) stored in the db from XQuery to `fn:transform` as parameters. 
The error encountred was:
```
class org.exist.dom.persistent.NodeProxy cannot be cast to class org.w3c.dom.Node (org.exist.dom.persistent.NodeProxy is in unnamed module of loader java.net.URLClassLoader @421faab1; org.w3c.dom.Node is in module java.xml of loader 'bootstrap')
```
This PR addresses this by accepting a `NodeProxy` and dereferencing it in cases in `fn:transform` implementation where a node was expected.

Fix passing database nodes from XQuery to fn:transform as parameters

---

exist-core/src/main/java/org/exist/util/SaxonConfiguration.java
exist-core/src/main/java/org/exist/xquery/functions/fn/transform/Options.java
exist-core/src/main/java/org/exist/xquery/functions/fn/transform/Transform.java
exist-core/src/main/java/org/exist/xquery/functions/fn/transform/URIResolution.java
exist-core/src/test/java/org/exist/xquery/functions/fn/transform/FunTransformTest.java

URI resolution passed to Saxon (used internally by `fn:rransform`) was not handling xmldb: URIs. Add a special case for this in the resolution used by `fn:transform`.
Closes https://github.com/eXist-db/exist/issues/3820
Discussed in https://stackoverflow.com/questions/73454333/xslt-fntransform-with-stylesheet-in-exist-db-having-xslimport
Manual test of xsl:import of database documents using eXide
Unit tests for updated resolution method

Fix the resolution of XmldbURIs from within fn:transform

---

exist-xqts/src/main/xslt/compare-results.xslt

In the XQTS CI job, there was a simple mistake in the XSLT that caused all test names to be returned rather than just those that have changed.

Comparison on node identity was incorrect, and so too much data was returned

---

.github/actions/install-mvnd/action.yml
.github/workflows/ci-test.yml

Builds atop https://github.com/eXist-db/exist/pull/4917 to switch CI from using `mvn` to `mvnd` (i.e. Maven Daemon)

Use mvnd in GitHub Actions

---

exist-distribution/pom.xml

Backport of https://github.com/eXist-db/exist/pull/4934

[6.x.x] Use newer copy-maven-plugin which does not have CVE issues with its dependencies

---

exist-core/src/main/java/org/exist/xquery/functions/fn/transform/Options.java
exist-core/src/main/java/org/exist/xquery/functions/fn/transform/Transform.java
exist-core/src/test/resources/org/exist/xquery/tei-toc.xsl
exist-core/src/test/xquery/xquery3/transform/fnTransformIssue4609.xqm

Backport of https://github.com/eXist-db/exist/pull/4883

[6.x.x] Fix missing fn:transform global parameters

---

exist-core/src/main/java/org/exist/management/impl/ExistMBean.java
exist-core/src/main/java/org/exist/management/impl/JMXAgent.java
exist-core/src/main/java/org/exist/management/impl/PerInstanceMBean.java
exist-core/src/main/java/org/exist/management/impl/ProcessReport.java
exist-core/src/main/java/org/exist/management/impl/ProcessReportMXBean.java
exist-core/src/main/java/org/exist/management/impl/RecentQueryHistory.java
exist-core/src/main/java/org/exist/management/impl/RunningQuery.java
exist-core/src/main/java/org/exist/management/impl/SystemInfo.java

To improve interoperability with a number of tools that consume JMX, this switches eXist-db from exporting JMX `CompositeData` to exporting `TabularData` for:
1. Running Queries
2. Recent Queries
3. Running Jobs
4. Scheduled Jobs

Improve JMX output

---

exist-core/src/main/java/org/exist/xquery/CastExpression.java
exist-core/src/test/xquery/xquery3/arrowop.xql
exist-core/src/test/xquery/xquery3/cast-constructor.xqm
exist-core/src/test/xquery/xquery3/castable-untyped-atomic.xqm

Type constructors like `xs:string` or `xs:integer` did wrongly check for EXACTLY_ONE item passed to them when used as a function. This happens for instance when used on the right hand side of an arrow operator.
```xquery
() => xs:string()
```
would fail with a cardinality error. The error message itself is hard to understand which should be addressed in a following PR.
This PR fixes the cast function to allow an empty sequence as its parameter.
fixes #4971 
XQSuite tests

[fix] cardinality of CastExpression#toFunction

---

exist-core/src/main/java/org/exist/xquery/functions/fn/transform/Options.java
exist-core/src/main/java/org/exist/xquery/functions/fn/transform/Transform.java

It looks like some Java 17 code snuck into eXist-db 6.x.x, this restores compatibility with Java 8.

[6.x.x] Restore compatibility with Java language level 8

---

extensions/modules/cache/src/main/java/org/exist/xquery/modules/cache/Cache.java
extensions/modules/cache/src/main/java/org/exist/xquery/modules/cache/CacheConfig.java
extensions/modules/cache/src/main/java/org/exist/xquery/modules/cache/CacheFunctions.java
extensions/modules/cache/src/main/java/org/exist/xquery/modules/cache/CacheModule.java
extensions/modules/cache/src/test/xquery/modules/cache/cache.xqm

This feature adds a configuration option 'expireAfterWrite' to the `$config` parameter of `cache:create()`.
This option is available in the Caffeine cache, but was not supported in eXist.
I have not made a GitHub issue requesting this feature.
A test has been added to `extensions\modules\cache\src\test\xquery\modules\cache\cache.xqm`.
It is similar to the test for `expireAfterAccess`.

Add support in `cache:create()` for 'expireAfterWrite' in `$config`

---

extensions/modules/cache/src/main/java/org/exist/xquery/modules/cache/Cache.java
extensions/modules/cache/src/main/java/org/exist/xquery/modules/cache/CacheConfig.java
extensions/modules/cache/src/main/java/org/exist/xquery/modules/cache/CacheFunctions.java
extensions/modules/cache/src/main/java/org/exist/xquery/modules/cache/CacheModule.java
extensions/modules/cache/src/test/xquery/modules/cache/cache.xqm

This is a forward port of #4975 to the develop [7.x.x] branch.
This feature adds a configuration option 'expireAfterWrite' to the $config parameter of cache:create().
This option is available in the Caffeine cache, but was not supported in eXist.

[7.x.x] Add support in cache:create() for 'expireAfterWrite' in $config

---

exist-parent/pom.xml

For a long time the retrieval of the owasp data is not reliable. This is a test to verify if the details configuration works more reliable.
... wait for build

[build] Use original CVE files

---

exist-core/src/main/java/org/exist/xquery/GeneralComparison.java
exist-core/src/main/java/org/exist/xquery/Optimizable.java
exist-core/src/main/java/org/exist/xquery/functions/fn/FunMatches.java
exist-core/src/main/java/org/exist/xquery/pragmas/Optimize.java
extensions/indexes/lucene/src/main/java/org/exist/xquery/modules/lucene/Query.java
extensions/indexes/lucene/src/main/java/org/exist/xquery/modules/lucene/QueryField.java
extensions/indexes/ngram/src/main/java/org/exist/xquery/modules/ngram/NGramSearch.java
extensions/indexes/range/src/main/java/org/exist/xquery/modules/range/FieldLookup.java
extensions/indexes/range/src/main/java/org/exist/xquery/modules/range/Lookup.java
extensions/indexes/range/src/test/resources-filtered/conf.xml
extensions/indexes/range/src/test/xquery/range/multi-collection-search.xqm

Fixes #3620 
When performing a Search on a parent collection that has several sub-collections each with different types of indexes configured, The optimizer was optimizing the query without checking if all sub-collections were fit to be optimized.
#3620 has a nice test suit to illustrate this issue thanks to @joewiz. This PR now passes all of those tests.
----
This open source contribution to the [exist](https://github.com/eXist-db/exist) project was commissioned by the Office of the Historian, U.S. Department of State, https://history.state.gov/.

Prevent omission of results from collections with different index styles 

---

exist-core/src/test/xquery/xquery3/serialize.xql

Refactor serialization tests for maintainability and readability.
- combine item-separator with method tests into one
`ser:item-separator-with-method`
- simplify test cases that used eq in combination with assertXPath
- make direct calls to function under test (serialize) in each test
- extract fixtures to module variables
- remove namespace from children of output:serialization-parameters
- convert QNames keys to strings for exist-db specific options
- convert string constructors to CDATA sections
- make HTML5 test data real world examples
- use unprefixed form of built-ins
- fix formatting
has to wait for
- #4773 
- #4816
XQSuite

[test] refactor serialization suite

---

exist-core/src/main/java/org/exist/xquery/XQueryContext.java
exist-core/src/main/java/org/exist/xquery/functions/request/GetData.java
exist-core/src/test/java/org/exist/xquery/functions/request/GetData2Test.java
extensions/exquery/restxq/src/main/java/org/exist/extensions/exquery/restxq/impl/RestXqServiceImpl.java

We believe we have seen some instances where calls to `request:get-data()` return an Empty Sequence even when there is request body content in the incoming HTTP request.
We think that the issue may be caused by the use of calls to `InputStream#available()` which may return a `0` when there is no data that can be read without blocking; this does **not** mean however that there is no data to read.
The eXist-db user experiencing this problem has trialed the patch in this PR and reported back to us that they believe they no longer experience the issue.

[6.x.x] InputStream#available() should not be used to determine if there is data available

---

exist-core/src/main/java/org/exist/xquery/functions/securitymanager/GroupManagementFunction.java
exist-core/src/main/java/org/exist/xquery/functions/system/FunctionTrace.java
exist-core/src/main/java/org/exist/xquery/functions/system/Shutdown.java
exist-core/src/main/java/org/exist/xquery/functions/system/TriggerSystemTask.java
exist-core/src/main/java/org/exist/xquery/functions/transform/Transform.java
exist-core/src/main/java/org/exist/xquery/functions/util/LogFunction.java
exist-core/src/main/java/org/exist/xquery/functions/util/Profile.java
exist-core/src/main/java/org/exist/xquery/functions/util/PrologFunctions.java
exist-core/src/main/java/org/exist/xquery/functions/xmldb/XMLDBDefragment.java
exist-core/src/main/java/org/exist/xquery/functions/xmldb/XMLDBMove.java
exist-core/src/main/java/org/exist/xquery/functions/xmldb/XMLDBRemove.java
exist-core/src/main/java/org/exist/xquery/functions/xmldb/XMLDBRename.java
exist-core/src/test/java/org/exist/storage/util/PauseFunction.java
extensions/modules/mail/src/main/java/org/exist/xquery/modules/mail/SendEmailFunction.java

This PR corrects the return type of functions that return `empty-sequence()`. Before this PR, the function signatures of several functions were described as returning a sequence of type `item()` with a cardinality of "empty sequence":
```java
SequenceType(Type.ITEM, Cardinality.EMPTY_SEQUENCE)
```
With this PR, the function signatures are now updated to return a sequence of type `empty-sequence()` and an unchanged cardinality:
```java
SequenceType(Type.EMPTY, Cardinality.EMPTY_SEQUENCE)
```
I shared my observation about this issue in Slack on July 18, 2023, at https://exist-db.slack.com/archives/CG2MRUZ35/p1689734379824689. Referencing the two code snippets above, I wrote:
> I don’t see why any function that returns an empty sequence should use the former instead of the latter. Shall I …

[bugfix] Correct function signatures that return empty sequences

---

exist-core/src/main/java/org/exist/xquery/CastExpression.java
exist-core/src/test/xquery/xquery3/arrowop.xql
exist-core/src/test/xquery/xquery3/cast-constructor.xqm

Backport of #4973 to eXist-6.x.x
fixes #4971
XQSuite tests

[6.x.x] cardinality of CastExpression#toFunction

---

exist-core/src/main/java/org/exist/xquery/functions/securitymanager/GroupManagementFunction.java
exist-core/src/main/java/org/exist/xquery/functions/system/FunctionTrace.java
exist-core/src/main/java/org/exist/xquery/functions/system/Shutdown.java
exist-core/src/main/java/org/exist/xquery/functions/system/TriggerSystemTask.java
exist-core/src/main/java/org/exist/xquery/functions/transform/Transform.java
exist-core/src/main/java/org/exist/xquery/functions/util/LogFunction.java
exist-core/src/main/java/org/exist/xquery/functions/util/Profile.java
exist-core/src/main/java/org/exist/xquery/functions/util/PrologFunctions.java
exist-core/src/main/java/org/exist/xquery/functions/xmldb/XMLDBDefragment.java
exist-core/src/main/java/org/exist/xquery/functions/xmldb/XMLDBMove.java
exist-core/src/main/java/org/exist/xquery/functions/xmldb/XMLDBRemove.java
exist-core/src/main/java/org/exist/xquery/functions/xmldb/XMLDBRename.java
exist-core/src/test/java/org/exist/storage/util/PauseFunction.java
extensions/modules/mail/src/main/java/org/exist/xquery/modules/mail/SendEmailFunction.java

[6.x.x] Correct function signatures that return empty sequences

---

exist-core/src/main/java/org/exist/xquery/TryCatchExpression.java

This was previously incorrectly assigned as xs:QName rather than xs:string

Correct the XDM type for the Sequence holding a representation of a Java Stack Trace when an error occurs

---

exist-core/src/main/java/org/exist/xquery/TryCatchExpression.java

Backport of https://github.com/eXist-db/exist/pull/4992

[6.x.x] Correct the XDM type for the Sequence holding a representation of a Java Stack Trace when an error occurs

---

exist-core/src/main/java/org/exist/http/servlets/EXistServlet.java

The exception was missing for a `BadRequestException` in this one location

Log exception if the response is already committed

---

exist-core/src/main/java/org/exist/xquery/Function.java
exist-core/src/main/java/org/exist/xquery/FunctionSignature.java
exist-core/src/main/java/org/exist/xquery/functions/fn/FunHigherOrderFun.java
exist-core/src/main/java/org/exist/xquery/functions/fn/FunNamespaceURI.java
exist-core/src/main/java/org/exist/xquery/functions/fn/LoadXQueryModule.java
exist-core/src/main/java/org/exist/xquery/functions/response/StreamBinary.java
exist-core/src/main/java/org/exist/xquery/functions/util/GetFragmentBetween.java
extensions/indexes/range/src/test/xquery/range/range.xql

The _overloaded_ flag is set to `true` for functions like `fn:concat`, which has an unlimited arity.
The term does however have a different meaning and therefore lead to confusion when I touched code in #3389.
It is therefore better to call this flag variadic (see the references for details).
The getter function and constructor parameter names are renamed to reflect this.
`response:stream-binary` and `util:get-fragment-between` are both non-variadic but flagged as such. This flag is removed.
`fn:namespace-uri#0` and `fn:namespace-uri#1` were flagged as non-variadic, which is the default. Therefore, setting of the flag is removed.
**Note:** There are variadic functions in the `range` module (FieldLookup.java). Removing the flag for `range:field-eq` for example results in failing tests. I …

Rename Function flag overloaded to variadic

---

exist-core/src/main/java/org/exist/client/InteractiveClient.java
exist-core/src/main/java/org/exist/repo/ExistRepository.java
exist-core/src/main/java/org/exist/util/Configuration.java
exist-core/src/main/java/org/exist/util/ConfigurationHelper.java
exist-core/src/main/java/org/exist/util/SingleInstanceConfiguration.java
exist-core/src/main/java/org/exist/xquery/XQueryContext.java
exist-parent/pom.xml

1. Given two EXPath Packages: `PkgA` and `PkgB`.
2. `PkgA` exports an XQuery Library Module via its `expath-pkg.xml` descriptor:
```xml
<xquery>
<namespace>https://pkgA/service</namespace>
<file>modules/service.xqm</file>
</xquery>
```
3. `PkgA`'s `modules/service.xqm` imports an XQuery Module - `config.xqm`, i.e..: `import module namespace config = "https://pkgA/config" at "config.xqm";`
4. `PkgB` contains an XQuery Library Module which imports `service.xqm` from `PkgA`, i.e.: `import module namespace validation-service = "https://pkgA/service";`
When the XQuery Library Module from `PkgB` was used, it would fail to compile as it attempted to import `PkgA`, but the compilation of `PkgA` was looking in the wrong location to find the code for `config.xqm`.
This PR fixes the above issue with …

[6.x.x] Fix an issue with XQuery transient imports within EXPath Package

---

exist-docker/src/main/resources-filtered/Dockerfile-DEBUG

Just makes the JDWP Suspend feature overridable by the user at Docker Image build time.
This can be passed to Maven `-Ddocker.buildArg.JVM_JDWP_SUSPEND=y`

Allow the user to override the JDWP Suspend at Docker build time

---

exist-docker/src/main/resources-filtered/Dockerfile

Backport of https://github.com/eXist-db/exist/pull/5005

[5.x.x] Fix the use of Debian Stretch repositories in the Docker builds

---

exist-core/src/main/java/org/exist/dom/QName.java
exist-core/src/main/java/org/exist/storage/NodePath.java
exist-core/src/main/java/org/exist/xquery/functions/inspect/InspectFunctionHelper.java
exist-core/src/main/java/org/exist/xquery/functions/inspect/InspectModule.java
exist-core/src/main/java/org/exist/xquery/functions/util/DescribeFunction.java
exist-core/src/test/java/org/exist/storage/NodePathTest.java

NodePath equality (i.e. `NodePath#equals()`) could return the wrong result if a `NodePath` object was being reused.

[6.x.x] Fix a bug in Node Path equality

---

exist-core/src/main/java/org/exist/dom/persistent/Match.java
exist-core/src/main/java/org/exist/dom/persistent/NewArrayNodeSet.java
exist-core/src/main/java/org/exist/dom/persistent/NodeProxy.java
exist-core/src/main/java/org/exist/xquery/CombiningExpression.java
exist-core/src/main/java/org/exist/xquery/FilteredExpression.java
exist-core/src/main/java/org/exist/xquery/LocationStep.java
exist-core/src/main/java/org/exist/xquery/Optimizer.java
exist-core/src/main/java/org/exist/xquery/Pragma.java
exist-core/src/main/java/org/exist/xquery/pragmas/Optimize.java
extensions/indexes/lucene/src/main/java/org/exist/indexing/lucene/LuceneConfig.java
extensions/indexes/lucene/src/main/java/org/exist/indexing/lucene/LuceneIndex.java
extensions/indexes/lucene/src/main/java/org/exist/indexing/lucene/LuceneIndexWorker.java
extensions/indexes/lucene/src/main/java/org/exist/indexing/lucene/LuceneMatch.java
extensions/indexes/lucene/src/main/java/org/exist/xquery/modules/lucene/Query.java
extensions/indexes/lucene/src/main/java/org/exist/xquery/modules/lucene/QueryField.java
extensions/indexes/lucene/src/test/xquery/lucene/facets.xql
extensions/indexes/ngram/src/main/java/org/exist/indexing/ngram/NGramMatch.java
extensions/indexes/range/src/main/java/org/exist/xquery/modules/range/OptimizeFieldPragma.java

Closes https://github.com/eXist-db/exist/issues/3207
Fixes a number of bugs whereby too many Matches were set from `ft:query` and several potentially optimisable expressions were not correctly optimised.
----

Fix issues with Lucene Index optimisations and Matches

---

exist-core/src/main/java/org/exist/util/GZIPInputSource.java
exist-core/src/main/java/org/exist/util/io/TemporaryFileManager.java
exist-core/src/main/java/org/exist/xmldb/AbstractRemoteResource.java
exist-core/src/main/java/org/exist/xmldb/RemoteResourceSet.java
exist-core/src/main/java/org/exist/xmlrpc/AbstractCachedResult.java
exist-core/src/main/java/org/exist/xquery/value/IntegerValue.java
exist-core/src/test/java/org/exist/TestDataGenerator.java
exist-core/src/test/java/org/exist/collections/ConcurrencyTest.java
exist-core/src/test/java/org/exist/xquery/XPathQueryTest.java

- Replaced all terminally deprecated constructors for primitive data types with their `valueOf` counter parts.
- Removed all `finalize()` methods, where a according `close()` method exists thru `AutoClosable`
- Replaced `finalize()` method with shutdown hook within `TemporaryFileManager`

[cleanup] clean up deprecated methods

---

exist-core/src/main/java/org/exist/xmldb/RemoteCollection.java
exist-core/src/main/java/org/exist/xmlrpc/RpcAPI.java
exist-core/src/main/java/org/exist/xmlrpc/RpcConnection.java
exist-core/src/test/java/org/exist/xmlrpc/MimeTypeTest.java

Closes #5067.
Since XML resources are always and only stored via the `parse()` method, we need to pass the Media Type as a parameter to this method.
A unit test in `exist-core/src/test/java/org/exist/xmlrpc`: `MimeTypeTest`
I successfully ran the full maven reactor locally.

Parameterise the XML-RPC parse method with the Media Type

---

exist-core/src/main/java/org/exist/xmldb/RemoteCollection.java
exist-core/src/main/java/org/exist/xmlrpc/RpcAPI.java
exist-core/src/main/java/org/exist/xmlrpc/RpcConnection.java
exist-core/src/test/java/org/exist/xmlrpc/MimeTypeTest.java

This is a cherry-pick of PR #5070 onto the `develop-5.x.x` branch.

[5.x.x] Parameterise the XML-RPC parse method with the Media Type

---

exist-core/pom.xml
exist-core/src/main/java/org/exist/xquery/AbstractPragma.java
exist-core/src/main/java/org/exist/xquery/ExtensionExpression.java
exist-core/src/main/java/org/exist/xquery/Optimizer.java
exist-core/src/main/java/org/exist/xquery/Option.java
exist-core/src/main/java/org/exist/xquery/Pragma.java
exist-core/src/main/java/org/exist/xquery/XQueryContext.java
exist-core/src/main/java/org/exist/xquery/pragmas/ForceIndexUse.java
exist-core/src/main/java/org/exist/xquery/pragmas/NoIndexPragma.java
exist-core/src/main/java/org/exist/xquery/pragmas/Optimize.java
exist-core/src/main/java/org/exist/xquery/pragmas/ProfilePragma.java
exist-core/src/main/java/org/exist/xquery/pragmas/TimePragma.java
exist-core/src/main/java/org/exist/xquery/pragmas/TimerPragma.java
extensions/indexes/range/src/main/java/org/exist/xquery/modules/range/OptimizeFieldPragma.java

Backported from FusionDB - A new XQuery Pragma called `exist:time` that is backwards compatible with the previous limited `exist:timer` pragma.
Like its predecessor `exist:timer` it can be used for timing an XQuery expression. However, its main advantage is that it can also be used to log multiple iterations of the same expression using the parameter `measurement-mode=multiple`. In addition to that the new `exist:time` pragma also adds:
1. Nanosecond precision (useful for measuring very fast expressions or multiple iterations thereof)
2. A humane format output of the total time elapsed.
3. Automatically adapts output between `ns` and `ms` units depending on the magnitude of the measurement
4. A `logging-level` parameter so that you may set the log-level dynamically on invocation.
5. …

[6.x.x] New exist:time XQuery Pragma

---

exist-core/pom.xml
exist-core/src/main/java/org/exist/interpreter/Context.java
exist-core/src/main/java/org/exist/storage/NativeBroker.java
exist-core/src/main/java/org/exist/util/serializer/XQuerySerializer.java
exist-core/src/main/java/org/exist/xquery/ModuleContext.java
exist-core/src/main/java/org/exist/xquery/XQueryContext.java
exist-core/src/test/java/org/exist/xquery/ImportModuleTest.java
extensions/exquery/restxq/pom.xml
extensions/exquery/restxq/src/main/java/org/exist/extensions/exquery/restxq/impl/RestXqServiceRegistryManager.java
extensions/exquery/restxq/src/test/java/org/exist/extensions/exquery/restxq/impl/AbstractClassIntegrationTest.java
extensions/exquery/restxq/src/test/java/org/exist/extensions/exquery/restxq/impl/AbstractInstanceIntegrationTest.java
extensions/exquery/restxq/src/test/java/org/exist/extensions/exquery/restxq/impl/AbstractIntegrationTest.java
extensions/exquery/restxq/src/test/java/org/exist/extensions/exquery/restxq/impl/IntegrationTest.java
extensions/exquery/restxq/src/test/java/org/exist/extensions/exquery/restxq/impl/LibraryCircularDependencyIntegrationTest.java
extensions/exquery/restxq/src/test/java/org/exist/extensions/exquery/restxq/impl/MediaTypeIntegrationTest.java
extensions/exquery/restxq/src/test/java/org/exist/extensions/exquery/restxq/impl/SelfImportCircularDependencyIntegrationTest.java
extensions/exquery/restxq/src/test/resources-filtered/conf.xml
extensions/exquery/restxq/src/test/resources/standalone-webapp/WEB-INF/controller-config.xml
extensions/exquery/restxq/src/test/resources/standalone-webapp/WEB-INF/web.xml

These errors although mostly in eXist-db itself were easy to manifest through using RESTXQ.
Closes https://github.com/eXist-db/exist/issues/3448
Closes https://github.com/eXist-db/exist/issues/1010
Closes https://github.com/eXist-db/exist/pull/4699
1. The first thing that this PR deals with is a Library Module that attempts to import itself. Whilst BaseX raises an error, and Saxon allows it. With this PR eXist-db now follows Saxon in basically skipping the superfluous import and continues. This is inline with the W3C XQuery 3.1 specification which states:
> The namespace prefix specified in a module declaration must not be xml or xmlns [err:XQST0070], and must not be the same as any namespace prefix bound in the same module by a schema import, by a namespace declaration, or by a module …

Fixes to eXist-db regarding circular imports

---

exist-core/src/main/java/org/exist/xquery/AbstractPragma.java
exist-core/src/main/java/org/exist/xquery/BasicExpressionVisitor.java
exist-core/src/main/java/org/exist/xquery/ExtensionExpression.java
exist-core/src/main/java/org/exist/xquery/Optimizer.java
exist-core/src/main/java/org/exist/xquery/pragmas/TimePragma.java

Forward port of https://github.com/eXist-db/exist/pull/5083
**NOTE**: requires https://github.com/eXist-db/exist/pull/5082 to be merged first.

Optimise Path Expressions that are visited by the BasicExpressionVisitor

---

exist-core/src/main/java/org/exist/xquery/AbstractPragma.java
exist-core/src/main/java/org/exist/xquery/BasicExpressionVisitor.java
exist-core/src/main/java/org/exist/xquery/ExtensionExpression.java
exist-core/src/main/java/org/exist/xquery/Optimizer.java
exist-core/src/main/java/org/exist/xquery/pragmas/TimePragma.java
extensions/indexes/range/pom.xml

Previously Path Expressions visited by the BasicExpressionVisitor were not optimisable. This means that a number of possible optimisations were never applied. One such example is that  expressions inside of Extension Expressions were not previously optimised.
This PR also includes a number of micro-optimisations to reduce memory use of the optimizer a small amount.
**NOTE**: requires https://github.com/eXist-db/exist/pull/5081 to be merged first.

[6.x.x] Optimise Path Expressions that are visited by the BasicExpressionVisitor

---

extensions/modules/file/src/main/java/org/exist/xquery/modules/file/DirectoryList.java
extensions/modules/file/src/main/java/org/exist/xquery/modules/file/FileErrorCode.java
extensions/modules/file/src/test/xquery/modules/file/directory-list.xqm

Closes #5028
The Java code of DirectoryList can throw an IllegalStateException when a non-existent directory is supplied as its first argument. This exception class is now handled in file:list#2.
This is a forward port of #5061 
Thanks to @nverwer for bringing this up and also finding the fix.

Handle IllegalStateException in `file:directory-list#2`

---

extensions/modules/file/src/main/java/org/exist/xquery/modules/file/DirectoryList.java
extensions/modules/file/src/main/java/org/exist/xquery/modules/file/FileErrorCode.java
extensions/modules/file/src/test/xquery/modules/file/directory-list.xqm

Backport of https://github.com/eXist-db/exist/pull/5092
Supersedes #5061

[6.x.x] Handle IllegalStateException in file:directory-list#2

---

CONTRIBUTING.md
PR-CODE-REVIEW-POLICY.md

Updates the CONTRIBUTING.md developer documentation so that it is up to date and also adds a copy of [Community Code Review and Merge Policy for the exist-db/exist Git Repository v2](https://docs.google.com/document/d/1O724HZ2s3ffhclMATVpVTIskdCNhazA11A7GqxlGe24) as Markdown to the Git repo so that it can be easily referenced.

Bring the CONTRIBUTING.md developer documentation up to date

---

exist-core/pom.xml
exist-core/src/main/antlr/org/exist/xquery/parser/XQueryTree.g
exist-core/src/main/java/org/exist/xquery/NamedFunctionReference.java
exist-core/src/test/xquery/xquery3/postfix-expr.xqm

There was previously a bug in the XQuery Parser where Postfix Expressions could not be used in all places where the XQuery 3.1 specification allows them. For example, this valid XQuery would not compile before this PR:
```xquery
xs:string#1("hello")
```

[6.x.x] Named Function References can have Postfix Expressions

---

schema/collection.xconf.xsd
schema/conf.xsd
schema/controller-config.xsd
schema/descriptor.xsd
schema/expath-pkg-extensions/cxan.xsd
schema/expath-pkg-extensions/exist.xsd
schema/expath-pkg-extensions/repo.xsd
schema/expath-pkg.xsd
schema/mime-types.xsd
schema/security-manager.xsd
schema/server.xsd
schema/users.xsd

Adds missing XML Schema fro EXPath Packaging System and related (undocumented) eXist-db extensions.

[6.x.x] Add Schema for EXPath Packaging System

---

.github/CODEOWNERS

This adds a CODEOWNERS file to GitHub as discussed in the last community call.

[ci] add CODEOWNERS file for GitHub

---

exist-core/src/main/antlr/org/exist/xquery/parser/XQuery.g
exist-core/src/main/antlr/org/exist/xquery/parser/XQueryTree.g
exist-core/src/main/java/org/exist/xquery/AbstractFLWORClause.java
exist-core/src/main/java/org/exist/xquery/BasicExpressionVisitor.java
exist-core/src/main/java/org/exist/xquery/BindingExpression.java
exist-core/src/main/java/org/exist/xquery/CountClause.java
exist-core/src/main/java/org/exist/xquery/ExpressionVisitor.java
exist-core/src/main/java/org/exist/xquery/FLWORClause.java
exist-core/src/main/java/org/exist/xquery/ForExpr.java
exist-core/src/main/java/org/exist/xquery/GroupByClause.java
exist-core/src/main/java/org/exist/xquery/LetExpr.java
exist-core/src/main/java/org/exist/xquery/OrderByClause.java
exist-core/src/main/java/org/exist/xquery/QuantifiedExpression.java
exist-core/src/main/java/org/exist/xquery/WhereClause.java
exist-core/src/main/java/org/exist/xquery/XQuery.java
exist-core/src/main/java/org/exist/xquery/value/DoubleValue.java
exist-core/src/main/java/org/exist/xquery/value/FloatValue.java
exist-core/src/test/java/org/exist/xquery/CountExpressionTest.java
exist-core/src/test/xquery/count.xql
exist-core/src/test/xquery/xquery3/count.xqm

This is currently passing 12 out of 13 XQTS tests. The 1 failing test is: `prod-CountClause/count-009`. 
The 1 failing test occurs due to the existing design and implementation of FLWOR expressions in eXist-db.
Specifically, eXist-db's implementation of the XQuery `order by` clause does not follow the W3C specification. The W3C XQuery 3.1 [Order By Clause](https://www.w3.org/TR/xquery-31/#id-order-by-clause) specification states:
> The purpose of an order by clause is to impose a value-based ordering on the tuples in the tuple stream. The output tuple stream of the order by clause contains the same tuples as its input tuple stream, but the tuples may be in a different order.
This means that any tuples in a tuple stream after an Order By Clause should be in the order defined by the order …

Support for Count Expressions

---

exist-installer/src/main/izpack/UnixShortcutSpec.xml
exist-installer/src/main/izpack/custom.eng.xml
exist-installer/src/main/izpack/install.xml
exist-installer/src/main/izpack/jobs.xml
exist-installer/src/main/izpack/shortcutSpec.xml
exist-installer/src/main/izpack/userInput.xml

Addes correct izPack 5 schema headers and fixes resulting schema errors within shortcut panel specs.
This fix is a precondiiton in order for the #5213 to be accepted.

[bugfix] Fixes izPack schema issues

---

exist-ant/pom.xml
exist-core/pom.xml
exist-core/src/main/java/org/exist/util/Configuration.java
exist-core/src/main/java/org/exist/util/io/ContentFile.java
exist-core/src/main/java/org/exist/util/io/ContentFilePool.java
exist-core/src/main/java/org/exist/util/io/ContentFilePoolObjectFactory.java
exist-core/src/main/java/org/exist/util/io/MemoryContentsImpl.java
exist-core/src/main/java/org/exist/util/io/VirtualTempPath.java
exist-core/src/test/java/org/exist/storage/lock/CollectionLocksTest.java
exist-core/src/test/java/org/exist/util/ConfigurationTest.java
exist-core/src/test/java/org/exist/util/io/ContentFilePoolTest.java
exist-core/src/test/resources-filtered/conf.xml
exist-distribution/src/main/config/conf.xml
exist-parent/pom.xml
extensions/contentextraction/pom.xml
extensions/exquery/restxq/pom.xml
extensions/indexes/lucene/pom.xml
extensions/indexes/range/pom.xml
extensions/indexes/spatial/pom.xml
extensions/modules/counter/pom.xml
extensions/modules/file/pom.xml
extensions/modules/image/pom.xml
extensions/modules/persistentlogin/pom.xml
extensions/modules/xmldiff/pom.xml
extensions/security/activedirectory/pom.xml
extensions/security/ldap/pom.xml
extensions/webdav/pom.xml
schema/conf.xsd

Backport of https://github.com/eXist-db/exist/pull/5195

[6.x.x] Adds ContentFilePool and companion tests

---

exist-core/pom.xml
exist-core/src/main/java/org/exist/util/io/ContentFilePool.java
exist-core/src/main/java/org/exist/util/io/MemoryContentsInputStream.java
exist-core/src/main/java/org/exist/util/io/VirtualTempPath.java
exist-core/src/main/java/org/exist/xmlrpc/CachedContentFile.java
exist-core/src/main/java/org/exist/xmlrpc/QueryResultCache.java
exist-core/src/main/java/org/exist/xmlrpc/RpcAPI.java
exist-core/src/main/java/org/exist/xmlrpc/RpcConnection.java
exist-core/src/main/java/org/exist/xmlrpc/XmldbRequestProcessorFactory.java
exist-core/src/test/java/org/exist/util/io/ContentFilePoolTest.java
exist-core/src/test/java/org/exist/util/io/MemoryContentsInputStreamTest.java
exist-core/src/test/java/org/exist/util/io/VirtualTempPathTest.java
exist-core/src/test/java/org/exist/xmlrpc/CachedContentFileTest.java
exist-core/src/test/java/org/exist/xmlrpc/QueryResultCacheTest.java
exist-core/src/test/java/org/exist/xmlrpc/XmlRpcTest.java
exist-distribution/src/main/config/conf.xml
exist-parent/pom.xml

Enables in-memory query result values less than 4 MB instead of writing them to a temporary file.
By using the in-memory-buffer no potential virus scanner is trigger either on the server as on the client side. This almost doubled the performance on our productive systems, when using this change.

Adds in memory cache for RPC query results

---

.github/workflows/ci-deploy.yml
.github/workflows/ci-test.yml
.github/workflows/ci-xqts.yml
exist-core/pom.xml
exist-core/src/main/java/org/exist/util/io/ContentFilePool.java
exist-core/src/main/java/org/exist/util/io/MemoryContentsInputStream.java
exist-core/src/main/java/org/exist/util/io/VirtualTempPath.java
exist-core/src/main/java/org/exist/xmlrpc/CachedContentFile.java
exist-core/src/main/java/org/exist/xmlrpc/QueryResultCache.java
exist-core/src/main/java/org/exist/xmlrpc/RpcAPI.java
exist-core/src/main/java/org/exist/xmlrpc/RpcConnection.java
exist-core/src/main/java/org/exist/xmlrpc/XmldbRequestProcessorFactory.java
exist-core/src/test/java/org/exist/util/io/ContentFilePoolTest.java
exist-core/src/test/java/org/exist/util/io/MemoryContentsInputStreamTest.java
exist-core/src/test/java/org/exist/util/io/VirtualTempPathTest.java
exist-core/src/test/java/org/exist/xmlrpc/CachedContentFileTest.java
exist-core/src/test/java/org/exist/xmlrpc/QueryResultCacheTest.java
exist-core/src/test/java/org/exist/xmlrpc/XmlRpcTest.java
exist-distribution/src/main/config/conf.xml
exist-parent/pom.xml

Backport of https://github.com/eXist-db/exist/pull/5188.
Enables in-memory query result values less than 4 MB instead of writing them to a temporary file.
By using the in-memory-buffer no potential virus scanner is trigger either on the server as on the client side. This almost doubled the performance on our productive systems, when using this change.

[6.x.x] Adds in memory cache for RPC query results

---

exist-core/src/main/java/org/exist/storage/NativeBroker.java
exist-core/src/main/java/org/exist/test/ExistXmldbEmbeddedServer.java
exist-core/src/test/java/org/exist/xquery/update/UpdateInsertTriggersDefrag.java

By setting the allowed-fragmentation attribute value to `-1` any modification will trigger the defragmentation of the dom.dbx (AKA BTree pages).
This setting triggers the NPE described in #5273 on the very first call to
```xquery
update (replace|insert) $nodeA (with|into) $nodeB
```
Unfortunately, it also triggers a totally different class of NPEs in XQueryTrigger and other subsystems of the database.
<details>
<summary>Failures before d145f29857be1cf7be5ab15226f8239b5e5aac3d</summary>
```
[ERROR] Failures:
[ERROR]   TriggerConfigTest.removeDocument:137 Cannot invoke "org.exist.storage.BrokerPool.getSecurityManager()" because "pool" is null
[ERROR]   TriggerConfigTest.removeDocument:137 Cannot invoke "org.exist.storage.BrokerPool.getSecurityManager()" because "pool" is null
[ERROR] …
```

[bugfix] fix errors on update operations

---

exist-core/pom.xml
exist-core/src/main/java/org/exist/collections/triggers/FilteringTrigger.java
exist-core/src/main/java/org/exist/scheduler/UserXQueryJob.java
exist-core/src/main/java/org/exist/security/User.java
exist-core/src/main/java/org/exist/security/internal/AccountImpl.java
exist-core/src/main/java/org/exist/storage/BrokerPool.java
exist-core/src/main/java/org/exist/util/ByteConversion.java
exist-core/src/main/java/org/exist/util/NamedThreadFactory.java
exist-core/src/main/java/org/exist/xmldb/RemoteXMLResource.java
exist-parent/pom.xml

- postprocess 'slower' new Integer(int) to cached Integer.valueOf() in generated antlr code as hinted by the build
- add @Deprecated to remaining methods

[ignore] reduce build warnings

---

.github/workflows/ci-test.yml
exist-core/pom.xml
extensions/indexes/range/pom.xml
extensions/indexes/range/src/test/java/org/exist/indexing/range/RangeIndexConfigTest.java
extensions/modules/simpleql/pom.xml

Fixes #5249
Contribution by https://github.com/omnifaces/antlr-maven-plugin

[bugfix] Make build compatible with Java18 and beyond.

---

exist-parent/pom.xml

Update to latest jetty release compatible with exist-db 6

Bump jetty from 9.4.50.v20221201 to 9.4.54.v20240208

---

extensions/indexes/spatial/pom.xml
extensions/webdav/pom.xml

Make sure the latest jdom(1) jar is used, i.s.o. 2 different older versions
fixes #5392

[Bugfix] Address two old jdom-1 jars on class path 

---

exist-core/pom.xml

This aligns the jackson-core version with the one that tika depends on.
While exist-db 6 declares a dependency on jackson-core v2.13.4 the recently updated tika library depends on 2.15.2. In my testing this lead to problems with a Java extension [oad](https://github.com/eeditiones/oad) that also depends on jackson-core (2.15.2).
Interesting to note here is that this works fine when the tika library is not updated as oad comes packaged with the correct version.  Only after that update the extension did not work anymore because the older version of jackson-core was used.
Thanks to @dizzzz for helping me find the issue in yesterdays community call.

Bump jackson-core from 2.13.4 to 2.15.2

---

.github/workflows/ci-test.yml

Java8 on macOS seems really impossible to find in GHA. Spending more time is IMO not worth the effort.
Personally I do not expect OpenJDK8 on macOS to be really used, it is a corner case, Apple ditched Java8 support ages ago.
Whilst OpenJDK11 might be a bit slower [not sure if this is true] , keeping Java8 support on this OS is IMHO not worth the effort of the eXist-db contributors.
More valuable is to have green builds again.
OpenJDK works just fine as reported by end-users.
It is up to the community (monday eve) to decide and agree.

[ci] Repair 6.x.x build for macOs

---

exist-distribution/src/main/config/webdav.properties
extensions/webdav/src/main/java/org/exist/webdav/ExistResourceFactory.java
extensions/webdav/src/main/java/org/exist/webdav/MiltonCollection.java
extensions/webdav/src/main/java/org/exist/webdav/MiltonDocument.java
extensions/webdav/src/main/resources/org/exist/webdav/webdav.properties

This PR...
- allows configuration of the  "size report method' via webdav.properties
- updates relevant in-code documentation
- simplifies code
- makes the webdav.properties file in sync again

[Feature] Make WebDAV document size reporting more configurable

---

exist-core/pom.xml
exist-parent/pom.xml

PR #5386 repairs the NVD scan;
This PR addresses some of the scanned vulnerabilities.
to discuss:
- nekohtml => 2.0.2 requires changes in conf.xml (textual)
- com.ibm.icu:icu4j:59.1 =? not sure about compatibility of newer versions
exclude
- quartz => unmaintained
- xpath2 => needed/embedded in latest Xerces?
for best build first pull-in #5385 and #5386

[bugfix] Address vulnerabilities as indicated by OWASP/NVD.

---

.github/actions/install-mvnd/action.yml
.github/workflows/ci-deploy.yml
.github/workflows/ci-test.yml
.github/workflows/ci-xqts.yml
exist-core/pom.xml
exist-core/src/main/java/org/exist/plugin/PluginsManagerImpl.java
exist-core/src/main/java/org/exist/storage/recovery/RecoveryManager.java

Closes https://github.com/eXist-db/exist/pull/5304
Liberica should still provide JDK 8 on macOS

[6.x.x] Switch CI from Temurin to Liberica

---

.github/actions/install-mvnd/action.yml
.github/workflows/ci-test.yml
exist-core/pom.xml
exist-core/src/main/java/org/exist/storage/recovery/RecoveryManager.java
exist-parent/pom.xml

Stops the CI logs from getting polluted

Hide journal recovery messages during test suite run

---

.github/workflows/ci.yml
build/scripts/junit.xml
exist-core/src/main/java/org/exist/plugin/PluginsManagerImpl.java
exist-core/src/main/java/org/exist/storage/recovery/RecoveryManager.java

Backport of https://github.com/eXist-db/exist/pull/5466
Liberica should still provide JDK 8 on macOS

[4.x.x] Switch CI from Temurin to Liberica

---

.github/workflows/ci-deploy.yml
.github/workflows/ci-test.yml
.github/workflows/ci-xqts.yml
.github/workflows/sonarcloud.yml

Use the same JDK vendor in 7.x.x as eXist-db eXist-db [4.x.x](https://github.com/eXist-db/exist/pull/5468), [5.x.x](https://github.com/eXist-db/exist/pull/5467), and [6.x.x](https://github.com/eXist-db/exist/pull/5466).
NOTE: There is no Temurin JDK 8 on macOS available in CI. So we are switching to Liberica which does support that.

Switch CI from Temurin to Liberica

---

exist-core/pom.xml
exist-core/src/test/xquery/xquery3/function-reference.xqm

Just adding a simple missing test for function references with postfix expressions

Test that Function References should be able to have postfix expressions

---

exist-core/src/main/java/org/exist/collections/triggers/XQueryTrigger.java
exist-core/src/test/java/org/exist/storage/StoreResourceTest.java

Backport of https://github.com/eXist-db/exist/pull/5481
**NOTE**: Needs https://github.com/eXist-db/exist/pull/5468 merged first and then this needs to be rebased

[4.x.x] Fix an issue where XQuery Trigger state may leak

---

exist-core/src/main/java/org/exist/util/Configuration.java

Try to reduce complexity and sonar warnings

Simplify configuration

---

extensions/modules/sql/src/main/java/org/exist/xquery/modules/sql/ExecuteFunction.java
extensions/modules/sql/src/test/java/org/exist/xquery/modules/sql/ExecuteIT.java

This change introduces two new signatures for the `sql:execute` function:
```
sql:execute($connection-handle as xs:long, $sql-statement as xs:string, $make-node-from-column-name as xs:boolean, $ns-prefix as xs:string, $ns-uri as xs:string) as element()?
sql:execute($connection-handle as xs:long, $statement-handle as xs:long, $parameters as element()?, $make-node-from-column-name as xs:boolean, $ns-prefix as xs:string, $ns-uri as xs:string) as element()?
```
These functions allow setting a namespace on the output of `sql:execute` that is different from the default.
This may be useful in contexts where namespace processing is unwanted, or different namespaces for different result sets are wanted.

[6.x.x] Allow setting the namespace on the result of sql:execute

---

.github/workflows/ci-test.yml
exist-core/pom.xml
exist-core/src/main/java/org/exist/test/ExistXmldbEmbeddedServer.java
exist-core/src/test/java/org/exist/xquery/update/UpdateInsertTriggersDefragTest.java
exist-parent/pom.xml

Fixes the resource leaks that were introduced in https://github.com/eXist-db/exist/pull/5276

Fix test resource leaks introduced in https://github.com/eXist-db/exist/pull/5276

---

.github/workflows/ci-test.yml
exist-core/pom.xml
exist-parent/pom.xml

* Remove JFR from CI
* Use Windows specific CI profile for testing in CI

[6.x.x] Fix CI Windows stream corruption

---

schema/collection.xconf.xsd

Closes #5432 by adding schema definitions for the `field` element's `binary` attribute in the `collection.xconf.xsd` schema. 
#5432
n/a

Register binary attribute in collection.xconf.xsd

---

.github/workflows/ci-deploy.yml
exist-docker/pom.xml
exist-docker/src/main/resources-filtered/Dockerfile
exist-docker/src/main/resources-filtered/Dockerfile-DEBUG

enables a long overdue feature: multi-arch containers for `existdb/existdb` 
backport will remove a release blocker for 6.3.1
sidessteps docker maven plugin bug, `deploy` is green again.
see fabric8io/docker-maven-plugin#1835
fixes outdated JRE patches, bumps base image to Debian 12 
see #5450
close #4151
close #5532
close #4153

Feat-multi-arch-containers

---

exist-core/src/main/java/org/exist/xquery/ForExpr.java
exist-core/src/test/xquery/xquery3/flwor.xql

Resolved an issue where ForClause's PositionalVar incorrectly returned values when faced with an empty sequence while allowing emptiness. This adjustment ensures accurate handling of edge cases in sequence evaluations, aligning behavior with expected standards.
https://github.com/eXist-db/exist/issues/5235
Added tests which verifies the same

Fix ForClause PositionalVar empty sequence handling

---

exist-core/src/main/java/org/exist/xslt/XsltURIResolverHelper.java
exist-core/src/test/java/org/exist/xquery/functions/transform/ImportLocalStylesheetTest.java

When importing stylesheets the URIs are resolved in order
- registered import-uris in package repo
- XMLDB-locations (relative, absolute and with or without scheme)
- any other location is treated as an exteranal source
The test class and its cases were renamed to reflect their purpose. Some inline comments were added to help describing the intent.
follow-up for #5574

[bugfix] registered import-uris have precedence

---

exist-core/src/main/java/org/exist/source/SourceFactory.java
exist-core/src/main/java/org/exist/test/XQueryCompilationTest.java
exist-core/src/main/java/org/exist/xquery/XQueryContext.java
exist-core/src/test/java/org/exist/xquery/AbsolutePathTests.java
exist-core/src/test/java/org/exist/xquery/ModuleImportTest.java
exist-core/src/test/resources-filtered/org/exist/xquery/conf.xml

- add modified conf.xml ModuleImport tests
- add tests for one-off queries with module imports
- using a modified conf.xml that loads functx into package repo via auto deploy
- of a registered module without location hint
- of a module with location hint
- change XQueryContext to allow imports again
- change SourceFactory to work with contextPath set to "."
fixes #5525
fixes #5530
Java tests added in src/test/java/org/exist/xquery/ModuleImportTest.java

Allow module imports in one-off xqueries

---

exist-core/src/test/java/org/exist/validation/CollectionConfigurationValidationModeTest.java
exist-parent/pom.xml
exist-start/src/main/java/org/exist/start/Main.java

To do: check start code
replaces https://github.com/eXist-db/exist/pull/5526 and https://github.com/eXist-db/exist/pull/5461

[library] bump version of xmlresolver to 6.0.x

---

.github/workflows/ci-container.yml
.github/workflows/ci-snapshots.yml
.github/workflows/ci-test.yml
.github/workflows/ci-xqts.yml
.github/workflows/sonarcloud.yml
BUILD.md
README.md
exist-core-jmh/pom.xml
exist-core/pom.xml
exist-docker/src/main/resources-filtered/Dockerfile
exist-docker/src/main/resources-filtered/Dockerfile-DEBUG
exist-docker/src/main/resources-filtered/README.md
exist-installer/src/main/izpack/install.xml
exist-parent/pom.xml

Migrate to Java21, including smaller cleanups in pom.xml to make configuration more consistent.
Todo:

[cicd] Migrate to Java21

---

.github/workflows/ci-test.yml
exist-parent/pom.xml

This is an attempt to re-enable builds of exist-db-6.x.x by switching to a different Nexus server.
https://repo.exist-db.org
The existing Nexus was kept in the parent-pom.

[bugfix] reenable builds by switching to a different nexus

---

.github/workflows/ci-test.yml

as discussed on the community call:
Now that we know that our Nexus has all necessary dependencies we can drop the -U flag from the build step.
```
-U --update-snapshots Forces a check for updated releases and snapshots on remote repositories
```

[ci] remove -U mvn flag again

---

exist-core/src/main/java/org/exist/xquery/FunctionSignature.java
exist-core/src/main/java/org/exist/xquery/UserDefinedFunction.java
exist-core/src/test/xquery/maps/maps.xqm

Wrong comparison in FunctionSignature lead to tail call optimisation where no recursion was happening. This lead to at least the NPE reported in #5685
I do suspect that this does fix other related issues but will have to retest those scenarios to confirm
In general the attempt to compare the signature of two functions of which one or both is an anonymous function is a bad idea.
It will still work but only for _identical FunctionSignature objects_. This should also be the more common case for recursive calls to the same function.
fixes #5685
The screenshot illustrates how two anonymous functions were deemed equal because both had an empty name and the same number of arguments.
One XQSuite test added.

[BUG] fix #5685 NPE on nested anonymous functions

---

exist-distribution/src/main/xslt/catalog.xml

jetty configuration DTD was loaded from the internet even though it was listed in the catalog. Added the public identifier and corrected the system identifier (which is now using https).

[fix] use local jetty configure DTDs

---

exist-core/src/main/java/org/exist/xquery/functions/system/GetMainModuleLoadPath.java
exist-core/src/main/java/org/exist/xquery/functions/system/SystemModule.java
exist-core/src/test/xquery/system/get-main-module-load-path.xqm
exist-core/src/test/xquery/system/get-module-load-path.xqm

refs #5731
This function will always return the moduleLoadPath of the root XQuery context.
Due to the fixes in module load path handling it became apparent that we will need a new function in the system module that would reliably always return the load path of the root context.
The documentation for `system:get-module-load-path` was ambigous and could be understood to do what the new function now does.

add new function `system:get-main-module-load-path#0`

---

exist-core/src/main/java/org/exist/xquery/functions/system/GetMainModuleLoadPath.java
exist-core/src/main/java/org/exist/xquery/functions/system/SystemModule.java
exist-core/src/test/xquery/system/get-main-module-load-path.xqm
exist-core/src/test/xquery/system/get-module-load-path.xqm

refs #5731
This function will always return the moduleLoadPath of the root XQuery context.
forward port of #5732

[enhancement] add new function system:get-main-module-load-path

---

exist-core/src/main/java/org/exist/management/client/JMXServlet.java

Repair JMXservlet for ipv6 addresses.
Interestingly the servlet container returns [0:0:0:0:0:1] as string.

[bugfix] Repair JMXservlet for ipv6 addresses.

---

exist-core/src/main/java/org/exist/test/runner/XMLTestRunner.java
exist-parent/pom.xml

The latest release of maven-surefire-plugin lead to a large amount of integration tests not running.
Integration test for us means tests written in XQuery and also those defined XML.
I could confirm that deliberately breaking a test in core did not lead to a failing build.
**NOTE:** The build of this PR will break because some tests are really broken.
Those tests will be fixed in separate PRs.
fixes #5805 
possibly related issues from the maven plugins in us: 
- https://github.com/apache/maven-surefire/issues/3156
- https://github.com/apache/maven-surefire/issues/2634

Reinstate integration tests in maven

---

exist-core/src/main/java/org/exist/xquery/functions/fn/FunAnalyzeString.java
exist-core/src/test/xquery/xquery3/analyze-string.xqm

`fn:analyze-string` was implemented such that an invalid pattern or flag or a pattern matching an empty string would only raise an error if the value was a non-empty string.
With this PR applied the error will be raised regardless of the provided value.
> Error Conditions
> A dynamic error is raised [[err:FORX0002](https://www.w3.org/TR/xpath-functions-31/#ERRFORX0002)] if the value of $pattern is invalid according to the rules described in section [5.6.1 Regular expression syntax](https://www.w3.org/TR/xpath-functions-31/#regex-syntax).
>
> A dynamic error is raised [[err:FORX0001](https://www.w3.org/TR/xpath-functions-31/#ERRFORX0001)] if the value of $flags is invalid according to the rules described in section [5.6.2 Flags](https://www.w3.org/TR/xpath-functions-31/#flags).
>
> A …

[bugfix] consistently raise errors in fn:analyze-string
