README.md

Fix to improve the appearance of README.md on GitHub

Fix formatting and minor typos

---

extensions/modules/src/org/exist/xquery/modules/httpclient/BaseHTTPClientFunction.java
extensions/modules/src/org/exist/xquery/modules/httpclient/HTTPClientModule.java

First simple integration from @shabanovd with some minor refactoring.

[bugfix] Fix concurrent bug for http client

---

src/org/exist/config/Configurator.java

Improvement for Configuration references from @shabanovd

[bugfix] Avoid resolving references

---

.classpath
.project

Bring the Eclipse project up to date with various library changes this year

[bugfix] Update Eclipse project

---

src/org/exist/util/hashtable/NamePool.java

Recent changes to QName class mess up namespaces in in-memory documents. NamePool needs to take prefix and nameType into account when testing for equality.
See http://markmail.org/message/jdub2fv6vj7pm5pd for bug report.

Regression: messed up namespaces in constructed document

---

build/scripts/build-impl.xml

* Can now compile eXist Aspects successfully with Java 8

Only compile aspects with AspectJ compiler

---

src/org/exist/xquery/RangeSequence.java
src/org/exist/xquery/functions/fn/FunHigherOrderFun.java
src/org/exist/xquery/value/ValueSequence.java
test/src/xquery/xquery3/higher-order.xml

* Higher performance implementation of fn:fold-left
* Non-recursive speedup for fn:fold-right uses when backed by `RangeSequence` or `ValueSequence`. Others could most likely be added too.

Optimise fold functions

---

src/org/exist/xquery/TypeswitchExpression.java
test/src/xquery/xquery3/typeswitch.xql

First matching case should exit loop (fix of #481).

[ignore] Small issue introduced by typeswitch change

---

src/org/exist/util/hashtable/NamePool.java
test/src/org/exist/util/hashtable/AllTests.java
test/src/org/exist/util/hashtable/NamePoolTest.java

Found a memory leak in develop while running some jmeter tests. Added test case.

[bugfix] Fix memory leak in NamePool.

---

extensions/webdav/src/org/exist/webdav/ExistCollection.java

Temp file needs to be closed last.

[bugfix] webdav interface broken by a24387d: saving resource failed. 

---

extensions/modules/src/org/exist/xquery/modules/httpclient/BaseHTTPClientFunction.java

Fix http client. Truncate and close stream

fix httpclient

---

extensions/indexes/lucene/src/org/exist/indexing/lucene/LuceneIndexConfig.java
extensions/indexes/lucene/src/org/exist/indexing/lucene/LuceneIndexWorker.java
extensions/indexes/lucene/test/src/org/exist/indexing/lucene/LuceneIndexTest.java
schema/collection.xconf.xsd
src/org/exist/dom/persistent/ElementImpl.java
src/org/exist/indexing/IndexController.java

Refactored and adapted to develop branch (2.3+)
No log flooding.

Adding a Lucene index attribute boosting feature

---

extensions/indexes/lucene/src/org/exist/indexing/lucene/LuceneIndexWorker.java

Making the attribute boosting indexing more robust in case the cache limit is exceeded

---

build/scripts/dist.xml

fix of https://github.com/eXist-db/exist/issues/410

Add auto deploy folder to 'dist'

---

test/src/org/exist/backup/BackupRestoreSecurityPrincipalsTest.java

[bugfix] The auto-deployment trigger could previously interfere with this test

---

src/org/exist/security/AbstractAccount.java
src/org/exist/security/AbstractSubject.java
src/org/exist/security/Account.java
src/org/exist/security/EffectiveSubject.java
src/org/exist/security/Group.java
src/org/exist/security/Principal.java
src/org/exist/security/User.java
src/org/exist/security/internal/AccountImpl.java
src/org/exist/security/internal/Password.java
src/org/exist/security/internal/aider/UserAider.java
src/org/exist/xquery/functions/securitymanager/AccountManagementFunction.java
src/org/exist/xquery/functions/securitymanager/AccountStatusFunction.java
src/org/exist/xquery/functions/securitymanager/FindGroupFunction.java
src/org/exist/xquery/functions/securitymanager/FindUserFunction.java
src/org/exist/xquery/functions/securitymanager/GetPrincipalMetadataFunction.java
src/org/exist/xquery/functions/securitymanager/GroupManagementFunction.java
src/org/exist/xquery/functions/securitymanager/GroupMembershipFunction.java
src/org/exist/xquery/functions/securitymanager/IdFunction.java
src/org/exist/xquery/functions/securitymanager/IsAuthenticatedFunction.java
src/org/exist/xquery/functions/securitymanager/PermissionsFunction.java
src/org/exist/xquery/functions/securitymanager/SecurityManagerModule.java
src/org/exist/xquery/functions/securitymanager/SetPrincipalMetadataFunction.java
src/org/exist/xquery/functions/securitymanager/UMaskFunction.java
test/src/org/exist/security/AbstractAccountTest.java

Closes https://github.com/eXist-db/exist/issues/513

Add XQuery function for setting user passwords from an encodedHash

---

extensions/indexes/lucene/src/org/exist/indexing/lucene/LuceneIndexConfig.java
extensions/indexes/lucene/src/org/exist/indexing/lucene/LuceneIndexWorker.java
extensions/indexes/lucene/test/src/org/exist/indexing/lucene/LuceneIndexTest.java

* moved logic from config to worker for cleaner separation
* extended test

Refactored attribute index boost

---

build/scripts/macosx.xml

Fixes some minor issues with the DMG build on Linux

Linux DMG build fix

---

src/org/exist/util/Occurrences.java
src/org/exist/xmldb/AbstractRemote.java
src/org/exist/xmldb/AbstractRemoteResource.java
src/org/exist/xmldb/DatabaseImpl.java
src/org/exist/xmldb/DatabaseStatus.java
src/org/exist/xmldb/FullXmldbURI.java
src/org/exist/xmldb/LocalResourceSet.java
src/org/exist/xmldb/MapResourceSet.java
src/org/exist/xmldb/RemoteBinaryResource.java
src/org/exist/xmldb/RemoteCollection.java
src/org/exist/xmldb/RemoteCollectionManagementService.java
src/org/exist/xmldb/RemoteCompiledExpression.java
src/org/exist/xmldb/RemoteDatabaseInstanceManager.java
src/org/exist/xmldb/RemoteIndexQueryService.java
src/org/exist/xmldb/RemoteResourceIterator.java
src/org/exist/xmldb/RemoteResourceSet.java
src/org/exist/xmldb/RemoteUserManagementService.java
src/org/exist/xmldb/RemoteXMLResource.java
src/org/exist/xmldb/RemoteXPathQueryService.java
src/org/exist/xmldb/RemoteXUpdateQueryService.java
src/org/exist/xmldb/UserManagementService.java
src/org/exist/xmldb/XPathQueryServiceImpl.java
src/org/exist/xmldb/XQueryService.java
src/org/exist/xmldb/XmldbURI.java
test/src/org/exist/xmldb/DOMTestJUnit.java
test/src/org/exist/xmlrpc/QuerySessionTest.java

General code audit and cleanup. Fixed several small bugs along the way that were the result of previous copy-pasta mistakes or bad code style.

Cleaned up the XML:DB Remote API implementation

---

extensions/indexes/ngram/src/org/exist/indexing/ngram/NGramIndexWorker.java

Allows future optimisation of directly seeking NGram value for attributes.

[feature] Infer NodeProxy node type from name type

---

test/src/org/exist/storage/RangeIndexUpdateTest.java

Prevents RangeIndexUpdateTest from breaking other tests if it fails

[bugfix] Make sure to always shutdown the database

---

extensions/security/oauth/src/org/exist/security/realm/oauth/OAuthRealm.java
extensions/security/openid/src/org/exist/security/realm/openid/OpenIDRealm.java
src/org/exist/security/AbstractRealm.java
src/org/exist/security/internal/RealmImpl.java
src/org/exist/util/function/Consumer2E.java
src/org/exist/util/function/ConsumerE.java

* Remove the old pre-Java 8 interface passing in favour of Java 8 lambdas.
* Use predicates for filtering users and groups. Makes the code much more readable :-)

Some cleanup of Realms

---

src/org/exist/config/Configuration.java
src/org/exist/config/ConfigurationImpl.java
src/org/exist/config/Configurator.java
src/org/exist/security/AbstractAccount.java
src/org/exist/security/internal/AccountImpl.java
test/src/org/exist/security/SecurityManagerRoundtripTest.java

In the least - it caused a problem with the order of groups of a user that also had DBA group membership; https://github.com/eXist-db/exist/issues/583

Fixes an issue with Configurator ordering

---

src/org/exist/security/PermissionFactory.java

Revert "CLI: removed NPEs for users without group"

---

build/scripts/build-impl.xml

Use ant to fix line endings in scripts

[build] - fixe line endings of files when building fixes #474

---

src/org/exist/xquery/ElementConstructor.java

Should implement "err:XQST0070" spec conform now. close #494

Possible fix for #494

---

src/org/exist/backup/Main.java
src/org/exist/backup/restore/listener/ConsoleRestoreListener.java

- pass quiet parameter to ConsoleRestoreListener fixes #455

backup.sh -q option is not quiet

---

src/org/exist/launcher/ConfigurationDialog.java

Cache calculation used default min/max mem values for inital cache calculation

Set min/max Memory before calculating CacheSizes fixes #296

---

src/org/exist/xmldb/LocalXMLResource.java

[bugfix] Fixes leaky abstraction in XMLDB:Local API by preventing internal persistent DOM node state from leaking out.

Plumb the leaky abstraction in XML:DB Local API

---

src/org/exist/webstart/JnlpJarFiles.java
src/org/exist/webstart/JnlpWriter.java

Related to https://github.com/eXist-db/exist/pull/612

Update webstart code for new rsyntaxtextarea library

---

tools/wrapper/wrapper-log4j.xsl

fixes https://github.com/eXist-db/exist/issues/634

Fix log4j2 configuration for wrapper ; 

---

nbproject/project.properties

Get in line with recent changes

---

src/org/exist/xslt/TransformerFactoryAllocator.java

Closes https://github.com/eXist-db/exist/issues/651

[bugfix] Make the TransformerFactory a singleton

---

src/org/exist/xslt/TransformerFactoryAllocator.java

Reverts eXist-db/exist#653 (org.exist.xslt.TransfomerFactoryAllocatorTest fail)

Revert "[bugfix] Make the TransformerFactory a singleton"

---

src/org/exist/xslt/TransformerFactoryAllocator.java
test/src/org/exist/xslt/TransfomerFactoryAllocatorTest.java

Closes https://github.com/eXist-db/exist/issues/651

[bugfix] Attempt 2 - Make the TransformerFactory a singleton

---

src/org/exist/security/SimpleACLPermission.java
src/org/exist/security/UnixStylePermission.java
src/org/exist/storage/NativeBroker.java
src/org/exist/util/function/Tuple2.java
test/src/org/exist/security/XMLDBSecurityTest.java

Closes https://github.com/eXist-db/exist/issues/377

Fix to ensure mode and ACL on sub-resources and collections is copied when copying from parent

---

src/org/exist/config/ConfigurationDocumentTrigger.java

Db corruption after delete of resource under /db/config/*

---

src/org/exist/xquery/functions/securitymanager/GetPrincipalMetadataFunction.java

Closes https://github.com/eXist-db/exist/issues/611

[bugfix] Avoid NPE when user or group does not exist

---

src/org/exist/xmldb/AbstractEXistResource.java
src/org/exist/xmldb/AbstractRemoteResource.java
src/org/exist/xmldb/EXistResource.java
src/org/exist/xmldb/LocalXMLResource.java
src/org/exist/xmldb/RemoteCollection.java
src/org/exist/xmlrpc/RpcAPI.java
src/org/exist/xmlrpc/RpcConnection.java
src/org/exist/xquery/functions/xmldb/XMLDBModule.java
src/org/exist/xquery/functions/xmldb/XMLDBTouch.java

xmldb:touch("/db", "something.xml")

[feature] Added xmldb:touch function

---

src/org/exist/xquery/Predicate.java
test/src/xquery/axes.xml

[bugfix] Fix reverse axis position.

---

src/org/exist/http/RESTServer.java
src/org/exist/util/serializer/json/JSONNode.java
src/org/exist/util/serializer/json/JSONSimpleProperty.java
src/org/exist/util/serializer/json/JSONValue.java
src/org/exist/util/serializer/json/JSONWriter.java
test/src/org/exist/util/serializer/json/JSONObjectTest.java

Closes https://github.com/eXist-db/exist/issues/465

[bugfix] json:literal and json:array should not be mutually exclusive.

---

src/org/exist/xquery/XQueryContext.java

[bugfix] Local variable cleanup causes endless loop

---

src/org/exist/dom/persistent/VirtualNodeSet.java

[performance] Do not use structural index for wildcard path steps like pfx:* or *:name: contrary to our expectations it may significantly slow down applications. For now just traversing the node is faster. Old code preserved for future review.
Closes #573.

Expressions with wildcard step became slow

---

src/org/exist/webstart/JnlpWriter.java

Closes https://github.com/eXist-db/exist/issues/717

Repair dependency JNLP code with milton

---

conf.xml.tmpl
extensions/build.properties

so releases can be built without changes

[ignore] Use the same configuration for development and releases

---

test/src/org/exist/backup/SystemExportImportTest.java

* Cleanup SystemExport ImportTest
* Add further non-direct test to complement direct test

[refactor] Cleanup SystemExportImportTest

---

src/org/exist/collections/CollectionConfigurationManager.java

http://exist-development.markmail.org/thread/g6vgcsmbp3dcnxst

[refactor] Do not config collections twice

---

bin/backup.bat
bin/client.bat
bin/server.bat
bin/shutdown.bat
bin/startup.bat
build.bat
installer/launch_client.bat
installer/scripts/build.bat
installer/scripts/setup.bat

Fix for Windows paths with Spaces

---

extensions/modules/src/org/exist/xquery/modules/expathrepo/Deploy.java
extensions/modules/src/org/exist/xquery/modules/expathrepo/GetResource.java
extensions/modules/src/org/exist/xquery/modules/expathrepo/InstallFunction.java
extensions/modules/src/org/exist/xquery/modules/expathrepo/ListFunction.java
extensions/modules/src/org/exist/xquery/modules/expathrepo/RemoveFunction.java
src/org/exist/launcher/Launcher.java
src/org/exist/repo/ClasspathHelper.java
src/org/exist/repo/Deployment.java
src/org/exist/storage/BrokerPool.java
src/org/exist/xquery/XQueryContext.java
src/org/exist/xquery/functions/util/ModuleInfo.java

in order to have indexing apps available when indexManager is initialized and startup triggers are executed.

Moving expathRepo init and updateClasspath() earlier

---

src/org/exist/storage/lock/DeadlockDetection.java

Was introduced by accident in 4e2b49f, and identified by @dizzzz here https://github.com/eXist-db/exist/pull/730/files#r35252916

[bugfix] Remove a bad dependency on log4j12-api 

---

build/scripts/junit.xml

* Just testing Travis-CI at the moment, do not merge!

[feature] Have Travis-CI run all JUnit tests

---

build/scripts/junit.xml

Reverts eXist-db/exist#752
sorry....

Revert "[feature] Have Travis-CI run all JUnit tests"

---

src/org/exist/xmlrpc/RpcConnection.java

Just like the REST API, when non-nodes results are returned by the
retrieveAll method, wrap ech one of them with the element `<exist:value>`.
Also, add a type attribute to that element, with the value type.
It fixes #755.
Accordingly with my findings, no code is using retrieveAll. Also, the Java client is retrieving a result at  time (it seems). I will dig that  little deeper, and if it is the case (and if this patch is welcome), I'll change it to using retrieveAll (and hopefully be faster).

Wrap non-nodes with <exist:value> element.

---

src/org/exist/storage/NativeBroker.java
test/src/org/exist/storage/NativeBrokerTest.java

* Fixes an issue with Deployment of Uploaded XAR files which was accidentally introduced by NIO.2 changes.

Correctly resolve binary files against fs paths

---

test/src/org/exist/xquery/functions/securitymanager/IdFunctionTest.java

Ensures that the test works with all XPath engines including eXist's memtree

Make sure the IdFunctionTests are stable

---

extensions/betterform/build.xml
extensions/betterform/ivy.xml
nbproject/project.properties

- update betterFORM to use Saxon 9.6.0-7. 
- finetuned "clean" target of betterFORM extension to remove jars handled by ivy
- update provided Saxon to 9.6.0-7

[extension] - update of betterFORM to Saxon 9.6.0-7

---

src/org/exist/http/servlets/EXistServlet.java

Remove logging ; 

---

extensions/modules/src/org/exist/xquery/modules/file/Directory.java
src/org/exist/backup/BackupDirectory.java
src/org/exist/backup/xquery/ListBackups.java
src/org/exist/launcher/ConfigurationDialog.java
src/org/exist/management/impl/DiskUsage.java
src/org/exist/repo/Deployment.java
src/org/exist/repo/RepoBackup.java
src/org/exist/storage/BackupSystemTask.java
src/org/exist/storage/NativeBroker.java
src/org/exist/storage/journal/Journal.java
src/org/exist/storage/recovery/RecoveryManager.java
src/org/exist/util/FileUtils.java
src/org/exist/util/io/TemporaryFileManager.java
test/src/org/exist/backup/BackupRestoreSecurityPrincipalsTest.java
test/src/org/exist/storage/StoreBinaryTest.java

* Solves an issue with eXist leaking file handles, particularly noticeable on `fs.journal` when eXist has been running for a while in production.

Close Stream's that use I/O resources

---

extensions/modules/src/org/exist/xquery/modules/compression/AbstractCompressFunction.java
extensions/modules/src/org/exist/xquery/modules/compression/GZipFunction.java
extensions/modules/src/org/exist/xquery/modules/compression/UnGZipFunction.java

Closes https://github.com/eXist-db/exist/issues/39

Bug fixes for functions in the Compression Module

---

src/org/exist/util/serializer/IndentingXMLWriter.java

Marks the beginning of whitespace week.

Add support for xml:space preserve in IndentingXMLWriter serializer

---

nbproject/project.properties

update lib paths for easymock and objenesis

update netbeans project

---

src/org/exist/repo/Deployment.java

- fixes for #836: close stream and use right variable for resources directory test

fix for #836: close stream and use right varible in resource directory test

---

extensions/webdav/src/org/exist/webdav/ExistCollection.java
extensions/webdav/src/org/exist/webdav/ExistDocument.java

Closes https://github.com/eXist-db/exist/issues/835

[bugfix] Address an NPE issue in WebDAV introduced by bce696e

---

extensions/exquery/restxq/src/main/java/org/exist/extensions/exquery/restxq/impl/ResourceFunctionExecutorImpl.java

Closes https://github.com/eXist-db/exist/issues/778

[bugfix] Make sure that RESTXQ adheres to setUid and setGid in eXist

---

src/org/exist/storage/BrokerPool.java
src/org/exist/storage/DBBroker.java
src/org/exist/util/Stacktrace.java

Some trace level logging, javadoc and sanity checks when releasing a broker. No major changes!

Minor BrokerPool improvements

---

.idea/runConfigurations/Client.xml
.idea/runConfigurations/Server.xml
.idea/vcs.xml

Run configurations are now part of file set.

Update of IDEA files 

---

src/org/exist/storage/DBBroker.java

[bugfix] Make sure to get the name not the object

---

src/org/exist/dom/memtree/AttrImpl.java
src/org/exist/dom/memtree/ProcessingInstructionImpl.java
test/src/org/exist/dom/memtree/MemtreeInXQuery.java

Fixes Memtree's processing-instructions and attributes so that they work correctly from XQuery

[bugfix] Fixes issues in Memtree DOM from XQuery

---

src/org/exist/xquery/XQueryContext.java

the error message was missing a close quote surrounding the module location hint URI

fix module load exception error message

---

extensions/build.properties
extensions/modules/build.xml
extensions/modules/ivy.xml
extensions/modules/src/org/exist/xquery/modules/xslfo/ApacheFopProcessorAdapter.java
extensions/modules/src/org/exist/xquery/modules/xslfo/RenderFunction.java
extensions/modules/src/org/exist/xquery/modules/xslfo/readme.txt

Completes the work started here - https://github.com/eXist-db/exist/commit/dc1511a9380ccd611ab602c86c203406a64d3c56

Update to FOP 2.1

---

extensions/modules/src/org/exist/xquery/modules/file/SerializeToFile.java

also truncate an already created file

---

extensions/exquery/restxq/src/main/java/org/exist/extensions/exquery/restxq/impl/ExistXqueryRegistry.java
extensions/exquery/restxq/src/main/java/org/exist/extensions/exquery/restxq/impl/xquery/exist/ExistRestXqModule.java
extensions/exquery/restxq/src/main/java/org/exist/extensions/exquery/restxq/impl/xquery/exist/RegistryFunctions.java
src/org/exist/security/internal/SecurityManagerImpl.java
src/org/exist/xquery/ModuleContext.java
src/org/exist/xquery/XQuery.java

Fixes an issue whereby RESTXQ failed to discover all Resource Functions when compiling a complex graph of dependent XQuery modules.

Restxq dependencies fix

---

src/org/exist/util/EXistInputSource.java
src/org/exist/util/FileInputSource.java
src/org/exist/util/GZIPInputSource.java
src/org/exist/util/VirtualTempFileInputSource.java
src/org/exist/util/ZipEntryInputSource.java
src/org/exist/xmlrpc/RpcConnection.java

Closes https://github.com/eXist-db/exist/issues/942

Fix remote restore of binary files

---

src/org/exist/storage/index/BTreeStore.java

Revert "Structure index: change lock to MultiReadReentrantLock"

---

extensions/contentextraction/ivy.xml

Note: the large nr of dependancies keep to be an issue ; I'd recommend to have a separate server for this instead....
fixes #937

Upgrade to Tika v1.12 ; fixes #937

---

extensions/indexes/lucene/src/org/exist/indexing/lucene/AnalyzerConfig.java

added additional checks if a 'value' is…really available;  convert to string-switch to make code more readable.

General improvement of the Lucene Analyzer config class 

---

src/org/exist/xquery/functions/system/FnExport.java

Fix for incorrect documentation in system:export function

---

src/org/exist/Indexer.java
src/org/exist/collections/Collection.java
src/org/exist/indexing/AbstractStreamListener.java
src/org/exist/indexing/IndexController.java
src/org/exist/indexing/StreamListener.java
src/org/exist/storage/NativeBroker.java

1. Provides better hints to the Index's StreamListener around the start and end of indexing for a document.
2. Sends start/end document events to the Index's StreamListener for adding and removing binary resources. This provides the facility for a custom index to index binary resources.

Indexing enhancements

---

test/src/org/exist/xslt/TransfomerFactoryAllocatorTest.java

[bugfix] Correct failing TransformerFactory test introduced by https://github.com/eXist-db/exist/pull/1002

Correct failing TransformerFactory test

---

build/scripts/junit.xml

Remove dead Any code for XSLTS

[cleanup] Remove old Ant code for building XSLT and XSLT Test Suite

---

src/org/exist/xquery/BasicFunction.java
src/org/exist/xquery/TryCatchExpression.java
test/src/org/exist/xquery/functions/xquery3/TryCatchTest.java
test/src/xquery/xquery3/xq3_trycatch.xml

Closes https://github.com/eXist-db/exist/issues/324

Fix issues with error handling

---

src/org/exist/collections/Collection.java
src/org/exist/dom/persistent/DefaultDocumentSet.java
src/org/exist/dom/persistent/QNamePool.java
src/org/exist/storage/XQueryPool.java
src/org/exist/storage/lock/LockedDocumentMap.java
src/org/exist/util/hashtable/AbstractHashSet.java
src/org/exist/util/hashtable/AbstractHashtable.java
src/org/exist/util/hashtable/Int2ObjectHashMap.java
src/org/exist/util/hashtable/Long2ObjectHashMap.java
src/org/exist/util/hashtable/NamePool.java
src/org/exist/util/hashtable/Object2IntHashMap.java
src/org/exist/util/hashtable/Object2LongHashMap.java
src/org/exist/util/hashtable/Object2LongIdentityHashMap.java
src/org/exist/util/hashtable/Object2ObjectHashMap.java
src/org/exist/util/hashtable/ObjectHashSet.java
src/org/exist/util/hashtable/SequencedLongHashMap.java
src/org/exist/xquery/functions/fn/ExtCollection.java
test/src/org/exist/util/hashtable/AbstractHashSetTest.java
test/src/org/exist/util/hashtable/Object2LongIdentityHashMapTest.java

1. Reformatted and cleaned up the code
2. Marked whether each implementation is ThreadSafe with JCIP annotations

General code cleanup of internal hashtable implementations

---

src/org/exist/backup/SystemExport.java
src/org/exist/collections/Collection.java
src/org/exist/util/io/Resource.java

Closes https://github.com/eXist-db/exist/issues/998

Collection contents locking

---

conf.xml.tmpl
extensions/expath/src/org/expath/exist/ZipEntryFunctions.java
extensions/modules/src/org/exist/xquery/modules/httpclient/BaseHTTPClientFunction.java
extensions/modules/src/org/exist/xquery/modules/jndi/GetDirContextFunction.java
extensions/modules/src/org/exist/xquery/modules/mail/MailSessionFunctions.java
extensions/modules/src/org/exist/xquery/modules/mail/MessageFunctions.java
extensions/modules/src/org/exist/xquery/modules/memcached/MemcachedClientFunction.java
extensions/modules/src/org/exist/xquery/modules/sql/GetConnectionFunction.java
extensions/modules/src/org/exist/xquery/modules/xmpp/XMPPConnectionFunction.java
extensions/modules/src/org/exist/xquery/modules/xslfo/RenderFunction.java
schema/conf.xsd
src/org/exist/util/Configuration.java
src/org/exist/util/HtmlToXmlParser.java
src/org/exist/util/ParametersExtractor.java
src/org/exist/xmldb/LocalCollection.java
src/org/exist/xquery/functions/util/Parse.java
src/org/exist/xquery/modules/ModuleUtils.java

* Allows eXist to support at least CyberNeko or TagSoup, configurable via conf.xml

Make the HTML to XML Parser Configurable

---

conf.xml.tmpl
src/org/exist/backup/SystemExport.java
src/org/exist/storage/serializers/AbstractChainOfReceivers.java
src/org/exist/storage/serializers/ChainOfReceivers.java
src/org/exist/storage/serializers/ChainOfReceiversFactory.java
src/org/exist/util/Configuration.java
test/src/org/exist/backup/FilterForBackup.java
test/src/org/exist/backup/FilterTest.java
test/src/org/exist/backup/SystemExportFiltersTest.java

That feature allow to modify content of document that was backup.

custom filters for backup

---

extensions/fluent/src/org/exist/fluent/Database.java
src/org/exist/storage/ContentLoadingObserver.java
src/org/exist/storage/NativeBroker.java
src/org/exist/storage/NativeValueIndex.java
src/org/exist/storage/ValueIndexFactory.java
src/org/exist/storage/io/AbstractVariableByteInput.java
src/org/exist/storage/io/VariableByteArrayInput.java
src/org/exist/storage/io/VariableByteOutputStream.java
src/org/exist/xquery/GeneralComparison.java

Code audit and cleanup in the NativeValueIndex

Tidy up the NativeValueIndex

---

nbproject/build-impl.xml
nbproject/project.properties
nbproject/project.xml

Updated nbprojects files and dependencies:
* adapted to new Wrapper yajsw, the library duplication is huge though
* adapted to removed extensions

Updated nbproject files and dependencies.

---

src/org/exist/launcher/Launcher.java
src/org/exist/launcher/LauncherWrapper.java
src/org/exist/start/Main.java

Closes https://github.com/eXist-db/exist/issues/1063

Launcher jetty 9

---

src/org/exist/xquery/value/ValueSequence.java
test/src/xquery/xquery3/fn.xql
test/src/xquery/xquery3/suite.xql

As reported in https://github.com/eXist-db/exist/issues/1067

Repair fold-right

---

src/org/exist/xquery/functions/fn/FunLocalName.java
test/src/org/exist/xquery/XQueryFunctionsTest.java

Closes https://github.com/eXist-db/exist/issues/735

[bugfix] fn:local-name() should not cause an NPE.

---

test/src/xquery/dates/format-dates.xql

as noted at https://github.com/eXist-db/exist/pull/1096#issuecomment-241097001

fix invalid picture string

---

src/org/exist/xquery/value/FunctionReference.java
test/src/org/exist/xquery/value/MapTest.java

Makes it compliant with the spec.

[bugfix] Make sure that the Effective Boolean Value of map causes FORG0006

---

src/org/exist/xquery/XQueryContext.java

Copy source too ; this caused a NPE in combination with the replication extension 
see https://github.com/eXist-db/messaging-replication/issues/84

add 'Copy source' ; missing caused NPE for  JMS extension

---

webapp/controller.xql

Closes https://github.com/eXist-db/exist/issues/1122

[bugfix] Make sure not to assume the URL is /exist/ when reverse proxying

---

src/org/exist/xquery/lib/kwic.xql

Highlights the serialized attribute matches with @exist:matches
attribute in KWIC summarized response.

Highlights attribute matches

---

src/org/exist/xquery/Function.java
src/org/exist/xquery/PathExpr.java
src/org/exist/xquery/VariableDeclaration.java
test/src/org/exist/xquery/XQueryTest.java

Closes https://github.com/eXist-db/exist/issues/1121

XPTY0018 should only be raised for Path Operations

---

src/org/exist/jetty/JettyStart.java

Closes https://github.com/eXist-db/exist/issues/1148

[bugfix] Show a more friendly config path on startup

---

build/scripts/jarsigner.xml
src/org/exist/webstart/JnlpJarFiles.java
src/org/exist/webstart/JnlpWriter.java

Fixes #1146 
- repaired unsigning / pack200'ing / normalizing 
- added missing jar files
- configure JUL to use log4j2
- add exist-db version to jnlp;
hint: pull-in PR with 'squash' option of Github webUI.

Repair and improve webstart feature

---

build/scripts/build-impl.xml
tools/yajsw/build.xml

This PR combines the work of @ljo #1157 and @dizzzz #1159.
An absolute path is now filled in the config files. Let travis show the results....

Rework of YAJSW changes by @dizzzz and @ljo

---

tools/yajsw/build.xml

Failing the build if environment variables JAVA_HOME and EXIST_HOME are not set for the yajsw wrapper config preparation. Addresses #1147.

Make build fail when JAVA_HOME and EXIST_HOME are not set

---

src/org/exist/indexing/IndexManager.java
src/org/exist/storage/BrokerPool.java

This was previously missing from the BrokerPool refactoring.

Fix the initialisation style of the IndexManager

---

tools/yajsw/bin/installDaemon.sh

This is the first round. It solves the issue with PID, but there is a bigger problem at play which I need to discuss with @ljo.

Yajsw systemd fixes

---

src/org/exist/ant/XMLDBExtractTask.java

Previously I accidentally broke the `xdb:extract` Ant task when cleaning up some code

[bugfix] Fix the xdb:extract Ant task

---

src/org/exist/xquery/functions/util/LogFunction.java

Improve log function

---

build/scripts/build-impl.xml

@wolfgangmm  this might be the fix of your issue

Do not remove the .DO_NOT_DELETE file from jetty/tmp during cleanup.

---

src/org/exist/collections/CollectionCache.java
src/org/exist/management/Cache.java
src/org/exist/management/CacheMBean.java
src/org/exist/storage/CollectionCacheManager.java
src/org/exist/storage/DefaultCacheManager.java
src/org/exist/storage/btree/BTree.java
src/org/exist/storage/cache/BTreeCache.java
src/org/exist/storage/cache/Cache.java
src/org/exist/storage/cache/Cacheable.java
src/org/exist/storage/cache/GClockCache.java
src/org/exist/storage/cache/LRDCache.java
src/org/exist/storage/cache/LRUCache.java
src/org/exist/storage/dom/DOMFile.java
src/org/exist/storage/index/BFile.java

Some general code cleanup and type safety improvements in eXist's Cache classes.

Collection cache cleanup

---

src/org/exist/repo/Deployment.java

As reported by Jonathan Rowell on exist-open

Make deployer write to logfile instead of stdout.

---

.idea/runConfigurations/Client.xml
.idea/runConfigurations/Server.xml

Now the expath repo is found at startup, and XAR files can executed

Intellij: Explicitly set EXIST_HOME during startup of server and client;

---

extensions/indexes/lucene/src/org/exist/indexing/lucene/LuceneIndex.java
test/src/org/exist/storage/ModificationTimeTest.java
test/src/org/exist/storage/MoveResourceTest.java

* Properly close lucene-based indexes before removing and use nio for deleting the files
* Fix test suite so it runs clean again

Fix recovery issues under windows

---

src/org/exist/xquery/functions/transform/Transform.java
src/org/exist/xquery/functions/transform/TransformModule.java

Fixed bug in `stream-transform(#5)` function where the 4th and 5th parameter were not correctly handled.
Generic code cleanup, simplified some code.
Hopefully fixing 
- http://exist.markmail.org/thread/om2n3yaa4kdnsfgu
- http://markmail.org/thread/5n6lxsn4tvk5jrkp 
updated function description (cardinality) in attached PDF
[XQuery Function Documentation.pdf](https://github.com/eXist-db/exist/files/706111/XQuery.Function.Documentation.pdf)

Bugfix/fix xslt module 

---

src/org/exist/xquery/OpAnd.java
src/org/exist/xquery/OpOr.java
test/src/xquery/logicalOp/andor.xql
test/src/xquery/logicalOp/suite.xql

Remove old, now probably unnecessary optimizations to fix #1106. Performance tests did not show any regression. 
Added tests for boolean operators.

Simplify processing of and/or

---

src/org/exist/collections/MutableCollection.java
src/org/exist/indexing/AbstractStreamListener.java
src/org/exist/indexing/StreamListener.java
src/org/exist/storage/NativeBroker.java

Such a facility is used by the Algolia Index plugin - https://gitlab.com/adamretter/exist-algolia-index/

[feature] A facility for optimising indexes which support differential updates when replacing a document

---

src/org/exist/util/serializer/XHTML5Writer.java

define void-elements for HTML5 writer

---

README.md

- Add description of eXist
- Show resources as a clear list
- Add links to mailing list, packages, hipchat
https://github.com/eXist-db/exist/issues/1247
None

Streamline README.md

---

src/org/exist/xquery/WhereClause.java
test/src/xquery/xquery3/forwhere.xml

where expresion must not be evaluated for empty sequence

---

src/org/exist/xquery/FunctionCall.java
test/src/org/exist/xquery/DeferredFunctionCallTest.java
test/src/xquery/xquery3/inline.xml
test/src/xquery/xquery3/recursion_calls.xml

make sure that functionDef do not shared between DeferredFunctionCallImpl

---

extensions/webdav/src/org/exist/webdav/ExistCollection.java
extensions/webdav/src/org/exist/webdav/ExistDocument.java
src/org/exist/protocolhandler/embedded/EmbeddedUpload.java
src/org/exist/storage/NativeBroker.java
src/org/exist/util/io/Resource.java
test/src/org/exist/storage/LargeValuesTest.java

Fixes a bunch of incorrect Lock mode issues.

Fix lock modes

---

installer/apps.properties

Trim list of packages in default installer
https://github.com/eXist-db/exist/issues/1302 (Closes #1302)
n/a

Trim list of packages in default installer

---

build.properties

Add monex to the list of apps fetched from the public-repo and placed in the autodeploy directory
Closes https://github.com/eXist-db/exist/issues/1309
n/a

Add monex to apps placed in autodeploy

---

src/org/exist/xquery/functions/fn/FunSerialize.java
test/src/xquery/TestRunnerMain.java

Just a couple of minor unrelated fixes

Minor fixes

---

src/org/exist/xquery/functions/system/Shutdown.java

or timer thread prevent jvm to exit

shutdown timer must be daemon

---

src/org/exist/xquery/ArrowOperator.java
test/src/xquery/xquery3/arrowop.xml
test/src/xquery/xquery3/arrowop.xql

arrow operator raise error if xquery is < 3.1

---

nbproject/project.properties

fix for #1355, netbeans ide properties

Netbeans properties

---

src/org/exist/client/InteractiveClient.java

Closes https://github.com/eXist-db/exist/issues/1354

Client should use the non-default password if provided

---

eXist-db.iml
extensions/indexes/lucene/src/org/exist/indexing/lucene/LuceneIndexConfig.java
extensions/indexes/range/extension.xml
extensions/indexes/range/src/org/exist/indexing/range/RangeIndexConfig.java
extensions/indexes/range/src/org/exist/indexing/range/RangeIndexConfigElement.java
extensions/indexes/range/test/src/org/exist/indexing/range/RangeIndexConfigTest.java
src/org/exist/dom/QName.java

Closes https://github.com/eXist-db/exist/issues/1339

Fixes missing context information in Range Index Config errors

---

build/scripts/build-impl.xml
build/scripts/git-support.xml

Closes https://github.com/eXist-db/exist/issues/1336

Should show git tag name and not "HEAD" when building from a tag

---

src/org/exist/backup/Main.java

Closes https://github.com/eXist-db/exist/issues/1338

Some arguments for Backup/Restore should not be required

---

src/org/exist/xquery/XQueryContext.java
src/org/exist/xquery/functions/inspect/InspectModule.java
test/src/xquery/inspect/InspectTests.java
test/src/xquery/inspect/inspect.xql
test/src/xquery/inspect/suite.xql

Closes https://github.com/eXist-db/exist/issues/1245

Avoid NPE when misusing library import

---

src/org/exist/client/ClientFrame.java
src/org/exist/client/InteractiveClient.java

address [issue](https://github.com/wolfgangmm/eXide/issues/151#issuecomment-285603580)

use XmldbURI instead of manual encoding/decoding at java client

---

src/org/exist/xquery/functions/fn/FunDocAvailable.java
src/org/exist/xquery/util/DocUtils.java
test/src/xquery/CoreTests.java
test/src/xquery/fn.xql
test/src/xquery/nill.xql

Closes https://github.com/eXist-db/exist/issues/1364

Fix error handling in fn:doc-available

---

extensions/indexes/lucene/src/org/exist/indexing/lucene/LuceneIndexWorker.java

Added option "lowercase-expanded-terms" for ft:query().
http://exist.2174344.n4.nabble.com/Analyzer-for-ft-query-td4669352.html

Added option "lowercase-expanded-terms" for ft:query().

---

CONTRIBUTING.md
exist-versioning-release.md

Closes https://github.com/eXist-db/exist/issues/1313

[doc] eXist Versioning Scheme and Release Process document

---

extensions/indexes/range/test/src/xquery/index-keys.xql
extensions/indexes/range/test/src/xquery/suite-index-keys.xql
extensions/security/iprange/src/org/exist/security/realm/iprange/IPRangeRealm.java
extensions/security/iprange/src/org/exist/security/realm/iprange/IPRangeServlet.java
src/org/exist/xquery/functions/transform/Transform.java

reworked version of https://github.com/eXist-db/exist/pull/834

Reworked IP range

---

src/org/exist/xmldb/XmldbURI.java
test/src/org/exist/xmldb/XmldbURITest.java

Fix the bug prevent use of short 'xmldb:/' url prefix

fix XmldbURI to handle 'xmldb:/' case correctly

---

src/org/exist/config/Configurator.java

Regression from [commit](https://github.com/eXist-db/exist/commit/c33c14dbaa7abf1266b5c0b4e2275aba5d931980#diff-14c997a296d3c6ef5867561c0e1ed25dR503).

handle correctly referenceBy not set case

---

src/org/exist/dom/memtree/DocumentBuilderReceiver.java
src/org/exist/dom/memtree/MemTreeBuilder.java
src/org/exist/xquery/EnclosedExpr.java
src/org/exist/xquery/ErrorCodes.java
test/src/xquery/namespaces.xql

close https://github.com/eXist-db/exist/issues/1237

fix namespace constructor in computed constructor

---

src/org/exist/client/CommandlineOptions.java

Closes https://github.com/eXist-db/exist/issues/1401

[bugfix] Correct the short version of the parse arg in the client

---

tools/yajsw/bin/uninstallDaemon.sh

Uninstall counterpart to previous install PR https://github.com/eXist-db/exist/pull/1171

Fixes the uninstallation of systemd for YAJSW

---

src/org/exist/dom/persistent/NewArrayNodeSet.java
test/src/xquery/axes.xql

process all elements at selectFollowingSiblings

---

extensions/debuggee/src/org/exist/debuggee/dbgp/packets/Source.java
extensions/expath/src/org/expath/exist/ZipFileFunctions.java
extensions/indexes/lucene/src/org/exist/xquery/modules/lucene/InspectIndex.java
extensions/security/openid/src/org/exist/security/realm/openid/OpenIDUtility.java
src/org/exist/util/io/Resource.java

Pretty straight forward stuff that was spotted through code review.

Fix a few issues with lock acquisition/release

---

src/org/exist/http/RESTServer.java
src/org/exist/http/servlets/EXistServlet.java
webapp/WEB-INF/web.xml.tmpl

These are the options as previously discussed to disable submission of XQuery and/or XUpdate by the REST Server.
Feel free to comment/discuss

[bugfix] Add options to disable XQuery and XUpdate execution via submission

---

src/org/exist/dom/persistent/AttrImpl.java
src/org/exist/dom/persistent/DocumentImpl.java
src/org/exist/dom/persistent/ElementImpl.java
src/org/exist/dom/persistent/NodeImpl.java
src/org/exist/dom/persistent/StoredNode.java
src/org/exist/dom/persistent/TextImpl.java
test/src/org/exist/dom/persistent/DocumentImplTest.java
test/src/org/exist/dom/persistent/ElementImplTest.java
test/src/org/exist/dom/persistent/TextImplTest.java

Closes https://github.com/eXist-db/exist/issues/1337

[bugfix] Ensure that isSameNode is correctly implemented

---

exist-versioning-release.md

Added details about all the steps needed to create and publish a production release!

Updated from a real world release

---

build/scripts/build-impl.xml

This can be used by other projects (e.g. extension module) to execute tests against exist.

[feature] Produce an exist-testkit.jar

---

src/org/exist/storage/serializers/EXistOutputKeys.java
src/org/exist/util/serializer/AbstractSerializer.java
src/org/exist/util/serializer/AdaptiveSerializer.java
src/org/exist/util/serializer/AdaptiveWriter.java
src/org/exist/util/serializer/IndentingXMLWriter.java
src/org/exist/util/serializer/XQuerySerializer.java
src/org/exist/xquery/functions/fn/FunSerialize.java
src/org/exist/xquery/functions/map/SingleKeyMapType.java
test/src/xquery/maps/maps.xql
test/src/xquery/xquery3/serialize.xql

Implement adaptive output mode as defined by [XQuery 3.1 serialization](https://www.w3.org/TR/xslt-xquery-serialization-31/#adaptive-output) spec. See tests for examples.

Adaptive output

---

extensions/indexes/lucene/test/src/xquery/lucene/inline_elements.xql
extensions/indexes/lucene/test/src/xquery/lucene/suite.xql

rework of https://github.com/eXist-db/exist/pull/1440
added testcase

rework: fix lucene inline elements in case of not yet applied whitespaces

---

src/org/exist/ant/RestoreTask.java
test/src/ant/exist.properties
test/src/ant/server.xml

Fixes bug #1453. Added missing test for xmldb:backup/restore ant task.

[bugfix] Fix xmldb:restore ant task. Closes #1453

---

src/org/exist/management/client/JMXtoXML.java
src/org/exist/management/impl/ActiveBroker.java
src/org/exist/management/impl/Database.java
src/org/exist/management/impl/DatabaseMXBean.java
src/org/exist/management/impl/Error.java
src/org/exist/management/impl/Job.java
src/org/exist/management/impl/Lock.java
src/org/exist/management/impl/LockManager.java
src/org/exist/management/impl/LockManagerMXBean.java
src/org/exist/management/impl/ProcessReport.java
src/org/exist/management/impl/ProcessReportMXBean.java
src/org/exist/management/impl/RecentQueryHistory.java
src/org/exist/management/impl/RunningQuery.java
src/org/exist/management/impl/SanityReport.java
src/org/exist/management/impl/SanityReportMXBean.java

After change to mxbean (in 5edf64625aa0df4f825be70630cfaf7444166cd4), information on running queries, query history, jobs, locks etc. was no longer provided. This not only affected eXist's JMXServlet but also jconsole and other JMX clients.

[bugfix] Fix JMX interface

---

src/org/exist/xquery/Lookup.java
test/src/xquery/maps/mapsLookup.xql

Attempt to fix https://github.com/eXist-db/exist/issues/1457

Fix for lookup operator / null values

---

build/scripts/junit.xml
extensions/modules/src/org/exist/xquery/modules/file/SerializeToFile.java
test/src/xquery/modules/file/FileTests.java
test/src/xquery/modules/file/serialize.xql
test/src/xquery/modules/file/suite.xql

Fixes https://github.com/eXist-db/exist/issues/1441 
Test case in issue report.

file:serialize() can not append to file

---

src/org/exist/xquery/functions/fn/FnModule.java
src/org/exist/xquery/functions/fn/FunSort.java
test/src/xquery/xquery3/fnSort.xql
test/src/xquery/xquery3/suite.xql

Implementation of [fn:sort](https://www.w3.org/TR/xpath-functions-31/#func-sort)

fn:Sort function

---

installer/install.xml.tmpl

[bugfix] Fix the installer with regards to the Mac AppLauncher

---

src/org/exist/Indexer.java

This PR slightly modifies the code order so that the `IndexListener#endElement` is not called until after `broker#updateNode` has been called.
Without this if you called `element#getChildNodes` in an IndexListener you might get an empty NodeList whilst `element#children > 0`. This ensures that the indexer does not work with nodes that are not finished in `endElement`.
I have tried to write a unit test for this, but the code in Indexer is so tightly coupled with other classes, that it proved almost impossible, even with a huge amount of mocking.
We have experience this bug in the Algolia Indexer for eXist-db and I have discussed it with @wolfgangmm.
We need this to complete the Algolia Indexer for @ttasovac at [BCDH](https://github.com/BCDH).

Previously the IndexListener could be called on unfinished elements

---

exist-versioning-release.md

A couple of notes on updating GitHub and the release announcement email

Added some missing points to the release proccess

---

.gitignore
build/scripts/build-impl.xml

* Remove `exist-testkit.jar` when Ant target `clean` is executed.
* Have Git ignore `exist-testkit.jar`

Make sure exist-testkit.jar is cleaned up also

---

src/org/exist/backup/ExportMain.java

Closes https://github.com/eXist-db/exist/issues/1499

Fix args in ExportMain

---

build/scripts/build-impl.xml
build/scripts/installer.xml

Closes https://github.com/eXist-db/exist/issues/1475

Fix the signing of core Jar files

---

src/org/exist/client/ClientFrame.java

fixes  #1503 and #129
These are the texts in de message bundle:
```
CreateBackupDialog.6a=Target
CreateBackupDialog.6b= exists. OK to delete?
CreateBackupDialog.6c=Confirm deletion
```

Revise backup creation when directory exists

---

nbproject/project.properties

These were previously out of date.

Fix the dependencies in the NetBeans project file

---

extensions/build.properties
extensions/modules/src/org/exist/xquery/modules/xslfo/ApacheFopProcessorAdapter.java

* Capture FOP messages to eXist-db's logs
* Update to FOP 2.2.

Apache FOP Improvements

---

build/scripts/jarsigner.xml

fix for https://sourceforge.net/p/exist/mailman/message/35814965/

Repair signing of jar files

---

src/org/exist/xquery/xqdoc/XQDocHelper.java
test/src/org/exist/xquery/functions/inspect/InspectModuleTest.java

Related to https://github.com/eXist-db/exist/issues/1386

[bugfix] Extraneous whitespace should be trimmed from the XQDoc output.

---

src/org/exist/util/io/FileFilterInputStreamCache.java
test/src/org/exist/util/io/CachingFilterInputStreamTest.java

Should fix the issue described by @dizzzz here: https://github.com/eXist-db/exist/pull/1391#issuecomment-321612976

Fix for FileFilterInputStreamCache

---

src/org/exist/dom/memtree/DocumentFragmentImpl.java
src/org/exist/dom/memtree/NodeImpl.java
src/org/exist/dom/persistent/AbstractCharacterData.java
src/org/exist/dom/persistent/DocumentImpl.java
src/org/exist/dom/persistent/DocumentTypeImpl.java
src/org/exist/dom/persistent/ElementImpl.java
src/org/exist/dom/persistent/NodeImpl.java
src/org/exist/dom/persistent/ProcessingInstructionImpl.java
src/org/exist/dom/persistent/StoredNode.java
src/org/exist/dom/persistent/VirtualNodeSet.java
src/org/exist/indexing/IndexUtils.java
src/org/exist/storage/NativeBroker.java
src/org/exist/xquery/OpSimpleMap.java
test/src/org/exist/xquery/XQueryTest.java
test/src/org/exist/xquery/functions/transform/TransformTest.java

Another fix to our DOM implementations: Closes https://github.com/eXist-db/exist/issues/1506

Node#hasChildNodes should not include attributes

---

src/org/exist/xquery/NameTest.java
test/src/xquery/axes.xql

This is a regression caused by changes to the DOM implementation. Test added.

[bugfix] Fix selection of processing instructions by target

---

extensions/indexes/range/src/org/exist/indexing/range/RangeIndexWorker.java
extensions/indexes/range/test/src/xquery/field-type.xql
extensions/indexes/range/test/src/xquery/suite-types.xql

New range index does not assign correct node type to results of a field query, thus leading to type errors. Closes #1454

[bugfix] Range index sets incorrect type

---

build.properties
build/scripts/build-impl.xml
build/scripts/macosx.xml
conf.xml.tmpl

Closes https://github.com/eXist-db/exist/pull/1535
@wshager I rebased your PR to add the missing properties that I suggested. I also squashed the commits into a single commit as the change was simple enough. Does this look okay to you?

Put db settings in build.properties

---

src/org/exist/xquery/ArrowOperator.java
src/org/exist/xquery/Function.java
src/org/exist/xquery/NamedFunctionReference.java
src/org/exist/xquery/XQueryContext.java
test/src/xquery/xquery3/arrowop.xql
test/src/xquery/xquery3/higher-order.xml

Fix arrow operator type errors

---

src/org/exist/xquery/functions/xmldb/XMLDBHasLock.java

Closes https://github.com/eXist-db/exist/issues/1484

Fixed the description of the xmldb:clear-lock function

---

src/org/exist/storage/BrokerPool.java
test/src/org/exist/storage/BrokerPoolTest.java

This is really just a test to prove that the BrokerPool works when it is saturated by requests.

Test for broker pool stauration

---

CONTRIBUTING.md

add security mail to contributing.md

---

.classpath
.idea/compiler.xml
.idea/libraries/ant.xml
.idea/misc.xml
eXist-db.iml
nbproject/project.properties
nbproject/project.xml

Fixes the project files for various IDEs.

Fixes NetBeans, Eclipse and Idea Ultimate IDEs

---

src/org/exist/storage/serializers/XIncludeFilter.java

Closes https://github.com/eXist-db/documentation/issues/137
Previously the documentation for XInclude would throw an XPathException unless you were running eXist-db on port 8080, this bugfix instead makes it fallback correctly.

Makes XInclude via http more generous in falling back

---

.idea/compiler.xml
src/org/exist/repo/ExistRepository.java
src/org/exist/start/Classpath.java
src/org/exist/start/EXistClassLoader.java
src/org/exist/xquery/XQueryContext.java

1. Re-enables AspectJ in IntelliJ Ultimate IDE now that we have Java 9 support.
2. Fixes issues with loading EXPath Modules (Java) under some run configurations e.g. debugging from IntelliJ
3. Minor corrections to logging and javadoc.

A couple of very small bug fixes

---

README.md

YourKit will provide us with licenses for our Open Source project, in exchange for a credit.

Added YourKit credit

---

src/org/exist/start/Classpath.java
src/org/exist/start/EXistClassLoader.java

Fixes an issue during startup.

[bugfix] Don't use logger during Bootstrap

---

src/org/exist/collections/triggers/HistoryTrigger.java
test/src/org/exist/collections/triggers/HistoryTriggerTest.java

Closes https://github.com/eXist-db/exist/issues/1618

Fixes a StackOverflow in the HistoryTrigger

---

src/org/exist/util/ConfigurationHelper.java

Previously caused problems on Windows platforms.
Closes https://github.com/eXist-db/exist/issues/1471

Fixes an issue with eXist home path not being correctly constructed.

---

extensions/modules/src/org/exist/xquery/modules/xslfo/ApacheFopProcessorAdapter.java

Fixes an issue when using automatic font detection.

[bugfix] Make sure the relative base URI is absolute

---

src/org/exist/xmldb/RemoteCollection.java

The issue indicated by the comment was recently solved in commit 73707ff

Removed dead code comment

---

extensions/betterform/ivy.xml
extensions/contentextraction/ivy.xml

Closes https://github.com/eXist-db/exist/issues/1614

Exclude jcip-annotations-1.0.jar dependency from extensions

---

src/org/exist/xmlrpc/RpcServlet.java

Actually fixes the broken build!

[bugfix] Fix the ability to restart eXist-db using the XML-RPC interface

---

src/org/exist/xquery/value/QNameValue.java
test/src/xquery/namespaces.xql

Closes https://github.com/eXist-db/exist/issues/741

[bugfix] Inability compare a QName should result in XPTY0004

---

src/org/exist/xquery/functions/fn/FunDocAvailable.java
test/src/xquery/fn.xql

Closes https://github.com/eXist-db/exist/issues/1364

Fix to return value of fn:doc-available on failure

---

src/org/exist/xquery/functions/fn/FunAnalyzeString.java
src/org/exist/xquery/functions/fn/FunMatches.java
src/org/exist/xquery/functions/fn/FunReplace.java
src/org/exist/xquery/functions/fn/FunTokenize.java
src/org/exist/xquery/regex/JDK15RegexTranslator.java
src/org/exist/xquery/regex/RegexTranslator.java
src/org/exist/xquery/regex/RegexUtil.java
test/src/xquery/regex.xml

Closes https://github.com/eXist-db/exist/issues/1281

Fixes to XPath 3.0 Regular Expression parsing

---

src/org/exist/dom/memtree/MemTreeBuilder.java
src/org/exist/dom/memtree/NodeImpl.java
src/org/exist/dom/memtree/SAXAdapter.java
src/org/exist/dom/persistent/ElementImpl.java
src/org/exist/repo/Deployment.java
src/org/exist/util/serializer/SAXSerializer.java
test/src/org/exist/dom/memtree/DocumentImplTest.java

Closes https://github.com/eXist-db/exist/issues/1620
I also checked that this PR keeps the same DOM Test Suite score that we have for eXist 3.6.0 - https://github.com/exist-db/exist-domts#exist-db-360

Fixes for MemTree namespace nodes

---

src/org/exist/xquery/value/AbstractDateTimeValue.java
src/org/exist/xquery/value/AnyURIValue.java
src/org/exist/xquery/value/NumericValue.java
test/src/xquery/namespaces.xql

Fix errorcodes several atomic comparisons

---

src/org/exist/xquery/GeneralComparison.java
test/src/xquery/namespaces.xql

Closes https://github.com/eXist-db/exist/pull/1647

Replaces PR 1647

---

src/org/exist/util/Collations.java
test/src/org/exist/util/CollationsTest.java

Closes https://github.com/eXist-db/exist/issues/1585
@joewiz I am certainly no collation expert, however I think this likely solves it.

Implement the HTML ASCII Case Insensitive Collation as defined in XPath F&O 3.1

---

schema/conf.xsd

Allow job/@unschedule-on-exception in conf.xml.
Closes #1657.
n/a

Allow job/@unschedule-on-exception in conf.xml

---

exist-versioning-release.md

The process for updating the website is now done via its source code.

Updated the process for modifying the website.

---

extensions/expath/src/org/expath/exist/SendRequestFunction.java
src/org/exist/backup/Backup.java
src/org/exist/client/ClientFrame.java
src/org/exist/client/QueryDialog.java
src/org/exist/jetty/JettyStart.java
src/org/exist/management/client/JMXtoXML.java
src/org/exist/protocolhandler/embedded/EmbeddedDownloadThread.java
src/org/exist/protocolhandler/embedded/EmbeddedUploadThread.java
src/org/exist/protocolhandler/xmlrpc/XmlrpcDownloadThread.java
src/org/exist/protocolhandler/xmlrpc/XmlrpcUploadThread.java
src/org/exist/scheduler/impl/ShutdownTask.java
src/org/exist/storage/journal/FileSyncThread.java
src/org/exist/storage/journal/Journal.java
src/org/exist/util/NamedThreadFactory.java
src/org/exist/validation/internal/node/NodeSerializerThread.java
src/org/exist/xquery/functions/util/Eval.java

1. Fixes a bug in the EXPath HTTP Client with connection pooling
2. Fixes a problem with bad thread synchronization in JMX
3. Explicitly names each thread that eXist creates for easier identification.

Fixes some synchronization and reuse issues

---

src/org/exist/http/RESTServer.java
test/src/org/exist/http/RESTServiceTest.java

Closes https://github.com/eXist-db/exist/issues/1646

Invalid query should result in HTTP 400

---

bin/run.sh
build.bat
build.sh
installer/launch_client.bat
installer/scripts/build.bat
installer/scripts/build.sh
installer/scripts/eXist-settings.sh
installer/scripts/setup.bat
installer/scripts/setup.sh
tools/jsvc/exist-init.d.sh
tools/jsvc/exist.sh

https://github.com/eXist-db/exist/issues/1671

Remove further use of endorsed folder

---

build/scripts/build-impl.xml
build/scripts/git-support.xml

Closes https://github.com/eXist-db/exist/issues/1673

Make sure the build labels are calculated for a non-git install

---

extensions/modules/src/org/exist/xquery/modules/persistentlogin/login.xql
webapp/xqts/xqts.xql

Currently breaks install after update to latest develop. Before release, fixes will also be required in
* function documentation
* dashboard
* demo apps

[bugfix] fix wrong uses of empty() type declaration. Closes #1707

---

exist-versioning-release.md

Closes action A-180115-3:
> Update release document about adding new releases to Homebrew
Also, adopts present tense for the document, as it is now in use.
https://docs.google.com/spreadsheets/d/10uqjXLrhWxvcZ9WlJzhT6IeD8gpy6a5abfmGVLw7LwM/edit?usp=sharing
n/a

Update release procedures

---

build.properties

New usermanager needs to be pulled into autodeploy as dashboard now depends on it.

Fix broken startup of current develop

---

src/org/exist/dom/persistent/ElementImpl.java
test/src/xquery/suite.xql
test/src/xquery/xquery-update.xql

Closes https://github.com/eXist-db/exist/pull/1664

Fixes a regression with XQuery Update insert

---

test/src/org/exist/xquery/LexerTest.java
test/src/org/exist/xquery/XPathQueryTest.java

Very small cleanup in two tests.

Remove stdout/stderr polution from tests

---

test/src/org/exist/xquery/XQueryTest.java

A nice clean solution to an old problem.

Use JUnit4 assumptions in test that requires internet access

---

src/org/exist/storage/SystemTaskManager.java

We can avoid a little work when a transaction is committed if there are no system tasks waiting to run.

[refactor] Avoid unnecessary work

---

tools/jetty/etc/standalone/WEB-INF/web.xml

Minor configuration file change

Remove reference to old Webdav interface

---

src/org/exist/xmldb/DatabaseImpl.java
src/org/exist/xmlrpc/ExistRpcTypeFactory.java
src/org/exist/xmlrpc/RpcAPI.java
src/org/exist/xmlrpc/RpcConnection.java
src/org/exist/xmlrpc/RpcServlet.java
src/org/exist/xmlrpc/TupleParser.java
src/org/exist/xmlrpc/TupleSerializer.java
test/src/org/exist/xmlrpc/XmlRpcTest.java

This is backwards compatible. No breaking API changes.

Some improvements to the XML RPC code

---

src/org/exist/http/urlrewrite/ControllerForward.java
src/org/exist/http/urlrewrite/Forward.java
src/org/exist/http/urlrewrite/ModuleCall.java
src/org/exist/http/urlrewrite/PassThrough.java
src/org/exist/http/urlrewrite/PathForward.java
src/org/exist/http/urlrewrite/Redirect.java
src/org/exist/http/urlrewrite/RewriteConfig.java
src/org/exist/http/urlrewrite/URLRewrite.java
src/org/exist/http/urlrewrite/XQueryURLRewrite.java

1. Simplify and make the logic for finding a `controller.xql` more transparent.
2. Lots of general code cleanup

Cleanup XQueryURLRewrite

---

extensions/exquery/restxq/src/main/java/org/exist/extensions/exquery/restxq/impl/RestXqServiceRegistryPersistence.java
extensions/modules/src/org/exist/xquery/modules/expathrepo/Deploy.java
extensions/modules/src/org/exist/xquery/modules/file/FileReadBinary.java
src/org/exist/backup/ZipArchiveBackupDescriptor.java
src/org/exist/http/RESTServer.java
src/org/exist/http/servlets/HttpRequestWrapper.java
src/org/exist/http/servlets/HttpServletRequestWrapper.java
src/org/exist/http/servlets/RequestWrapper.java
src/org/exist/protocolhandler/embedded/EmbeddedUpload.java
src/org/exist/repo/RepoBackup.java
src/org/exist/util/IterableEnumeration.java
src/org/exist/util/VirtualTempFile.java
src/org/exist/util/VirtualTempFileInputSource.java
src/org/exist/util/io/Resource.java
src/org/exist/util/io/TemporaryFileManager.java
src/org/exist/xmldb/AbstractRemoteResource.java
src/org/exist/xmldb/RemoteBinaryResource.java
src/org/exist/xmldb/RemoteResourceSet.java
src/org/exist/xmldb/RemoteXMLResource.java
src/org/exist/xmlrpc/RpcConnection.java
src/org/exist/xquery/functions/request/GetUploadedFile.java
src/org/exist/xquery/functions/request/GetUploadedFileSize.java
src/org/exist/xquery/functions/validation/Jaxp.java
src/org/exist/xquery/functions/xmldb/XMLDBStore.java
src/org/exist/xquery/value/BinaryValue.java
src/org/exist/xquery/value/BinaryValueFromFile.java
test/src/org/exist/util/VirtualTempFileTest.java

Feel free to ignore the `[ignore]...` commit as it is mechanical cleanup.
This is a pre-requisite to further binary improvements before fixing https://github.com/eXist-db/exist/issues/1709

Small improvements and cleanup to binary handling

---

src/org/exist/xquery/value/BinaryValueFromBinaryString.java
src/org/exist/xquery/value/BinaryValueFromFile.java
test/src/xquery/modules/file/read-binary.xql

Closes https://github.com/eXist-db/exist/issues/1768
Closes https://github.com/eXist-db/exist/issues/1740

Fix regression with Binary values from Files and Strings

---

extensions/exquery/restxq/src/main/java/org/exist/extensions/exquery/restxq/impl/RestXqServiceRegistryPersistence.java
extensions/modules/src/org/exist/xquery/modules/file/FileMove.java

Closes https://github.com/eXist-db/exist/issues/1803

Atomic Move cannot be used where src and dest are on different fs

---

src/org/exist/xmlrpc/RpcConnection.java
test/src/org/exist/xmlrpc/XmlRpcTest.java

@dizzzz I think this is the issue you described to me recently; I just found it myself.

Fix regression in chunked transfer of XML-RPC

---

src/org/exist/util/Leasable.java
src/org/exist/xmldb/AbstractRemoteResource.java
src/org/exist/xmldb/DatabaseImpl.java
src/org/exist/xmldb/RemoteBinaryResource.java
src/org/exist/xmldb/RemoteCollection.java
src/org/exist/xmldb/RemoteCollectionManagementService.java
src/org/exist/xmldb/RemoteResourceIterator.java
src/org/exist/xmldb/RemoteResourceSet.java
src/org/exist/xmldb/RemoteUserManagementService.java
src/org/exist/xmldb/RemoteXMLResource.java
src/org/exist/xmldb/RemoteXPathQueryService.java
src/org/exist/xmldb/RemoteXUpdateQueryService.java

Closes https://github.com/eXist-db/exist/issues/1785

Some small fixes to XML:DB management of XmlRpcClient and cleanup

---

src/org/exist/backup/BackupHandler.java
src/org/exist/collections/Collection.java
src/org/exist/collections/CollectionConfigurationManager.java
src/org/exist/collections/MutableCollection.java
src/org/exist/dom/persistent/NodeSet.java
src/org/exist/security/Permission.java
src/org/exist/storage/NativeBroker.java

Small cleanups

---

build.properties

Add XAR file to repair new usermanager.
After startup the usermanager is functional 
Fixes eXist-db/usermanager#16 and #1813

Add functx XAR for usermanager

---

installer/apps.properties

Installer won't work without it.

[installer] usermanager now requires functx

---

build/scripts/build-impl.xml

exist-testkit.jar in our next release can now be used from Maven projects via XSuite to run XQSuite Unit Tests on apps etc.

Added XQSuite to exist-testkit.jar

---

appveyor.yml

Let's see if this fixes the AppVeyor builds

[bugfix] Fix AppVeyor builds on branches

---

src/org/exist/source/SourceFactory.java
src/org/exist/xquery/functions/inspect/ModuleFunctions.java

Closes https://github.com/eXist-db/exist/issues/1827

[bugfix] Make sure to use the correct source for the URI

---

src/org/exist/start/start.config

[bugfix] repair xmlunit functions

---

src/org/exist/source/ClassLoaderSource.java
test/src/org/exist/source/SourceFactoryTest.java

Closes https://github.com/eXist-db/exist/pull/1668/files

Fixup of PR #1668

---

src/org/exist/util/io/TemporaryFileManager.java

Closes https://github.com/eXist-db/exist/issues/1863

Reduce the severity of TemporaryFileManager logging

---

test/src/org/exist/xquery/XQueryTest.java
test/src/org/exist/xquery/external-classpath-module.xqm

Just a simple test against future regressions.

Test for a module stored in the DB importing a module from the classpath

---

BUILD.md

now with a clean PR
link is already live so ready to merge
close #1868

fix link in build.md

---

src/org/exist/indexing/IndexManager.java
src/org/exist/storage/BrokerPool.java
src/org/exist/storage/DBBroker.java
src/org/exist/storage/NativeBroker.java
src/org/exist/util/TimestampedReference.java
test/src/org/exist/storage/IndexManagerTest.java
test/src/org/exist/storage/MoveOverwriteResourceTest.java
test/src/org/exist/util/TimestampedReferenceTest.java
test/src/org/exist/xquery/update/IndexIntegrationTest.java

Enhances and fixes some shortcoming of #1679
Closes #1679

Fixup PR-1679

---

appveyor.yml

* Display JUnit results in the AppVeyor console
* Upload JUnit results as an artifact (so that it can be downloaded to help diagnose test failures).

Appveyor enhancements

---

src/org/exist/xquery/functions/fn/FnFormatDates.java
src/org/exist/xquery/value/AbstractDateTimeValue.java
test/src/xquery/dates/format-dates.xql

Closes https://github.com/eXist-db/exist/issues/1878
Corrects a small issue when converting between Calendar bases.

Written day of week was off by +1

---

src/org/exist/xmlrpc/RpcServlet.java
webapp/WEB-INF/web.xml.tmpl

Closes https://github.com/eXist-db/exist/issues/1899

Set the HTTP response character encoding for XML-RPC

---

tools/yajsw/build.xml

Replaces https://github.com/eXist-db/exist/pull/1345

Allow JAVA_HOME or java from the PATH for YAJSW build

---

src/org/exist/http/urlrewrite/XQueryURLRewrite.java
webapp/WEB-INF/web.xml.tmpl

Closes https://github.com/eXist-db/exist/issues/1861

XQueryURLRewrite challenge is now configurable

---

extensions/webdav/src/org/exist/webdav/ExistDocument.java
src/org/exist/http/RESTServer.java
src/org/exist/storage/NativeBroker.java
src/org/exist/storage/serializers/NativeSerializer.java
src/org/exist/util/serializer/IndentingXMLWriter.java
src/org/exist/util/serializer/MicroXmlWriter.java
src/org/exist/util/serializer/SAXSerializer.java
src/org/exist/util/serializer/TEXTWriter.java
src/org/exist/util/serializer/XMLWriter.java
src/org/exist/util/serializer/json/JSONWriter.java
src/org/exist/xmldb/LocalXMLResource.java
src/org/exist/xmlrpc/RpcConnection.java
test/src/org/exist/test/ExistEmbeddedServer.java
test/src/org/exist/test/ExistXmldbEmbeddedServer.java
test/src/org/exist/xmldb/SerializationTest.java
test/src/org/exist/xmldb/XmldbLocalTests.java

Closes https://github.com/eXist-db/exist/issues/1724

Fix empty namespace serialization issues

---

src/org/exist/config/ConfigurationDocumentTrigger.java
src/org/exist/security/AbstractRealm.java
src/org/exist/security/SecurityManager.java
src/org/exist/security/internal/RealmImpl.java
src/org/exist/security/internal/SecurityManagerImpl.java
src/org/exist/security/realm/Realm.java
src/org/exist/util/ConcurrentValueWrapper.java
src/org/exist/util/WeakLazyStripes.java
src/org/exist/xmldb/DatabaseImpl.java
test/src/org/exist/security/AbstractSecurityManagerRoundtripTest.java
test/src/org/exist/security/LocalSecurityManagerRoundtripTest.java
test/src/org/exist/security/internal/BackupRestoreSecurityPrincipalsTest.java
test/src/org/exist/test/ExistEmbeddedServer.java
test/src/org/exist/test/ExistXmldbEmbeddedServer.java
test/src/org/exist/util/WeakLazyStripesTest.java
test/src/org/exist/xmldb/DOMTest.java
test/src/org/exist/xquery/functions/util/SerializeTest.java

Closes https://github.com/eXist-db/exist/pull/1056
**NOTE**: These changes affect the format of the `/db/system/security/config.xml`. I think the changes are forwards compatible i.e. old backups should continue to work with eXist-db. However newer backups once this PR is applied will likely not work with older versions of eXist-db.
**NOTE**: This PR includes an API change where I have corrected a typo and spelling of an existing function name.
As such this should be merged as part of the work for eXist-db 5.0.

Fixup PR-1056

---

src/org/exist/util/EXistInputSource.java
src/org/exist/xmldb/AbstractRemoteResource.java
src/org/exist/xmldb/EXistResource.java
src/org/exist/xmldb/ExtendedResource.java
src/org/exist/xmldb/RemoteCollection.java

Closes https://github.com/eXist-db/exist/issues/1913
Closes https://github.com/eXist-db/exist/issues/1874

Fix an issue with uploading compressed zip entries with XML:DB Remote API

---

src/org/exist/http/RESTServer.java
src/org/exist/http/servlets/EXistServlet.java
src/org/exist/xmldb/AbstractLocal.java

Closes https://github.com/eXist-db/exist/issues/1928
Sorry guys this was a missed back-port from Granite.
I am very surprised that all the tests were passing without this... Seems we don't have enough tests for the REST Server in general!

Make Http Servlets Transaction aware

---

extensions/exiftool/src/org/exist/exiftool/xquery/MetadataFunctions.java
extensions/xqdoc/src/org/exist/xqdoc/xquery/Scan.java
src/org/exist/collections/triggers/XQueryStartupTrigger.java
src/org/exist/http/servlets/XQueryServlet.java
src/org/exist/source/SourceFactory.java
src/org/exist/xquery/XQueryContext.java
src/org/exist/xquery/functions/fn/FunUnparsedText.java
src/org/exist/xquery/functions/inspect/ModuleFunctions.java
src/org/exist/xquery/functions/util/Eval.java
src/org/exist/xquery/util/DocUtils.java
test/src/org/exist/source/SourceFactoryTest.java

Closes https://github.com/eXist-db/exist/issues/1927

Make sure that Source Factory correctly and safely resolves sources

---

build.properties
extensions/exiftool/src/org/exist/exiftool/xquery/MetadataFunctions.java
extensions/xqdoc/src/org/exist/xqdoc/xquery/Scan.java
src/org/exist/collections/triggers/XQueryStartupTrigger.java
src/org/exist/http/servlets/XQueryServlet.java
src/org/exist/source/SourceFactory.java
src/org/exist/util/serializer/HTML5Writer.java
src/org/exist/xquery/XQueryContext.java
src/org/exist/xquery/functions/fn/FunUnparsedText.java
src/org/exist/xquery/functions/inspect/ModuleFunctions.java
src/org/exist/xquery/functions/util/Eval.java
src/org/exist/xquery/util/DocUtils.java
test/src/org/exist/source/SourceFactoryTest.java
test/src/org/exist/util/serializer/HTML5WriterTest.java

Back-port of https://github.com/eXist-db/exist/pull/1934

(5.0.0) Make sure that Source Factory correctly and safely resolves sources

---

extensions/exiftool/src/org/exist/exiftool/xquery/MetadataFunctions.java
extensions/xqdoc/src/org/exist/xqdoc/xquery/Scan.java
src/org/exist/collections/triggers/XQueryStartupTrigger.java
src/org/exist/http/servlets/XQueryServlet.java
src/org/exist/source/SourceFactory.java
src/org/exist/xquery/XQueryContext.java
src/org/exist/xquery/functions/fn/FunUnparsedText.java
src/org/exist/xquery/functions/inspect/ModuleFunctions.java
src/org/exist/xquery/functions/util/Eval.java
src/org/exist/xquery/util/DocUtils.java
test/src/org/exist/source/SourceFactoryTest.java

Back-port of https://github.com/eXist-db/exist/pull/1934

(4.x.x) Make sure that Source Factory correctly and safely resolves sources

---

extensions/indexes/ngram/src/org/exist/xquery/modules/ngram/NGramSearch.java
src/org/exist/xquery/FunctionCall.java
src/org/exist/xquery/VariableDeclaration.java
src/org/exist/xquery/XQueryContext.java
src/org/exist/xquery/functions/fn/FunReplace.java
src/org/exist/xquery/parser/XQuery.g
src/org/exist/xquery/parser/XQueryParser.java
src/org/exist/xquery/parser/XQueryTree.g
src/org/exist/xquery/parser/XQueryTreeParser.java
src/org/exist/xquery/value/AbstractSequence.java
src/org/exist/xquery/value/OrderedDurationValue.java

Backport of https://github.com/eXist-db/exist/pull/1948

(4.x.x) Use ErrorCodes for XQuery Errors

---

src/org/exist/xquery/update/Modification.java
test/src/org/exist/xquery/update/UpdateInsertTest.java

Forward port of https://github.com/eXist-db/exist/pull/1949

Fix an NPE with XQuery Update and in-memory documents

---

src/org/exist/xquery/update/Modification.java
test/src/org/exist/xquery/update/UpdateInsertTest.java

Closes https://github.com/eXist-db/exist/issues/1761

(4.x.x) Fix an NPE with XQuery Update and in-memory documents

---

extensions/indexes/ngram/src/org/exist/xquery/modules/ngram/NGramSearch.java
src/org/exist/xquery/FunctionCall.java
src/org/exist/xquery/VariableDeclaration.java
src/org/exist/xquery/XQueryContext.java
src/org/exist/xquery/functions/fn/FunReplace.java
src/org/exist/xquery/parser/XQuery.g
src/org/exist/xquery/parser/XQueryParser.java
src/org/exist/xquery/parser/XQueryTree.g
src/org/exist/xquery/parser/XQueryTreeParser.java
src/org/exist/xquery/value/AbstractSequence.java
src/org/exist/xquery/value/OrderedDurationValue.java

Backport of https://github.com/eXist-db/exist/pull/1948

(5.0.0) Use ErrorCodes for XQuery Errors

---

src/org/exist/xquery/update/Modification.java
test/src/org/exist/xquery/update/UpdateInsertTest.java

Forward port of https://github.com/eXist-db/exist/pull/1949

(5.0.0) Fix an NPE with XQuery Update and in-memory documents

---

src/org/exist/backup/ZipArchiveBackupDescriptor.java
src/org/exist/backup/restore/RestoreHandler.java
src/org/exist/util/Compressor.java
src/org/exist/xmldb/RemoteCollection.java
src/org/exist/xmlrpc/RpcConnection.java

I will send the backport PR's after CI and after @windauer confirms that it fixes his issues.

(4.x.x) Fixes an issue with restoring zero byte binaries via XML:DB Remote API

---

src/org/exist/backup/ZipArchiveBackupDescriptor.java
src/org/exist/backup/restore/RestoreHandler.java
src/org/exist/util/Compressor.java
src/org/exist/xmldb/RemoteCollection.java
src/org/exist/xmlrpc/RpcConnection.java

Forward port of https://github.com/eXist-db/exist/pull/1950

Fixes an issue with restoring zero byte binaries via XML:DB Remote API

---

src/org/exist/backup/ZipArchiveBackupDescriptor.java
src/org/exist/backup/restore/RestoreHandler.java
src/org/exist/util/Compressor.java
src/org/exist/xmldb/RemoteCollection.java
src/org/exist/xmlrpc/RpcConnection.java

Forward port of https://github.com/eXist-db/exist/pull/1950

(5.0.0) Fixes an issue with restoring zero byte binaries via XML:DB Remote API

---

src/org/exist/xmldb/LocalCollection.java

Backport of https://github.com/eXist-db/exist/pull/1961

(5.0.0) Fix an XML:DB Local document lock issue

---

extensions/indexes/lucene/test/src/org/exist/indexing/lucene/LuceneIndexTest.java
extensions/xprocxq/main/src/xquery/util.xqm
src/org/exist/http/run-xproc.xq
src/org/exist/xquery/functions/util/Parse.java
src/org/exist/xquery/lib/xqsuite/xqsuite.xql
test/src/xquery/util/util.xml
webapp/xqts/xqts.xql

Back port of https://github.com/eXist-db/exist/pull/1959

(5.0.0) Replace eXist-db specific util:parse with XPath function

---

extensions/indexes/lucene/test/src/org/exist/indexing/lucene/LuceneIndexTest.java
extensions/xprocxq/main/src/xquery/util.xqm
src/org/exist/http/run-xproc.xq
src/org/exist/xquery/functions/util/Parse.java
src/org/exist/xquery/lib/xqsuite/xqsuite.xql
test/src/xquery/util/util.xml
webapp/xqts/xqts.xql

clean version of #1946 
replaces util:parse with parse-xml
close #1944

Replace eXist-db specific util:parse with XPath function

---

build/scripts/jarsigner.xml

sync of 4ab16695aafafac30b0d6e3c4d95df64e0c86663 
see #1966

(5.0.0) Fix Java10 signing problem

---

src/org/exist/dom/memtree/MemTreeBuilder.java
test/src/org/exist/dom/memtree/MemtreeBuilderTest.java

Backport of https://github.com/eXist-db/exist/pull/1973

(5.0.0) Fixes an issue when constructing MemTrees via SAX parsers

---

src/org/exist/dom/memtree/MemTreeBuilder.java
test/src/org/exist/dom/memtree/MemtreeBuilderTest.java

Backport of https://github.com/eXist-db/exist/pull/1973

(4.x.x) Fixes an issue when constructing MemTrees via SAX parsers

---

src/org/exist/xquery/XQueryContext.java
src/org/exist/xquery/util/DocUtils.java
test/src/org/exist/dom/memtree/DocumentImplTest.java
test/src/org/exist/xquery/functions/fn/DocTest.java

Backport of https://github.com/eXist-db/exist/pull/1974

(5.0.0) Basic support for available documents of Dynamic Context

---

src/org/exist/util/Collations.java

Backport of https://github.com/eXist-db/exist/pull/1989

(5.0.0) Support the Collation used in XQTS 3.1

---

src/org/exist/dom/memtree/SAXAdapter.java
src/org/exist/util/XMLReaderObjectFactory.java
src/org/exist/xquery/EnclosedExpr.java
src/org/exist/xquery/functions/fn/FunData.java
src/org/exist/xquery/functions/map/MapFunction.java
src/org/exist/xquery/value/AbstractSequence.java
src/org/exist/xquery/value/Sequence.java
test/src/org/exist/dom/memtree/DocumentBuilderReceiverIntegrationTest.java
test/src/org/exist/xquery/XQueryTest.java
test/src/org/exist/xquery/functions/fn/ExtDocTest.java
test/src/xquery/maps/maps.xql

Check the commits for the issues this closes.
Once the CI passes, I will send backports for 5.0.0 and 4.x.x...

A collection of small fixes for various issues

---

src/org/exist/dom/memtree/SAXAdapter.java
src/org/exist/util/XMLReaderObjectFactory.java
src/org/exist/xquery/EnclosedExpr.java
src/org/exist/xquery/functions/fn/FunData.java
src/org/exist/xquery/functions/map/MapFunction.java
src/org/exist/xquery/value/AbstractSequence.java
src/org/exist/xquery/value/Sequence.java
test/src/org/exist/dom/memtree/DocumentBuilderReceiverIntegrationTest.java
test/src/org/exist/xquery/XQueryTest.java
test/src/org/exist/xquery/functions/fn/ExtDocTest.java
test/src/xquery/maps/maps.xql

Backport of https://github.com/eXist-db/exist/pull/1991

(5.0.0) A collection of small fixes for various issues

---

src/org/exist/dom/memtree/SAXAdapter.java
src/org/exist/util/XMLReaderObjectFactory.java
src/org/exist/xquery/EnclosedExpr.java
src/org/exist/xquery/functions/fn/FunData.java
src/org/exist/xquery/functions/map/MapFunction.java
src/org/exist/xquery/value/AbstractSequence.java
src/org/exist/xquery/value/Sequence.java
test/src/org/exist/dom/memtree/DocumentBuilderReceiverIntegrationTest.java
test/src/org/exist/xquery/XQueryTest.java
test/src/org/exist/xquery/functions/fn/ExtDocTest.java
test/src/xquery/maps/maps.xql

Backport of https://github.com/eXist-db/exist/pull/1991

(4.x.x) A collection of small fixes for various issues

---

src/org/exist/xquery/value/AbstractSequence.java

Fix an issue where AbstractSequence#convertTo(int) was returning an empty sequence when it should not

---

extensions/modules/src/org/exist/xquery/modules/file/SerializeToFile.java

Backport of https://github.com/eXist-db/exist/pull/2008

(4.x.x) Fix encoding of file:serialize

---

extensions/modules/src/org/exist/xquery/modules/file/SerializeToFile.java

Backport of https://github.com/eXist-db/exist/pull/2008

(5.x.x) Fix encoding of file:serialize

---

extensions/indexes/range/test/src/xquery/field-type.xql
src/org/exist/xquery/XQueryContext.java
src/org/exist/xquery/functions/fn/ExtCollection.java
test/src/org/exist/xquery/functions/fn/CollectionTest.java
test/src/xquery/count.xql

Implements basic support for https://www.w3.org/TR/xpath-31/#dt-available-collections
We need this to be able to execute the XQTS correctly.

Basic support for available collections of Dynamic Context

---

extensions/modules/src/org/exist/xquery/modules/file/SerializeToFile.java

Closes https://github.com/eXist-db/exist/issues/1922

Fix encoding of file:serialize

---

extensions/indexes/range/test/src/xquery/field-type.xql
src/org/exist/xquery/XQueryContext.java
src/org/exist/xquery/functions/fn/ExtCollection.java
test/src/org/exist/xquery/functions/fn/CollectionTest.java
test/src/xquery/count.xql

Implements basic support for https://www.w3.org/TR/xpath-31/#dt-available-collections
We need this to be able to execute the XQTS correctly.

(5.0.0) Basic support for available collections of Dynamic Context

---

src/org/exist/xquery/functions/fn/FunError.java
src/org/exist/xquery/functions/fn/FunExactlyOne.java

Backport of https://github.com/eXist-db/exist/pull/2017

(5.0.0) Reduce unnecessary error logging

---

src/org/exist/xquery/functions/fn/FunError.java
src/org/exist/xquery/functions/fn/FunExactlyOne.java

Backport of https://github.com/eXist-db/exist/pull/2017

(4.x.x) Reduce unnecessary error logging

---

extensions/security/ldap/README.txt
extensions/security/ldap/src/org/exist/security/realm/TransformationContext.java
extensions/security/ldap/src/org/exist/security/realm/ldap/AbstractLDAPPrincipalRestrictionList.java
extensions/security/ldap/src/org/exist/security/realm/ldap/AbstractLDAPSearchPrincipal.java
extensions/security/ldap/src/org/exist/security/realm/ldap/LDAPAccountImpl.java
extensions/security/ldap/src/org/exist/security/realm/ldap/LDAPGroupImpl.java
extensions/security/ldap/src/org/exist/security/realm/ldap/LDAPPrincipalBlackList.java
extensions/security/ldap/src/org/exist/security/realm/ldap/LDAPPrincipalWhiteList.java
extensions/security/ldap/src/org/exist/security/realm/ldap/LDAPRealm.java
extensions/security/ldap/src/org/exist/security/realm/ldap/LDAPSearchAccount.java
extensions/security/ldap/src/org/exist/security/realm/ldap/LDAPSearchContext.java
extensions/security/ldap/src/org/exist/security/realm/ldap/LDAPSearchGroup.java
extensions/security/ldap/src/org/exist/security/realm/ldap/LDAPTransformationContext.java
extensions/security/ldap/src/org/exist/security/realm/ldap/LdapContextFactory.java
extensions/security/ldap/src/org/exist/security/realm/ldap/LdapUtils.java
extensions/security/ldap/src/org/exist/security/realm/ldap/xquery/AccountFunctions.java
extensions/security/ldap/src/org/exist/security/realm/ldap/xquery/LDAPModule.java

Closes https://github.com/eXist-db/exist/issues/2000
Closes https://github.com/eXist-db/exist/issues/2001

Fixes a couple of issues with LDAP authentication

---

extensions/security/ldap/README.txt
extensions/security/ldap/src/org/exist/security/realm/TransformationContext.java
extensions/security/ldap/src/org/exist/security/realm/ldap/AbstractLDAPPrincipalRestrictionList.java
extensions/security/ldap/src/org/exist/security/realm/ldap/AbstractLDAPSearchPrincipal.java
extensions/security/ldap/src/org/exist/security/realm/ldap/LDAPAccountImpl.java
extensions/security/ldap/src/org/exist/security/realm/ldap/LDAPGroupImpl.java
extensions/security/ldap/src/org/exist/security/realm/ldap/LDAPPrincipalBlackList.java
extensions/security/ldap/src/org/exist/security/realm/ldap/LDAPPrincipalWhiteList.java
extensions/security/ldap/src/org/exist/security/realm/ldap/LDAPRealm.java
extensions/security/ldap/src/org/exist/security/realm/ldap/LDAPSearchAccount.java
extensions/security/ldap/src/org/exist/security/realm/ldap/LDAPSearchContext.java
extensions/security/ldap/src/org/exist/security/realm/ldap/LDAPSearchGroup.java
extensions/security/ldap/src/org/exist/security/realm/ldap/LDAPTransformationContext.java
extensions/security/ldap/src/org/exist/security/realm/ldap/LdapContextFactory.java
extensions/security/ldap/src/org/exist/security/realm/ldap/LdapUtils.java
extensions/security/ldap/src/org/exist/security/realm/ldap/xquery/AccountFunctions.java
extensions/security/ldap/src/org/exist/security/realm/ldap/xquery/LDAPModule.java

Backport of https://github.com/eXist-db/exist/pull/2011

(5.0.0) Fixes a couple of issues with LDAP authentication

---

extensions/security/ldap/README.txt
extensions/security/ldap/src/org/exist/security/realm/TransformationContext.java
extensions/security/ldap/src/org/exist/security/realm/ldap/AbstractLDAPPrincipalRestrictionList.java
extensions/security/ldap/src/org/exist/security/realm/ldap/AbstractLDAPSearchPrincipal.java
extensions/security/ldap/src/org/exist/security/realm/ldap/LDAPAccountImpl.java
extensions/security/ldap/src/org/exist/security/realm/ldap/LDAPGroupImpl.java
extensions/security/ldap/src/org/exist/security/realm/ldap/LDAPPrincipalBlackList.java
extensions/security/ldap/src/org/exist/security/realm/ldap/LDAPPrincipalWhiteList.java
extensions/security/ldap/src/org/exist/security/realm/ldap/LDAPRealm.java
extensions/security/ldap/src/org/exist/security/realm/ldap/LDAPSearchAccount.java
extensions/security/ldap/src/org/exist/security/realm/ldap/LDAPSearchContext.java
extensions/security/ldap/src/org/exist/security/realm/ldap/LDAPSearchGroup.java
extensions/security/ldap/src/org/exist/security/realm/ldap/LDAPTransformationContext.java
extensions/security/ldap/src/org/exist/security/realm/ldap/LdapContextFactory.java
extensions/security/ldap/src/org/exist/security/realm/ldap/LdapUtils.java
extensions/security/ldap/src/org/exist/security/realm/ldap/xquery/AccountFunctions.java
extensions/security/ldap/src/org/exist/security/realm/ldap/xquery/LDAPModule.java

Backport of https://github.com/eXist-db/exist/pull/2011

(4.x.x) Fixes a couple of issues with LDAP authentication

---

src/org/exist/xmldb/LocalXMLResource.java

Backport of https://github.com/eXist-db/exist/pull/2031

(5.0.0) Reinstates protection for leaky DOM in XML:DB Local API

---

src/org/exist/xmldb/LocalXMLResource.java

We removed this previously to work around some issues, for which I also previously added tests. This should now pass all tests and plug the leaky abstractions.

Reinstates protection for leaky DOM in XML:DB Local API

---

src/org/exist/backup/restore/CollectionDeferredPermission.java
src/org/exist/backup/restore/ResourceDeferredPermission.java

Backport of https://github.com/eXist-db/exist/pull/2027

(4.x.x) Fix document URI logging during restore

---

src/org/exist/backup/restore/CollectionDeferredPermission.java
src/org/exist/backup/restore/ResourceDeferredPermission.java

Backport of https://github.com/eXist-db/exist/pull/2027

(5.0.0) Fix document URI logging during restore

---

test/src/org/exist/xquery/XQueryTest.java
test/src/org/exist/xquery/external-classpath-library-module.xqm
test/src/org/exist/xquery/external-classpath-main-module.xq
test/src/org/exist/xquery/external-classpath-module.xqm

Backport of https://github.com/eXist-db/exist/pull/2024

(5.0.0) Test for importing a main module from the classpath

---

test/src/org/exist/xquery/XQueryTest.java
test/src/org/exist/xquery/external-classpath-library-module.xqm
test/src/org/exist/xquery/external-classpath-main-module.xq
test/src/org/exist/xquery/external-classpath-module.xqm

Backport of https://github.com/eXist-db/exist/pull/2024

(4.x.x) Test for importing a main module from the classpath

---

test/src/org/exist/xquery/XQueryTest.java
test/src/org/exist/xquery/external-classpath-library-module.xqm
test/src/org/exist/xquery/external-classpath-main-module.xq
test/src/org/exist/xquery/external-classpath-module.xqm

Just a simple test against future regressions.

Test for importing a main module from the classpath

---

src/org/exist/util/ConfigurationHelper.java

Needed for the XQTS Test Runner.

Fix an error when loading conf.xml from a Jar

---

src/org/exist/util/ConfigurationHelper.java

Backport of https://github.com/eXist-db/exist/pull/2021

(5.0.0) Fix an error when loading conf.xml from a Jar

---

src/org/exist/util/ConfigurationHelper.java

Backport of https://github.com/eXist-db/exist/pull/2021

(4.x.x) Fix an error when loading conf.xml from a Jar

---

src/org/exist/xmldb/RemoteCollection.java
test/src/org/exist/xmldb/RemoteCollectionTest.java

Backport of https://github.com/eXist-db/exist/pull/2038

(4.x.x) Fixes another issue with zero byte binary resources in the XML:DB Remote API

---

build/scripts/setup.xml

(5.0.0) Improve reporting of xar downloads from package repo during build process

---

build/scripts/build-impl.xml
build/scripts/dist.xml

Backport of https://github.com/eXist-db/exist/pull/2065

(5.0.0) Fixes the dist targets

---

extensions/modules/src/org/exist/xquery/modules/scheduler/ScheduleFunctions.java

Backport of https://github.com/eXist-db/exist/pull/2062

(4.x.x) Updated the function defintions for scheduling jobs via XQuery

---

extensions/modules/src/org/exist/xquery/modules/scheduler/ScheduleFunctions.java

Backport of https://github.com/eXist-db/exist/pull/2062

(5.0.0) Updated the function defintions for scheduling jobs via XQuery

---

test/src/org/exist/backup/XMLDBBackupTest.java

Test inspired by https://github.com/eXist-db/exist/issues/2064

(4.x.x) Test backup/restore over both Local and Remote XML:DB APIs

---

src/org/exist/backup/restore/RestoreHandler.java
test/src/org/exist/backup/XMLDBBackupTest.java

Closes https://github.com/eXist-db/exist/issues/2064

Fixes a problem with restoring a backup over the XML:DB Remote API

---

src/org/exist/backup/restore/RestoreHandler.java
test/src/org/exist/backup/XMLDBBackupTest.java

Backport of https://github.com/eXist-db/exist/pull/2072

(5.0.0) Fixes a problem with restoring a backup over the XML:DB Remote API 

---

installer/install.xml.tmpl
installer/scripts/setup.bat

Backport of relevant parts of https://github.com/eXist-db/exist/pull/2075

(4.x.x) Fix an issue with IzPack on Windows

---

tools/yajsw/build.xml

Port of https://github.com/eXist-db/exist/commit/ed7b83b
Closes https://github.com/eXist-db/exist/issues/2043

Fix variables used by installer for wrapper.conf.

---

tools/yajsw/build.xml

Port of https://github.com/eXist-db/exist/commit/ed7b83b
Closes https://github.com/eXist-db/exist/issues/2043

(5.0.0) Fix variables used by installer for wrapper.conf.

---

build.properties
src/org/exist/plugin/PluginsManagerImpl.java

Backport of https://github.com/eXist-db/exist/pull/2084

(4.x.x) Fix an issue with logging and some documentation

---

build.properties
src/org/exist/plugin/PluginsManagerImpl.java

Backport of https://github.com/eXist-db/exist/pull/2084

(5.0.0) Fix an issue with logging and some documentation

---

test/src/org/exist/xmldb/ShutdownTest.java
test/src/org/exist/xmldb/concurrent/ComplexUpdateTest.java
test/src/org/exist/xmldb/concurrent/ConcurrentAttrUpdateTest.java
test/src/org/exist/xmldb/concurrent/ConcurrentQueryTest.java
test/src/org/exist/xmldb/concurrent/ConcurrentQueryUpdateTest.java
test/src/org/exist/xmldb/concurrent/ConcurrentResourceTest.java
test/src/org/exist/xmldb/concurrent/ConcurrentResourceTest2.java
test/src/org/exist/xmldb/concurrent/ConcurrentResourceTest3.java
test/src/org/exist/xmldb/concurrent/ConcurrentTestBase.java
test/src/org/exist/xmldb/concurrent/ConcurrentXUpdateTest.java
test/src/org/exist/xmldb/concurrent/DBUtils.java
test/src/org/exist/xmldb/concurrent/FragmentsTest.java
test/src/org/exist/xmldb/concurrent/TextUpdateTest.java
test/src/org/exist/xmldb/concurrent/ValueIndexUpdateTest.java
test/src/org/exist/xmldb/concurrent/action/Action.java
test/src/org/exist/xmldb/concurrent/action/AttributeUpdateAction.java
test/src/org/exist/xmldb/concurrent/action/ComplexUpdateAction.java
test/src/org/exist/xmldb/concurrent/action/CreateCollectionAction.java
test/src/org/exist/xmldb/concurrent/action/MultiResourcesAction.java
test/src/org/exist/xmldb/concurrent/action/RemoveAppendAction.java
test/src/org/exist/xmldb/concurrent/action/ReplaceResourceAction.java
test/src/org/exist/xmldb/concurrent/action/RetrieveResourceAction.java
test/src/org/exist/xmldb/concurrent/action/TextUpdateAction.java
test/src/org/exist/xmldb/concurrent/action/ValueAppendAction.java
test/src/org/exist/xmldb/concurrent/action/XQueryAction.java
test/src/org/exist/xmldb/concurrent/action/XQueryUpdateAction.java
test/src/org/exist/xupdate/RemoveAppendTest.java
test/src/org/exist/xupdate/StressTest.java

Backport of further test improvements from - #2075

(4.x.x) Cleanup and Improve concurrent test code

---

samples/http/put.py

Update put.py to support py3 and also be more pythonic
Thank you for your contribution to eXist-db! 
To help the community judge your pull request (PR), please include the following:
- A (short) description of the content of changes.
- A context reference to a [Github Issue](https://github.com/eXist-db/exist/issues), a message in the [eXist-open mailinglist](http://exist-open.markmail.org), or a [specification](https://www.w3.org/TR/xquery-31/).
- Tests. The [XQSuite - Annotation-based Test Framework for XQuery](http://exist-db.org/exist/apps/doc/xqsuite.xml) makes it very easy for you to create tests. These tests can be executed from the [eXide editor](http://exist-db.org/exist/apps/eXide/index.html) via XQuery > Run as Test.
Your PR will be tested using [Travis …

Update put.py to support py3

---

extensions/modules/src/org/exist/xquery/modules/compression/CompressionModule.java
extensions/modules/src/org/exist/xquery/modules/compression/DeflateFunction.java
extensions/modules/src/org/exist/xquery/modules/compression/InflateFunction.java
extensions/modules/src/org/exist/xquery/modules/compression/example-deflate.xql

Forward port of https://github.com/eXist-db/exist/pull/2080

(5.0.0) Add DEFLATE compression (RFC 1950 / 1951) to compression module

---

extensions/modules/src/org/exist/xquery/modules/compression/CompressionModule.java
extensions/modules/src/org/exist/xquery/modules/compression/DeflateFunction.java
extensions/modules/src/org/exist/xquery/modules/compression/InflateFunction.java
extensions/modules/src/org/exist/xquery/modules/compression/example-deflate.xql

Forward port of https://github.com/eXist-db/exist/pull/2080

Add DEFLATE compression (RFC 1950 / 1951) to compression module

---

src/org/exist/backup/ConsistencyCheck.java

Forward port of https://github.com/eXist-db/exist/pull/2100

Consistency check should check the entire document

---

src/org/exist/client/ConnectionDialog.java
src/org/exist/client/InteractiveClient.java

Closes https://github.com/eXist-db/exist/issues/2063

Allow the password to be provided to the Client GUI via the command line args

---

src/org/exist/client/ConnectionDialog.java
src/org/exist/client/InteractiveClient.java

Backport of https://github.com/eXist-db/exist/pull/2110

(5.0.0) Allow the password to be provided to the Client GUI via the command line args

---

src/org/exist/client/ConnectionDialog.java
src/org/exist/client/InteractiveClient.java

Backport of https://github.com/eXist-db/exist/pull/2110

(4.x.x) Allow the password to be provided to the Client GUI via the command line args

---

.travis.yml
test/src/org/exist/validation/TestTools.java

Backport of https://github.com/eXist-db/exist/pull/2119

(4.x.x) Various small improvements

---

.travis.yml
test/src/org/exist/validation/TestTools.java

Backport of https://github.com/eXist-db/exist/pull/2119

(5.0.0) Various small improvements

---

src/org/exist/management/impl/JMXAgent.java
test/src/org/exist/management/JmxRemoteTest.java

- Repair output JMX servlet to contain all eXist-db specific information.
- Fixes #2118
- added unit tests
- verified Monex to work again

(4.x.x) Repair output JMX servlet to contain all eXist-db specific information.

---

extensions/modules/src/org/exist/xquery/modules/image/CropFunction.java

Backport of https://github.com/eXist-db/exist/pull/2128

Fix bugs in CropFunction

---

bin/functions.d/getopt-settings.sh

Backport of https://github.com/eXist-db/exist/pull/2117

(5.0.0) Correct jmx option parsing

---

src/org/exist/management/client/JMXtoXML.java
src/org/exist/management/impl/JMXAgent.java
test/src/org/exist/management/JmxRemoteTest.java

Repair output JMX servlet to contain all eXist-db specific information.
Fixes #2118
port of #2125

(5.0.0) Repair output JMX servlet to contain all eXist-db specific information.

---

extensions/modules/src/org/exist/xquery/modules/sql/ExecuteFunction.java
test/src/org/exist/xquery/modules/sql/ExecuteFunctionTest.java

Bugfix: Fixes in SQL module (#2139) (5.0.0 port)

---

src/org/exist/source/SourceFactory.java

Closes https://github.com/eXist-db/exist/issues/2157

Fix a regression for loading modules from non-XMLDB URI

---

src/org/exist/source/SourceFactory.java

Backport of https://github.com/eXist-db/exist/pull/2161

(4.x.x) Fix a regression for loading modules from non-XMLDB URI

---

src/org/exist/source/SourceFactory.java

Backport of https://github.com/eXist-db/exist/pull/2161

(5.0.0) Fix a regression for loading modules from non-XMLDB URI

---

exist-versioning-release.md

Don't forget to clean before build

---

build/scripts/dist.xml

Backport of https://github.com/eXist-db/exist/pull/2164

(5.0.0) Add some missing files to the dist

---

build/scripts/dist.xml

Backport of https://github.com/eXist-db/exist/pull/2164

(4.x.x) Add some missing files to the dist

---

conf.xml.tmpl
src/org/exist/util/Configuration.java
src/org/exist/util/XMLReaderPool.java
test/src/org/exist/util/XMLReaderSecurityTest.java

Backport of https://github.com/eXist-db/exist/pull/2145

(5.0.0) Add options for securing the XML Parser

---

src/org/exist/xquery/RootNode.java
test/src/org/exist/xquery/XQueryDeclareContextItemTest.java

(4.x.x) Fix handling of / when context item was declared

---

src/org/exist/xquery/RootNode.java
test/src/org/exist/xquery/XQueryDeclareContextItemTest.java

5xx: Fix handling of / when context item was declared, closes #2156

---

src/org/exist/xquery/RootNode.java
test/src/org/exist/xquery/XQueryDeclareContextItemTest.java

develop: Fix handling of / when context item was declared, closes #2156

---

build/scripts/macosx.xml
installer/vm.properties
src/org/exist/launcher/ConfigurationDialog.java
src/org/exist/launcher/Launcher.java
src/org/exist/launcher/ServiceManager.java
src/org/exist/launcher/vm.properties
src/org/exist/repo/ClasspathHelper.java
src/org/exist/repo/Deployment.java
vm.properties

Various, mostly cosmetic issues spotted while reviewing launcher code, first-time startup experience, and app build targets.
n/a
n/a

Various minor cosmetic fixes

---

build/scripts/macosx.xml
installer/vm.properties
src/org/exist/launcher/ConfigurationDialog.java
src/org/exist/launcher/Launcher.java
src/org/exist/launcher/ServiceManager.java
src/org/exist/launcher/vm.properties
src/org/exist/repo/ClasspathHelper.java
src/org/exist/repo/Deployment.java
vm.properties

Port of https://github.com/eXist-db/exist/pull/2190

Various minor cosmetic fixes (4.x.x)

---

build/scripts/macosx.xml
installer/vm.properties
src/org/exist/launcher/ConfigurationDialog.java
src/org/exist/launcher/Launcher.java
src/org/exist/launcher/ServiceManager.java
src/org/exist/launcher/vm.properties
src/org/exist/repo/ClasspathHelper.java
src/org/exist/repo/Deployment.java
vm.properties

Port of https://github.com/eXist-db/exist/pull/2190

Various minor cosmetic fixes (5.0.0)

---

src/org/exist/storage/NotificationService.java
src/org/exist/xquery/XQueryContext.java

Closes https://github.com/eXist-db/exist/issues/2185

Fix a concurrency issue in ContextUpdateListener

---

src/org/exist/storage/NotificationService.java
src/org/exist/xquery/XQueryContext.java

Backport of https://github.com/eXist-db/exist/pull/2210

(4.x.x) Fix a concurrency issue in ContextUpdateListener

---

src/org/exist/storage/NotificationService.java
src/org/exist/xquery/XQueryContext.java

Backport of https://github.com/eXist-db/exist/pull/2210

(5.0.0) Fix a concurrency issue in ContextUpdateListener

---

src/org/exist/xquery/ErrorCodes.java
src/org/exist/xquery/functions/map/MapExpr.java

Closes https://github.com/eXist-db/exist/issues/2203

Map Constructor should not allow duplicate keys

---

src/org/exist/xquery/ErrorCodes.java
src/org/exist/xquery/functions/map/MapExpr.java

Backport of https://github.com/eXist-db/exist/pull/2213

(4.x.x) Map Constructor should not allow duplicate keys

---

src/org/exist/xquery/ErrorCodes.java
src/org/exist/xquery/functions/map/MapExpr.java

Backport of https://github.com/eXist-db/exist/pull/2213

(5.0.0) Map Constructor should not allow duplicate keys

---

src/org/exist/ant/XMLDBExistTask.java

typo (4.x.x)

---

src/org/exist/ant/XMLDBExistTask.java

typo (5.0.0)

---

src/org/exist/management/impl/LockTable.java
src/org/exist/management/impl/LockTableMXBean.java
src/org/exist/security/PermissionFactory.java
src/org/exist/storage/lock/LockTable.java
src/org/exist/storage/lock/LockTableUtils.java
src/org/exist/storage/txn/Txn.java

Backport of https://github.com/eXist-db/exist/pull/2244

(5.0.0) Fix an issue with lock lifetime when changing permissions

---

extensions/images/README

Develop: Update location of JAI downloads

---

extensions/images/README

4xx: Update location of JAI downloads

---

extensions/images/README

5xx: Update location of JAI downloads

---

.travis.yml

enable oracleJDK11 on travis

---

src/org/exist/start/LatestFileResolver.java

Forward port of https://github.com/eXist-db/exist/pull/2268

(5.0.0) Fix a regression with loading the XML:DB API Jar via bin/startup

---

src/org/exist/start/LatestFileResolver.java

Forward port of https://github.com/eXist-db/exist/pull/2268

Fix a regression with loading the XML:DB API Jar via bin/startup

---

src/org/exist/util/ExistSAXParserFactory.java

Backport of https://github.com/eXist-db/exist/pull/2271

(4.x.x) Fix verbose logging regression in ExistSAXParserFactory

---

src/org/exist/util/ExistSAXParserFactory.java

Backport of https://github.com/eXist-db/exist/pull/2271

(5.x.x) Fix verbose logging regression in ExistSAXParserFactory

---

src/org/exist/backup/ExportGUI.java

Fix a NPE regression in ExportGUI

(4.x.x) Fix a regression in ExportGUI

---

src/org/exist/backup/ExportGUI.java

Forward port of https://github.com/eXist-db/exist/pull/2275

Fix a regression in ExportGUI

---

src/org/exist/backup/ExportGUI.java

Forward port of https://github.com/eXist-db/exist/pull/2275

(5.x.x) Fix a regression in ExportGUI

---

extensions/indexes/ngram/src/org/exist/indexing/ngram/NGramIndex.java
extensions/indexes/sort/src/org/exist/indexing/sort/SortIndex.java
src/org/exist/storage/NativeValueIndex.java
src/org/exist/storage/btree/BTree.java
src/org/exist/storage/btree/Paged.java
src/org/exist/storage/dom/DOMFile.java
src/org/exist/storage/index/BFile.java
src/org/exist/storage/index/CollectionStore.java
src/org/exist/storage/journal/AbstractLoggable.java
src/org/exist/storage/journal/Journal.java
src/org/exist/storage/journal/JournalManager.java
src/org/exist/storage/journal/JournalReader.java
src/org/exist/storage/journal/Loggable.java
src/org/exist/storage/journal/Lsn.java
src/org/exist/storage/recovery/RecoveryManager.java
src/org/exist/storage/structural/NativeStructuralIndex.java
src/org/exist/storage/txn/Checkpoint.java
test/src/org/exist/storage/RemoveCollectionTest.java
test/src/org/exist/storage/journal/LsnTest.java

Backport of https://github.com/eXist-db/exist/pull/2292

Remove the 2GB log file limit for the Journal

---

extensions/indexes/ngram/src/org/exist/indexing/ngram/NGramIndex.java
extensions/indexes/sort/src/org/exist/indexing/sort/SortIndex.java
src/org/exist/storage/NativeValueIndex.java
src/org/exist/storage/btree/BTree.java
src/org/exist/storage/btree/Paged.java
src/org/exist/storage/dom/DOMFile.java
src/org/exist/storage/index/BFile.java
src/org/exist/storage/index/CollectionStore.java
src/org/exist/storage/journal/AbstractLoggable.java
src/org/exist/storage/journal/Journal.java
src/org/exist/storage/journal/JournalManager.java
src/org/exist/storage/journal/JournalReader.java
src/org/exist/storage/journal/Loggable.java
src/org/exist/storage/journal/Lsn.java
src/org/exist/storage/recovery/RecoveryManager.java
src/org/exist/storage/structural/NativeStructuralIndex.java
src/org/exist/storage/txn/Checkpoint.java
test/src/org/exist/storage/RemoveCollectionTest.java
test/src/org/exist/storage/journal/LsnTest.java

Backport of https://github.com/eXist-db/exist/pull/2292

(5.0.0) Remove the 2GB log file limit for the Journal

---

build/scripts/jarsigner.xml

Forward port of https://github.com/eXist-db/exist/pull/2298

Don't unsign the Bouncy Castle jar file

---

src/org/exist/webstart/JnlpJarFiles.java

Repair of missing webstart jar file. Fixes #2311

4xx: Repair of missing webstart jar file.

---

src/org/exist/webstart/JnlpJarFiles.java

Develop: Repair of missing webstart jar file. 

---

.travis.yml
README.md

4.x.x chore: add link to readme cleanup travis

---

.travis.yml
README.md

5.0.0 chore: add link to readme cleanup travis

---

.travis.yml

Backport of https://github.com/eXist-db/exist/pull/2344

(4.x.x) Compress the JUnit logs from Travis before uploading

---

.travis.yml

Backport of https://github.com/eXist-db/exist/pull/2344

(5.0.0) Compress the JUnit logs from Travis before uploading

---

README.md

They gave us 50GB of storage :-)

[doc] Acknowledge BinTray's generous service

---

.travis.yml

Backport of https://github.com/eXist-db/exist/pull/2348

(5.0.0) Move from Ubuntu Trusty to Xenial on Travis-CI

---

.travis.yml

Backport of https://github.com/eXist-db/exist/pull/2348

(4.x.x) Move from Ubuntu Trusty to Xenial on Travis-CI

---

src/org/exist/xquery/functions/array/ArrayFunction.java
src/org/exist/xquery/functions/array/ArrayType.java
test/src/xquery/arrays/arrays.xql

Backport of https://github.com/eXist-db/exist/pull/2328

(4.x.x) Fix an ArrayOutOfBoundException with array:get

---

src/org/exist/xquery/functions/array/ArrayFunction.java
src/org/exist/xquery/functions/array/ArrayType.java
test/src/xquery/arrays/arrays.xql

Closes https://github.com/eXist-db/exist/issues/2317

Fix an ArrayOutOfBoundException with array:get

---

src/org/exist/xquery/functions/array/ArrayFunction.java
src/org/exist/xquery/functions/array/ArrayType.java
test/src/xquery/arrays/arrays.xql

Backport of https://github.com/eXist-db/exist/pull/2328

(5.0.0) Fix an ArrayOutOfBoundException with array:get

---

src/org/exist/xquery/functions/fn/FunTrace.java
src/org/exist/xquery/functions/fn/JSON.java
src/org/exist/xquery/functions/util/LogFunction.java

fixes #2340 
@wolfgangmm Can all serialization be done with the xqueryserializer with the 'adaptive' mode switched on?

4xx: Implement adaptive serialisation for fn:trace and util:log* functions

---

src/org/exist/xquery/functions/fn/FunTrace.java
src/org/exist/xquery/functions/fn/JSON.java
src/org/exist/xquery/functions/util/LogFunction.java

develop: Implement adaptive serialisation for fn:trace and util:log* functions 

---

src/org/exist/xquery/functions/fn/FunTrace.java
src/org/exist/xquery/functions/fn/JSON.java
src/org/exist/xquery/functions/util/LogFunction.java

5xx: Implement adaptive serialisation for fn:trace and util:log* functions

---

src/org/exist/source/SourceFactory.java
test/src/org/exist/source/SourceFactoryTest.java

Backport of https://github.com/eXist-db/exist/pull/2360

(5.0.0) Improve classpath modules resolution

---

src/org/exist/storage/BrokerPool.java
src/org/exist/storage/SystemTaskManager.java
src/org/exist/storage/journal/Journal.java
src/org/exist/storage/txn/TransactionManager.java
src/org/exist/storage/txn/Txn.java
test/src/org/exist/storage/txn/TransactionManagerTestHelper.java

Forward port of https://github.com/eXist-db/exist/pull/2305

New implementation of the Transaction Manager

---

src/org/exist/storage/BrokerPool.java
src/org/exist/storage/SystemTaskManager.java
src/org/exist/storage/journal/Journal.java
src/org/exist/storage/txn/TransactionManager.java
src/org/exist/storage/txn/Txn.java
test/src/org/exist/storage/txn/TransactionManagerTestHelper.java

Forward port of https://github.com/eXist-db/exist/pull/2305

(5.0.0) New implementation of the Transaction Manager

---

schema/collection.xconf.xsd

(5.0.0) Add coverage for new range index features to collection.xconf.xsd

---

schema/collection.xconf.xsd

(4.x.x) Add coverage for new range index features to collection.xconf.xsd

---

src/org/exist/collections/CollectionConfigurationManager.java
src/org/exist/config/Configurator.java
src/org/exist/dom/QName.java
src/org/exist/dom/memtree/InMemoryXMLStreamReader.java
src/org/exist/dom/memtree/SAXAdapter.java
src/org/exist/http/Descriptor.java
src/org/exist/http/RESTServer.java
src/org/exist/storage/serializers/EXistOutputKeys.java
src/org/exist/storage/serializers/XIncludeFilter.java
src/org/exist/util/Configuration.java
src/org/exist/util/serializer/XMLWriter.java
src/org/exist/util/serializer/XQuerySerializer.java
src/org/exist/xmldb/LocalXPathQueryService.java
src/org/exist/xmldb/RemoteXPathQueryService.java
src/org/exist/xquery/CDATAConstructor.java
src/org/exist/xquery/XQueryContext.java
src/org/exist/xquery/modules/ModuleUtils.java
src/org/exist/xquery/util/DocUtils.java
src/org/exist/xquery/util/SerializerUtils.java
test/src/org/exist/dom/persistent/CDataIntergationTest.java
test/src/org/exist/dom/persistent/PersistentDomTest.java
test/src/org/exist/xquery/XPathQueryTest.java
test/src/org/exist/xquery/XQueryTest.java

(5.0.0) Fix CDATA handling and implement output:cdata-section-elements

---

src/org/exist/collections/CollectionConfigurationManager.java
src/org/exist/config/Configurator.java
src/org/exist/dom/QName.java
src/org/exist/dom/memtree/InMemoryXMLStreamReader.java
src/org/exist/dom/memtree/SAXAdapter.java
src/org/exist/http/Descriptor.java
src/org/exist/http/RESTServer.java
src/org/exist/storage/serializers/EXistOutputKeys.java
src/org/exist/storage/serializers/XIncludeFilter.java
src/org/exist/util/Configuration.java
src/org/exist/util/serializer/XMLWriter.java
src/org/exist/util/serializer/XQuerySerializer.java
src/org/exist/xmldb/LocalXPathQueryService.java
src/org/exist/xmldb/RemoteXPathQueryService.java
src/org/exist/xquery/CDATAConstructor.java
src/org/exist/xquery/XQueryContext.java
src/org/exist/xquery/modules/ModuleUtils.java
src/org/exist/xquery/util/DocUtils.java
src/org/exist/xquery/util/SerializerUtils.java
test/src/org/exist/dom/persistent/CDataIntergationTest.java
test/src/org/exist/dom/persistent/PersistentDomTest.java
test/src/org/exist/xquery/XPathQueryTest.java
test/src/org/exist/xquery/XQueryTest.java

Forward port of https://github.com/eXist-db/exist/pull/2374

Fix CDATA handling and implement output:cdata-section-elements

---

src/org/exist/storage/NativeBroker.java

Forward port of https://github.com/eXist-db/exist/pull/2310

Copying an XML Resource must remove the nodes of any XML resource it overwrites!

---

src/org/exist/storage/NativeBroker.java

(5.0.0) Copying an XML Resource must remove the nodes of any XML resource it overwrites!

---

src/org/exist/collections/CollectionConfigurationManager.java
src/org/exist/config/Configurator.java
src/org/exist/dom/QName.java
src/org/exist/dom/memtree/InMemoryXMLStreamReader.java
src/org/exist/dom/memtree/SAXAdapter.java
src/org/exist/http/Descriptor.java
src/org/exist/http/RESTServer.java
src/org/exist/storage/serializers/EXistOutputKeys.java
src/org/exist/storage/serializers/XIncludeFilter.java
src/org/exist/util/Configuration.java
src/org/exist/util/serializer/XMLWriter.java
src/org/exist/util/serializer/XQuerySerializer.java
src/org/exist/xmldb/LocalXPathQueryService.java
src/org/exist/xmldb/RemoteXPathQueryService.java
src/org/exist/xquery/CDATAConstructor.java
src/org/exist/xquery/XQueryContext.java
src/org/exist/xquery/modules/ModuleUtils.java
src/org/exist/xquery/util/DocUtils.java
src/org/exist/xquery/util/SerializerUtils.java
test/src/org/exist/dom/persistent/CDataIntergationTest.java
test/src/org/exist/dom/persistent/PersistentDomTest.java
test/src/org/exist/xquery/XPathQueryTest.java
test/src/org/exist/xquery/XQueryTest.java

Closes https://github.com/eXist-db/exist/issues/2233
Closes https://github.com/eXist-db/exist/issues/2081
Thanks to the University of Richmond for sponsoring,

(4.x.x) Fix CDATA handling and implement output:cdata-section-elements

---

build/scripts/installer.xml
build/scripts/setup.xml

Backport of https://github.com/eXist-db/exist/pull/2200

(5.0.0) If downloading XARs fails, the build should fail

---

build/scripts/installer.xml
build/scripts/setup.xml

Backport of https://github.com/eXist-db/exist/pull/2200

(4.x.x) If downloading XARs fails, the build should fail

---

tools/yajsw/bin/installDaemon.sh

Backport of https://github.com/eXist-db/exist/pull/2240

(4.x.x) Unattended Installation

---

tools/yajsw/bin/installDaemon.sh

(5.0.0) Unattended Installation

---

src/org/exist/xquery/functions/util/Eval.java

Forward port of https://github.com/eXist-db/exist/pull/2420

(5.0.0) Tiny bug fix in fn:eval-and-serialize

---

src/org/exist/Indexer.java
src/org/exist/dom/QName.java
src/org/exist/dom/memtree/MemTreeBuilder.java
src/org/exist/util/XMLNames.java
src/org/exist/xquery/DynamicAttributeConstructor.java
src/org/exist/xquery/DynamicPIConstructor.java
src/org/exist/xquery/ElementConstructor.java
src/org/exist/xquery/NamespaceConstructor.java
src/org/exist/xquery/functions/fn/FunId.java
src/org/exist/xquery/functions/fn/FunIdRef.java
src/org/exist/xquery/functions/fn/FunQName.java
src/org/exist/xquery/value/StringValue.java
test/src/xquery/xmlid.xql

Forward port of https://github.com/eXist-db/exist/pull/2296

Fix failing xml:id tests by using proper checks for xs:NCName

---

src/org/exist/xquery/functions/util/Eval.java

Forward port of https://github.com/eXist-db/exist/pull/2420

Tiny bug fix in fn:eval-and-serialize

---

build/scripts/junit.xml

Fixes the OutOfMemory error by specify start/maximum heap size and tweak some GC settings.

Fixes OOM by adding memory options and GC tweaks

---

build/scripts/junit.xml

Backport of https://github.com/eXist-db/exist/pull/2430

(5.0.0) Fixes OOM by adding memory options and GC tweaks

---

build/scripts/junit.xml

Backport of https://github.com/eXist-db/exist/pull/2430

(4.x.x) Fixes OOM by adding memory options and GC tweaks

---

src/org/exist/backup/RestoreDialog.java

(4xx) Improve restore progress window 

---

src/org/exist/backup/RestoreDialog.java

(5xx) Improve restore progress window 

---

src/org/exist/storage/serializers/Serializer.java

Fixes a performance issue in the serializer.

Improve serializer performance

---

src/org/exist/storage/serializers/Serializer.java

Backport of https://github.com/eXist-db/exist/pull/2457

(4.x.x) Improve serializer performance

---

src/org/exist/xquery/functions/util/Eval.java
test/src/org/exist/xquery/functions/util/EvalTest.java

Closes https://github.com/evolvedbinary/pebble-api/issues/9

(4.x.x) Fix a serialization issue with util:eval-and-serialize

---

src/org/exist/xquery/functions/util/Eval.java
test/src/org/exist/xquery/functions/util/EvalTest.java

Forward port of https://github.com/eXist-db/exist/pull/2453

(5.0.0) Fix a serialization issue with util:eval-and-serialize

---

src/org/exist/xquery/functions/util/Eval.java
test/src/org/exist/xquery/functions/util/EvalTest.java

Forward port of https://github.com/eXist-db/exist/pull/2453

Fix a serialization issue with util:eval-and-serialize

---

eXist-db.iml

Remove cql module from sources as there is a external dependency

---

.travis.yml

Port of https://github.com/eXist-db/exist/pull/2472

(5.0.0) Send Travis notifications to Slack

---

.travis.yml

Backport of https://github.com/eXist-db/exist/pull/2472

(4.x.x) Send Travis notifications to Slack

---

build/scripts/dist.xml
installer/install.xml.tmpl

(4xx) Fix dist build with module changes

---

build/scripts/dist.xml
installer/install.xml.tmpl

(develop) Fix dist build with module changes

---

build/scripts/dist.xml
installer/install.xml.tmpl

(5xx) Fix dist build with module changes

---

README.md

see #2475
forward port of #2484

(5.0.0) fix hipchat references on readme 

---

README.md

(4.x.x) fix hipchat references on readme 

---

src/test/xquery/unparsed-text.xql

(4xx) Change github path to reflect new situation

---

README.md

fix hipchat references on readme see #2475

---

src/main/java/org/exist/xquery/functions/fn/FunUnparsedText.java
src/test/xquery/unparsed-text.xql

(4xx) Prevent NPE in unparsed-text-available for GitHub URL

---

src/main/java/org/exist/xquery/functions/fn/FunUnparsedText.java
src/test/xquery/unparsed-text.xql

(5xx) Prevent NPE in unparsed-text-available for GitHub URL

---

exist-core/src/test/xquery/unparsed-text.xql

(develop) Change github URL (again) after current code restructuring

---

exist-core/src/test/xquery/unparsed-text.xql

(4xx) Change github URL (again) after current code restructuring

---

exist-core/src/test/xquery/unparsed-text.xql

(5xx) Change github URL (again) after current code restructuring

---

tools/yajsw/conf/wrapper.conf.in

(develop) Update path to new location of yajsw classes

---

tools/yajsw/conf/wrapper.conf.in

(5xx) Update path to new location of yajsw classes

---

exist-core/src/main/java/org/exist/webstart/JnlpJarFiles.java

Remove whitespace from jar entry (4xx only)

---

exist-core/src/main/java/org/exist/xquery/functions/util/LogFunction.java

(4xx) log functions: Do not use serializer for simple String conversion

---

exist-core/src/main/java/org/exist/xquery/functions/util/LogFunction.java

(develop) log functions: Do not use serializer for simple String conversion

---

exist-core/src/main/java/org/exist/xquery/functions/util/LogFunction.java

(5xx) log functions: Do not use serializer for simple String conversion

---

build/scripts/junit.xml
exist-core/src/main/java/org/exist/storage/BrokerPool.java
exist-core/src/test/java/org/exist/storage/BrokerPoolNoRecoveryTest.java

Closes https://github.com/eXist-db/exist/pull/2534
Closes https://github.com/eXist-db/exist/issues/2533

Start fine with recovery disabled (Fixes issue #2533)

---

build/scripts/junit.xml
exist-core/src/main/java/org/exist/storage/BrokerPool.java
exist-core/src/test/java/org/exist/storage/BrokerPoolNoRecoveryTest.java

(4.x.x) Start fine with recovery disabled (Fixes issue #2533 on develop-4.x.x)

---

build/scripts/junit.xml
exist-core/src/main/java/org/exist/storage/BrokerPool.java
exist-core/src/test/java/org/exist/storage/BrokerPoolNoRecoveryTest.java

Backport of https://github.com/eXist-db/exist/pull/2538

(5.0.0) Start fine with recovery disabled (Fixes issue #2533 on develop-5.0.0) 

---

exist-core/src/main/java/org/exist/SystemProperties.java
exist-core/src/main/java/org/exist/Version.java
exist-core/src/main/java/org/exist/repo/Deployment.java

Small code cleanup

---

exist-core/src/main/java/org/exist/SystemProperties.java
exist-core/src/main/java/org/exist/Version.java
exist-core/src/main/java/org/exist/repo/Deployment.java

Backport of https://github.com/eXist-db/exist/pull/2540

(5.0.0) Small code cleanup

---

exist-core/src/main/java/org/exist/SystemProperties.java
exist-core/src/main/java/org/exist/Version.java
exist-core/src/main/java/org/exist/repo/Deployment.java

Backport of https://github.com/eXist-db/exist/pull/2540

(4.x.x) Small code cleanup

---

exist-core/src/main/java/org/exist/storage/lock/EnsureLockingAspect.java

Backport of https://github.com/eXist-db/exist/pull/2543

(5.0.0) Fix some issues with equality in the EnsureLockingAspect

---

tools/yajsw/bin/installDaemon.sh

Fixes a regression introduced by https://github.com/eXist-db/exist/pull/2413
Backport of https://github.com/eXist-db/exist/pull/2551

(5.0.0) Fix the YAJSW installation

---

tools/yajsw/bin/installDaemon.sh

Fixes a regression introduced by https://github.com/eXist-db/exist/pull/2412
Backport of https://github.com/eXist-db/exist/pull/2551

(4.x.x) Fix the YAJSW installation

---

installer/install.xml.tmpl

See https://exist.markmail.org/thread/ho6cdvrhka6ryix3

Fix source code location in built installer

---

installer/install.xml.tmpl

Backport of https://github.com/eXist-db/exist/pull/2548

(4.x.x) Fix source code location in built installer

---

installer/install.xml.tmpl

Backport of https://github.com/eXist-db/exist/pull/2548

(5.0.0) Fix source code location in built installer

---

extensions/modules/expathrepo/src/main/java/org/exist/xquery/modules/expathrepo/Deploy.java

Fixes an issue as reported in Slack by @windauer

Fix transaction issue in EXPath Deployment

---

extensions/modules/expathrepo/src/main/java/org/exist/xquery/modules/expathrepo/Deploy.java

Backport of https://github.com/eXist-db/exist/pull/2545

(5.0.0) Fix transaction issue in EXPath Deployment

---

exist-core/src/main/java/org/exist/xquery/functions/util/Serialize.java
exist-core/src/test/java/org/exist/xquery/functions/util/SerializeTest.java

Closes https://github.com/eXist-db/exist/issues/200

Fix an issue with util:serialize params

---

exist-core/src/main/java/org/exist/xquery/functions/util/Serialize.java
exist-core/src/test/java/org/exist/xquery/functions/util/SerializeTest.java

Backport of https://github.com/eXist-db/exist/pull/2561

(4.x.x) Fix an issue with util:serialize params

---

exist-core/src/main/java/org/exist/xquery/functions/util/Serialize.java
exist-core/src/test/java/org/exist/xquery/functions/util/SerializeTest.java

Backport of https://github.com/eXist-db/exist/pull/2561

(5.0.0) Fix an issue with util:serialize params

---

exist-core/src/main/java/org/exist/xquery/functions/securitymanager/AccountManagementFunction.java

Closes https://github.com/eXist-db/exist/issues/2446

Avoid NPE when empty string is given as Primary Group

---

exist-core/src/main/java/org/exist/xquery/functions/securitymanager/AccountManagementFunction.java

Backport of https://github.com/eXist-db/exist/pull/2564

(4.x.x) Avoid NPE when empty string is given as Primary Group

---

exist-core/src/main/java/org/exist/xquery/functions/securitymanager/AccountManagementFunction.java

Backport of https://github.com/eXist-db/exist/pull/2564

(5.0.0) Avoid NPE when empty string is given as Primary Group

---

exist-core/src/main/java/org/exist/Indexer.java
exist-core/src/main/java/org/exist/dom/persistent/AbstractCharacterData.java
exist-core/src/main/java/org/exist/dom/persistent/AttrImpl.java
exist-core/src/main/java/org/exist/dom/persistent/CDATASectionImpl.java
exist-core/src/main/java/org/exist/dom/persistent/ElementImpl.java
exist-core/src/main/java/org/exist/dom/persistent/TextImpl.java
exist-core/src/main/java/org/exist/storage/NativeBroker.java
exist-core/src/main/java/org/exist/storage/NativeValueIndex.java
exist-core/src/main/java/org/exist/util/CharArrayPool.java
exist-core/src/main/java/org/exist/util/CharSlice.java
exist-core/src/main/java/org/exist/util/UTF8.java
exist-core/src/main/java/org/exist/util/XMLString.java
exist-core/src/main/java/org/exist/util/serializer/TEXTWriter.java
exist-core/src/main/java/org/exist/util/serializer/XMLWriter.java
exist-core/src/test/java/org/exist/storage/btree/BTreeTest.java
exist-core/src/test/java/org/exist/util/XMLStringTest.java
extensions/indexes/ngram/src/main/java/org/exist/indexing/ngram/NGramIndexWorker.java
extensions/indexes/range/src/main/java/org/exist/indexing/range/ComplexTextCollector.java
extensions/indexes/range/src/main/java/org/exist/indexing/range/TextCollector.java

See - https://github.com/eXist-db/exist/issues/2373

Fix some CharArrayPool and ByteArrayPool leaks

---

exist-core/src/main/java/org/exist/Indexer.java
exist-core/src/main/java/org/exist/dom/persistent/AbstractCharacterData.java
exist-core/src/main/java/org/exist/dom/persistent/AttrImpl.java
exist-core/src/main/java/org/exist/dom/persistent/CDATASectionImpl.java
exist-core/src/main/java/org/exist/dom/persistent/ElementImpl.java
exist-core/src/main/java/org/exist/dom/persistent/TextImpl.java
exist-core/src/main/java/org/exist/storage/NativeBroker.java
exist-core/src/main/java/org/exist/storage/NativeValueIndex.java
exist-core/src/main/java/org/exist/util/CharArrayPool.java
exist-core/src/main/java/org/exist/util/CharSlice.java
exist-core/src/main/java/org/exist/util/UTF8.java
exist-core/src/main/java/org/exist/util/XMLString.java
exist-core/src/main/java/org/exist/util/serializer/TEXTWriter.java
exist-core/src/main/java/org/exist/util/serializer/XMLWriter.java
exist-core/src/test/java/org/exist/storage/btree/BTreeTest.java
exist-core/src/test/java/org/exist/util/XMLStringTest.java
extensions/indexes/ngram/src/main/java/org/exist/indexing/ngram/NGramIndexWorker.java
extensions/indexes/range/src/main/java/org/exist/indexing/range/ComplexTextCollector.java
extensions/indexes/range/src/main/java/org/exist/indexing/range/TextCollector.java

Backport of https://github.com/eXist-db/exist/pull/2567

(4.x.x) Fix some CharArrayPool and ByteArrayPool leaks

---

exist-core/src/main/java/org/exist/Indexer.java
exist-core/src/main/java/org/exist/dom/persistent/AbstractCharacterData.java
exist-core/src/main/java/org/exist/dom/persistent/AttrImpl.java
exist-core/src/main/java/org/exist/dom/persistent/CDATASectionImpl.java
exist-core/src/main/java/org/exist/dom/persistent/ElementImpl.java
exist-core/src/main/java/org/exist/dom/persistent/TextImpl.java
exist-core/src/main/java/org/exist/storage/NativeBroker.java
exist-core/src/main/java/org/exist/storage/NativeValueIndex.java
exist-core/src/main/java/org/exist/util/CharArrayPool.java
exist-core/src/main/java/org/exist/util/CharSlice.java
exist-core/src/main/java/org/exist/util/UTF8.java
exist-core/src/main/java/org/exist/util/XMLString.java
exist-core/src/main/java/org/exist/util/serializer/TEXTWriter.java
exist-core/src/main/java/org/exist/util/serializer/XMLWriter.java
exist-core/src/test/java/org/exist/storage/btree/BTreeTest.java
exist-core/src/test/java/org/exist/util/XMLStringTest.java
extensions/indexes/ngram/src/main/java/org/exist/indexing/ngram/NGramIndexWorker.java
extensions/indexes/range/src/main/java/org/exist/indexing/range/ComplexTextCollector.java
extensions/indexes/range/src/main/java/org/exist/indexing/range/TextCollector.java

Backport of https://github.com/eXist-db/exist/pull/2567

(5.0.0) Fix some CharArrayPool and ByteArrayPool leaks
